### ISSUE TITLE
If user does not have Firefox installed, don't trick them with menu item/label 

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1025]
maybe we can think about other ways to promote Firefox, if not installed, eg. rather say "Get/Download Firefox" in share menu or somewhere else

Basically, we want users who don't have Firefox installed, suggest to install Firefox as they might also like to use Firefox

Similar to iOS: https://github.com/mozilla-mobile/focus-ios/issues/142

**Comment by antlam** [comment]
I think we should measure the engagement with this button to compare before/after copy changes, as with iOS.

**Comment by antlam** [comment]
@mheubusch since the language that the Google Play Store uses is "Install"... what do you think of:

- For users without Firefox.... "Install Firefox"
- For users with Firefox...keep it as... "Open with Firefox"

**Comment by pocmo** [comment]
Is the idea to still add this as a menu item - or do we want to show this in some kind of unified share/open menu (#224)?

**Comment by bbinto** [comment]
I'd be up for trying this, @antlam...ideas?...andwill help one of the issues surfaced during research, i.e. to simplify the options in the menu

**Comment by antlam** [comment]
I'd like to hold off on issue #224 and keep it separate for now because I think that requires that we remove explicit "Share..." and "Open with..." options in lieu of a unified button. That might be **too simplified** right now. And I worry it can cause more confusion for users looking to either Share or Open in a browser.

I like the idea of a shorter menu too, but I think the problem we're looking to solve here is different. Here, it's about being upfront with our users as we promote Firefox, and being explicit about what their expectations should be when pressing this button.

The language fix here will also likely be useful when we have a unified "Share" and "Open with" menu in the future since we probably still want to promote Firefox installs through that new, unified, Share/Open in" menu.

@pocmo I'm pretty sure this is hard, but ... what if we had "Install Firefox" on the top of the Share list UI that we currently use after a user presses "Open with..." ? Instead of having it in the overflow menu like we do currently.

**Comment by pocmo** [comment]
@antlam Our "Open With sheet" is already a customized view. So adding this shouldn't be hard actually. Can you create a mock? :)

**Comment by antlam** [comment]
Forgot to leave a note after talking to @pocmo about this.

He's going to post the screenshot in here when hes ready 😬

**Comment by antlam** [comment]
WIP @pocmo @bbinto

![screen shot 2017-08-31 at 10 45 22 am](https://user-images.githubusercontent.com/1994820/29937175-88423108-8e39-11e7-8a98-68b46502ea27.png)

**Comment by antlam** [comment]
@mheubusch any thoughts on the copy here?

> @mheubusch since the language that the Google Play Store uses is "Install"... what do you think of:
- For users without Firefox.... "Install Firefox"
- For users with Firefox...keep it as... "Open with Firefox"

**Comment by antlam** [comment]
cc @BrianNJones too :)

**Comment by BrianNJones** [comment]
@antlam @mheubusch Think we need to take a slight step back. Here's how the interaction would look on the screen:
Open with
<Firefox icon> Firefox
<Chrome icon> Chrome
<Other icons> Other names

So we wouldn't say:
Open with
Install Firefox

Thinking there are 2 remedies. 
1. A visual divider. Users should have the obvious option of opening via an app that's already installed. We need a mechanism to clearly indicate that Firefox isn't installed AND to clearly indicate that user has  to do something to install it. The installed options should be listed first. We could then add a divider, followed by: Get Firefox from the Play Store. It's weird, period, because we're taking users away from their intended action and asking them to enter into a separate flow. 
2. A new construction. Same challenges as above. We could show this:
Open with
<Firefox icon> Firefox (Get from Play Store)

**Comment by antlam** [comment]
I think the first step would be to put this shortcut in here with the rest of the other browser apps/ apps that can handle the open-with intent. 

It may be a bit awkward at first but putting it at the bottom would severely hide it given that this list can be pretty long. But maybe we could fix it to the bottom? ... Let me mock this up.

**Comment by antlam** [comment]
![screen shot 2017-09-05 at 2 39 12 pm](https://user-images.githubusercontent.com/1994820/30085610-26e858d0-924c-11e7-9b24-ac85eecae673.png)

Here's where we are right now. Key things to note: 
- Both options are for the case where the user does not have Firefox installed **only**
- Once Firefox is installed, we're just inside the list like the other browsers
- The purple button idea fixes to the bottom of the list, in the unlikely event that scrolling is necessary, that will should behind the button.

@pocmo as far as strings go, I think we have the options we need to export. 
- "Firefox (Get from Play Store)"
- "Get Firefox from the Play Store"

@bbinto @pocmo how do you both feel about the new options on the right? with the snippet-looking UI. We're thinking we might want to offer a dismiss button if it's going to be so similar to a snippet but not sure what the Product implications would be in particular :). Feedback welcome!

**Comment by pocmo** [comment]
Just a quick note on the string: We either have to replace "Play Store" with a placeholder or leave it out. In most cases it will be the Play Store that opens but it's not guaranteed.

We did the same for the dialog that pops up when opening an app that is not installed yet (%2$s is the placeholder for the name of the store):
> None of the apps on your device are able to open this link. You can leave %1$s to search %2$s for an app that can.

Regarding the implementation: I have to look into how to implement such a sticky item in a scrolling list. Can be easy or complex. I assume that most regular uses have only a small amount of browsers installed.

**Comment by bbinto** [comment]
I'm fine with the snippet idea, however, if this becomes too complicated eng-wise, I wonder if we can keep it very simple, and only replace the wording of "Open with Firefox" in the menu as it is right now to say "Instal (or) Get Firefox" if it's not installed.

**Comment by BrianNJones** [comment]
Thanks for showing me WIP on Vidyo, Anthony. Recommend we go with <Download Firefox> at bottom of list, with purple highlight to differentiate from programs user already has installed.

**Comment by antlam** [comment]
Final designs after feedback:
@pocmo @BrianNJones @bbinto 

![screen shot 2017-09-06 at 11 30 31 am](https://user-images.githubusercontent.com/1994820/30128546-ea514bc8-92f7-11e7-9ce0-a1344291e0e2.png)

Same styles as current UI. I've also shown an example of what double-line text may look like but we probably won't need it.

@bbinto as per @pocmo and @BrianNJones comments, having this at the bottom of the list is more honest to our users since we separate "Open with..." and "Download Firefox". But  I wanted to know what's the “business value” or “product sizing” for having this button "stand out" more? Obviously purple does a better job in that regard but also seems more ad-like. 

I'll leave it up to you :)

Side note: @pocmo suggested using whatever the icon of whatever the system "store" is on the users device on the left of "Download Firefox". That way, we can reference more clearly what will happen after the user taps the button.

Purple button matte: #B5007F
Grey button matte: #E4E4E4

**Comment by bbinto** [comment]
Business value: L

I'd like to support @pocmo suggestion to use the "default store" icon, as well as using the purple background.

**Comment by bbinto** [comment]
@pocmo what BB version is this in? I can't seem to see this update in my version 2.1 (Build # 12501414)

**Comment by pocmo** [comment]
I'll reopen and check - this should be in for quite some time.

**Comment by pocmo** [comment]
For it to show up you need to:
* Have no Firefox channel installed (including Beta, Nightly etc.)
* Have an app installed that can handle market:// links (e.g. Google Play)
* Scroll to the bottom of the list if you have a lot of browsers installed.

Just verified that it shows up on my devices after uninstalling all other foxes.

**Comment by bbinto** [comment]
Strange, I only have Focuses installed.

> Have an app installed that can handle market:// links (e.g. Google Play)
It should be included as an option in Focus though under "Open with"?

![screenshot_20170925-110144](https://user-images.githubusercontent.com/122897/30815533-8680e8e4-a1e1-11e7-802d-c9b22d9a43d7.png)
![screenshot_20170925-110229](https://user-images.githubusercontent.com/122897/30815536-880ed680-a1e1-11e7-8126-20df1fa610f1.png)

**Comment by pocmo** [comment]
@bbinto How does the sheet look like when you click on "Open with..."?

**Comment by bbinto** [comment]
![screenshot_20170925-121043](https://user-images.githubusercontent.com/122897/30818885-d9ec517c-a1ea-11e7-98a1-4348bef986f1.png)
