### ISSUE TITLE
Cookies preferences

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1041]
There's should be (at least) possible to enable or disable cookies (third-party and/or first-party).

Thanks.

**Comment by pocmo** [comment]
Btw. cookies are destroyed whenever a browsing session is erased.

**Comment by bbinto** [comment]
@dimqua, could you please elaborate on a case you've encountered or you'd like cookies to persist? Can you share some example websites?

**Comment by dimqua** [comment]
>or you'd like cookies to persist

Yes, in some cases, not by default.

Generally, I have few websites which I visit frequently and I want to keep cookies for them (whitelist); for any other websites I want to block third-party and/or first-party cookies compeltly or destroy them:
* when I go to the next website (although I'm not sure if it's possible),
* at the end of a browsing session.

But it probably require too much work to implement this, that's why I suggest to add only basic options, which we already have in desktop version of Firefox:

![](http://i.imgur.com/TGFTsHn.png)

Do I need to create new issue for cookie whitelist too?

**Comment by jimmoffet** [comment]
I can't use focus because I read nytimes.com multiple times per day and would have to sign in each time I visit.

I suspect a *very* large swath of users visits a site they need to login to multiple times a day, so this directly bears on the reach of this product.

To my mind, a row in the in-browser settings menu (three dots, upper right while browsing) is warranted. Something like "Stay logged into this site" with a switch. Instant whitelist. You can elaborate in the settings if necessary, but I think this is the most minimal approach.

You could also flash a card the first time users fill a login after downloading that makes them aware of the option.

**Comment by klint** [comment]
Another use case in Europe: any site must warn visitors about cookies.. So each time we go on a site we often visit, we get the same information message about cookies that we have to dismiss!

**Comment by cwmke** [comment]
My main issue is not being able to use my default search engine's custom settings since they're stored in a cookie. A whitelist would solve this issue and make Focus more pleasant to use.

**Comment by bbinto** [comment]
Please keep the use cases coming, this is great info that helps us prioritize these feature requests.

**Comment by klint** [comment]
For instance, to answer this thread, I had to click on the link in the mail which opened the page in Focus... But not signed in! So I had to open Firefox from revient menu in Focus to get the cookies context back and be signed in... And write this. ☺️
Rather frustrating indeed
