### ISSUE TITLE
Consider cleaning up long-press context menu options with Telemetry

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1105]
![screenshot_20170809-160740](https://user-images.githubusercontent.com/1994820/29113320-445782bc-7d23-11e7-921b-e25d2a03f282.png)

IIRC we only talked about "Save image", "Copy", and maybe another one in here... But it looks like we have a bunch of other ones in there too for some reason.

I wanted to file this bug to keep an eye out on which we can remove to clean it up before it gets overwhelming and starts being less useful :)

**Comment by pocmo** [comment]
Here's some data from telemetry (percentages only). Note that a context menu might not show all options all the time though (e.g. link without image, or image without link).

![image](https://user-images.githubusercontent.com/89638/29115916-845acd62-7cf9-11e7-96ff-0c501699c2e5.png)

**Comment by feikname** [comment]
> I wanted to file this bug to keep an eye out on which we can remove to clean it up before it gets overwhelming and starts being less useful :)

I can't think of any new options that might be added in any near future besides "Open image in new tab" or "Copy", which in my opinion is far from overwhelming. Also, those options are ubiquitous for browsers, no matter how many users actually use them, please **DO NOT** remove any, each has its own use case that can be handy.

If things do start to be way too overwhelming, perhaps a custom tabbed UI element for long press could be created, something like this:

![image](https://user-images.githubusercontent.com/4926869/29148914-cffe8af4-7d46-11e7-95e9-953a972dbcdd.png)

Another alternative would be to dumb down the interface by default and have an setting to re-enable all the options, but wait, we might have to remove other settings because there are too many already? (yes, this is sarcasm, sorry)

Now seriously, please don't remove things for the sake of removing them, this dumbing down trend in software is starting to make us having more powerful hardware that can do less stuff than older products.

**Comment by antlam** [comment]
@bbinto do you have thoughts on this? :)

**Comment by antlam** [comment]
@feikname thanks for your input! The tabbed approach is also something we did in Firefox for Android so it's something to consider for sure. Good point!

On another note, there are lots of things to consider in general. And rest assured, we are not going to be making changes just for the sake of changes. The goal here is not to "dumb down" anything. But as UX designers, its important to keep the big picture in mind. And when there are more options, the hierarchy of the information definitely changes.

**Comment by bbinto** [comment]
@antlam, what would a clean-up look like in your mind? Which options would want to clean-up/remove?
