### ISSUE TITLE
Run ImageOptim on generated screenshots

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1136]
I noticed that our automated screenshots are quite large. I picked a random screenshot and its size was 298 KB. I ran ImageOptim on it and the new size was only 118 KB (~60% saved). It might be worth applying this to all images before uploading them. Although this might take a while.

**Comment by pocmo** [comment]
@npark-mozilla Do you think that's feasible? You can drop the whole folder into ImageOptim and it will optimize all PNGs it finds. However this will take a significant amount of time I guess.

**Comment by npark-mozilla** [comment]
Hmm, I ran ImageOptim in one of the locale folder, and for some reason, it's taking 15+ minutes on it. with 50+ locales, that would be  a really long time.  I think I need to go back to using the curator (http://furius.ca/curator/#download) to generate image thumbnails of sufficient size. This would reduce the download time since the thumbnails are smaller in size, but texts are still discernible.

**Comment by pocmo** [comment]
Some ways to make it faster:
* Resize the image before optimizing (assuming we do not need full resolution screenshots)
* ImageOptim has settings to select the algorithms (less = faster) and an option to favor speed over optimization

**Comment by npark-mozilla** [comment]
I was looking for the options to reduce the resolution, but fastlane screengrab doesn't seem to have that option :(

**Comment by pocmo** [comment]
@npark-mozilla Maybe there's some (command-line) tool to resize all images in the folders by a fixed factor like 50%?

**Comment by npark-mozilla** [comment]
hmm you're right, I think 'convert' utility will work.  I can probably do something like:
find . -name "*.png" | xargs mogrify -resize 50%

**Comment by pocmo** [comment]
Closed? :)
