### ISSUE TITLE
Re-create URL input animation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#115]
This didn't survive refactoring. When clicking the URL input field on the start page it should move up "into" the URL bar. Compare with Focus for iOS.

**Comment by ahunt** [comment]
It seems fragment transitions only work when you replace() a fragment (at least those set with setSharedElementEnterTransition()) - i.e. transitions are ignored when you add() the fragment.  Which means that the focus wordmark/HomeFragment have to disappear if we add the animation:
![urlentry2](https://cloud.githubusercontent.com/assets/1546915/23653137/bab4fb5a-032b-11e7-9292-f678d638ecfb.gif)
(No idea if this will actually work, it should be a gif-video of the animation)

I guess we could manually re-add the focus wordmark as part of the background when showing the UrlInputFragment if we do want to do this. That wouldn't break the other usecase (i.e. URL entry when you've already browsing). We can still keep the browser in the background when browsing, since we don't need to animate shared elements in that case anyway.

**Comment by ahunt** [comment]
We could always implement our own animation (for which we'd have to pass the size/position of the original urlbar through to the new fragment). That would be more complicated/brittle (whereas the fragment transition code is relatively simple), but it's doable if we really want it.

**Comment by pocmo** [comment]
I talked to antlam yesterday and we might try to add a simpler fade animation. However this isn't something you see in the screenshots so we could delay working on this a bit.
