### ISSUE TITLE
Rename "Send anonymous usage data" because is misleading

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1163]
https://github.com/mozilla-mobile/focus-ios/issues/294

**Comment by antlam** [comment]
![screen shot 2017-08-17 at 2 32 57 pm](https://user-images.githubusercontent.com/1994820/29437379-0400eec2-8365-11e7-88b9-bf44947bedcf.png)

> Send usage data
> Learn more about how and why we collect  usage data

**Comment by antlam** [comment]
@bbinto needs triage :)

**Comment by antlam** [comment]
@mheubusch copy look good to you here?

**Comment by quakenet2** [comment]
Fucking Github flagged me as a bot, WTF.

Anyway, this issue is the original. Just for reference.

https://github.com/mozilla-mobile/focus-android/issues/1120

**Comment by quakenet2** [comment]
> Mozilla strives to collect only what we need to provide

Question: Is assigning "unique ID" to each device really necessary?
I can argue with "only" in this sentence.

Why not just say:

> "Send usage data to improve Mozilla Product"
> Learn More> (link)

**Comment by quakenet2** [comment]
"Unique ID"(GUID) and "Device name" is really not necessary to improve any app.

**Comment by quakenet2** [comment]
ping @liuche

**Comment by quakenet2** [comment]
"Device name": Not OK
"Device Model": OK

**Comment by mheubusch** [comment]
Yes. Looks good. Did you intend to underscore the Learn more to indicate the hyperlink?

**Comment by eleemoz** [comment]
Hi @quakenet2, in this case I think it is accurate because "Mozilla strives" to collect only what is needed. Obviously different people may disagree with specific decisions about what is necessary, but Mozilla does strive for that!

I am not an expert, but my understanding is that without some sort of unique identifier, data cannot be analyzed longitudinally "over time" which reduces the usefulness of the information, and can make it much more challenging to diagnose and fix some of the problems with a browser.

There may be some confusion, but my read of the [documentation](https://github.com/mozilla-mobile/focus-ios/wiki/Install-Tracking-in-Firefox-Focus-with-the-Adjust-SDK) that you referenced shows that only the device model name is recorded:

```
device_name:             iPad6,3
```

Of course, if you have feedback that isn't directly related to the app's design, it might be better to participate in one of the other ways from the README:

- IRC: #focus (irc.mozilla.org)
- Mailing list: mobile-firefox-dev

**Comment by npark-mozilla** [comment]
#1301
