### ISSUE TITLE
Add link to download manager to menu

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1169]
I saw some comments from users unable to find downloads. Does it make sense to link to the download manager from within the menu? We could also implement our own UI - but this seems to be overkill.

**Comment by bbinto** [comment]
UX: S, Eng: S

**Comment by lime124** [comment]
@brampitoyo can you take a look at this please?

**Comment by brampitoyo** [comment]
Yes. It does make sense to have a “Downloads” menu item – and it doesn’t make sense to implement our own download manager UI.

One important question: does the Android download manager operate like a desktop browser’s download manager, or like a shortcut to open your Download folder in File Manager?

If it operates like a desktop download manager, then clearing the list of downloaded files won’t actually delete file stored in the device.

If it operates as a shortcut to File Manager, then deleting the file there would delete the file stored in the device.

Knowing how the Android download manager works has a few implications to think about.

First, whether giving a shortcut to downloaded files that are permanently stored will get our users confused with a browser history that’s impermanent and easily cleared. We already have a warning message about this, though, so maybe it’s not so much of a problem.

Second, whether a “Downloads” menu item is useful to display at all times, or *only* when/after you download a file. For example, let’s say that you’ve just tapped the “Erase” button. Should you see a “Downloads” menu item? If you do, what does it display?

These are some things I’m thinking about beyond adding a menu item. Let me know of your thoughts!

**Comment by antlam** [comment]
> whether giving a shortcut to downloaded files that are permanently stored will get our users confused with a browser history that’s impermanent and easily cleared. 

> For example, let’s say that you’ve just tapped the “Erase” button. Should you see a “Downloads” menu item? If you do, what does it display?

> Showing a downloads menu item that will display a bunch of downloads (not from Focus) without the user ever downloading anything might be super confusing (and unexpected?).

I share these concerns too. Otherwise, a simple menu item would suffice. And given the session-based nature of a product like Focus, this gets quite tricky form a messaging stand point. E.g. If Focus is about erasing my "stuff" from a browsing session, how come downloads are still there (readily available) after I hit Erase?

On Android, downloads usually come paired with a notification as well. Since these users probably don't have access to that notification anymore (either they hid it purposefully, or missed it, or their Android flavor/version doesn't show it), that's something to be aware of. Maybe this issue is as much about the OS as it is about the application they're using to download the files (Focus in this case)

@brampitoyo @bbinto @pocmo sorry I missed this in triage while I was on PTO so I'm not sure how much of a priority this is... but I think we have some good UX/Eng options here. 

I think the next steps should be to figure out the impact of each of those options on our messaging, product direction, etc... Those would be good answers to have before deciding on what to build. IIRC "downloads" didn't come up as something we heard from our research per se. But perhaps we could even user test some of these ideas for messaging issues and expectations?

**Comment by pocmo** [comment]
I get more and more the impression we shouldn't do this - it only introduces more confusion. :)

**Comment by bbinto** [comment]
@pocmo can you share the exact pain points/requests/comments these users posted?

**Comment by pocmo** [comment]
Back then I was looking through the comments of the version in staged roll out (1-2 stars) to see if there are any new issues. I just tried to find those comments again but I couldn't.

**Comment by antlam** [comment]
From @brampitoyo: 

> I feel nervous about including a “Downloads” menu item... Until we’ve ascertained user expectations through testing.

**Comment by antlam** [comment]
@bbinto this doesn't sound like a high priority item for Product (unless I'm misreading). 

Could we move this out of Denim and into the appropriate position in our backlog for a later date?
