### ISSUE TITLE
Settings open slowly (Pixel XL, Android 8)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1193]
On my Pixel XL running Android 8 it takes about 4 seconds until the settings show up after clicking the menu item. That's super slow and feels like the app is frozen.

**Comment by pocmo** [comment]
I think it's LocaleListPreference.buildList() that is taking quite long.

**Comment by jenn-chaulk** [comment]
@bbinto should this be in folly?  was removed from cobalt.

**Comment by bbinto** [comment]
Makes sense, I wonder why it was removed from Cobalt? I can't remember, expect all eyes were supposed to be on finishing the multitasking feature?!?

**Comment by shikhart98** [comment]
Yes, it took about 2 seconds for app to launch settings menu! but when I start the app from quick launch and then open settings, it responds quickly!

**Comment by aperfilyev** [comment]
I dug a bit into this and it seems that lag is happening because OS instantiates [Transliterator](https://android.googlesource.com/platform/external/icu/+/1537b2f/android_icu4j/src/main/java/android/icu/text/Transliterator.java) to convert the first letter of Ελληνικά locale to upper case ([see here])(https://android.googlesource.com/platform/libcore/+/master/libart/src/main/java/java/lang/CaseMapper.java#152)

Maybe we can check if it's already uppercased and skip this step? If so, I can send a PR.

**Comment by aperfilyev** [comment]
The time of building a list went down from ~1800 ms to ~90 on my device. Thinking about it further we can certainly offload this method to a background thread.

**Comment by pocmo** [comment]
@aperfilyev Nice find! Please open a PR and add a comment explaining why we do this. :)

**Comment by aperfilyev** [comment]
@pocmo will do in the evening when I get home.

**Comment by aperfilyev** [comment]
@pocmo I've made a PR.

**Comment by pocmo** [comment]
Awesome. Thank you!
