### ISSUE TITLE
I want to know when I hit back too many times and erase the history by accident (exiting the app)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1195]
Via Carter Trout

I personally would love to have browsing history that automatically expires after e.g. 24 hours or some time frame. 

When I page through multiple links and then decide I want to go backwards to my initial page, I hit the back arrow and load prior pages but I don't know when to stop going back. If I press back one time too many, Focus will shut down the app and when I reopen the Focus app, I can't get back to that initial page because Focus has erased everything (and also, there's no history).

**Comment by antlam** [comment]
Reading this again, it sounds like the core problem here is a bit about not knowing the "trail" of webpages that you will be "back"-ing through as you press the back button/hardware back.

(I could be wrong but) I think users do "know when [they] hit back too many times and have exited/erased" because right now we show a toast for that.... Maybe this is more about "getting to a specific page I visited this session" than "know when I hit back too many times"? 🤔

**Comment by pocmo** [comment]
> Maybe this is more about "getting to a specific page I visited this session" than "know when I hit back too many times"? 🤔

Like in Fennec where you can long press "back" and we show the list of pages you can go back too?

**Comment by antlam** [comment]
Yeah, that's kind of what I'm imagining. But I'm not looking at the interaction and discover-ability issues there. Using it purely as an example of the users "browsing session/trail".
