### ISSUE TITLE
In android O, the shortcut name is not set

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1223]
In API 26 simulator, go to google.com
When webpage is loaded, select 'Add to Homescreen' and change the title
Click 'Add automatically'

Expected:
- The app minimizes and home screen appears with the custom name shortcut
Actual:
- The app does not minimize, and when homescreen is opened, the shortcut says 'Google' instead of custom set name

**Comment by pocmo** [comment]
Not going to the home screen is intentional. On Android 8+ the user can decide to go to the home screen and place the icon or let Android do it automatically (in which case we won't switch to the home screen. The user already got a "visual" confirmation when the dialog popped up).

The title is definitely an issue but I can't reproduce this. My phone always uses the title I entered (Android 8).

**Comment by pocmo** [comment]
I'm also unable to reproduce this on Android 8 emulators (5X and Nexus 9).

However in the code I saw that we might set the URL as "long" title. I haven't seen this long title being used by the launcher yet - however we want to always use the entered title. In your case was the URL used instead of the entered title?

**Comment by pocmo** [comment]
I'll wrote a patch for the issue mentioned above. I'll move this to the QA column to re-test. :)
