### ISSUE TITLE
Bookmarks/Recent sites within browser

### ISSUE THREAD

**Issue by simonsteiner1984** [mozilla-mobile/focus-android#1226]
When I click on the url bar, I should see recent sites/ bookmarks so i can quickly load a website rather than going back to android homescreen and clicking on a bookmark.

**Comment by pocmo** [comment]
Can you elaborate? The idea behind Focus is that it does not save any history.

**Comment by simonsteiner1984** [comment]
What about showing bookmarks within the browser
My alternative is to use normal firefox with ublock origin but this is a much slower app than firefox focus

**Comment by simonsteiner1984** [comment]
I would like to see a compromise that allows me to use focus as the app to visit my common sites

**Comment by antlam** [comment]
@simonsteiner1984 We're leveraging "Add to Home screen" to allow users to shortcut to the web pages they'd like, but still benefit from the speed of Firefox Focus.

Since we're currently rallying under the notion of **privacy** first, a collective/saved record of multiple web pages you visit (frequently or otherwise) presents a lot of friction with our current goals.

**Comment by pocmo** [comment]
I'll close this issue for now as it's not something that is on our immediate roadmap.
