### ISSUE TITLE
Overflow: hidden does not prevent page length increase with absolutely positioned div outside page width

### ISSUE THREAD

**Issue by Banjopalmo** [mozilla-mobile/focus-android#1228]
It seems like overflow: hidden isn't working, I tried with overflow, overflow-x and overflow-y in different cases (pseudo-elements, transform and absolute positioning) and in all cases I get an unwanted scroll.

I don't get the problem on regular firefox mobile.

**Comment by pocmo** [comment]
* Do you see the same behavior in Chrome?
* What Android device / version are you using?
* Do you happen to have a test/demo page for this? :)

**Comment by Banjopalmo** [comment]
- Weirdly, yes, I don't think I had that problem before (it works fine on desktop and on firefox mobile)
- I'm using a LG G4 Plus on Android 7.0
- Made this incredible demo : www.benjaminpalmero.be/overflow

**Comment by Banjopalmo** [comment]
Here is a test page : www.benjaminpalmero.be/overflow

**Comment by mcomella** [comment]
> Here is a test page : www.benjaminpalmero.be/overflow

To be explicit, my understanding of the problem is clicking "Pseudo-Element" on the page is expected to keep the page length the same but instead it makes the page extra long (this is how the behavior differs on Focus and Firefox). I can reproduce on device and also reproduce on desktop Chrome in responsive design mode.

---

Underneath the hood, we use WebKit, Chrome's rendering engine, and given that we can reproduce in Chrome, I don't think there's much we can do here beyond filing a bug against chromium: I filed https://bugs.chromium.org/p/chromium/issues/detail?id=776865. @Banjopalmo, please add any additional details to that bug that you think would be helpful!

That being said, doing [a DDG search for "overflow: hidden chrome"](https://duckduckgo.com/?q=overflow%3A+hidden+chrome&t=ffab&ia=qa), it seems a lot of people find that `overflow` doesn't work the way they expect it to between browsers. I wonder if Chromium has the expected behavior or if this is one of those issues that the behavior diverges between browsers and aren't expected to be fixed (e.g. for legacy reasons).

[This SO post](https://stackoverflow.com/q/19304582/2219998) (without any one top answer) mentions specifying `position:absolute/relative` and setting an explicit height as possible solutions but I don't have the expertise to say whether or not these are good workarounds, or even the correct way to use `overflow: hidden` (since I'm not a web developer).

**Comment by Banjopalmo** [comment]
I tried some other things, and it seems like the problem occurs only when the overflow property is set on the body. 

If I put all the divs inside a section and set the overflow-x: hidden on the section, there is no horizontal scroll.

I've added this to my test page: http://www.benjaminpalmero.be/overflow

And indeed, firefox has the most intuitive behavior since overflow: hidden is supposed to hide elements that are outside of their "parent's size".
