### ISSUE TITLE
New tab shows more than first subdomain

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1231]
According to the UX spec, the url should only display up to first subdomain, but opening a new tab on embedded url shows more subdomains past 1st level.

![screenshot_20170829-164738](https://user-images.githubusercontent.com/6930774/29843521-31f2688c-8cda-11e7-94be-3fcc48e0be5c.png)

**Comment by pocmo** [comment]
So far the implementation only does:
* Remove the scheme (http://  https://)
* Removes common unspecific sub domains (m. www. mobile.) - Code borrowed from Fennec

I noticed two things:
* We only allow opening new tabs from the context menu. Using this I often opened a bunch of tabs  that are from the same "page". Meaning at least the domain (and sometimes parts of the path) are the same for a bunch of tabs. Making it hard or impossible to distinguish between them.
* Strictly following the spec I end up with pages that are reduced to the same "label":
** https://en.m.wikipedia.org/wiki/Firefox_Focus -> m.wikipedia.org/wiki
** https://en.m.wikipedia.org/wiki/Mozilla -> m.wikipedia.org/wiki

Picking a "label" from a URL is pretty hard. We had this discussion a bunch of times for Activity Stream and whatever algorithm we pick there are always cases where it doesn't work correctly. I understand that we need to somehow cut off the string if it's too long - but I'm not sure why we purposefully make it shorter if there's space to show more.

Unfortunately I have no other proposal. Sometimes the domain is important, sometimes the path and other times the page title is the most helpful.

@brampitoyo @antlam What do you think?

**Comment by antlam** [comment]
What if we started with removing the scheme, and the common unspecific sub domains....

And then started truncating with ellipsis immediately but showed as many characters as we can from the end of the URL? That could be helpful if we're looking to differentiate URLs from the same domain.

Eg.
- wikipedia.org/wiki/.../Mozilla
- wikipedia.org/w.../red_pandas
- wikipedia.org...furry_wombats

**Comment by brampitoyo** [comment]
@pocmo Hey. You’re right that we might have truncated way too much of the URL to be helpful, and to make good distinction between resources located on the same site.

I like @antlam’s suggestion, but want to expand on it a bit more.

Our intention isn’t only to truncate, but also help clarify what each URL might be about. This is a big, hairy problem!

> Sometimes the domain is important, sometimes the path and other times the page title is the most helpful.

On the bottom of this post, I’ve written the thought process I’ve gone through to arrive at these truncation rules. Feel free to read it should you need more explanation.

### Truncation rules

* `parameter` and `value` seems to not be essential for understanding most of the time… unless you’re YouTube or Google Play Store. I hate to make exceptions, but YouTube is so popular that I must accommodate it. But at least we should keep only the first `parameter` and `value`, so it doesn’t grow too long.
* `directory` and `subdomain` are tied in importance, but `directory` is more important.
  * Sometimes, the first `directory` is essential to understanding (like in Amazon’s case, it contains the book name). Other times, it’s not essential (like `/2017`). Let’s keep only the first directory.
  * Interestingly, `subdomains` don’t seem to play that big of a part in helping you to understand what the URL is about, because the information tends to repeat or be clarified in the directory (like many Google products). And plus, if you open URLs from the same site in a new tab, repeating the same subdomain on the list of tabs is redundant.
* `TLD` is important for security, especially if people use Focus for any sort of banking. Show it.
* Sometimes, the first `path` is essential to understanding (like in Amazon’s case). Most of the time, it’s not (like `/2017` or `/articles`). On a minority of cases, it’s debatable. Should we show `store` on Google Play Store? This is my second candidate for removal.

And where is the right point to cut off the URL? My advice would be to cut **the end of the URL, rather than the start**, because important information tends to go towards the start.

### Applying truncation rules

<img width="720" alt="screen shot 2017-08-31 at 3 34 46 pm" src="https://user-images.githubusercontent.com/51007/29914242-018c4116-8e62-11e7-9481-9c5a38184a63.png">

Hey, it’s not so bad! Even on WordPress and Tumblr, where the subdomain is important, you can still tell each resource apart because each post has got a unique name.

What do you think?



### Thought process (optional read)

First, let’s take a random URL from 10 popular sites. Then, let’s find all the components that can 1) help tell us what the URL is about, and 2) differentiate one resource from another resource located on the same domain.

* en.m.wikipedia.org/wiki/Adler_Planetarium
  * The URL is about: `wikipedia` + `Adler_Planetarium`
* youtube.com/watch?v=WXqGDW7kuAk
  * The URL is about: `youtube` + `WXqGDW7kuAk`
* open.spotify.com/album/6JVdzwuTEaLj7Tga8DpFpz
  * The URL is about: `spotify` + `6JVdzwuTEaLj7Tga8DpFpz`
* mail.google.com/mail/u/0/#inbox/15e34774924ddfb5
  * The URL is about `mail` + `google` + `15e34774924ddfb5`
* play.google.com/store/apps/details?id=com.facebook.katana&hl=en
  * The URL is about: `play` + `google` + `store` + `com.facebook.katana`
* amazon.com/Mockingjay-Hunger-Games-Suzanne-Collins/dp/0545663261/ref=pd_sim_14_2?_encoding=UTF8&psc=1&refRID=90ZHE3V976TKBGDR9VAM
  * The URL is about: `amazon` + `Mockingjay-Hunger-Games-Suzanne-Collins`
* onlinebanking.usbank.com/Auth/Login
  * The URL is about: `usbank.com` (`.com` shows that it’s a legitimate site) + `Login`
* wsj.com/articles/mexican-presidential-candidate-calls-for-nafta-talks-to-be-suspended-1504137175
  * The URL is about: `wsj` + `mexican-presidential-candidate-calls-for-nafta-talks-to-be-suspended`
* nytimes.com/2017/08/30/world/europe/princess-diana-death-anniversary.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=second-column-region&region=top-news&WT.nav=top-news
  * The URL is about `nytimes` + `princess-diana-death-anniversary`
* headlines.yahoo.co.jp/hl?a=20170830-00000008-jct-soci
  * The URL is about `headlines` + `yahoo` + `20170830-00000008-jct-soci`

Now, let’s try and apply the rules we’ve come up with above to the same URLs above.

* <s>en.m.</s>wikipedia.org<s>/wiki/</s>Adler_Planetarium
* youtube.com/watch?v=WXqGDW7kuAk
* <s>open.</s>spotify.com/album/6JVdzwuTEaLj7Tga8DpFpz
* <s>mail.</s>google.com/mail/<s>u/0/#inbox/</s>15e34774924ddfb5
* <s>play.</s>google.com/store/<s>apps/</s>details?id=com.facebook.katana<s>&hl=en</s>
* amazon.com/Mockingjay-Hunger-Games-Suzanne-Collins/<s>dp/0545663261/</s>ref=pd_sim_14_2?_encoding=UTF8<s>&psc=1&refRID=90ZHE3V976TKBGDR9VAM</s>
  * Hopefully, the first part will spell out “Mockingjay” and is enough to make sense of the URL
* <s>onlinebanking.</s>usbank.com/Auth/Login
* wsj.com/articles/mexican-presidential-candidate-calls-for-nafta-talks-to-be-suspended-1504137175
* nytimes.com/2017/<s>08/30/world/europe/</s>princess-diana-death-anniversary.html?hp&action=click<s>&pgtype=Homepage&clickSource=story-heading&module=second-column-region&region=top-news&WT.nav=top-news`</s>
  * Note how I remove the `file extension` here
* <s>headlines.</s>yahoo.co.jp/hl?a=20170830-00000008-jct-soci

**Comment by pocmo** [comment]
@brampitoyo I started to implement this and have some follow up questions:

* If we remove parts of the host we do not add an ellipsis character right?
  * https://mail.google.com -> google.com or …google.com
  * Or play.google.com/store/apps/details?id=com.facebook.katana&hl=en -> google.com/store/…/details?id=com.facebook.katana… or …google.com/store/…/details?id=com.facebook.katana…
* How do we handle fragments (#...) in a URL? Just remove it?
  * e.g. #Preis in https://de.wikipedia.org/wiki/AdBlue#Preis
* Port numbers and login details?
  * e.g. https://user:password@example.org:8888/foobar
* If the generated URL is still too long to display then we cut the string off at the end, right?

**Comment by brampitoyo** [comment]
> If we remove parts of the host we do not add an ellipsis character right?

Correct.

* https://mail.google.com/mail
   → google.com/mail
* https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en
   → google.com/store/…/details?id=com.facebook.katana…

-----

> How do we handle fragments (#...) in a URL? Just remove it?
> e.g. `#Preis` in https://de.wikipedia.org/wiki/AdBlue#Preis

Definitely remove it.

https://de.wikipedia.org/wiki/AdBlue#Preis
→ wikipedia.org/wiki/AdBlue

-----

> Port numbers and login details? 

Also remove it. Is it worth it to add ellipsis in place of port numbers/login details? I don’t think so.

https://user:password@example.org:8888/foobar
→ example.org/foobar

-----

> If the generated URL is still too long to display then we cut the string off at the end, right?

This will almost certainly happen on long URLs. Yes. We cut the string off at the end of the URLs, rather than the start.

Thanks for working on this, @pocmo.
