### ISSUE TITLE
Confirm if we need to notify user when a new WebView update is available

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#1237]
This is coming from a [security review](https://docs.google.com/document/d/1H7fQIyxRqe7ourXOGbELE_4Z7-ASIztuEiQxtqZnkdQ/edit#heading=h.4z3ocg9beeok) on WebView for Zerda.

In summary: Users are widely unaware that they need to update their WebView version to stay secure while browsing with Focus. We might be able to mitigate the risk by educating or even nagging users about the importance of updates.

@pocmo, can we somehow confirm that users will reliably get an auto-update via Playstore for WebView updates in Focus? And for the ones who have auto-update disabled (or potentially users via #830), do the check for them, and prompt to update?

**Comment by pocmo** [comment]
This came up before: #148.

For us it's very hard to know what the latest version of WebView is for this specific device - and how it receives updates (Chrome channel vs. WebView APK vs. System update).

Some ideas:
* File this additionally as bug with Google - we are probably not the only ones who want to be able to use the latest WebView in our app.
* Collect telemetry about what WebView versions our users are running.
* Try to find documentation about if update-able WebViews are required for all Android devices since 5.0 or if there are outliers. Additionally try to find docs about how WebView is deployed and how we can make sure to know what the latest version is.

**Comment by antlam** [comment]
Leaving a note here from Triage:

- Talked about impact to end users
- Messaging concerns around challenges for user value and "why they should care"
- Difficult to understand how much of a "big deal" this would be for our users
