### ISSUE TITLE
Revisit Multitasking via tabs/other means usage histogram

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1248]
We ran into a limitation with V1 Multitasking in issue #960 where we didn't have time to limit the number of tabs a user could hold onto at one-time. Meaning users can hold an unlimited number of tabs, but they still all delete when they press Erase.

Since we're pushing ahead with an unlimited possibility in V1, I know this could have larger affects on the long-term shape of Focus. This would obviously also involve ur/ux/pm/eng. So I'm filing to use this as a follow up.

**Comment by klint** [comment]
Pertaining to @jbreckmckye remark in issue #960 about loving Focus because it is a one-tab browser at the moment, would it be possible to imagine an option to still use Focus with one tab only? In which case the navigation would be like today, no question ask when a tab is already open, just replace it.
Or allow the user to specify the max number of tabs in the parameters, which if set to 1, would just behave like today.
But maybe that's what you had in mind actually. Or not :)

**Comment by antlam** [comment]
@klint thanks for the feedback! if you take a look at the updated UX specs in #960, that's completely possible at this point.

**Comment by klint** [comment]
@antlam Thanks. Do I get things right, below?
- I will be able to set up a max number of tabs
- When navigating, as long as I don't press LONG, it stays is the same tab (whatever the '_target' is, for instance)
- And when opening from an application, I'll be asked for a new tab to be created, and if a tab is already existing and the max has been set to 1, I'll have the option to replace the existing tab.
Cheers

**Comment by antlam** [comment]
@klint 

> I will be able to set up a max number of tabs
There are no plans to make this a setting in the first version

> When navigating, as long as I don't press LONG, it stays is the same tab (whatever the '_target' is, for instance)
Correct

**Comment by antlam** [comment]
@bbinto since the feature itself is still in Beta, I think we might need to move this issue to Granite since we still don't understand what data we have yet. For Ebony, we don't have enough time to decide what the next UX course-of-action is here :)

**Comment by bbinto** [comment]
@antlam that makes total sense
