### ISSUE TITLE
Opening shortcuts/links always opens a new tab - even if there is a tab with identical URL open

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1257]
This is more of a question: If there is a tab already open, and the homescreen shortcut has exactly same URL, should Focus open the already opened tab, or should it create a new tab?  Previously we had only one tab open max, so we didn't have to worry about this scenario.

**Comment by pocmo** [comment]
Not defined in spec. Just opening a new tab is definitely less complex.

**Comment by pocmo** [comment]
I accidentally closed this issue. @bbinto did you remove the labels on purpose or is this some automatic behavior? :)

**Comment by antlam** [comment]
I think we should keep this simple for now. I see the point that it's the "same web page" and that causes some awkwardness in terms of the behaviour here.

But to keep it simple, a press on the URL should trigger a "new tab" if the user is opening it in Focus.

**Comment by pocmo** [comment]
Okay, I'll remove the "Cobalt" milestone. I'll flag it for triage so that we can decide if we want to look at this again in another milestone.
Also I'm renaming this issue: It's not only about home screen shortcuts. Whenever the user opens a URL (from another app) then we could decide to switch to the tab where the URL is already open.

**Comment by antlam** [comment]
Thanks! Going to leave my thoughts here because I will probably forget this context. 

Switching "to a tab" can get pretty messy UX-wise and doesn't seem like a hi-priority thing ATM. There's a lot of user expectations that we just don't understand yet around it and it can get way more complicated depending on how we want to continue iterating on our "multitasking" feature.
