### ISSUE TITLE
Open with Firefox (Nightly etc) not present for strava.com

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#1298]
Pixel - Android 8.0
Build 2844

1. Go to strava.com and open the 3 dot menu
2. Check for Open with Firefox

<img src="https://user-images.githubusercontent.com/1391451/30205934-2fe3a0e0-9493-11e7-8fb4-6926d51d3027.jpg" width="300" height="550" />

**Comment by pocmo** [comment]
This changed in "Denim" (#1025). We now only show up to two options:
* Open with [default] (If there's a default browser / app)
* Open with.. (If there are multiple other browsers).

The option to "download firefox" is now at the end of the list in the "Open with" sheet. But only if no Firefox channel is installed.

**Comment by ioana-chiorean** [comment]
Sorry, I don't understand. I do have Nightly and beta installed and it does show for to her  websites.  This is missing:

- Open with [default] (If there's a default browser / app)

Forgot to mention that this works for other pages, for example for facebook.com: 

![photo_2017-09-08_16-28-43](https://user-images.githubusercontent.com/1391451/30213787-d0ee56b4-94b2-11e7-931f-46cb1f17d454.jpg)

**Comment by pocmo** [comment]
Can you go to strava.com, click on "Open with.." and post a screenshot of this? I assume that you have an app that is registered for "strave.com" URLs and that's why there's no default app for this URL.

**Comment by ioana-chiorean** [comment]
@pocmo I do have one (like I have for facebook too)

<img src="https://user-images.githubusercontent.com/1391451/30215846-f1f21d08-94b9-11e7-97bf-15b79712dc33.jpg" width="300" height="550" />

**Comment by pocmo** [comment]
I assume if you click a strava.com link in a different app (maybe a note taking app) then Android will show you a screen to pick an app (Strava or a browser). [There can be different defaults based on the URL if some apps register for specific domains]. Afaik Facebook doesn't do that.

**Comment by pocmo** [comment]
On Android apps can register for specific URLs (e.g. "I'm the Mozilla app and whenever someone opens a mozilla.org/...whatever URL then this should open the app and not in the browser"). This means for a specific URL there could be multiple apps that want to open this app.

Whenever the user clicks on a URL that multiple apps can open Android will show an "Open with" sheet so the user can make a decision. In this sheet the user can say "always open in app X" and from this point on Android will always open the specified app and not ask anymore.

In Focus we have a menu item "Open with [default]". This menu item always shows up when there is a default app for the current URL. Most of the cases this might be the default browser (because no other app wants to open the URL). But sometimes it can be another app (e.g. on a play.google.com URL it can be Google Play). To determine what app we show here we ask the system: "What is the default handler for this URL"?. This will work whenever there's a default defined. In situations where there is no default, because there are multiple apps and the user has made no decision so far ("Always open in.."), we do not get a default app from the system. In this situation we do not show the menu item. However there's still the option to select "Open with..." and select an app from the sheet.

With this implementation this is not strictly a bug: In this case above the URL can be opened by the default browser or the strava app and no default handler has been picked yet.

-> We need to define a new expected behavior and change the implementation if we want to.
