### ISSUE TITLE
Focus does not cache intermediate CAs; can cause SSL errors on sites that work in other browsers

### ISSUE THREAD

**Issue by wesinator** [mozilla-mobile/focus-android#1338]
Focus 2.0 on 6.0.1
WebView 61.0.3163.98

https://help.equifax.com gives a "Secure connection failed" error, but the site works in Chrome 61

**Comment by mcomella** [comment]
When loading help.equifax.com, [`onReceivedSslError` is being called](https://github.com/mozilla-mobile/focus-android/blob/a79c096ff138422320bd5a980c085a9afdec58a3/app/src/webview/java/org/mozilla/focus/webview/FocusWebViewClient.java#L252):

```java
    public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
        handler.cancel();

        // WebView can try to load the favicon for a bad page when you set a new URL. If we then
        // loadErrorPage() again, WebView tries to load the favicon again. We end up in onReceivedSSlError()
        // again, and we get an infinite loop of reloads (we also erroneously show the favicon URL
        // in the toolbar, but that's less noticeable). Hence we check whether this error is from
        // the desired page, or a page resource:
        if (error.getUrl().equals(currentPageURL)) {
            ErrorPage.loadErrorPage(view, error.getUrl(), WebViewClient.ERROR_FAILED_SSL_HANDSHAKE);
        }
}

If we call `handler.proceed` instead of cancel and comment out the `ErrorPage` line, we load the page successfully. I'm looking into what we can do about it.

**Comment by mcomella** [comment]
The error we're receiving is `SSL_UNTRUSTED`, "The certificate authority is not trusted" for the primary url, https://help.equifax.com. Here's the full `toString()`:

primary error: 3 certificate: Issued to: CN=help.equifax.com,O=Equifax Inc,L=Alpharetta,ST=Georgia,C=US;
Issued by: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US;
 on URL: https://help.equifax.com/

Chrome and Firefox on both desktop and Android have no issues loading the site, nor do they indicate any troubles in the UI.

**Comment by mcomella** [comment]
It appears a new app with a fresh WebView gets the same SSL error so it's not something we're misconfiguring (though maybe we should try Chrome's user agent). I don't see anything in the logs (desktop browsers, fresh WebView, Focus) that indicates a problem.

**Comment by mcomella** [comment]
I found two possible causes:
- [Symantec certs only work for 10 weeks from the build date of](https://stackoverflow.com/a/41792850/2219998) Chrome 53 and 54 (so they expire Jan. 2017); they're fixed in Chrome 55. WebView might still be affected, however.
- [Google intends to deprecate Chrome support for existing Symantec certs](https://www.theregister.co.uk/2017/03/24/google_slaps_symantec_for_sloppy_certs_slow_show_of_snafus/) ([+ mailing list announcement](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/symantec%7Csort:relevance/blink-dev/eUAKwjihhBs/rpxMXjZHCQAJ)): I don't think sites are affected by this just yet though

Note: Symantec is the authority behind help.equifax.com.

**Comment by mcomella** [comment]
Curiously, the WebView Browser Tester on my Pixel emulator works for help.equifax.com; it mentions "58.0.3029.125" at the top of the screen.

**Comment by mcomella** [comment]
Higher priority issues so I'm not actively working on this.

**Comment by mcomella** [comment]
My next step would have been to debug the SSL cert using command-line tools and see what's different in it from other SSL websites. Then I would have investigated the Android system to see if there was a discrepancy in the certs (maybe Chrome, Firefox, and the WebView browser all ship their own set of certs).

**Comment by wesdawg** [comment]
`https://help.equifax.com/: (60, 'SSL certificate problem: unable to get local issuer certificate')`
It may have incomplete chain.

**Comment by mcomella** [comment]
> It may have incomplete chain.

I don't understand this output at the moment but this seems plausible:

```bash
$ openssl s_client -connect help.equifax.com:443
CONNECTED(00000003)
depth=0 /C=US/ST=Georgia/L=Alpharetta/O=Equifax Inc/CN=help.equifax.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /C=US/ST=Georgia/L=Alpharetta/O=Equifax Inc/CN=help.equifax.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 /C=US/ST=Georgia/L=Alpharetta/O=Equifax Inc/CN=help.equifax.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Georgia/L=Alpharetta/O=Equifax Inc/CN=help.equifax.com
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 Secure Server CA - G4
---
```

In Certificate chain, "s:" is "subject" and "i:" is "issuer".

In the final summary, we also see:
```
Verify return code: 21 (unable to verify the first certificate)
```

**Comment by mcomella** [comment]
I only skimmed this, but ["Missing intermediate certificate authority" in the Android SSL docs looks relevant](https://developer.android.com/training/articles/security-ssl.html#MissingCa):

> What is interesting to note here is that visiting this server in most desktop browsers does not cause an error like a completely unknown CA or self-signed server certificate would cause. This is because most desktop browsers cache trusted intermediate CAs over time. Once a browser has visited and learned about an intermediate CA from one site, it won't need to have the intermediate CA included in the certificate chain the next time.

But they mention Android apps are less forgiving. WebView might also need to create a set of trusted intermediate certificates.

**Comment by mcomella** [comment]
Here's the error I get when using `URLConnection`:

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException:
  PKIX path building failed:
    java.security.cert.CertPathBuilderException:
      No issuer certificate for certificate in certification path found.

	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.mozilla.focus.shortcut.IconGeneratorTest.testEquifaxSSL(IconGeneratorTest.kt:67)
```

**Comment by mcomella** [comment]
I think I understand the problem. https://help.equifax.com is providing an intermediate CA. Android only comes with root CAs by default and these intermediate CAs, which are verified by the root CAs, are typically cached by browsers while navigating the web. If an intermediate CA is cached from a one page, it's valid on another page (which I assume is how help.equifax.com thinks you're supposed to use it). **It's unclear if WebView does automatic caching of these intermediate CAs.**

The intermediate CA we're missing is `Symantec Class 3 Secure Server CA - G4`. I looked into my cached intermediate CAs in Firefox and I found it there (under VeriSign, Inc). Notably, Firefox does not ship with this such that **a clean desktop Firefox profile will fail to connect to help.equifax.com.** I filed [bug 1411792](https://bugzilla.mozilla.org/show_bug.cgi?id=1411792) for tech evangelism to reach out to them to fix this issue.

The best we can do to work as well as other browsers would be to ensure WebView is caching intermediate CAs. If WebView can do this automatically, we should enable it. If not, we should do one of...
- Implement custom intermediate certificate caching (error prone and a security risk). There's a sample implementation from the AOSP browser linked in the [`onReceivedClientCertRequest`](https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedClientCertRequest(android.webkit.WebView,%20android.webkit.ClientCertRequest)) docs.
- Use code from elsewhere (library? Chromium?). We'll have to make sure it stays up to date with upstream to plug security holes
- Nothing (WONTFIX)

I also filed #1563 to allow users to ignore SSL errors, which would be a workaround for this issue. It goes hand-in-hand with this one.

**Comment by mcomella** [comment]
> ensure WebView is caching intermediate CAs. If WebView can do this automatically, we should enable it.

After searching, I have found no references that the WebView (or the Android system) will automatically cache CAs – in fact, [the Android's docs provide code samples to manually trust new CAs](https://developer.android.com/training/articles/security-ssl.html#MissingCa).

So we'll need to choose on of the options above for this bug. Unfortunately, since I think this greatly increases the scope of the issue and it's not urgent, I'm going to put this back into triage.

**Comment by mcomella** [comment]
> - Nothing (WONTFIX)

Some reasons we may want to take this approach:
- Caching intermediate CAs has been used [to fingerprint browsers, including Firefox](https://duckduckgo.com/?q=cache+intermediate+ca+fingerprinting&t=ffab&ia=web)
- Since the user clicks erase after each session, presumably we'd want to erase the intermediate certificates too - this may be a lot of work and risk for little gain (especially when users may be able to ignore SSL errors or open them in other browsers: #1563)

That being said, there is a case where caching intermediate certificates is useful. From [the Android SSL docs](https://developer.android.com/training/articles/security-ssl.html#MissingCa):

> Some sites do this intentionally for secondary web servers used to serve resources. For example, they might have their main HTML page served by a server with a full certificate chain, but have servers for resources such as images, CSS, or JavaScript not include the CA, presumably to save bandwidth.

**Comment by mcomella** [comment]
Actually, this is a product discussion: do we want to fix this?

Typically, if we don't fix this, the effect will be:
- Resources on some HTTPS pages will fail to load: sometimes, a site will send the intermediate CA with the initial connection and exclude the intermediate CA in loading resources (e.g. images, CSS, JS) to save bandwidth: these resources will fail to load
- Some websites will have permanent SSL errors: sometimes, a site is configured to require a cached intermediate CA (like help.equifax.com). I'm not sure why you'd configure a site like this because desktop browsers will have this problem with clean profiles

There are potential problems associated with caching:
- We could implement this incorrectly and create security risks
- Caching intermediate CAs has been used [to fingerprint browsers, including Firefox](https://duckduckgo.com/?q=cache+intermediate+ca+fingerprinting&t=ffab&ia=web)
- Since the user clicks erase after each session, presumably we'd want to erase the intermediate certificates too - caching may be a lot of work and risk for limited gain

We could also come up with alternative solutions / workarounds like letting users users ignore SSL errors or encouraging them to open SSL-failures in other browsers (#1563).

@bbinto What do you think? (CC @pocmo @Sdaswani)

**Comment by pocmo** [comment]
> We could implement this incorrectly and create security risks

I tend to WONTFIX because of that. Do we have the resources and knowledge to maintain and keep this code secure? Using the AOSP browser code seems to be acceptable if it appears to be maintained and if it is rather small amount of code.

**Comment by bbinto** [comment]
>We could also come up with alternative solutions / workarounds like letting users users ignore SSL > errors or encouraging them to open SSL-failures in other browsers (#1563). 

@Sdaswani and @pocmo  - How about this?

I just don't want the user end up in a dead end without knowing why/how/what to do.

**Comment by bbinto** [comment]
I like the probe idea to start with first.

**Comment by mcomella** [comment]
> @mcomella Would it be possible to add a telemetry probe for this problem? Would be interesting to see how often that happens in the wild.

I don't think we can distinguish between just any SSL error and missing an intermediate CA, but we can do something creative:
- We can add a probe to report SSL errors that occur for the non-primary URL (e.g. you go to google.com and get SSL errors for additional requests like images): this is more likely to indicate intermediate CA errors but sometimes this could just be regular SSL errors
- We can add a checkbox to report SSL errors to Mozilla, like we do on desktop, and we can investigate the specific URLs that are causing problems for Focus.
- ^ Blank Firefox profiles have the same issues as we have, I wonder if we can borrow the investigations they've done (I'm going to try to ask around, but I find it hard to get in contact with desktop folks)

**Comment by mcomella** [comment]
> We can add a checkbox to report SSL errors to Mozilla, like we do on desktop, and we can investigate the specific URLs that are causing problems for Focus.

Note: we may be able to share the same endpoint as desktop: https://firefox-source-docs.mozilla.org/browser/base/sslerrorreport/index.html
