### ISSUE TITLE
New tab button

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1363]
Currently it's not possible to open an empty tab.

**Comment by codebu5ter** [comment]
Currently, there's no way to close an individual tab, but to repeatedly press the back button until it closes. I've implemented a more user-intuitive way, in which the user just has to long press the tab and it will be closed.

The same goes for closing all tabs, which requires two clicks at the moment. I've implemented the same functionality to close all tabs, in which the floating action button needs to be long pressed to close all tabs, which is more user-intuitive.

My solution doesn't address the above feature of creating an empty new tab, but it could pave the way for this feature. Instead of having a delete button when only a single tab is open, we could have a '+' icon, which would signify the ability to add a new tab. In case the user wants to delete the data on the current tab instead, he/she can always long press on the '+' icon to delete the current tab.

**Comment by bbinto** [comment]
Will be investigated in #1250

**Comment by moshpirit** [comment]
Is this feature taking much longer to implement? (just asking, no bitterness intended)

**Comment by vesta0** [comment]
Closing this issue (duplicate) as it is currently being addressed in #1250
