### ISSUE TITLE
Titles for tabs

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#1365]
Added by @bbinto

### User Benefits
- Better way to go back to the page that has been visited before (get users back to their results faster)
- Provide more context / reference to the opened tabs

### What/How
- Add title to opened tabs in tabs tray

### Acceptance Criteria
- Avoid to introduce a way to spoof our users

### Metrics
- Watch if users now open/close/revisit tabs more frequently?

---
Please consider to add an option to display page titles on the tabbar instead of the links.

**Comment by pocmo** [comment]
@dimqua Do you mean the toolbar or the sheet that shows all tabs?

**Comment by pocmo** [comment]
Let's make sure we do not introduce a way to spoof our users. :)

**Comment by brampitoyo** [comment]
@dimqua While showing page title instead of the link _in the URL bar_ can lead to higher risk of spoofing and phishing, showing page titles _in the tab list_ does make a lot of sense.

It solves these problems:

![android tab names old 2x](https://user-images.githubusercontent.com/51007/41209190-eed94cca-6d7d-11e8-91a2-6d0ae98db73a.png)

1. Sometimes, domains don’t always tell you what the webpage is _about_.
2. When you open multiple pages within the same domain, things can look ambiguous.

By showing page titles:

![android tab names 2x](https://user-images.githubusercontent.com/51007/41209226-31290c3c-6d7e-11e8-95f8-cbd58ab2518d.png)

1. It’s easier to distinguish the content of each tab.
2. Spoofing and phishing risk still happens (as it does in our current solution). However, checking them is straightforward (although some scammers hide the spoofed URLs very well; manual checking is not perfect). Just open each tab and see whether the URL matches the website they claim to represent.

By showing page titles in the tab list, users will get a bit more readability into each tab content. In that respect, having this feature makes a lot of sense.

**Comment by brampitoyo** [comment]
If everything looks good here, this issue is ready for Engineering breakdown.

**Comment by ekager** [comment]
PR for this open, we can merge whenever product wants this in a release :)

**Comment by ekager** [comment]
Do we want this in 7.0? I can pull the ticket into the 6.3 sprint.

**Comment by brampitoyo** [comment]
This is a quality-of-life improvement, so it would be good to include it in the 6.3 release.
