### ISSUE TITLE
[Partners] Home Screen Should Be Partner-Brandable

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#1423]
The home screen should be able to have branding elements of partners.

It should be easily-configurable so we don't have to do custom work on a per-partner basis.

Please provide both a UX and Engineering T-shirt estimate for this work. The Engineering T-Shirt estimate will follow the UX designs.
S: 1 Sprint
M: 2 - 3 Sprints
L: 4 - 6 Sprints

**Comment by antlam** [comment]
WIP Mock to show possibilities, not final design:

![splash keyboard up - mdpi](https://user-images.githubusercontent.com/1994820/31141764-29a3bd8e-a82d-11e7-8a97-5dbfb063a7cb.png)

**Comment by pocmo** [comment]
I'd be very cautious here. From Fennec we know that partner distributions are something we have to support for a very long time. Every UI change we do is something that can become a roadblock in future iterations. In this case: If we for example decide we need some kind of top site / bookmark grid because users visit the same pages all the time then we are suddenly stuck with a giant partner image here that we have no place to put.

**Comment by antlam** [comment]
@pocmo I completely agree. We need to maintain the Vision and Mission for Focus when going after these opportunities.

**Comment by Sdaswani** [comment]
Agree @pocmo @antlam cc @bbinto
