### ISSUE TITLE
Very slow loading on apkmirror.com

### ISSUE THREAD

**Issue by motfis** [mozilla-mobile/focus-android#1479]
I tried to compare the performance to other browser, such as google chrome, and even the latest "firefox rocket". For example I open apkmirror.com, anf ff focus need like more than 10 seconds to load completely, while other browsers is much-much faster. I have tried to reinstall, disable trackers, etc, and it seems that doesnot solve this slow loading. Looks like the problem is originated from the app itself.
Can anyone confirm this slow loading time? And maybe this issue can be solved in the next release?

**Comment by mcomella** [comment]
Sorry it took so long to get back to you. I haven't been able to reproduce this issue – in fact, Focus tends to load faster than other browsers (like because there is less browser chrome code running and we're blocking requests to trackers).

@motfis What's your user agent? You can find it by visiting https://www.whatismybrowser.com/detect/what-is-my-user-agent in Focus.

**Comment by mcomella** [comment]
Actually, I see this on apkmirror.com, even with trackers disabled (but haven't witnessed it on other pages). Adding back to triage...
