### ISSUE TITLE
[meta] Add feature flags

### ISSUE THREAD

**Issue by jenn-chaulk** [mozilla-mobile/focus-android#1550]
From focus-android created by [jenn-chaulk](https://github.com/jenn-chaulk) : mozilla-mobile/focus-android#1549  

From focus-android created by [liuche](https://github.com/liuche) : mozilla-mobile/focus-android#1515  

We want to add the ability to turn on/off features based on feature flags so that we can
1) incrementally land features that may not be complete
2) allow predictable feature releases

Breakdown:
- [ ] Do investigation into whether we want to do this or not. Additional tasks may follow.

**Comment by liuche** [comment]
To give some context, Feature Flags is for controlling features so they are in the code base, but not visible. This doesn't strictly require UX because the main use case is to turn features on/off for builds (dev vs release vs QA builds).

However, one thing we could do is to add a settings item for turning features on/off, which could be nice for our beta users (if they want to turn on experimental/partial features) or for people to manually test the pieces of features as they land - but you can also decide that we don't need to expose any UI for this.

**Comment by bbinto** [comment]
closing in favour of #1515
