### ISSUE TITLE
[ux] Quick access to favourite sites (requiring login) - deliverables

### ISSUE THREAD

**Issue by lime124** [mozilla-mobile/focus-android#1609]
#1546 [Meta] [ux] Quick access to favourite sites (requiring login)

- [ ]  specs for autocomplete (IA, mocks, visual specs)
- [ ]  copy

**Comment by lime124** [comment]
Just need final copy

![flow - add new url](https://user-images.githubusercontent.com/287322/33045360-62d020da-ce01-11e7-9bf2-d7dfe78e9f26.png)
![flow - remove custom url](https://user-images.githubusercontent.com/287322/33045361-62e44ee8-ce01-11e7-9b25-d9ad5dd9d37c.png)
![other states](https://user-images.githubusercontent.com/287322/33045362-62f8ef42-ce01-11e7-8581-bf3f7d8df6f2.png)

**Comment by lime124** [comment]
@itsDevyani - here is the android one

**Comment by Sdaswani** [comment]
Thanks @lime124 ! I was talking to @bbinto about the autocomplete feature and we are wondering is there a way to quickly add to the custom autocomplete list from the URL bar? Also do we need to advise users that the list won't be backed up (i.e., if the app is deleted, the list is lost)?

**Comment by lime124** [comment]
@Sdaswani 

Re: adding a way to the URL bar. That was actually my initial take on it as well but later changed my stance after a lot of thinking on the problem. We have pretty limited real estate and people like the simplicity of the app. I want to keep things clean and simple. I know we have the overflow menu on Android, but I want to be cautious about that being over-used and becoming a catchall. I'd like to see how the telemetry goes and then follow up with another iteration when we have more information. 

This is something I actually want to get better at and talk about more in Austin - getting a MVP out there faster and iterating on it rather than over-designing a solution that people aren't going to find useful.

To your second point - we don't do it for search engines either. Since our value prop is privacy and we don't sync with an account or anything, I don't think people would have the expectation that that data is saved somewhere.

**Comment by bbinto** [comment]
Thanks @lime124  -- I'm sure we'll hear feedback if/how people like the implementation of this feature.

Please yes, let's talk about MVP, fast validation ideas etc. in Austin, please add it to our shared agenda doc.

>  I'd like to see how the telemetry goes and then follow up with another iteration when we have more information.

Please make sure to inform eng what specific telemetry probes you want to see. What do you try to learn besides people using/adding/removing URLs?

@pocmo, for your breakdown for now I think the following probes should be added:
- event when add, remove URL is used
- # of items in custom list
- pre-defined / custom autocomplete toggle off/on
- # of times/URL loaded by using pre-defined or custom list

**Comment by pocmo** [comment]
@lime124 I wonder if we need the ability to reorder the autocomplete list. In the list we are shipping with Focus the order determines which domain might be autocompleted first. For example if you type "g" we will autocomplete to "google.com" instead of "gap.com".

**Comment by Sdaswani** [comment]
> To your second point - we don't do it for search engines either. Since our value prop is privacy and we don't sync with an account or anything, I don't think people would have the expectation that that data is saved somewhere.

Fair point @lime124 . Though if we could transparently allow users to opt-in to storing their data in the cloud _securely_, it may help retention (since a user made more investment into the app). Oddly I don’t see any type of CloudKit service baked into (Google’s) Android, so this isn’t an option currently.

**Comment by pocmo** [comment]
There's an Auto Backup Service on Android 6+:
https://developer.android.com/guide/topics/data/autobackup.html

**Comment by pocmo** [comment]
@lime124 @BrianNJones I have some questions regarding the Strings and/or mocks:

* The "Autocomplete Status" in the mock is "On". However the text on the right says it is "Enabled" or "Disabled"
* The text says the default value for the pre-installed autocomplete list is going to be "off" - Are we changing the behavior of the app here?
* Do we need an accessibility String for the "reorder" icon? I can see what other (Google) apps use.
* We probably need an accessibility string for the trash can icon. Maybe just "Remove"?
* The "empty state" mock contains a dummy explanation text. Do we need a text / string here?

For future features it might make sense to list all the strings somewhere. Searching them in the mocks and re-typing them is error-prone. :)

**Comment by antlam** [comment]
> Fair point @lime124 . Though if we could transparently allow users to opt-in to storing their data in the cloud securely...

Going back to the original feedback of adding directly from the URL bar 🤔 .... maybe we could use the long-press context menu for this? 

1. User navigates to somesportswebsite.com/traderumours
2. They decide they want to save this frequented site of theirs
3. Long-press on the URL bar (or anywhere else maybe?)
4. User presses a button to quickly add the site they're on to this list

Thoughts?

**Comment by antlam** [comment]
[Similar feedback here](https://github.com/mozilla-mobile/focus-ios/issues/638) about the duplicate "Autocomplete" prefs as well. Especially if we're going to have another one in the top level Settings too :)

Also, maybe we could simplify the input field here too and remove the Floating label text? Since we already have the top title (Add custom URL), the placeholder (Paste or enter URL) and the example, (Example: example.com).

Quick suggestion for the "Remove Custom URL Flow" as well, typically on the Android platform, the overflow menu contains "Actions" and so "Remove" would be the action of removing rather than "Selecting" or changing state. On iOS, "Edit" takes this place here so that makes more sense. Not to say we can't diverge from this platform pattern, but I think we could leverage that to make this a bit clearer here too.

Perhaps we could say "Select" (and maybe also add a "Select all" in the future!) instead of of "Remove"? If we want, we could also implement a long-press action for "selecting" when a user long-presses on the items in the list :)

@lime124 thoughts?

**Comment by Sdaswani** [comment]
> Going back to the original feedback of adding directly from the URL bar 🤔 .... maybe we could use the long-press context menu for this?

I'm all for anything that makes this process more automatic. :)

**Comment by bbinto** [comment]
> Going back to the original feedback of adding directly from the URL bar 🤔 .... maybe we could use the long-press context menu for this?

I like that idea we well.

>The text says the default value for the pre-installed autocomplete list is going to be "off" - Are we changing the behavior of the app here?

@lime124 , could you explain if that's the case and why. I'm hesitant to turn it off for this release.

**Comment by lime124** [comment]
you guys were busy!

@pocmo @bbinto - I would like to turn the default state to off (so yes changing the current behaviour). During usertesting (and anecdotally myself and Brian as well), I noticed confusion about why URL were auto-complete if this app is supposed to be private. One person commented they though Focus was somehow getting their history from their current app. Since people didn't activate it, they don't realize this is a feature or how it's working. This is why I'm advocating for changing the default state to off. I think this should only affect new installs and not those people who already have it installed.

@bbinto @Sdaswani @antlam  - we can add it into a context menu if you want, but I think our goal for auto-complete (and in general) should be to avoid user intervention (once enabled). What I mean by that is improve our built-in list so it just works and this process is a rare exception. I also want to reiterate that I think it would behoove us to wait for some telemetry to see how many people are using the manual entry. I don't see the need to over complicate things when it isn't necessary. 

@antlam The reason I chose to use Remove is because there is only one Action that can be done to the list items. In instances where there are multiple actions it does make more sense to use Select or Select All and then select which Action to perform, but in this instance, as with Search Engine, that isn't the case. You can find an example of this in the Android Language Settings UI.

Answered the rest of @pocmo questions over slack. Thanks everyone!

**Comment by antlam** [comment]
> You can find an example of this in the Android Language Settings UI.

Sorry I should clarify! 

Yes, this language does exist in Android Settings.

But what I was trying to say was that since the action a user needs to perform _after_ pressing "Remove" is to **select** what they _want to remove_..... maybe this should follow more of an Android convention and say "Select" instead of "Remove" :)

**Comment by Sdaswani** [comment]
@lime124 happy to wait for telemetry on the current solution. 👍 🌮

**Comment by bbinto** [comment]
>  I think this should only affect new installs and not those people who already have it installed.

Is that possible, @pocmo? 

We need to make sure to have the ability to create a cohort of the new set of users via telemetry so we can actually measure if they change the autocomplete to on or keep it off. 

Here was my probe proposal from earlier, is this still do-able/valid?

- event when add, remove URL is used
- #of items in custom list
- pre-defined / custom autocomplete toggle off/on
- #of times/URL loaded by using pre-defined or custom list (over other search bar activities)

>  I noticed confusion about why URL were auto-complete if this app is supposed to be private. 

@lime124, @BrianNJones - I could still see the same worries arise even for custom autocomplete lists, will the "Learn more" inform users that the list with xxxxx.com will stay only on the device and won't be shared / send to us?

**Comment by pocmo** [comment]
> Is that possible, @pocmo?

The problem here is that we previously didn't have a setting If we would have had a settings previously then changing the default would only affect new users. I filed #1813 yesterday and can do some research. We can detect app updates for the "What's new" feature. So maybe we could use that. We definitely should think of a plan B in case we have to pick a default for **all** users.

> Here was my probe proposal from earlier, is this still do-able/valid?

I'm currently implementing telemetry for this feature in #1771. I'll copy your comment over. This seems doable.

**Comment by lime124** [comment]
i think we can close this now...
