### ISSUE TITLE
Renumber telemetry timestamps so sessions can be split up (for Redash)

### ISSUE THREAD

**Issue by wcbeard** [mozilla-mobile/focus-android#1633]
When querying from the events table (telemetry_focus_event_parquet), I'm seeing about 6% of the pings returning sequences of events where the timestamps are not monotonically increasing. It is common that there will be a foreground event half way through, and the time stamp restarts at 0. I'm not sure how much of this is expected behavior.

[Here is a query](https://sql.telemetry.mozilla.org/queries/48551/source) with some example pings.

**Comment by pocmo** [comment]
The current implementation does:
* Use the "time since boot" to calculate the timestamps of events.
* We use the timestamp of the first event as baseline and the following events' timestamps are relative to the first event.
* For various reasons it can happen that we cannot write the actual ping to disk before the process dies (e.g. app crash, app killed manually, ..). The next time the app starts we'd continue with a new series of events (starting at 0). When writing the ping to disk (in order to send it) we would write all events into it (also the ones from the previous run).

It's not directly a bug - but caused by the way this is implemented. What is your requirement for analyzing the pings? We can change that behavior.

Some ideas:
* Always use "time since boot" and don't do any "normalization". With that a process restart wouldn't create a new sequence but continue to previous one (maybe with large gap at times). We might see the same behavior as above for hard reboots (device runs out of battery).
* On next app start send ping for already gathered events so that they do not get mixed with the events we are collecting next.

**Comment by wcbeard** [comment]
> @pocmo: What is your requirement for analyzing the pings?

My interest now is in looking at issues/events that happen within a session. 

If I have a ping where the timestamps look like [0, 2, 4, 0, 1, 5], it sounds like (from your third point) I should be splitting it up into two sessions, with timestamps [0, 2, 4] & [0, 1, 5]. Am I understanding you correctly?

**Comment by pocmo** [comment]
> If I have a ping where the timestamps look like [0, 2, 4, 0, 1, 5], it sounds like (from your third point) I should be splitting it up into two sessions, with timestamps [0, 2, 4] & [0, 1, 5]. Am I understanding you correctly?

Yes, for our current definition of "session" this would be two sessions in one ping.

**Comment by liuche** [comment]
@wcbeard just checking in since it's been about a month since the last updates on this bug and we're reaching the end of this sprint. How do the session timestamps look with this context? Would you prefer the other options mentioned earlier, or is this ordering of timestamps separated by session fine?

**Comment by pocmo** [comment]
We talked about this briefly on Slack some time ago:

> I wonder if we need to do a change in our telemetry library here? -> https://github.com/mozilla-mobile/focus-android/issues/1633 

> hmm…I would *like* that, but since I pull a lot of the stuff into python I think I’m able to manually split them on my own
> but for redash users, it would probably more convenient to have the pings already split up in the data set
> It could be tricky figuring out how to renumber the sequences, though
> I guess I feel I’m not familiar enough w/ the telemetry to know how much engineering effort it would require vs the improvements in information, to be able to give a strong recommendation

Probably something we could do in the future but maybe not a P2 anymore.

**Comment by liuche** [comment]
Removing the milestone and priority to surface in triage and updating the title to reflect the new issue. Mentioning @bbinto here in case she has feedback that this should still stay in the milestone!

The context for setting priority (mainly for our redash consumers; Q: who is that), what is the priority for updating our telemetry timestamps so when sessions are combined into a single telemetry report/ping they can easily be split up?

**Comment by bbinto** [comment]
I think we should ask @wcbeard why/how he'd use the updated data

**Comment by wcbeard** [comment]
Sorry all, just saw the updates

@bbinto:
> why/how he'd use the updated data

Current things I’ve been working on have involved looking at what happens in the 1st or 2nd session, where these are defined by `seq == 1` or `seq == 2`. In this case, the bug could lead to inflated statistics for what happens (I.e., a foreground event could be double counted if we’re combining 2 sessions into a single session-ping). 

Another analysis I could see would be looking at how early a user discovers a feature, and how soon do we see this event. In this case, the bug could similarly make it look like features are used sooner than they actually are. 

@liuche:
> Would you prefer the other options mentioned earlier, or is this ordering of timestamps separated by session fine?

Either of the options mentioned above sounds good, but I like the 2nd a bit better since it keeps the normalization. (_On next app start send ping for already gathered events so that they do not get mixed with the events we are collecting next._)
