### ISSUE TITLE
Pull down to refresh animation freezes on error page 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#1685]
<img width="318" alt="screen shot 2017-11-09 at 11 03 53 am" src="https://user-images.githubusercontent.com/25442310/32624321-bc1b9826-c53d-11e7-90d9-b5aa091a5b0c.png">

Found when investigating #1610

STR: 
1. Go to invalid address
2. Pull down to refresh 

Expected Behavior : Error page is refreshed 
Behavior : Spinning loading animation never goes away

**Comment by pocmo** [comment]
Ouch.

@ekager Do you have time to investigate that?

**Comment by ekager** [comment]
Yes, I can look into it!

**Comment by pocmo** [comment]
@ekager I am unable to reproduce this on my device. What Android version / device are you using?

**Comment by pocmo** [comment]
Oh, and maybe the "user agent" to see the WebView/Chrome version.

**Comment by pocmo** [comment]
@npark-mozilla Do you see this on your devices?

**Comment by npark-mozilla** [comment]
@pocmo ah yes, I see this.  I go to an url with invalid domain, and the spinning wheel doesn't go away upon refresh. I built it from the tip of the master and loaded it.  (I'm on Android 8.0 Pixel 2)

**Comment by pocmo** [comment]
@npark-mozilla What's the user agent on this device? I tried on a Pixel XL with Android 8.1 and could not reproduce.

**Comment by npark-mozilla** [comment]
It's 
![image](https://user-images.githubusercontent.com/6930774/32902771-4cc81286-cac1-11e7-968f-d8db9170188a.png)

**Comment by pocmo** [comment]
This seems to be caused by the fix for #1179 (PR #1526). In this situation WebView only calls onPageFinished() but never onPageStarted(). In #1179 we implemented an optimization that we will ignore onPageFinished() when we are not actually loading (-> without onPageStarted()). Because of that we never reset the animation. This doesn't happen to the loading bar and toolbar animation because this one is triggered by onPageStarted() which is never called.
