### ISSUE TITLE
Issuses with buddy build and Firefox Focus

### ISSUE THREAD

**Issue by afarsi** [mozilla-mobile/focus-android#1707]
Hi Firefox Focus team.
I have alpha version(Test Version) of Firefox Focus for Android on my mobile phone.

I received build #3353 email, on Thursday (2017/11/09), and Friday (2017/11/10) build #3364.
I installed 3353 on Thursday (2017/11/09), and 3364 on Friday (2017/11/10). But when I installed build 3364, I received update notification in app, when I tapped on update button, it wanted to download older build (build 3353)!!!

Note: Unfortunately, there isn't any way to check what build number is on device?! Because build number in about window is different than four digits like 3353 and 3364 and it's a long number. In addition, in application settings of android only showing version of Focus (For example: 2.5, not build number).

I think build number in about window and in Buddy build email should be in same format, not one of them is four digits and another is long number. Current status is a bit confusing.

Note: Before now, we had more problems with it. Because version of Focus that we could update via on Buddy Build was older than version of Focus that was on Google Play (Released version, not beta)! This problem solved by you and publishing new focus versions via Buddy Builds every Friday regularly. But as you saw in upper lines, it seems this problem happening again. I described reasons of it in upper lines.

In Addition, I have another problem with Firefox focus and buddy build. There is a gap between when i receive email of new build of Focus and when i receive update notification on my mobile phone(When i open the Focus app) via buddy build. This gap is few days(Between email and update notification).  As result, I should move the link in email to my phone and download focus or wait few days for update notification!

Another problem is about loss of update notification! When i recieve update notification, if i haven't time to install that update on time of notification, or cleared update notification, i will not receive any update notification again and there is not way(Like check for Update button in Firefox for Android's About window) to check for update manually! I think Firefox focus alpha version should be able to check for update manually while it's not on Google Play. Yes. It's on Google Play and i can subscribe to beta program via google play, but google play have beta version not alpha version(Latest and latest build) of focus.  

I think Firefox for Android Nightly have better updating system than Firefox Focus. It's available via google play and it have a check for update system manually and automaticly and independently. What’s your opinion about using a system like Firefox for Android Nightly?
Thanks.

Note: I talked with Delphine lebedel about it in telegram group of L10n teams. She recommended to submit a bug about it.

Amir Farsi
Member of Persian language L10n Team.

**Comment by pocmo** [comment]
Thank you for reporting this!

Getting prompted for older builds is something that Softvision saw too in the past: #928. Unfortunately this is a bug in the buddybuild SDK and can't be fixed by us.

> Note: Unfortunately, there isn't any way to check what build number is on device?! Because build number in about window is different than four digits like 3353 and 3364 and it's a long number. In addition, in application settings of android only showing version of Focus (For example: 2.5, not build number).

Yeah, they used to be the same but nowadays we generate the build number ourselves for a couple of reasons. The basic rule is still: The higher the build number the newer the build. They never go backwards.

A build number follows this pattern: yDDDHHmm (Day of build)

* y   = Double digit year, with 16 subtracted: 2017 -> 17 -> 1
* DDD = Day of the year, pad with zeros if needed: September 6th -> 249
* HH  = Hour in day (00-23)
* mm  = Minute in hour 

For September 6th, 2017, 9:41 am this will generate the versionCode: 12490941 (1-249-09-41).

> I think Firefox for Android Nightly have better updating system than Firefox Focus. It's available via google play and it have a check for update system manually and automaticly and independently. What’s your opinion about using a system like Firefox for Android Nightly?

Absolutely agree. Our goal is to eventually use the Alpha channel on Google Play (Currently we only use the Beta channel) to distribute Nightly builds of Focus for Android. The big blocker here is that we haven't fully automated our release builds yet and it's too inconvenient to create releases manually every day. :-)

**Comment by pocmo** [comment]
We stopped using buddybuild. For now preview builds (potentially unstable!) are available here: https://bit.ly/focus-preview-builds
