### ISSUE TITLE
Screen does not sleep in fullscreen media playback mode when paused/stopped

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1720]
STR:
Open a video, and make it fullscreen.
pause/stop the video playback, but keep it in fullscreen mode.

Actual: the screen does not sleep even though it's stopped/paused. (This does not happen when the media is not in fullscreen mode)

Just double checked that in Chrome paused fullscreen mode enters sleep mode normally.

**Comment by ekager** [comment]
When entering full screen mode, we actually [set this behavior](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L531) and then don't detect the video being paused. Not sure if it's possible through the webview to detect this?

**Comment by pocmo** [comment]
Yeah, for the current implementation this is our intended behavior: During full screen we keep the screen on so that it doesn't turn off doing playing videos etc.

Some time ago I saw a snippet where they extracted a VideoView from the full screen view and then attach listeners to it. Might be a solution here - although a bit hacky too.

**Comment by lobontiumira** [comment]
@pocmo, if this is the expected behavior, can this issue be closed?
Thank you!
