### ISSUE TITLE
Autocomplete: Add telemetry probes for autocomplete

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1771]
meta: #1766 

#### Managing of autocomplete domains

* [x] Add autocomplete domain: (action, save, autocomplete_domain)
* [x] Remove autocomplete domains: 
* [x] Reorder autocomplete domain: 
* [x] Enable/Disable default autocomplete domains:
* [x] Enable/Disable custom autocomplete domains:

#### Autocompleting

* [x] Domain autocompleted
  * Which list
  * How many items are on the list

**Comment by pocmo** [comment]
Barbara's wish list from #1609:

>  -  event when add, remove URL is used
>  -  #of items in custom list
>  -  pre-defined / custom autocomplete toggle off/on
>  -  #of times/URL loaded by using pre-defined or custom list (over other search bar activities)

**Comment by pocmo** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

* Are users interested in maintaining their own list of autocomplete domains?
* How often is a typed URL autocompleted? And from which list?
* How many domains does a user have on this list? And how often are new ones added or old ones removed?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

This is a new feature that doesn't exist even in Firefox for Android. Therefore we do not have any historic data to know if it is helping users and how they use it. So far we haven't had any telemetry about autocomplete in Focus. In regards to autocomplete we have been flying completely blind so far.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

In theory we could make guesses based on Firefox for Android. However there's no telemetry for autocomplete and it doesn't allow to add custom autocomplete domains.

4) Can current instrumentation answer these questions?

_I do not know what "instrumentation" means in this case?_

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

I'll update our telemetry wiki and will add a link here. All added probes are “Interaction data” (Category 2).

6) How long will this data be collected?  Choose one of the following:

For now we want to permanently monitor this data.

7) What populations will you measure?

* Which release channels?

Firefox Focus/Klar release builds (if telemetry is enabled)

All countries, all locales.

8) Please provide a general description of how you will analyze this data.

Various redash queries to analyze usage of the feature and autocomplete behavior.

9) Where do you intend to share the results of your analysis?

Only internally in redash and with the mobile teams.

**Comment by pocmo** [comment]
@liuche --^

**Comment by liuche** [comment]
# Data Review Form (to be filled by Data Stewards)

Instructions: Data Stewards will review a request for data collection and endorse responses to each question. **If the request does not provide answers to questions, reviewers give an r- and point to the questions that can’t be answered.**

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate? (see [here](https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/data_dictionary.md), [here](https://github.com/mozilla-mobile/focus/wiki/Install-and-event-tracking-with-the-Adjust-SDK), and [here](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/index.html) for examples).  Refer to the appendix for "documentation" if more detail about documentation standards is needed.

Yes, already present on https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, telemetry toggle in Settings UI.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**

Permanent, @bbinto is responsible for monitoring data.

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

Type 2, interaction with autocomplete list, usage of it, number of items

5) Is the data collection request for default-on or default-off?
Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
No, only usage data

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**
Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No
