### ISSUE TITLE
Telemetry probe for SSL errors

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1775]
See #1338. We want to see how often our users run into SSL errors. If possible we would like to even see categories of SSL errors.

**Comment by ekager** [comment]
I did a PR for telemetry for the basic SSL error types that are received in onReceivedSslError but not sure if we wanted to also implement the more complicated solution @mcomella gave in #1138 for the ones missing an intermediate CA?

**Comment by mcomella** [comment]
> not sure if we wanted to also implement the more complicated solution @mcomella gave in #1338 for the ones missing an intermediate CA?

I think this is a chicken and egg problem: since we can't implement something that gives us the correct answer, we don't have a clear idea of what we want to learn and it's a lot of work so product hasn't prioritized it. But if we knew it occurs frequently, it might get prioritized!

Here are some possible solutions again, via https://github.com/mozilla-mobile/focus-android/issues/1338#issuecomment-342924009:

>> @mcomella Would it be possible to add a telemetry probe for this problem? Would be interesting to see how often that happens in the wild.
>
> I don't think we can distinguish between just any SSL error and missing an intermediate CA, but we can do something creative (for a lot more effort):
> - We can add a probe to report SSL errors that occur for the non-primary URL (e.g. you go to google.com and get SSL errors for additional requests like images): this is more likely to indicate intermediate CA errors but sometimes this could just be regular SSL errors
> - We can add a checkbox to report SSL errors to Mozilla, like we do on desktop, and we can investigate the specific URLs that are causing problems for Focus.
> - ^ Blank Firefox profiles have the same issues as we have, I wonder if we can borrow the investigations they've done (I'm going to try to ask around, but I find it hard to get in contact with desktop folks)

In my opinion (disclaimer: after brief investigation), I think we should start with regular SSL errors (if they're low, then we don't need to worry about more complicated solutions). Then if we decide we want to determine how frequently intermediate CA errors occur, we should look into desktop Firefox to see if they already have that data. If that also fails, only then would I start implementing some complex guesswork in focus.

**Comment by ekager** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

Which SSL Errors are Focus users most frequently receiving? How often are our users running into SSL Errors? Are SSL errors happening much more often in Focus than other browsers? 

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

Beneficial to our users for us to know if they are receiving more SSL errors with Focus than with other browsers, we can try to implement solutions to improve their SSL error (and browser) experience. 

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

Printed logs for specific problem sites, and we now want to see how often this is a problem for users. If it is a large problem, we will have to think of creative work-around.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Technical Data: SSL Error codes with no personal or browsing information</td>
    <td>Category 1</td>
    <td>#1775 / #1338</td>
  </tr>
</table>


6) How long will this data be collected?  Choose one of the following:

* I want to permanently monitor this data. (@bbinto)

7) What populations will you measure?

All populations except Germany Klar users

8) Please provide a general description of how you will analyze this data.

Will analyze the data by reviewing the number of SSL errors received to see if this is a large problem for our users. 

9) Where do you intend to share the results of your analysis?

With the Focus/NMX team.

**Comment by ekager** [comment]
Tagging our data peer @liuche :)

**Comment by liuche** [comment]
1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes, on https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, under the Settings telemetry switch.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**

Yes, @bbinto (Barbara Bermes)

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

Type 1

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No, telemetry can only include the set of error strings.

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**

Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**

Yes

Data-review+ from liuche.

@ekager please make sure to update the documentation as part of this bug, and close this issue when that's finished - include all the possible values that can be sent as part of this ping (which is the error strings).

**Comment by ekager** [comment]
Ok will do @liuche !
Thanks!

**Comment by ekager** [comment]
Updated the Telemetry wiki !
