### ISSUE TITLE
UX issues with Pull-To-Refresh

### ISSUE THREAD

**Issue by Benestar** [mozilla-mobile/focus-android#1776]
There are some UX issues with the new Pull-To-Refresh feature that need to be fixed. The desired behaviour is the following:

* Pull-To-Refresh is only enabled when the user cannot perform any other action by swiping down on the page (eg. Google Maps)
* When swiping up to dismiss the reload indicator, the page should not scroll down.
* The reload indicator should only appear when the page is already at the top. When the user scrolls up and the page is still moving, swiping down should *not* reload the page.

This results in two distinct states:
* Normal scrolling mode is active by default and no reload happens in this state.
* When the page cannot be scrolled up and no other swiping action can happen on the page, the user can swipe down to see the reload indicator. Then, no scrolling events can occur on the page until the user releases their finger.

**Comment by SavageBiscuits** [comment]
Well, my problem is that I sometimes accidentally cause the refresh to happen. It's happened a few times today. Maybe I'm at the top of the page and don't really realise or my finger accidentally brushes the screen while dithering on a page. It just seems to me to happen too easily.

I usually use Firefox for Android or sometimes Opera Mini. Firefox doesn't have this feature, while Opera Mini does. It's a feature that I rarely use, even if enabled in a browser. In Opera Mini, it seems less sensitive to causing a refresh, so that's maybe why I haven't really had this problem with it, while I'm having it with Firefox Focus. Maybe it's my own usage (or misusage), but maybe it's set too sensitively for Focus.

Personally, I'd prefer an option to disable the feature, but that could be seen to introduce bloat. Failing that, maybe make it less sensitive.

As for sites where this happens. As I've said above, it's mainly inadvertently causing this by my usage. But if you want a site, then www.indpendent.co.uk is one example.

**Comment by Benestar** [comment]
Thanks a lot for your valuable feedback. 😃 I am right now looking into how to implement the suggested improvements of the feature. Hopefully, we can find a solution that fits all users and does not disturb anyone.

**Comment by max2505** [comment]
Well, in my case, it's a bit different. Currently, I only see this on a single page (which unfortunately is not publicly available) where a chat conversation is displayed.
By default, you're pointed to the bottom of the conversation and only the last 10 messages are displayed. If you want to see more of the previous messages in that conversation, you'll need to swipe down. But, of course, this reloads the page and you'll get the same again (last 10 messages and you're at the bottom).

I'm trying to find another (publicly available) page with this behavior. If I find it, I'll add the link here.

But already a big thanks for your help :)

**Comment by pocmo** [comment]
Also see #1779

**Comment by jolcsk** [comment]
I would also prefer an option to turn this feature off/on. I would even settle for an "about:config"-like style of an option (I am saying "style" because Focus does not have about:config page, or does it?).

**Comment by bbinto** [comment]
Thanks all for the feedback, we will look into these issues.

@pocmo another German comment via Google Play Store:
"War mit der alten Version ganz zufrieden, jetzt mit Swype nicht mehr nutzbar, springt unkontrolierbar hin und her; kann man leider nicht ausschalten"

**Comment by pocmo** [comment]
Also see #1776 - Pinch to zoom triggers pull-to-refresh.
