### ISSUE TITLE
Autocomplete: Change default value for settings

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1813]
meta: #1766 

Follow-up from: #1609 -> Autocompleting from our list of top domains should be disabled by default. If possible this should only affect new installs.

**Comment by pocmo** [comment]
@lime124 I don't think we can change the default only for new installations - because the preference doesn't exist yet. Two options:

1) We pick one default for all users (on or off)

2) We turn autocomplete on for all users (like it is now) and in 4.1 (or whatever the next release is) we change the default for false. In **this** case the default would only change for new users and existing users will still have the feature turned on.

**Comment by lime124** [comment]
thanks @pocmo !

@bbinto in this case, i suggest that we leave the default to on (otherwise it will 'randomly' disappear for existing users). and then we can take a look at the telemetry to see how many people are turning the feature off/on and revisit the default state for future installations. 

thoughts?

i want to add @boek to the conversation since i would expect to encounter the same problem on iOS and thus ios should have the same solution.

**Comment by bbinto** [comment]
I'm happy with your proposal, @lime124 -- due to the issues mentioned by Sebastian, let's keep the status quo and iterate it with more data points.

**Comment by pocmo** [comment]
Okay, great.

In this case I can close this issue for this sprint. :)
