### ISSUE TITLE
Telemetry probes for autofill

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1821]
We want to see how the autofill capabilities are used.

**Comment by Sdaswani** [comment]
I spoke to @bbinto - for a first pass, she just wants to know when a user employs the autofill functionality. So dropping a probe when they do so would be just enough.

**Comment by pocmo** [comment]
I added two probes:


| Event                    | category | method     | object |
|-----------------|----------|--------------|---|
| Autofill popup is shown                | action   | show                  | autofill   |
| Autofill performed                     | action   | click                 | autofill   |

**Comment by Sdaswani** [comment]
@bkmunar can you please use the same events for iOS.

**Comment by pocmo** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

* Are users using the Autofill feature of the system? -> Do they see and click on autofill popups?
* Is it worth investing more in autofill features and compatibility with third-party apps?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* Determining if autofill is a feature that supports our uses cases. Again this is a feature that is not available in Firefox for Android in this form. So we cannot rely on data from the main browser.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

* -

4) Can current instrumentation answer these questions?

* No, not really. With autofill being a new feature there's not much information on it in general.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

Category 2 “Interaction data”:

| Event                    | category | method     | object |
|-----------------|----------|--------------|---|
| Autofill popup is shown                | action   | show                  | autofill   |
| Autofill performed                     | action   | click                 | autofill   |

6) How long will this data be collected?  Choose one of the following:

* For now we are collecting this without any deadline.

7) What populations will you measure?

* All release users with telemetry enabled.

8) Please provide a general description of how you will analyze this data.

* Re-dash queries + dashboards

9) Where do you intend to share the results of your analysis?

* Only on re-dash and with mobile teams.

**Comment by Sdaswani** [comment]
@bkmunar can you also fill this out for iOS - you should be able to use a lot of the content here. https://github.com/mozilla-mobile/focus-ios/issues/728

**Comment by liuche** [comment]
# Data Review Form (to be filled by Data Stewards)

Instructions: Data Stewards will review a request for data collection and endorse responses to each question. **If the request does not provide answers to questions, reviewers give an r- and point to the questions that can’t be answered.**

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate? (see [here](https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/data_dictionary.md), [here](https://github.com/mozilla-mobile/focus/wiki/Install-and-event-tracking-with-the-Adjust-SDK), and [here](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/index.html) for examples).  Refer to the appendix for "documentation" if more detail about documentation standards is needed.

Yes, on https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, telemetry toggle in Settings UI.

If the answer to either of the first two questions is no, reviewers give an r-. **Incremental changes to measurements or systems that have previously gone through analysis review may not require additional review.**

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**

Permanent, @bbinto is responsible for monitoring data.

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **
Type 2

5) Is the data collection request for default-on or default-off?
Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
No, only click interaction data

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**

Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No

**Comment by Sdaswani** [comment]
Thanks for data review @liuche !!!
