### ISSUE TITLE
Content description of "menu" button in search engine and autocomplete settings not translated

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1855]
In the search engine and autocomplete settings screens we let Android create the overflow menu via onCreateOptionsMenu().

This means Android will set the content description (for screen readers). However for some languages Focus ships in (for example "ast") Android does not have a translation.

We need to set the content description manually - if that's possible.

**Comment by pocmo** [comment]
In screens where we add the menu button manually we use R.string.content_description_menu.

**Comment by pocmo** [comment]
CC: @liuche @ekager

**Comment by ekager** [comment]
I researched this a bit today and I don't *think* it's possible to set the content description for the system overflow menu item since it's set by the framework and has no accessible methods. It might be possible with some major hacking to find a reference to the menu item view by searching for the framework string, or creating our own custom menu view like we did in other parts of Focus.

**Comment by bbinto** [comment]
Part of #1561
