### ISSUE TITLE
Add telemetry for "Add Search Engines" feature

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#1856]
Include telemetry for "Add Search Engines" to collect actions such as:
- Clicks on "Add another search engine"
- Clicks on "Remove" or "Restore Default"
- Successful "Save" of new search engine

**Comment by liuche** [comment]
@bbinto are there other probes you'd like to include?

**Comment by pocmo** [comment]
For the "URL entered" event I added extras for autocomplete (was this autocompleted? from which list?). Maybe something like this would be interesting for the "search entered" event too? E.g.: Was this a search with a default or custom search engine. However I'm not sure if we even know at this point. It's probably not worth adding complexity at the end of the sprint. :)

**Comment by liuche** [comment]
That would be nice to collect! but I think I'd rather not add too much complexity now :/ but I will file.

**Comment by bbinto** [comment]
@liuche if you ask me (as you did :)), I would *really* like to have this in now:

> Was this a search with a default or custom search engine.

It will really help us understand how many of our users customize for a puropse, i.e if the feature increased retention not only if somebody has set their custom search engine but actually used it. 

Otherwise good start to track the feature.
