### ISSUE TITLE
When no search engine is selected for deletion, tapping trash icon exits 'Remove Search Engines' dialog

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1876]
STR:
Go to search engine list in Settings menu
Tap 3-dot menu and select 'Remove'
Tap Trash can icon without selecting search engine checkbox

Expected:
Since no search engine is selected, either the trash can should be greyed out or have no action
Actual:
exits 'Remove search engines' dialog

Copied from #1836

**Comment by pocmo** [comment]
UX from #1836:
> In this case we should disable the trash can until at least one item is selected.

**Comment by liuche** [comment]
Also, just to be explicit because we've mentioned "short on time" here and there, but this is a `release-blocker` and we want to uplift this patch to ship with the 4.0 release. I think the pace that we've been reviewing PR #1898 is good, and I expect this last round of changes will fix everything and allow us to land this Dec 6 on schedule. But on the off-chance that this gets more complicated pushes beyond Dec 6, either @mcomella or I will make any outstanding changes in a commit on top so we can get this into 4.0.

Again, I think @layely is doing great on this patch and I'm pretty confident he will have a finished patch that's ready land in time for Dec 6, but just to document this in the issue.

**Comment by liuche** [comment]
@npark-mozilla should be in the next master - if you can verify this I'll uplift it! Also, #1915 may be a dupe, but filed before this was finished and merged.

**Comment by npark-mozilla** [comment]
👍
