### ISSUE TITLE
Add setting for blocking images

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#188]
**Theme:** _General Improvement_

**User Story**

> As a user I want to know & be in control of how much data I use when browsing the web

**Background**

We implemented this in #116 and discovered some issues in #173. We are not going to add it to v1 - unless we have time left.

**Tasks**

- [x] Re-enable setting
- [x] Address concerns from #173

**Comment by pocmo** [comment]
@antlam We have two options here:
* (1) Block images loaded from the network
* (2) Block all images

Currently we are doing (1) because that's how we can save data. However this means we will still show images that are embedded in documents or generated otherwise. For example you still see images in Googles image search. We could enable (2) to avoid surprises for the user - although this doesn't save more data.

**Comment by antlam** [comment]
Since this isn't a priority for V1, I'll take some more time to think about it. 

But in general, I think the way we've messaged this to our users is that images are images. That means there's not a difference in their minds about "images from network" versus "all images".

So I would suggest we just block all images unless we change our messaging to clearly define the difference between "loaded from the network" and "all images".

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blocking images](https://trello.com/c/Qduel3kZ/6-blocking-images)

**Comment by bbinto** [comment]
User feedback: https://appbot.co/apps/1486200-firefox-klar-private-browser/reviews/517430516

**Comment by xrxrxr** [comment]
In opera mini it have a feature that reduce image quality for data saving but i don't know if it really works
