### ISSUE TITLE
Incorrect error msg when a search engine with same name is being added

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1880]
STR:
add a search engine with name 'Test'
add another search engine with sam name

Expected:
rejects with the error message saying "there is already a search engine with same name"
Actual:
There is only one error msg shown, which says "Check that search string matches example format" which is misleading in this case.

**Comment by liuche** [comment]
@lime124 I added this behavior without really thinking about it needing an error string - what do you think we should do here?

**Comment by mcomella** [comment]
@lime124 What string should we show in the Snackbar when the user tries to add two custom search engines with the same name?

@liuche How does uplift of Strings work? Or will this just appear in english for this release?

**Comment by liuche** [comment]
It might be late to add a new string - it would just show up in English, if we're okay with that, but we'd need a string from @BrianNJones.

**Comment by lime124** [comment]
The behaviour seems reasonable, but I agree the string doesn't really make sense here. I can't remember what we decided for these situations - in general are we moving forward with english strings and then translating when we can?

**Comment by Sdaswani** [comment]
IMHO we can ship with this bad string and fix it in future release (e.g,. 4.1). Up to @bbinto though.

**Comment by bbinto** [comment]
I agree with @Sdaswani -- we can fix it in 4.1

**Comment by liuche** [comment]
Adding @BrianNJones so we can get strings for this for 4.1.

**Comment by BrianNJones** [comment]
Let's use:
An installed search engine is already using that name.

**Comment by mcomella** [comment]
> Let's use:
An installed search engine is already using that name.

@BrianNJones The other error string, "Check that search string matches Example format", does not include a period – should I omit one for this string as well? It looks like the Snackbar Material Design examples don't include periods either: https://material.io/guidelines/components/snackbars-toasts.html

**Comment by BrianNJones** [comment]
@mcomella If you scroll down on https://material.io/guidelines/components/snackbars-toasts.html you'll see examples w/punctuation. The driver is typically complexity of the snackbar message. "Archived" doesn't need punctuation and kinda looks weird with it (IMHO). I'd leave it in for this one.

**Comment by antlam** [comment]
🤔 Typically on Android, the way to display Error messages is to use the form field itself. The snackbar is more reserved for confirmation type messages.

Since we already inherently follow these guidelines for the text fields, it gives us plenty of room to provide specific feedback (more specific since it's right next to the offending input field). 

Maybe we should try putting the error message in the/next to the field instead? @lime124 @BrianNJones 

https://material.io/guidelines/components/text-fields.html#text-fields-layout

**Comment by liuche** [comment]
Was worried this string would be too long so I hacked it in for size - it's on the long side, but looks okay.

![screenshot_1512765260](https://user-images.githubusercontent.com/1082253/33784054-2a6e5b46-dc14-11e7-93d3-82316f48471c.png)

**Comment by liuche** [comment]
Clearing strings approved bc the strings have landed on master.

**Comment by antlam** [comment]
@liuche @lime124 the styling for the "Example" placeholder looks off... it should be the same as the "Enter search string" error. Then when there's an error, we could even just highlight that to turn red. We might not need to show both the helper ("Example") AND the error ("Enter search string") since it's kind of redundant.

**Comment by bbinto** [comment]
Part of #1561

**Comment by sv-ohorvath** [comment]
Verified as fixed on Beta v5.0. 
Device: Pixel XL (Android 8.1.0)
