### ISSUE TITLE
Use constant for detekt version in build.gradle

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1886]
Right now, we specify it individually: e.g. the last time we updated the version is https://github.com/mozilla-mobile/focus-android/pull/1878/files

Since the values are duplicated, we should use a constant, like `kotlin_version`.

**Comment by siddware** [comment]
Could I work on this?

**Comment by pocmo** [comment]
@siddware Yes. This is still available. :)

You'll need to modify the build.gradle file in the root directory:
https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle

The detekt version is duplicated:
* https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L26
* https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L30

Other constants are defined here:
https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L7

**Comment by siddware** [comment]
@pocmo Thanks for the detailed instructions :) Switching the version value to a constant was straightforward for the [detekt block](https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L30) but unfortunately facing an issue with the [plugins block](https://github.com/mozilla-mobile/focus-android/blob/master/build.gradle#L26). The reason is plugin block doesn't seem to [support this type of usage](https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations). There are some discussions [here](https://github.com/gradle/gradle/issues/1697) and [here](https://discuss.gradle.org/t/how-to-use-property-for-version-when-using-a-plugin-via-id/22122/5) The suggested method seems to be using an undocumented API method and even that requires a higher version of gradle than the one that is currently being used in Focus. Any advise?

**Comment by pocmo** [comment]
@siddware Oh. That's annoying. Thank you for trying this. In this case I would almost prefer to just live with the duplication. @mcomella What do you think?

According to the detekt docs we could also remove the version from the detekt block:
> version = "1.0.0.[version]"  // When unspecified the latest detekt version found, will be used. Override to stay on the same version.
However this might have unpredictable results and break builds randomly.

**Comment by mcomella** [comment]
> Thank you for trying this. In this case I would almost prefer to just live with the duplication.

Thanks for the investigation, @siddware ! I agree – I'd rather not use a hack to reduce duplication.

> we could also remove the version from the detekt block:

Thanks for the alternative. I also don't like this though – not pinning the version creates non-reproducible builds, which can make it difficult to debug issues between developers and creates problems trying to build old versions of Focus.

---

@siddware, as for the action items in this bug, could you add a comment the the build script mentioned that this number is duplicated and why we had to duplicate it? Note: don't duplicate the comment! :P Just add a comment in the duplicated code location referencing the first, e.g.:
```
// Explain the duplication
<duplicated code>
...
// This code is duplicated - see other duplication above for details.
<second duplicated code>
```

While not perfect, this prevents the comments from going out of sync.

---

If you'd like to help us out on more build work after this, perhaps you'd like to look at #1900 ?
