### ISSUE TITLE
Default search engine name is not updated in Settings menu when locale is changed

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1899]
STR:
- Go to settings, change to locale with a different default search engine (i.e. setting locale to Korean used to show Naver as search engine),
- Go to main settings menu

Expected:
- Main settings shows the default search engine of new locale
Actual:
- Main settings shows the previous default search engine.

**Comment by harisankerPradeep** [comment]
I'd like to work on this :)

**Comment by guruprasath-b** [comment]
can I work on this issue?

**Comment by npark-mozilla** [comment]
Hi @sank20, it used to be that each locale has a list of specific search engines tailored to the locale, like Russian => Yandex, Korean => Naver.  That seems no longer the case.  I removed the incorrect STR so it's less confusing. Thanks!

**Comment by levimatheri** [comment]
This has already been fixed by [this commit](https://github.com/mozilla-mobile/focus-android/commit/2faefedfafd6cc6b8d7d8447a4e16af880559d52). The only issue is one has to completely clear the app from the overview apps list. Relaunching the app works as expected, the search engines correspond to the locale. I am planning on opening an issue for this

**Comment by levimatheri** [comment]
Looks like `LocaleSearchLocalizationProvider` is not getting the right Locale from JVM after the change?

**Comment by levimatheri** [comment]
I have submitted a PR on mozilla android-components that fixes this
