### ISSUE TITLE
Inconsistency when closing pages from Your Rights

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-mobile/focus-android#1920]
Devices:
Nexus 5 (Android 6.0.1)
Nexus 6 (Android 7.1.1)
build: Focus 4.0 Beta Build #3691

Steps to reproduce:

Launch Focus and go to Settings.
Tap on Your Rights.
Open another link from page.
Tap on back arrow or on back device button.

Expected results:
Your Rights page is opened with all the information.

Actual results:
Settings is opened.
Same behavior for About Firefox Focus, Help, Privacy Notice.

**Comment by npark-mozilla** [comment]
@pocmo hmm, this might be related to #1924 ?

**Comment by pocmo** [comment]
This one is different.

In InfoActivity we didn't override the back button behavior. Back will just leave the screen. We could decide to go back in history if there's history. I'll leave this decision to UX (ping @lime124).

For this and a related issue I wonder whether it would be an alternative to just open a tab instead of showing web content in this sub screen.

**Comment by liuche** [comment]
Talked to @Sdaswani, not a release blocker.

**Comment by lime124** [comment]
@brampitoyo i think this is related to what you've been working on recently with opening settings' pages in new tabs? does that work might make this bug irrelevant?

**Comment by brampitoyo** [comment]
Normally, our in-content pages are websites. But “About Firefox Focus” and “Your Rights” are two are pages that then contain links to websites.

@pocmo is correct. We can override the current back and system back buttons behaviour so that they go back in history if there’s any, then leave the screen if there’s no more history.

But a better solution is as @lime124 proposed: figure out a way to handle opening in-content links (#2107) in a clean way.

**Comment by brampitoyo** [comment]
We’re solving this problem by fixing issue #2107. Closing it.
