### ISSUE TITLE
Import strings before v4.0 release

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1931]
Cross-functional said we needed to import strings before release.

@Sdaswani, anything to add here?

**Comment by liuche** [comment]
This is covered in the release engineering bug so duping to #1765

**Comment by Sdaswani** [comment]
Re-opening so Delphine can provide a list of locales for us to import here. 1765 looks a bit much for Delphine to annotate.

**Comment by liuche** [comment]
Generally she emails that list out, but okay.

**Comment by Delphine** [comment]
I'm thinking it may be a better idea to list these out here from now on, because it's just easier to track in the future than by email. However, let me know you'd prefer doing this by mail next time (fwiw we used to do it on bugzilla which worked fine, and GitHub is good by me for the same reasons!)
We can sign-off for v4 Focus Android for all locales except "lt" (Lithuanian) and "oc" (Occitan): https://github.com/mozilla-l10n/focus-android-l10n/tree/master/locales.
This means:

ar
--
az
bg
bs
cy
da
de
dsb
eo
es-AR
es-CL
es-ES
es-MX
fa
fr
fy-NL
he
hsb
hu
id
it
ja
ka
kab
ko
ms
nb-NO
nl
nn-NO
pl
pt-BR
ro
ru
sk
sl
sq
sr
sv-SE
ta
tr
uk
vi
zh-CN
zh-TW
ast
th
mix
trs
meh
fi
cs
kk
bn-IN
cak
eu
hi-IN
hy-AM
ia
bn-BD
ne-NP
ur
lo
el
my
ca
te
wo
ga-IE
zam
am

**Comment by Delphine** [comment]
Please import latest strings before adding these locales to release! thank you

**Comment by Sdaswani** [comment]
Thanks @Delphine - I agree GH is better for these, so we can track this all per release.

**Comment by liuche** [comment]
Hi @Delphine, are there any locales that need to be screenshotted, but not approved? Also, if it's not much trouble in the future can you send this list alphabetized?

**Comment by liuche** [comment]
Thank you!

Sorry, what I mean is, are there any locales that are partially localized and need to have localized screenshots of the app (for them to verify) other than "lt"?

**Comment by Delphine** [comment]
Yes, all locales should get screenshots, whether entirely localized or not. That's what we've been doing since the beginning with No-Jun.

**Comment by liuche** [comment]
haha sorry this is still not clear! What I mean is, are there any other locales that now need screenshots? The list you've sent are the locales that are now approved to ship - but are there any new locales that have been started I guess, that will now need screenshots.

**Comment by liuche** [comment]
Okay clarified in real-time communication: "lt" is the only locale that gets screenshots, but is not shipping.

**Comment by Delphine** [comment]
(For my own records and sanity: new locales this time around that were added to release are "meh" and "bs")
