### ISSUE TITLE
Quick "Add" URL to autocomplete list 

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1933]
Why
- Users are currently unable to easily add URLs to the autocomplete list

What / Requirements
- [ ] Provide a convenient and quick way to add the current visited URL to autocomplete list
- [ ] Allow user to save path with URL
- [ ] (optional) Fuzzy autocomplete?

Acceptance Criteria (how do I know when I’m done?)
- User can add any URL successfully to the autocomplete list
- Current list management should stay the same (delete, view etc, via settings)
- Probes should be added and working

-----

We discussed this briefly in issue #1609, leaving it to @lime124 for more thoughts 

Should we try to add (and of course, measure) another context menu item for "Add search engine" and "Add to URL autocomplete"?

> maybe we could use the long-press context menu for this?
1. User navigates to somesportswebsite.com/traderumours
2. They decide they want to save this frequented site of theirs
3. Long-press on the URL bar 
4. User presses a button to quickly add the site they're on to this "URL autocomplete" list

**Comment by pocmo** [comment]
The autocomplete case seems to be straight-forward. "Search engine" needs more thought: How do we know where to put the placeholder for the search query?

**Comment by lime124** [comment]
@brampitoyo please take a look! thanks!

**Comment by brampitoyo** [comment]
The UI for adding custom URL via the address bar is actually quite simple and straightforward:

![url - add via address bar](https://user-images.githubusercontent.com/51007/37436355-7265e7f0-284c-11e8-89bd-d4b6cbd38406.png)

As @pocmo wrote, if all we do is add the character content of the address bar into our database of URL to autocomplete, it’s straight-forward. Let’s definitely do this.

**Comment by brampitoyo** [comment]
However, if we want to add a search engine, we’ll need to know to put the `%s` placeholder in the right place.

I did a little investigation yesterday, as well as talked with @ekager, who has been an awesome help.

Hypothesis: search URLs declare their queries in a standardised way `domain.url/[whatever]?[search/q]=%s`

Strawman solution: if this is the case, then we can just look for the `q` bit in the URL to determine whether the site is a search engine or not, and where to put our `%s` query placeholder.

Results:

* Google, Yahoo, Bing, DuckDuckGo, Twitter, Ask.com, AOL, IMDb and Shopify stores uses `q=%s`
* Wikipedia uses `search=%s`
* Baidu, Amazon, Yandex, so.com, Naver, etc. uses their own formatting, which is neither `q` nor `search`. It can be something like `wd`, `field-keywords`, `text`, or anything else

So it seems like we can’t go with a one-size-fits-all approach in order to detect search URLs.

**Comment by pocmo** [comment]
> It seems like we can’t go with a one-size-fits-all approach in order to detect search URLs.
> What do you think, @pocmo?

I agree. There's no nice solution that works for all of them.

There are two additional things that Fennec does and maybe they are interesting (and probably worth a new issue):
* If the markup of a page contains a opensearch XML definition then Fennec will offer to add the current page as search engine via "menu->page->add a search engine". This of course only works for some pages - but then without any help from the user because the XML contains all information to construct the search URL.
* Long-pressing a form field and selecting "Add search engine" from the text selection menu. From the data in the form and the name of the selected field we create the search URL. Might now work sometimes. But works often quite well because the user knows exactly which field to select.

Both these options are not perfect either - but maybe inspiration for new/other ideas.

**Comment by brampitoyo** [comment]
@pocmo What’s our chance of using Fennec’s implementation on Focus? Are their implentation ‘expensive’ in terms of resource use and increasing APK size?

**Comment by Sdaswani** [comment]
@brampitoyo just getting a status check - is the UX for this work done or do you still need time to finalize mocks?

**Comment by brampitoyo** [comment]
@Sdaswani I just renamed this issue so that it’s focused specifically on the **context menu item that allows you to add a URL**.

This menu item is called “Add Custom URL”. It appears alongside “Copy” and “Paste” when you tap and hold the URL bar.

<img src="https://user-images.githubusercontent.com/51007/37881289-36ef0432-30f2-11e8-9261-5830ad546dd4.png" width="320">

The UX for this work is now finished.

**Comment by brampitoyo** [comment]
The new UI is slightly different and takes less time to access.

Instead of piggybacking on the cut-copy-paste text selection menu, we have a separate menu containing only one item. This menu will appear when you tap and hold the URL bar.

![url - add via address bar 2x](https://user-images.githubusercontent.com/51007/38343056-ec59722c-38d5-11e8-8dc8-295fc539d8f1.png)

**Comment by sv-ohorvath** [comment]
Verified this feature on the Focus Beta v5.0 build.
Devices:
Sony Xperia Z5 Premium (Android 6.0.1)
Google Pixel (Android 8.1.0)
