### ISSUE TITLE
Simplify removal of search engines and auto-complete custom URLs

### ISSUE THREAD

**Issue by Jacquester** [mozilla-mobile/focus-android#1956]
Instead of removing a search engine by clicking options > Remove and selecting the search engines to be removed, why not include a long press functionality on the list similar to deleting chats in whatsapp or IMO ?
If you long press one of the search engines on the list the fragment asking which engines to remove comes up with the selected engine already checked.

The same applies to auto-complete custom URLs

**Comment by pocmo** [comment]
I think @antlam proposed this too - I wonder if there's a duplicate somewhere.

**Comment by Sdaswani** [comment]
@brampitoyo just getting a status check - is the UX for this work done or do you still need time to finalize mocks?

**Comment by brampitoyo** [comment]
@Sdaswani I didn’t know that this was an issue.

The UX for this work can be considered finished because it’s so straightforward: **on long pressing the name of a search engine, show a context menu called “Remove”.**

If the search engine to be removed is currently selected as a default, then after removal, the next search engine down the the list should be set as default.

**Comment by Sdaswani** [comment]
@brampitoyo sorry confused again - you assigned this issue to yourself but you say the UX work is finished?

**Comment by pocmo** [comment]
> show selection mode with a menu item called “Remove”

In the mock it looks like I can only select one item (radio button vs. checkbox) - Is this intended?
