### ISSUE TITLE
Provide new string for error handling for "Add Search Engine" URL validation, or update handling entirely

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#1963]
We re-used the "Server not found" string so we should either:
- Replace the string with a specific one for this place
- Update the error handling entirely (invalidating needing a new string)

**Comment by liuche** [comment]
I'm sorry we made so much new UI while you were gone! fwiw @antlam helped, so hopefully it's not too off the rails.

**Comment by antlam** [comment]
I think this needs to be expanded a bit more generally for UX. Reason being, there were a few error cases that we glazed over at the 11th hour and it would definitely be more thorough and consistent if we took a look at all the error states altogether.

How about:
> Specify error cases when user is adding a new search engine.

**Comment by lime124** [comment]
@brampitoyo can you follow up on any error cases we need to cover and/or tweak and then work with @BrianNJones to figure out strings? Thanks!

**Comment by brampitoyo** [comment]
I suspect that we want to have a warning that’s easier to understand. Instead of `Server not found`, we may say something like `We’re having trouble finding that site` or `Can’t connect to google.com`.

But before explaining the context to Brian and asking for content help, there are a few things that would be good to know:

1. By which process did this error come from? My guess: we send a ping to google.com and see if it gets a response. If not, then this error is shown.
2. Is this the only error that will need a string? A quick strawman scenario: if google.com can be reached successfully, but the search query that the user has entered produces an error, do we consider that an error? Are there other scenarios considered to be errors?

**Comment by pocmo** [comment]
> @mcomella @liuche Perhaps you can help?

They are both busy with FireTV currently.

From a quick look at the code I think our only error cases right now are:
* Empty name: "Enter search engine name"
* Empty URL: "Enter search string"
* Invalid format: "Check that search string matches Example format"
* Server returns anything that is not 2xx when requesting the URL: "Server not found"

**Comment by BrianNJones** [comment]
@pocmo, thank you. @brampitoyo, i'll hold off on the new "server not found" string until we have more info re: context.
Let's look at updating the invalid format string to: Make the search string matches Example form.

**Comment by brampitoyo** [comment]
Thanks a lot for giving us all the error cases, @pocmo! It’s just what we need to take a look at them side by side.

The first two errors have no problem, and I agree with @BrianNJones on updating the string for invalid formatting. I’ll file a new issue for that.

@BrianNJones, our context: Focus has a feature to add a custom search engine. In a perfect world, the user success rate would be very close to 100%. We’re researching some better ways to do this. At the moment, the user would enter the search engine name and URL manually. This inevitably leads to errors due to keyboard input.

The problem is, a search URL isn’t like a normal URL, and adding it to Focus isn’t as straightforward as we like it to be. You can’t simply enter `google.com`, you have to enter `google.com/?q=%s`. This takes up time and energy, so we want to make the sure that the search engine you add would work when you use it.

To do this, we check with the search engine when you submit the form. Can we connect to them? If yes, then great. But if not, then we show the “Server not found” message, which now needs to be reevaluated or rewritten.

**Comment by brampitoyo** [comment]
This issue is still relevant, although not high priority given that not many users will utilise this feature.
