### ISSUE TITLE
Number of locales in locales.py and on Pontoon differs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1975]
In locales.py I see 69 locales (68 release + 1 screenshot-only) but on Pontoon there are 75 locales (However one with no strings).

Ignoring the locale without strings there seem to be 5 locales that should either be in release or in the screenshot list.

* https://github.com/mozilla-mobile/focus-android/blob/master/tools/l10n/locales.py
* https://pontoon.mozilla.org/projects/focus-for-android/

**Comment by pocmo** [comment]
@delphine @liuche Is this known?

**Comment by Delphine** [comment]
Looking into this now. It's weird because our dashboards show only 72 locales: https://l10n.mozilla-community.org/webstatus/?product=focus-android
Going to check what's going on, thanks for surfacing!

**Comment by Delphine** [comment]
Seems like "am" was left out of the locales.py list. 
"oc" should have appeared there too but under screenshots only since it can't ship yet. That was a confusion from a discussion we had on irc, where I left it out although I had called it out on my sign-off along with "lt" here: https://github.com/mozilla-mobile/focus-android/issues/1931
Croatian (hr) and Marathi (mr) only have suggested strings on Pontoon which is why they don't show up on our dashboards - which is normal and they shouldn't be included in the locales.py anyways. 
So that's all the 6 locales you noticed Sebastian.

**Comment by pocmo** [comment]
This should be fixed now. We landed a script that makes sure that this won't happen again. :)
