### ISSUE TITLE
Automatically bring up the keyboard when the user presses "+ Add another search engine"

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#1979]
When the user presses the button to Add search engine, the form has 2 input fields and the user has to select one to get the keyboard to show up.

A simple convenience thing we could do is already bring it up once they press the button so they can start typing in the new view right away.

Thoughts @lime124 ?

**Comment by rucquoy** [comment]
Hello @antlam !
I'd like to give a contribution (of any kind) to this project. Can i give it a try ? Do you think it's worth a PR ? 
regards

**Comment by antlam** [comment]
hey @rucquoy ! I think this would be a great thing to take a stab at. If you don't mind, it would be great to get a build together so that @lime124 could see how it feels on device (with these changes). 

Thanks so much!

**Comment by rucquoy** [comment]
Hello ! Sorry if my question sounds stupid (i'm an open-source newbie, and only a student) but what do you want me to do when you say "get a build together" ?

**Comment by antlam** [comment]
hey @rucquoy sorry, we've been away this week. 

But we should have more time to help you next week. If this is something you're really interested in, you should work with @mcomella or @liuche from Engineering to get a patch togther. They might be able to provide more guidance. 

Until then, this still needs to be triaged and discussed with Product and UX to decide on shipping finalizing details etc.

**Comment by mcomella** [comment]
Hey @rucquoy – we discussed this in triage and Tif mentioned this is definitively a bug. If you could make the changes locally and make a pull request, it'd be great! :)

> but what do you want me to do when you say "get a build together" ?

antlam wanted our UX designer, lime, to take a look at the changes you've made to see how it feels. Since lime doesn't have a development environment set up, he wanted you to make the changes locally and send lime the build so they could see how the changes felt. However, since we know it's definitively a bug now, you can skip sending lime the build and just make the pull request. Thanks!

**Comment by lime124** [comment]
Thanks everyone and sorry for the delay - I was on PTO and then a crazy work week. As @mcomella said no need to send me a build, it's a bug. Thanks for your help!

**Comment by rucquoy** [comment]
I Will open a PR ASAP then. Thanks for your time @mcomella
