### ISSUE TITLE
 Share Pocket(Firefox)

### ISSUE THREAD

**Issue by wisdoms-arcanum** [mozilla-mobile/focus-android#1995]
That app works to share to pocket but, when I share a youtube video link to pocket, it mostly just saves youtube's home page instead the video i wished to save. Thankyou for all your hard work.

**Comment by mcomella** [comment]
Strange – @npark-mozilla can you reproduce (I'm heads down coding this week)?

**Comment by npark-mozilla** [comment]
I can repro this. 
Device: Pixel 2, API 27
STR:
- Install Pocket on android, sign in with firefox accounts
- Open Focus, go to Youtube, pick a video, and select Share, then select 'Add to Pocket'
- Switch to Pocket, and check the new content - it shows 'Best of Youtube' instead of the video that I picked.

When we share to Firefox, the link is shared to the video correctly.

**Comment by npark-mozilla** [comment]
It seems like it's a pocket bug. When I copy the youtube url to clipboard, and open pocket, it asks to add the clipboard URL to content.  when I do so, pocket again shows 'Best of youtube' instead.

**Comment by bbinto** [comment]
@npark-mozilla emailed Pocket to clarify - this is on Pocket's end to fix

**Comment by liuche** [comment]
@npark-mozilla said he sent an email to the Pocket support team, because we think this is a pocket bug.

**Comment by mmiermans** [comment]
@npark-mozilla @bbinto @mcomella I fixed this issue on our end and verified I can now save YouTube videos from Firefox Focus on a Pixel 2.

For any videos from this site that have been already saved, the Article View must be re-downloaded by tapping the refresh button at the very top right corner of the video.

Thanks for bringing this to our attention! :100:
