### ISSUE TITLE
Status bar gradient remains shown in mutitasking mode

### ISSUE THREAD

**Issue by aleksandar-todorovic** [mozilla-mobile/focus-android#1997]
**Description:** If you're using Firefox Focus in the multitasking mode, the gradient status bar remains shown (but empty). This unnecessarily uses up a really valuable vertical screen estate when using the multitasking mode, so I think that this should be identified as a bug.

**Device info:**

* Device: Nexus 5X
* Android version: 8.1 (Oreo)

**Steps to reproduce:**

Prerequisite: Android 7+

1. Open any other app.
2. Long press the "overview" button (according to [this](https://android.stackexchange.com/questions/32697/what-is-the-offical-name-of-the-third-on-screen-button#32700), that's its name)
3. Choose to open Firefox Focus in the lower part of the screen.

**Screenshots:**

* Running: YouTube's app up, Firefox Focus down.
* Showing pages: example.com as an example, and BBC's homepage to prove that this affects websites once the address bar gets hidden.

![screenshot_20171213-173135](https://user-images.githubusercontent.com/4890548/33950532-eee2d242-e02c-11e7-85a2-01df09511662.png)

![screenshot_20171213-173141](https://user-images.githubusercontent.com/4890548/33950540-f609ee2a-e02c-11e7-8bb2-5ab6105e858c.png)

![screenshot_20171213-173204](https://user-images.githubusercontent.com/4890548/33950542-f6e220c4-e02c-11e7-81d7-04fe3d252ffa.png)

**EDIT to note:** I don't have any other devices to try replicating this to. I have searched for all open issues that mention the word "bar" and couldn't find anything related to this issue, so I'm like 70% sure that this is not a duplicate.

**Comment by mcomella** [comment]
Thanks for the report, aleksander!

I think this is happening because we're drawing underneath the system status bar (i.e. with time) so that it can take our colors and we need to shorten our view if we're not under the system status bar. That being said, I'm concerned that we'd be missing the indicator that 1) hey! we're the Focus browser and 2) you have tracking protection enabled (shown by the gradient at the top, rather than black) but maybe users already know that, especially those using multitasking.

@lime124 What's the ideal UX outcome here?

FYI, here are docs on multiwindow support: https://developer.android.com/guide/topics/ui/multi-window.html Which is supported on 7+

**Comment by eaceto** [comment]
I could reproduce it in a Moto Z Play with Android 7.1.1. Can also fix it and submit a PR if you want.

**Comment by Sdaswani** [comment]
@eaceto I suggest you suggest a fix and then see if UX is happy with it. What is your proposed solution? It may be helpful to see what other browsers do in this case. Thanks for your willingness to contribute!

**Comment by eaceto** [comment]
Morning @Sdaswani . In order to get a better understanding of the issue, I'm attaching several screenshots in multi windows mode with Chrome.

if Focus is on top, everything is okey

![screenshot_20180126-055345](https://user-images.githubusercontent.com/870528/35433054-d461a1d6-0260-11e8-8d5b-134be3a0b1d3.png)

if Focus is on the left or right, is okey too.

![screenshot_20180126-055506](https://user-images.githubusercontent.com/870528/35433097-f59ab3a6-0260-11e8-9491-aafa4ccc7dbd.png)

![screenshot_20180126-055403](https://user-images.githubusercontent.com/870528/35433111-fc668070-0260-11e8-9317-bdbe2a9ef3bf.png)

But if Focus is on the bottom of the screen in multi window mode, there is too much separation between the search bar and the top of the middle of the screen.

![screenshot_20180126-055458](https://user-images.githubusercontent.com/870528/35433188-3c4a7d36-0261-11e8-9933-2cddf03b048b.png)

Moreover, when scrolling, the issue is more relevant.

![screenshot_20180126-055517 1](https://user-images.githubusercontent.com/870528/35433225-61cc6f38-0261-11e8-99d3-145ed58eaaee.png)



When Chrome is on the bottom and you scroll, they keep the search bar. I like that Focus doesn't keep it. So my resolution will be:

Detect on the "onResume" event that we are in multi window mode, and if so, change theme and activity properties in order to hide the status bar background.  I have tested that the onResume event is called when the app is put on multi window, and that Activity.isInMultiWindowMode() return true in that case only.

**Comment by Sdaswani** [comment]
Thanks for the details @eaceto ! I think your resolution sounds like a good plan. Can you attach a 'before' and 'after' screens (or even better, video) so we can easily evaluate the change from a UX perspective? Thanks!

**Comment by KazaHesto** [comment]
Was this fixed by PR #2317?

**Comment by pocmo** [comment]
Yes, this is possible. @npark-mozilla Can you verify?

**Comment by aleksandar-todorovic** [comment]
It _should_ be, via this commit made in #2275 (and later refactored in #2317): https://github.com/pocmo/focus-android/commit/e5bf5071d4a0e4a31a3d538a57260ada37d27948

I would still prefer for someone to verify it before closing this, since I'm using the Google Play beta version which doesn't contain that commit for now.

**Comment by pocmo** [comment]
@aleksandar-todorovic It should show up in the play store beta beginning of next week.

**Comment by npark-mozilla** [comment]
@pocmo yes on my pixel 2, the gradient below the split does not show anymore.
![screenshot_20180316-114030](https://user-images.githubusercontent.com/6930774/37530033-09ff895a-290f-11e8-99e7-e3a76ffa2d39.png)

**Comment by aleksandar-todorovic** [comment]
In that case, I'll consider this issue solved!
