### ISSUE TITLE
Not showing Firefox Focus in Recent Apps list at all.

### ISSUE THREAD

**Issue by Emegy** [mozilla-mobile/focus-android#2037]
By default, Firefox Focus is shown as a blank window in Recent Apps list. But simply clicking on this window will result in anyone getting into the browser and seeing what user was viewing, which makes it kind of pointless.

I think that the good idea would be to completely remove Firefox Focus from a Recent Apps list. This way a browser would be accessible only from a shortcut, and unless someone runs it on purpose, he won't know that Firefox Focus was used, or what was viewed there.

[InBrowser](https://www.inbrowserapp.com/) currently has this feature, and this is my favorite feature in it by far.

**Comment by grubdragon** [comment]
I found something that could be implemented, if we go ahead with this.
https://stackoverflow.com/questions/3762763/how-to-remove-application-from-recent-application-list

**Comment by mcomella** [comment]
I don't think we'd want to do this:
- we deliberately display a notification any time focus is running to let the user know that it's running and provide easy access. The recent app switcher is similar behavior
- This breaks platform conventions and would be an unintuitive default to users. We could make it configurable but more options means more code (and potentially more bugs) and a more cluttered settings for users who wouldn't benefit from this feature.

Our current design implies we want the user to be aware that they may have private data visible and to erase their session before they get into a revealing situation rather than protecting them from unveiling private data all the time (e.g. putting a passcode when returning to the app).
