### ISSUE TITLE
dragging/holding 3-dot overflow menu 

### ISSUE THREAD

**Issue by Biskvit** [mozilla-mobile/focus-android#2053]
Instead of tapping the 3-dot overflow menu once, and then tapping "refresh" once again for refreshing the page, things should be changed so you can hold the action overflow menu, move your finger towards the "refresh" icon (or any other option in the menu), and release, so the page can be refreshed in a single press. 
Almost all of the system apps after Lollipop, and many third-party apps work like this. Was that behaviour intentionally disabled to prevent accidents? 

English is my second language, and I don't know much about Android's design I can't really use the concise words you devs would like, Sorry about that.

**Comment by mcomella** [comment]
For triage: is this worth the code complexity to implement? I think existing apps get this for free when they use the standard ActionBar/Toolbar and menu combo, but since we have a custom view in the menu (# of trackers blocked), we'd have to implement this ourselves. If so, I'd recommend P5, help wanted.

Note that I can perform this behavior in Chrome.
