### ISSUE TITLE
Tab queue

### ISSUE THREAD

**Issue by Mikaela** [mozilla-mobile/focus-android#2069]
I would like to use Firefox focus as my default browser, but it's missing tab queueing from Firefox Android.

Often when I haven't looked at my phone for some time, I tend to look through instant messaging backlogs which often have interesting links and with Firefox I can just pile them to background until I have finished with the backlog, but Firefox Focus just pops up making me feel confused when I return to the backlog.

I am not sure if this is within scope of Firefox Focus, but I would hope so as I get the impression that it would like to be the user's default browser.

**Comment by mcomella** [comment]
I love tab queues and I think this is a great idea – thanks for the suggestion!

Engineering suggestion: perhaps we can make tab queues a library to make it easy to integrate into our range of link-based products.

**Comment by Sdaswani** [comment]
Thanks for the suggestion @Mikaela ! We will consider it during our next triage meeting. cc @bbinto

**Comment by layely** [comment]
Hi guys! Is there a way to work on this during the GSOC 2018 or another feature that might be needed.
Here the list of ideas: https://wiki.mozilla.org/Community:SummerOfCode18.

**Comment by Sdaswani** [comment]
Interesting idea @layely , we are still evaluating whether the Focus Android team will participate in GSOC 2018. If so we will consider this.

**Comment by mcomella** [comment]
FYI: tab queue usage on Firefox for Android: https://sql.telemetry.mozilla.org/queries/2819/source#table

I think if we invest in building and maintaining this, we should be sure to make sure users know about it.

**Comment by grubdragon** [comment]
I'm also interested in GSoC 2018 too. Sadly, uni hasn't given me much time to work on focus, but I would be so much more free come this summer. If you guys do participate, could you'll compile a small list of ideas? That would be great.

**Comment by Sdaswani** [comment]
@grubdragon here is what we have so far :) . https://github.com/mozilla-mobile/focus-android/labels/GSoC%202018%3F

**Comment by bbinto** [comment]
@mcomella - I like your idea of making it a library for other Android browsers to use.

@Mikaela and @Sdaswani - I like the idea and we'll prioritize.

**Comment by pocmo** [comment]
I liked working on tab queues in Fennec a lot. But I do not think it's a good match for Focus. Primarily because:
* It violates our promise to not save any data. When queuing URLs we save them to disk and open them the next time the browser is opened. This is something I wouldn't expect from Focus (Opening [senstivie?] URLs when opened).
* Drawing overlays on top of other apps has become more complicated on newer versions of Android. On Fennec we had to add prompts to ask the user to go to the system settings and allow Firefox to draw over other apps. That's super annoying and not an easy setup.
* Android has evolved since the introduction of tab queues. Nowadays a lot of links open in custom tabs. They are not suitable for being queued.

Regarding GSoC: This would at least require an additional UX mentor. The UI in Fennec is quite dated and there have been plans to change that in the past; but priorities...

I wonder what @antlam thinks about TQ in Focus?

**Comment by antlam** [comment]
My gut-reaction two cents right now would be to agree with @pocmo . It feels just a bit outside the realm of Focus because of the technical issues but also because the use cases are more nuanced.

To avoid the overlap here with a general purpose browser, maybe we could be more creative in solving the core use problems here? perhaps we integrate with Tab Queues in Fennec better? allow users to queue tabs in other applications? there's room for more ideas here I think
