### ISSUE TITLE
Add Telemetry for Average Page Time Load

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2091]
I'd like to get an average of all page load times across all focus installs. This will allow us to measure if our different webview choices (Android, GeckoView) have different aggregate loading times.

So I suggest the following:
1) For each foreground session,
2) Keep _local_ stats on how long a page load took, i.e., take time page load start and then finished,
3) Add that to a _local_ average,
4) and then the next time we upload telemetry, include that local average.

This obfuscates how many page loads the user does per foreground session, and just focuses on the average. Later on the server side we should be able to sum all the averages to get a global average.

cc @bbinto

**Comment by bbinto** [comment]
+1 ! Should we reach out to PI to get expert help on how we can achieve that and if there are other probes we can/should include.

**Comment by Sdaswani** [comment]
@bbinto i did remember that Klar doesn’t have UT on by default so this won’t give us much useful data until we use GV in Focus.

**Comment by bbinto** [comment]
I'm wondering if we should revisit the Klar telemetry piece and maybe consider switching to
- core - opt-out
- event - opt-in
with some clear onboarding to make the user understand why we collect data.

For now we have a small number of people who've opted in to telemetry for Klar. I know it's not a lot but better than nothing to get started.

**Comment by Sdaswani** [comment]
Another option @bbinto is to enable it for the alpha/beta channel but shut if off for release.

**Comment by Sdaswani** [comment]
Also the number of opt-in telemetry users for Klar is high enough for this metric to mean something 👍🏾.

**Comment by bbinto** [comment]
Data team confirmed this number is sufficient, should be fine for such metric (see more context [here](https://mozilla.slack.com/archives/C4DPE7X2A/p1518463347000626))

**Comment by ekager** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

* What is the average page load time for GeckoView vs WebView?  - Is the loading time of GeckoView comparable to WebView? 

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* Determining if GeckoView loading times compare to WebView loading times in the wild.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

* Side by side testing but want to compare average times for real world usage.

4) Can current instrumentation answer these questions?

* No. This is the first GeckoView is being used with Klar/Focus.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

Category 1 “Technical data”:

Adding GeckoView / WebView tag to the Core Ping

Category 2 “Interaction data”:

| Event                    | category | method     | object | extras|
|-----------------|----------|--------------|---------| ----- |
| Average Page Load Time For Foreground Session | action   | foreground  | browser   | { "average": 3858 } |

6) How long will this data be collected?  Choose one of the following:

* For now we are collecting this without any deadline.

7) What populations will you measure?

* All Klar users with telemetry enabled (opt-in).

8) Please provide a general description of how you will analyze this data.

* Re-dash queries + dashboards

9) Where do you intend to share the results of your analysis?

* Only on re-dash and with mobile teams.

**Comment by ekager** [comment]
@liuche tagging for data review :)

**Comment by pocmo** [comment]
Is an average over all loads really statistically meaningful (e.g. mobile vs. wifi, country restrictions, different contracts, different servers/sites)?

**Comment by bbinto** [comment]
@Sdaswani should we bring in the Rebecca Weiss / PI team for suggestions?

**Comment by Sdaswani** [comment]
@pocmo my thought is if you compared the average load time across all pages of Firefox Quantum Desktop vs. Google Chrome Desktop, it's safe to assume that both populations are very similar, so it would give a useful metric about rendering speed. I wanted to compare GeckoView vs. Webview for Klar in similar fashion.

But happy to bring in PI team @bbinto if you want too make sure.

**Comment by ekager** [comment]
@liuche tagging for data review!

**Comment by liuche** [comment]
@fbertsch, since you handle a lot of our data, I'd like to get your point of view on whether this would be meaningful data to have.

What can you learn from having "average load time across all a user's page-loads", from both Klar GeckoView (opt-in) and Webview? See sebastian's [comment](https://github.com/mozilla-mobile/focus-android/issues/2091#issuecomment-366915344) earlier.

If we want to compare performance of page loads, is there data that you think is useful? (e.g., number pageloads above a certain amount of time, avg pageloads as suggested, etc)?

**Comment by liuche** [comment]
Discussed this data collection with @fbertsch and @Sdaswani, regarding what conclusions could be drawn from this data, and whether it would answer "Determining if GeckoView loading times compare to WebView loading times in the wild" by averaging-by-user the page loads of GeckoView vs Webview. Since Klar would have GeckoView, and Focus would have Webview, it seems like the "Klar vs Focus" browsing effects might drown out the GeckoView vs Focus effects.

The data review form has been updated to clarify that this is to "establish baselines for browser engines on Focus and Klar".

**Comment by liuche** [comment]
data-review+

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?

Yes, in Focus Android wiki

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, Focus data controls.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**

Permanent, to establish baseline and ongoing perf monitoring - @bbinto will be monitoring.

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

Type 2/Type 1, for average page loads

5) Is the data collection request for default-on or default-off?
default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
No

7) Is the data collection covered by the existing Firefox privacy notice? 
Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No, baseline collection

**Comment by liuche** [comment]
@ekager: I assume @bbinto would be monitoring data (because she does it for Focus) - please include her in the review form next time, for permanent monitoring.
