### ISSUE TITLE
Configure Gradle to run Gecko/Webview appropriate UI tests after #2087

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#2104]
Once the geckoview is added to the project, we should redefine and group UI Tests that can run on geckoview vs. webview

**Comment by pocmo** [comment]
*In theory* shouldn't the same UI tests pass regardless of engine?

**Comment by npark-mozilla** [comment]
Because we don't have visibility of Geckoview DOM unlike webview, we have no way of checking whether the screen is rendered. So tests like download test need to be disabled, because we can't find the download link to be clicked.  @snorp says enabling this on geckoview is a big a11y work, so it might take a while until it's addressed.  Until then, those tests should be disabled/redefined.

**Comment by Sdaswani** [comment]
@pocmo makes a good point though - aren't we missing functionality in GeckoView if we have to disable some tests? If not, why did we need the tests in the first place?

**Comment by npark-mozilla** [comment]
@Sdaswani With geckoview, we're definitely losing visibility w.r.t. UI Tests because of above mentioned limitation. (More specifically: https://bugzilla.mozilla.org/show_bug.cgi?id=1343317) Until this bug is addressed, (and probably not in the near future) we would have to make concessions in UI Tests.  

To the end user, this won't matter at all - it's only affecting the automated UI tests.

**Comment by Sdaswani** [comment]
So what you are saying @npark-mozilla is we can't test all user features with GeckoView until that bug is completed. So we may not catch regressions as we build new features. Thanks for bringing this to my attention, and FYI @bbinto .

**Comment by npark-mozilla** [comment]
Technically yes. to Espresso/UIAutomator, the Geckoview area is completely dark.  We might be able to get around to modify some tests, but some would have to be disabled for Geckoview, and covered by manual tests.

**Comment by Sdaswani** [comment]
Yes we would need to add manual tests for all those dark areas @npark-mozilla .

**Comment by Sdaswani** [comment]
@npark-mozilla can you drop the bugzilla here?

**Comment by npark-mozilla** [comment]
#2160 and #2291 are for this bug, and FYI, the bug that tracks DOM implementation on geckoview is https://bugzilla.mozilla.org/show_bug.cgi?id=1343317
