### ISSUE TITLE
Inconsistency with Fennec at L10n 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-mobile/focus-android#2116]
Device: Pixel 2 (Android 8.1.0)
Build: +GeckoView  #3898

I am seeing some locales I have never met. I know I don't own all knowledge in this world at this but I am failing to identify them both on world wide web or in Mozillațs resources:

* https://hg.mozilla.org/l10n-central/
* https://support.mozilla.org/en-US/locales

![l10ns](https://user-images.githubusercontent.com/1391451/36424442-f693b20e-164b-11e8-9424-e01bb3942e5a.png)

**Comment by pocmo** [comment]
Focus languages:
https://pontoon.mozilla.org/projects/focus-for-android/

cc: @delphine

**Comment by Delphine** [comment]
If I understand this issue correctly, what Ioana sees is expected, since we don't ship the same languages in each product we launch :) 

I confirm that the locales shown to the left exist (they are in their "original" name) and should appear on Focus for Android builds. Some of these (like Triqui) are only shipping on Fennec single-locale builds, which is why you don't see them in both products. But it's safe to say in general that Fennec and Focus Android don't share the same list of locales. I think we can close this issue, unless I misunderstood something :) thanks!

**Comment by ioana-chiorean** [comment]
@Delphine you understood the issue correctly but still in the link provided i do not see them: https://pontoon.mozilla.org/projects/focus-for-android/ Probably i am missing them so if u think they are ok we are good to close this.

**Comment by Delphine** [comment]
Yes, as mentioned they are listed in their original language under the phone settings, which is why you can't recognize all of them by comparing them with the Pontoon list, where that's not the case (except for Triqui that is the same in both cases).
The locale in your 1st Focus Android screenshot corresponds to Zapoteco ("zam").
The 2 locales listed under Triqui in your 2nd Focus Android screenshots are Mixteco Yucuhiti ("meh") and Mixtepec Mixtec ("mix").
So, I think we can close this!

**Comment by ioana-chiorean** [comment]
Thanks @Delphine !
