### ISSUE TITLE
Google maps get location should be inactive 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2128]
Build: Klar+GeckoView #3898

STR:
1. Go to maps.google.com
2. Tap the get location button.

Expected results:
As on Focus, the button is inactive. Can't ask for location. 

Actual results:
You can ask to get location, but with no result, it just keeps searching.
Recording: https://drive.google.com/open?id=1AaLQX8qsPUiYaVUZqJh4th2CtJeMT824

**Comment by ekager** [comment]
Some more information - with Android WebView, we can disable these permissions so that the WebView cannot even request them (https://github.com/mozilla-mobile/focus-android/blob/master/app/src/webview/java/org/mozilla/focus/web/WebViewProvider.java#L119), but with GeckoView, we can't disable these currently and if we do not implement the callbacks, then the user will just see the browser as not working. GeckoSessionSettings would need to add a way for us to disable these permissions.

**Comment by pocmo** [comment]
I filed an issue to determine whether GeckoView can do the same as WebView:
https://bugzilla.mozilla.org/show_bug.cgi?id=1440710

To reduce risk I would avoid adding location etc. as a new feature unless @bbinto thinks it's a feature we want to ship in 5.0.

**Comment by ekager** [comment]
I think without setting any PermissionDelegate, this issue is now solved. It's not "disabled" but it doesn't continue to search or prompt the user, which seems to be what Focus does as well. Closing.
