### ISSUE TITLE
Add telemetry event when switching from custom tab to full browser

### ISSUE THREAD

**Issue by layely** [mozilla-mobile/focus-android#2187]
A follow up of [open in firefox focus PR](https://github.com/mozilla-mobile/focus-android/pull/1634#pullrequestreview-96672658)

**Comment by pocmo** [comment]
Now that users can switch from a custom tab to the full-featured browser we added a probe for that:
* (action, open, menu, full_browser)


# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

* Get an idea how often users switch from a custom tab to a the full-featured browser experience
* Identify what browser features a user might be missing in a custom tab

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?

* This probe should be helpful to make product/UX decisions around custom tabs.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

* No alternative methods have been considered. UI telemetry is already in place and seems to be the right tool for this.

4) Can current instrumentation answer these questions?

* No, this is a new feature and therefore no data/instrumentation exists yet.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

One additional UI telemetry probe is sent whenever the menu item to switch to the browser is selected:

* (action, click, menu, full_browser)


6) How long will this data be collected?  Choose one of the following:

* For now unlimited.

7) What populations will you measure?
8) If this data collection is default on, what is the opt-out mechanism for users?

Release users that have telemetry enabled (Focus: Opt-out, Klar: Opt-in).

9) Please provide a general description of how you will analyze this data.

ReDash / sql.telemetry.mozilla.org

10) Where do you intend to share the results of your analysis?

ReDash dashboards.

**Comment by liuche** [comment]
A few quick questions:

* Who will monitor this data permanently?
* Are you collecting other data to answer the second question "Identify what browser features a user might be missing in a custom tab" ? I don't see any additional probes requested in this review (to action-click-menu-full_browser)

**Comment by liuche** [comment]
Pending questions ^

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?
On Focus-Android telemetry wiki

2) Is there a control mechanism that allows the user to turn the data collection on and off?
Focus data controls

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**
I assume Barbara Bermes, but await confirmation from @pocmo on that.

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **
Type 2

5) Is the data collection request for default-on or default-off?
Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
No

7) Is the data collection covered by the existing Firefox privacy notice? 
Yes, Focus data collection

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No

**Comment by pocmo** [comment]
> Who will monitor this data permanently?

I expect this probe to become part of @bbinto's dashboards.

> Are you collecting other data to answer the second question "Identify what browser features a user might be missing in a custom tab" ? I don't see any additional probes requested in this review (to action-click-menu-full_browser)

No additional probes added for that. But we can look at the flow with our existing probes to see something like:
* Switch to full browser
* Add to home screen
