### ISSUE TITLE
Add animation when switching from custom tab to full browser

### ISSUE THREAD

**Issue by layely** [mozilla-mobile/focus-android#2188]
A follow up of [open in firefox focus PR](https://github.com/mozilla-mobile/focus-android/pull/1634#pullrequestreview-96672658)

**Comment by pocmo** [comment]
CC: @brampitoyo

**Comment by brampitoyo** [comment]
Thanks for following up, @layely!

I have a few questions:

1. Do we currently use or specify any switch animation?
2. Phone manufacturers (like Samsung) may choose to implement their own transition animation. Is there a way for us to say “use the OS default animation”, instead of writing our own implementation?

**Comment by layely** [comment]
> 1. Do we currently use or specify any switch animation?

We are using some (default I think) transition when opening  setting or help page via the menu. 

> Phone manufacturers (like Samsung) may choose to implement their own transition animation. Is there a way for us to say “use the OS default animation”, instead of writing our own implementation?

After some investigation, I did not find a way to get the default switch animation which is as you mentionned vendor or theme dependant.

CC: @mcomella

**Comment by brampitoyo** [comment]
@layely Then using our current transition (which is seen when going in and out of Settings) for custom tabs sounds like a good move to make here.

**Comment by vesta0** [comment]
Not on the Focus roadmap but will be be taken into consideration.
