### ISSUE TITLE
GeckoView: No web content rendered while playing dismiss animation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2250]
When erasing a session we play an animation where the current browsing session shrinks and drops out of the screen. In the GeckoView version this animation is missing the rendered web content.

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1445285

**Comment by cpeterso** [comment]
This polish bug probably doesn't need to block the Focus 7.0 milestone. The blocking [Firefox bug 1445285](https://bugzil.la/1445285) is a P2, meaning it probably won't be fixed for GeckoView 62.

**Comment by pocmo** [comment]
We should first decide what to do with the animation: Keep it as-is even though it does only animate the toolbar or disable it (cc @brampitoyo)

**Comment by brampitoyo** [comment]
@pocmo What if the current tab fades to pure white before it shrinks? This way, we essentially only animate a white-coloured box and not the actual web content.

**Comment by ekager** [comment]
If you remove the `alpha` in `erase_animation` then I'm seeing that the content is rendered as it is animated. Could we alter this `alpha` to have it look as desired?

**Comment by sblatz** [comment]
I think it'd be best to remove the alpha animation _for now_ until this is fixed (since it's not an active priority for GV team)

Here is the current buggy animation vs. no alpha transition:

**Current**
![current](https://user-images.githubusercontent.com/4400286/45041033-5aec7000-b035-11e8-80cc-6e01d8864986.gif)

**No Alpha Transition**
![no alpha](https://user-images.githubusercontent.com/4400286/45041060-6b044f80-b035-11e8-8b02-23cc148c572a.gif)

@brampitoyo thoughts?

**Comment by brampitoyo** [comment]
@sblatz Agreed. This may fix the slowness problem that @ekager experienced in #3158?

**Comment by snorp** [comment]
I'm going to look into making GeckoView switch between a TextureView and a SurfaceView dynamically, so you can use the TextureView mode for animations. Chrome WebView has a ton of code that integrates their compositor into the View drawing infrastructure, so they don't have this problem. We're never going to do that, so some kind of SurfaceView/TextureView toggle seems like the best way to enable animatinos like this. Until then, avoiding alpha/scaling/etc seems best.
