### ISSUE TITLE
Android: Option for automatic "Open with..."

### ISSUE THREAD

**Issue by xpoke** [mozilla-mobile/focus-android#2307]
This might be a duplicate, but didn't see any open issue specific for this.

Most android browsers allow opening the native app when a supported URL is clicked. For example, tapping an in-browser link to youtube.com would open the content in the youtube app.

In Focus, this is available only using two taps (Menu -> Open with ...) which slows down the interaction.
Please add a feature to automatically open supported links in their native app without requiring additional user action.

**Comment by pocmo** [comment]
I think I have seen this before. But I can't find it.

We are not opening other apps by default right now to avoid leaking the browsing session to another app. What happens in Focus stays in Focus. Unless the user decides to open or share with other apps. I'm pretty sure that we talked about making switching to an app easier though (@brampitoyo do you remember something?)

**Comment by xPoke** [comment]
I understand wanting to keep the user in the app, but an "Open with" action in android is a user-dictated action (android prompts the user and it is then decided by the user if to use the app on a per-request basis, always open in app, or always open in browser) - Focus doesn't need to decide for the user which app he prefers (In this instance Focus decides that it takes priority).

**Comment by brampitoyo** [comment]
Hi @xPoke, thanks a lot for bringing this to our attention.

I agree with @pocmo that we want to avoid giving another app your URLs without your consent. What happens in Focus stays in Focus. At the same time, we also want to make it easy to open certain links (YouTube, Facebook, Twitter, Pinterest, etc.) directly in the app. As you can see, they are two goals that almost always directly contradict each other!

The compromise we have is by having a menu item called “Open with…”, that will let you choose your app. Even here, we only have an option for “Just Once” in order to maximise privacy.

OK. That’s our context – the story so far. To answer your question:

What if we have an “Always” option on this “Open with…” dialogue? If you select it, you only have to do two taps (Menu -> Open with...) once. The next time you open a link by tapping on it directly, Focus will respect your preference and open it in the right app.

We can also have this “Open with…” dialogue show up when you tap directly on a link, but this action is so easily performed, that the risk of leaking browser session becomes high. Therefore, I think that access to this dialogue should be limited to the menu.

This way, users who want to set up exactly how their links open can do so from within the menu, and future access is just one tap if they choose “Always” – but most users will be protected from leaking browser sessions.

Thoughts?

**Comment by xPoke** [comment]
That seems like a really good option without changing current behavior too much.

One issue to be aware of is how users would undo the "always open in..." functionality, since users won't have the Focus menu options when a different app is opened for a link.

**Comment by pocmo** [comment]
> One issue to be aware of is how users would undo the "always open in..." functionality, since users won't have the Focus menu options when a different app is opened for a link.

That's a good point. And makes me wonder if we start confusing people if we simulate the same behavior the system does - but then this doesn't show up in Android's system settings (where you can clear default apps).

**Comment by brampitoyo** [comment]
@xPoke My concern is, if the user keeps undoing “always open in”, do we even need to provide an “always” option to begin with?

I then wonder if a better solution is to provide a toggle that says something like:

> **Open link using third-party applications**
> Ex. If you have YouTube app installed, all youtube.com links will open there

A very big caveat: not sure if this is even possible or smart to do!

This toggle only controls what would happen when you tap on the link. The “Open With…” item will stay inside the menu and have the same behaviour as we currently have.
