### ISSUE TITLE
Fullscreen mode and devices with camera cutouts

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#2316]
Related to #2275. When using a device with a camera cutout and switching to fullscreen mode, there's a black bar at the top of the page. I assume this is caused by our code that adds the statusbar  padding.

**Comment by pocmo** [comment]
@fercarcedo Maybe something for you again? :)

**Comment by pocmo** [comment]
![screenshot_1521196889](https://user-images.githubusercontent.com/89638/37516687-36565aa6-290f-11e8-97f9-edc40e9ee962.png)

**Comment by fercarcedo** [comment]
Yes, definitely I can take a look at this

**Comment by fercarcedo** [comment]
@pocmo I have been looking at this and we don't add any padding on fullscreen mode, since the video_container FrameLayout takes up the whole screen, without padding. I have also tested this on Android P without simulating a notch and it works just fine (it doesn't leave space for the status bar).

Moreover, if I disable entering immersive mode, it takes the full screen (displaying under the status bar), so there is no padding being applied.

So, I have come to the conclusion that this is Android-related, and it kind of makes sense, since on a real device the camera cutout would be obscuring part of the content, so I think Android P on immersive mode forces apps to draw immersive mode content right below the status bar

**Comment by pocmo** [comment]
@fercarcedo Oh, yeah, of course. This makes sense. It's confusing on the emulator where there is just a black bar. But on a real device you do not want your video or whatever be displayed behind the notch. Thank you for looking into this and sorry for wasting your time.
