### ISSUE TITLE
Send Histogram Data for Load Times

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2347]

**Comment by pocmo** [comment]
_No description provided._

**Comment by Sdaswani** [comment]
😂 I’m working on it....

**Comment by fbertsch** [comment]
Initial doc here for the new `mobile-metrics` ping spec: https://docs.google.com/document/d/1q2V45_fyzm_DGaCos34QEQimsodYJMJCq5Ix-ys9KkE/edit

**Comment by Sdaswani** [comment]
Thanks @fbertsch !!!!

**Comment by pocmo** [comment]
Note: This ping type should be implemented in the telemetry library.

https://github.com/mozilla-mobile/telemetry-android/issues/68

**Comment by Sdaswani** [comment]
@bbinto to decide when we do this.

**Comment by pocmo** [comment]
Summary from a meeting with gfritzsche and aplacitelli:

Process:
* Gecko / Telemetry core is responsible for collecting, persisting and accumulating the data.
* The app requests the data from GeckoView via the API :esawin defined
* The app side is responsible for building the ping and uploading it (implemented in telemetry-android)

Constraints:
* Those pings are too large to send them often. Therefore the app will limit how often the data is collected for ping generating/upload. For parity with desktop the app will wait until locally midnight has been crossed (-> Data is collected and send max. once a day)
* The app needs to talk to GeckoView in order to collect the data. Therefore we are going to collect the data while there's a GeckoView around (to avoid starting Gecko just for the collection) either at the start, end or during a session.
* We may want to wait a minimum time (e.g. 5 minutes) before we do the initial collection to avoid that the first ping doesn't contain any meaningful data.

**Comment by bbinto** [comment]
Agreed with @cpeterso
