### ISSUE TITLE
FR: Load website when internet connection restored

### ISSUE THREAD

**Issue by daivat15** [mozilla-mobile/focus-android#2416]
Why:
It would be nice to add a feature where a webpage loads on its own once internet is available to the device. This will make it easier for users as they will not have to periodically press the refresh button.
Suppose the device has no internet initially, so the user would see a "Server not found" screen. If the device regains internet connection while the app is in the foreground, it should try to load the webpage again(something like what Google Chrome does).

What:
Add a check to reload the webpage if it has been not loaded already and an internet connection is established.

Acceptance Criteria:
Attempt to load a webpage without an internet connection. Focus will redirect the user to the "Server not found" screen. Establish an internet connection with the device. Focus should automatically recognize that an internet connection has been established and attempt to reload the webpage.

**Comment by shikhart98** [comment]
This is a nice issue, can I work on it?

**Comment by levimatheri** [comment]
Is anyone assigned to this? Would like to work on it

**Comment by bbinto** [comment]
@daivat15 - would you mind following our new template to understand the user problem, and to help us prioritize better?


### Why/User Benefit/User Problem

### What / Requirements

### Acceptance Criteria (how do I know when I’m done?)

**Comment by daivat15** [comment]
@bbinto I have updated the issue description. Looks okay?

**Comment by brampitoyo** [comment]
Hi @ekager, in my opinion, this issue should have no user-visible component. We can check whether the user is actually connected to the internet ourselves, then reload the URL if that condition is true.

![image](https://user-images.githubusercontent.com/51007/45466587-cdb0c600-b76e-11e8-9618-94623d7510b8.png)

Edge case: when you have a bunch of “server not found” pages over many tabs, should we reload them all at once when internet is found, or wait until the user has visited the tab in order to perform a reload?

**Comment by EmmanuelMess** [comment]
@brampitoyo 
Maybe tell the user that he doesn't need to frantically press the reload button for the page to reload, "When internet is connected the page will reload" should work.

**Comment by colintheshots** [comment]
There's several states to consider as being "connected" from Android's point of view isn't a single state:
- not connected to any network: easy, just wait until the UI is visible and we are connected to try again.
- connected to a network with a captive portal: ideally, we would open a tab to handle the portal before we attempt to reload. Connecting through a portal isn't instant and there may be a delay where we have to wait and retry.
- connected to an unreliable network which drops packets: this is notoriously hard to detect when we're "connected" and when we're "not connected" because we're technically connected the whole time as far as Android is concerned. The only option is retries with a fall-off strategy.
- connected to a reliable network: just load the page.

**Comment by EmmanuelMess** [comment]
> There's several states to consider as being "connected"...

I am supposing the user doesn't know that.

I would think that the user knowing that the app will do it's best to reload the page when it can be is better for him (less to worry about).

For each of the points I would think you already have a set procedure to load (or fail to load) pages that can be used for this issue. With that being said, if there is a case that is specifically problematic, do tell.

**Comment by vesta0** [comment]
@ekager would you please assign a t-shirt size to this one?

**Comment by brampitoyo** [comment]
I had a chat with @ekager, and she brought up two important points:

1. When you’re browsing a page that’s already loaded, we need to indicate (subtly) that you’re not connected to the internet – and that the fault lies in your connection, not the browser.
2. When you’re not connected and try to load a site, we need to indicate (strongly) that the site is unavailable, but will be reloaded when connectivity becomes available again.

So, the user flow needs to be expanded:

![user-flow](https://www.lucidchart.com/publicSegments/view/f7c2afe8-d6e1-4e1a-8238-fc1fe052e109/image.png)

And our mockup needs to cover this subtle indicator (a banner), as well as a strong indicator (a connection error page).

![offline-warning-i01 2x](https://user-images.githubusercontent.com/51007/45659186-52248f80-bb47-11e8-9d6b-7eb07af08316.png)

What do you think?

**Comment by EmmanuelMess** [comment]
@brampitoyo This looks amaizing!

Although I think the reload button should be kept (in the "Error page") in case an error occurs and the app doesn't autoreload.

**Comment by ekager** [comment]
I have a WIP for this feature but have hit a road block with the GV loadData API showing the data url for the error page in history see filed bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1483677

It looks like this may have to be pushed to the next sprint if we want to incorporate our own error page.
