### ISSUE TITLE
Use Mozilla's location service for search country code

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#245]
Currently we use the device's locale for determining the search engines and default. However Fennec asks Mozilla's GeoIP service to determine the country code. So that I get German search engines / defaults in Germany even with en_US locale. That's something we probably should copy.

Related code:
https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/search/SearchEngineManager.java?q=path%3ASearchEngineManager&redirect_type=single#428

**Comment by pocmo** [comment]
Focus for iOS seems to pick the search engines solely based on the region setting.

**Comment by st3fan** [comment]
We do not use this service in *Focus for iOS* currently. Let's ask mkaply if he thinks this is a requirement for *Focus for Android v1.0* or if we are good with the locale detection that we currently do.

**Comment by mkaply** [comment]
The reason Focus for iOS doesn't use the search service is because we never ported any of the search service work over to iOS at all.

If we could use the search services in Focus, that would be helpful so we don't end up with a technical debt there.

The code to query the search service is pretty self contained in https://dxr.mozilla.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/search/SearchEngineManager.java.

**Comment by pocmo** [comment]
From talking on Slack: Should be implemented - but can be in the next release.

**Comment by jaller94** [comment]
I consider this to be an anti-feature (called 'Tracking' in the F-Droid store) because it builds up a connection without the user's consent.
Using the system's locale setting is the right way to determine the country for a privacy-focused product.

**Comment by cpeterso** [comment]
Why would an en_US user in Germany want to use a German language search engine? If they spoke or preferred German, they could set their device locale to de_DE or manually navigate to a German language search engine like google.de.

What is the behavior of Chrome on Android and Safari on iOS?

**Comment by mkaply** [comment]
> Using the system's locale setting is the right way to determine the country for a privacy-focused app.

Unfortunately in our testing, 50% of users have en-US set as their locale but are not located in the US. So using the system locale is very unreliable.

The issue here is not the language of the search per say, it's about agreements we have to use a particular search engine (or search code) in a particular region. So we need to know someone is in Ireland so we can give them the Irish eBay, for instance.

Again, locale is completely unreliable.

**Comment by jaller94** [comment]
I did not know that the agreements also affect Firefox Focus/Klar and have to be enforced.

Other (no-network) ways of determining the location:

- "Choose your country" dialog
- Request coarse/fine location

A choice of a dialog and the network-based locating would be acceptable in my opinion. Otherwise the app implys that the user agreed to "coarse location" and considers the use of Mozilla's service safe for their means (including letting the network infrastructure and DNS servers know).

**Comment by mkaply** [comment]
I definitely don't want to ask for coarse/fine location because it gives us data we aren't going to use (too fine).

**Comment by TPS** [comment]
> - "Choose your country" dialog

This would make an _excellent_ addition/replacement to #1692 as some way to use all that 1st-open blank space!

**Comment by pocmo** [comment]
Yep.
