### ISSUE TITLE
Adjust size of "Open with..." bottom sheet on tablets

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#248]
Our "open with" screen:

![open_with](https://cloud.githubusercontent.com/assets/89638/23963133/ac85c9b6-09b0-11e7-9b46-2e90bba53a34.png)

Compare with native "Share" screen:

![share](https://cloud.githubusercontent.com/assets/89638/23963189/c926ec12-09b0-11e7-9d18-80464cce6849.png)

And while we are fixing that... the initial height of the bottom sheet is weird on tablets. It's only showing one option and therefore looks like that's all there is:

![initial](https://cloud.githubusercontent.com/assets/89638/23963254/f33a3b62-09b0-11e7-95e2-c8d044987ea6.png)

**Comment by antlam** [comment]
+1, let's match that Share sheet

**Comment by ahunt** [comment]
![device-2017-03-22-125618](https://cloud.githubusercontent.com/assets/1546915/24218041/0e112e7a-0eff-11e7-9048-0a3627911487.png)

**Comment by ahunt** [comment]
The fix I landed makes the dialog _much_ taller. It looks like it's using a 16:9 keyline relative to the width of the dialog (as opposed to 16:9 keyline relative to the whole screen, which is what the system one does). I'll see if I can fix that too.

**Comment by ahunt** [comment]
Ignore my previous comment: the reason the dialog was previously showing only 1 line was because it was using a 16:9 keyline relative to the entire screen.

The system version use 50% of the screen height, which isn't explicitly mentioned in the spec - but that's what the example tablet screens show:
https://material.io/guidelines/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets

**Comment by ahunt** [comment]
I've updated the heights to match what Android does on my N9 (approx 320dp height, although it reduces the height slightly below that in landscape - which is odd):
![open2portrait](https://cloud.githubusercontent.com/assets/1546915/24260437/14876a3c-0fb1-11e7-84c8-382fe779951e.png)
![open2landscape](https://cloud.githubusercontent.com/assets/1546915/24260441/185ef062-0fb1-11e7-82da-9f7ac46e1dfb.png)

**Comment by ahunt** [comment]
I'm slightly concerned that the system share dialog size might vary on other devices (I've only tested with an N9 so far). Another potential issue is that we enable this for sw600dp and larger, I don't know what criteria Android uses to decide the BottomSheet size.

(It seems that the system share dialog uses a completely separate implementation to the support library, since I haven't found any code explaining even the height that they use on tablets, or even code that makes the dialog narrower on tablets. I haven't found the system implementation yet.)
