### ISSUE TITLE
Sometimes "loading does not finish" when displaying error pages

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#250]
Sometimes when showing an error page the loading indicator is still visible and the toolbar color doesn't change. Refreshing the page usually fixes that.

![errorpage_loading](https://cloud.githubusercontent.com/assets/89638/23965178/74a50424-09b7-11e7-8539-b317beef1927.png)

**Comment by ahunt** [comment]
I don't know if there's a clean way for us to fix this: webview is doing the following:

1. pageStarted() when trying to load the page
2. onErrorReceived() (where we load the error page)
3. onPageFinished()
4. onPageStarted() (we start the progress bar again)
5. Only sometimes (about 50/50), onPageFinished() again

We could probably write some hacky code to ignore onPageStarted() when called directly after onErrorReceived(), I'm not sure how reliable that would be.

(All callbacks supply the same URL, since we're pretending to load the original URL in onErrorReceived()).

Trying to call WebView.stopLoading() before loading the error page doesn't seem to help either.
