### ISSUE TITLE
Very High Event Timestamps

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/focus-android#2573]
We're seeing high event timestamps in the telemetry pipeline. This is happening even for clients who have relatively correct `created`, which means it's not related to clock skew.

See here for a few examples: https://sql.telemetry.mozilla.org/queries/52830

I found that only about 97% of events happen within one day of `created`. I'll have a CDF of values available soon.

**Comment by fbertsch** [comment]
cc @bbinto, this explains the long sessions we're seeing. I'll leave it to you to prioritize investigating this. Let me know if the team needs any more info to do so.

**Comment by bbinto** [comment]
@fbertsch -- could you please elaborate more on the problem that this finding reveals, and what the solution is to fix it?

To repeat in my own words what you said: So is your feeling that the long sessions are actually not "real" and are caused by a specific timestamp issue (that I don't understand yet).

Thanks :)

**Comment by pocmo** [comment]
@pocmo just to confirm - the event time is time in ms, relative to process start time?

The "created" timestamp in the ping uses "current time in milliseconds" (+ separate timezone offset field):
* https://developer.android.com/reference/java/lang/System.html#currentTimeMillis()
* https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/measurement/CreatedTimestampMeasurement.java#L16

An event uses: "milliseconds since boot" but web substract the first value we got so that we start at 0:
* https://developer.android.com/reference/android/os/SystemClock.html#elapsedRealtime()
* https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/event/TelemetryEvent.java#L95

**Comment by fbertsch** [comment]
@pocmo so the event timestamp is essentially `ms since first event`. `created` occurs after the first event, which explains why there are future events; we're adding an extra delta between `first event` and `created` to every event.

Can we populate the `processStartTimestamp` with the UNIX timestamp at time zero [0]?

[0] https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/focus-event/focus-event.1.schema.json#L81

**Comment by pocmo** [comment]
@fbertsch Yeah, we can do that. I filed this issue:
https://github.com/mozilla-mobile/android-components/issues/190

Note that:
> System.currentTimeMillis() is the standard "wall" clock (time and date) expressing milliseconds since the epoch. The wall clock can be set by the user or the phone network (see setCurrentTimeMillis(long)), so the time may jump backwards or forwards unpredictably.
https://developer.android.com/reference/android/os/SystemClock

**Comment by fbertsch** [comment]
@pocmo great, that's helpful. Thanks for the doc link. Given that we _have_ to use something from the client it'll have to be best-effort.

I've created a bug for using it in Amplitude: https://bugzilla.mozilla.org/show_bug.cgi?id=1462684

**Comment by bbinto** [comment]
@fbertsch thanks for the details, still I'm unfortunately not able to translate this into
a question/observations for me (sorry :)), e.g.  

- What does that mean for product and making decisions based on telemetry events I'm seeing?
- Ok, so seeing longer sessions is a result of this issue and therefore could mean that people actually don't stay that long in the app after all? Will this issue automatically increase exponentially over time and result is super long sessions that are not representative anymore?

**Comment by bbinto** [comment]
@pocmo, just to clarify if mozilla-mobile/android-components#190 is fixed, this issue can closed?

**Comment by pocmo** [comment]
Yes, once we switch here to the latest components release that includes the fix.
