### ISSUE TITLE
Signing task of build/sign/push pipeline doesn't rename *-unsigned.apk to *-signed.apk

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/focus-android#2779]
### Steps to reproduce
It looks like the signing task log is fetching the signed apks from scriptworker, but not renaming them:

```
2018-06-22 17:25:28,373 - signingscript.sign - INFO - "/builds/scriptworker/work/public/app-klar-webview-universal-release-unsigned.apk" has been zip aligned
2018-06-22 17:25:28,379 - signingscript.utils - INFO - Copying /builds/scriptworker/work/public/app-klar-webview-universal-release-unsigned.apk to /builds/scriptworker/artifacts/public/app-klar-webview-universal-release-unsigned.apk
```

https://taskcluster-artifacts.net/AsA3BQ8RQaSj9C9DgquKyQ/0/public/logs/live_backing.log

### Expected behavior

Task should rename apk file to *-signed.apk. (@pocmo @JohanLorenzo I'm not sure where this script is, I assume it's not https://github.com/mozilla-mobile/focus-android/blob/master/tools/taskcluster/sign-preview-builds.py#L58 (which maybe is meant to be run locally?))

**Comment by JohanLorenzo** [comment]
Thanks for filing this issue @liuche. We haven't encountered that issue in Fennec before, because we keep naming the file `target.apk` after each task. Therefore, I think the easiest solution is to name focus and klar in a generic manner.

If you'd prefer a fix in the worker. The call stack is the following:
* https://github.com/mozilla-releng/signingscript/blob/9367421c388b0e83186ca254b229305a933b4e8a/signingscript/script.py#L49
* https://github.com/mozilla-releng/signingscript/blob/9367421c388b0e83186ca254b229305a933b4e8a/signingscript/task.py#L158
* https://github.com/mozilla-releng/signingscript/blob/65cbb99ea53896fda9f4844e050a9695c762d24f/signingscript/sign.py#L160

As you can see, the worker returns the name of the original file. This is due to `jarsigner` which alters the original file (and doesn't create a new one).


Tell me what you all think!
