### ISSUE TITLE
Hide toolbar and FAB when web content is scrolled

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#28]

**Comment by pocmo** [comment]
![focus_scrolling_gif](https://cloud.githubusercontent.com/assets/89638/22977064/81f1d4bc-f38d-11e6-832a-b2f0ab0a0e72.gif)

I implemented the following behavior. @antlam What do you think?

**Comment by antlam** [comment]
I like the completely transparent status bar at the top! But I don't think that's supported on all versions of Android right? IF not, we should fill it with the same gradient as we have on the Toolbar/Actionbar.

As for the FAB, can we scale it out instead of scrolling it off the screen? like this :D https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior

**Comment by pocmo** [comment]
The transparent status bar is supported all the way down to Android 5.0 - our current minimum. :)

I'll have a look at the scaling animation!
