### ISSUE TITLE
Create a new "NIGHTLY" app icon for Focus/Klar nightly track builds

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2823]
### Why/User Benefit/User Problem

Some Focus Nightly testers are confusing that nightly builds use the "DEV" app icon.

![](https://raw.githubusercontent.com/mozilla-mobile/focus-android/master/app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png)

### What / Requirements

We should create a new "NIGHTLY" app icon for official Focus Nightly builds, similar to the "BETA" app icon. The "DEV" app icon should just be used for developers' local builds.

### Acceptance Criteria (how do I know when I’m done?)

Users can tell by the app icon whether they have the Focus prod, beta, nightly, or a developer build installed.

**Comment by pocmo** [comment]
* Nightly builds do not actually have the "Dev" logo. They get the regular release icon. #2818 is about creating a separate logo and changing that in Nightly builds.

* Beta builds get the regular release icon and are 100% release builds. That's on purpose so that we can promote good Beta builds in Google Play from Beta to Production without rebuilding anything.
