### ISSUE TITLE
Feedback about Request Desktop Site

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2841]
<img width="670" alt="screen shot 2018-07-03 at 7 47 48 am" src="https://user-images.githubusercontent.com/122897/42218095-7adccce2-7e95-11e8-8d4e-e11fd629e198.png">

<img width="662" alt="screen shot 2018-07-03 at 7 47 56 am" src="https://user-images.githubusercontent.com/122897/42218102-7d6e1eac-7e95-11e8-8911-20c66714169b.png">

**Comment by bbinto** [comment]
@brampitoyo - could you please help us think through issue 1, should the sub links be also requesting the Desktop site? I think they should, keep it on a domain level?

**Comment by brampitoyo** [comment]
@bbinto Originally, I designed the request desktop site behaviour to be carried forward across tabs and sessions:

> 1. Checkbox state “carries forward”, based on state of current tab.
> 2. Checkbox state doesn’t “carry back”.
> 3. Checkbox state “carries forward” across session, based on state of current tab.

But we opted to go with something more temporary, which is:

> All actions in the menu either apply to the current tab or page and do not affect other tabs.

It turned out that this is _too_ temporary, so we need to make the setting a little more permanent. There are a few ways to do this.

The first is to make desktop site permanent, but only for the current tab:

* User opens a page and turns on “Request Desktop Site”
* User taps on a link
  * If the link opens in the same tab, “Request Desktop Site” should be on
  * If the link opens in a new tab, “Request Desktop Site” should be off

The second is to make desktop site permanent, but only for the current domain:

* User opens a page and turns on “Request Desktop Site”
* User taps on a link
  * If the link opens the same domain, “Request Desktop Site” should be on
  * If the link opens a different domain, “Request Desktop Site” should be off

While the user asked for a domain-based solution, I think that we should go for the tab one.

1. It doesn’t have as many logic; less risk of potential bugs
2. It follows the behaviour of other Android browsers (Firefox, Chrome, Opera, Edge)

Thoughts?

**Comment by pocmo** [comment]
> I think that we should go for the tab one.

👍

**Comment by bbinto** [comment]
Thanks @brampitoyo - great summary, outline of options!

I'm with you and @pocmo on the decision. Thanks!

Anything we need @boek and @ekager to change (for the next release)?

**Comment by rpappalax** [comment]
As it is right now, it looks busted.  If I'm at www.youtube.com for example and request desktop site it redirects me to m.youtube.com.  If I repeat that action, it redirects me to www.youtube.com and so on.

**Comment by ekager** [comment]
@rpappalax  on WV or GV?

**Comment by rpappalax** [comment]
@ekager both.  but i'm wondering now if that's the desired behavior  - though perhaps a bit confusing??.

### Expected Behavior
1. enter youtube.com as URL
2. get directed to m.youtube.com (as expected)
3. Select 3-dot menu > "Request desktop site"
4. Get redirected to www.youtube.com (as expected).

## Actual behavior
5. Open 3-dot menu > Select "Request desktop site"
6. Returns you to m.youtube.com

## Expected behavior
5. Open 3-dot menu > Displays "View as mobile site"
6. Returns you to m.youtube.com

**Comment by swarnava** [comment]
I can see two **Request Desktop Site** options in Focus nightly, is it known? 
![image](https://user-images.githubusercontent.com/1162991/43818365-e0bc78f0-9afb-11e8-8797-bcd60cd2c581.png)

**Comment by swarnava** [comment]
Recently seeing two Request Desktop site option, filled #3087

**Comment by vesta0** [comment]
@ekager @rpappalax was this issue looked into?
