### ISSUE TITLE
Confirm latest telemetry probes

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#2844]
Trying to get some preliminary beta data for

1) Find in page
Beta channel should be filtered by channel = beta, right?
https://sql.telemetry.mozilla.org/queries/56481/source

2) Request Desktop Site
https://sql.telemetry.mozilla.org/queries/56483/source

**Comment by boek** [comment]
@bbinto re: Request desktop site

I'm not sure where the wires got crossed but the event object is `desktop_request_check` not `request_desktop_check`. I've updated the docs accordingly. Does that work?

**Comment by pocmo** [comment]
> Beta channel should be filtered by channel = beta, right?

That's how it worked in the past. Nowadays they are just release versions - because we promote them to release once they pass testing - without building anything again. Either just look at the event (as its only in Beta/Nightly anyways) or filter by build-id (See Play Store for which version code is currently on the Beta channel).

**Comment by bbinto** [comment]
Chatted with mreid in the telemetry slack channel, app version is currently not part of the core parquet table, therefore I can't filter by app version during beta

https://bugzilla.mozilla.org/show_bug.cgi?id=1473129

**Comment by pocmo** [comment]
@bbinto There should be `metadata.app_build_id` which is set to the version code. You can see the version code in Google Play in "App releases". Currently Focus Beta is 21772238.

**Comment by bbinto** [comment]
@pocmo yeah! that worked. Thanks so much for this temp solution!
