### ISSUE TITLE
Unable to scroll after watching fullscreen video

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2852]
This may be a GV bug, but we should spend a few hours seeing if it's on Focus.

https://bugzilla.mozilla.org/show_bug.cgi?id=1471340

**Comment by cpeterso** [comment]
@Sdaswani - We should add this bug to the Focus 7.0 milestone.

Randall says Firefox Reality had this issue. He fixed the issue by checking before calling GeckoSession.goBack() if it was currently in fullscreen and exiting fullscreen instead of calling goBack. He says Focus should do the same when it handles the back button so GV doesn't get into a bad state from calling goBack when in fullscreen.

GV will eventually add defensive code to exit fullscreen itself when goBack is unexpectedly called while in fullscreen, but this is something the app should have handled so the app is not in a bad state either.
