### ISSUE TITLE
Selecting 'Find in page' does not show the dialog when the dialog is

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#2859]
### Steps to reproduce
- Open webpage, open find in page dialog
- Scroll up, so the find in page dialog disappears from screen
- Go to menu, and select find in page menu item again

### Expected behavior
- Find in page dialog is in focus

### Actual behavior
- Find in page dialog is not shown on screen

### Device information
- Nexus 4, API 23

**Comment by ekager** [comment]
It's hidden when you scroll up, but still activated. @brampitoyo do you think we should disable the menu item while find in page is active?

**Comment by brampitoyo** [comment]
@ekager Actually, I don’t think that the Find in Page dialogue should ever be minimised/hidden and maximised/shown as you scroll up and down the page.

It’s not only to prevent this problem, but also to keep the UI focused on the find interface.

Otherwise, I agree with @npark-mozilla that the find-in-page text box should be re-focused when the user taps Main Menu -> Find in Page.

What do you think?

**Comment by lobontiumira** [comment]
This is no longer reproducible on 8.16.0 build using a Google Pixel (Android 10), and Samsung Galaxy Note 8 (Android 9).
