### ISSUE TITLE
'Stealth' and 'Send usage data' toggle switch interferes with each other

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2860]
### Steps to reproduce
- Go to settings, and open 'Privacy and Security' submenu
- When both 'Stealth' and 'Send usage data' are disabled, 
- Enable 'Stealth', then 'Send usage data'
- Disable 'Stealth'

### Expected behavior
- Only 'Stealth' is disabled

### Actual behavior
- Send usage data is also disabled as well

### Device information
Nexus 4, API 23. Pixel 2, API 27

**Comment by ekager** [comment]
Hi @npark-mozilla , are you seeing this on a Debug build or Release build? I think this is because we set the Send Usage Data checked every time the view is bound, so when we update the other setting, the view is rebound, and for debug builds, TelemetryEnabled is always `false`. If this is only in Debug, we can close this.

**Comment by npark-mozilla** [comment]
You're right, I don't see this on release build, will close, thanks!
