### ISSUE TITLE
Your Rights license link broken

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#2879]
### Steps to reproduce
- Settings -> Mozilla -> Your rights
- Click "licenses"

### Expected behavior
Licenses open

### Actual behavior
Nothing

### Device information

* Android device: Pixel 2
* Focus version: Tried local Klar WebView build (checked out at a random commit) and Focus GeckoView build, probably recent

**Comment by ekager** [comment]
Weird this is working for me on Pixel 2 in Klar+WebView... We changed it recently to open as a real tab so maybe something happened there

**Comment by pocmo** [comment]
@ekager It's about the "licenses" link on the "your rights" page - not the "your rights" page itself.

**Comment by ekager** [comment]
Oh apparently you're better at reading English than I am :P Thanks I'll look into this

**Comment by ekager** [comment]
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1475762

**Comment by ekager** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1475762 for a work around suggestion

**Comment by ekager** [comment]
There is a security issue that data URIs are not allowed to link local files and changing this would require work from the GV team. Since this is not a RB IMO I would rather not waste their time. Can we get a hosted Mozilla site for this information maybe? @Sdaswani I'm not sure who to contact about this?

**Comment by Sdaswani** [comment]
@ekager can you ask @jonisavage if this is something SUMO can host? If not then I will ask around the Legal team.

**Comment by ekager** [comment]
Hi @jonisavage , these are the two pages we would be looking to host.
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/assets/gpl.html
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/assets/licenses.html

**Comment by ekager** [comment]
Reasons we may want to host it: if we just open a WV, we are exposing users to data collected by WebView and would have to handle Tracking Protection. For moving away from WV, this seems like not the best idea.
https://github.com/mozilla-mobile/focus-android/issues/2070

**Comment by mcomella** [comment]
fwiw, having the licenses in product guarantees the licenses are accurate for the user's current device and app version while hosting on the web makes it harder to guarantee.

**Comment by bbinto** [comment]
@jonisavage - would you mind providing a SUMO page/link for this licence page instead?

**Comment by jonisavage** [comment]
This makes more sense on mozilla.org as users who come to this page might end up asking questions that are beyond our scope and the content and structure aren't a good fit for SUMO. If Legal can't get a page up in the next couple of days, I can provide a link to a temporary page, but we won't be able to get a page up until Tuesday since we have to reformat this content for SUMO. Here's a temporary link: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/license

**Comment by jonisavage** [comment]
Do we also need a separate page for GPL?

**Comment by Sdaswani** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1487893
