### ISSUE TITLE
Long press to copy URL during normal browsing

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#2885]
### Why/User Benefit/User Problem
I love the feature we added to long press the URL bar and copy the URL in custom tabs, and I want it for easier copying of URLs during normal browsing too.

### What / Requirements
- Remove Custom Tab check in on Long Press to allow copying URL to work for normal browsing as well.

### Acceptance Criteria (how do I know when I’m done?)
- Users are able to copy URLs by long press URL Bar during normal browsing

**Comment by sholkayvishal** [comment]
Can I work on this issue? It's my first time to **Open source contribution** and I think I'll be able to solve it.

**Comment by ekager** [comment]
Hi! This issue hasn't been considered by product yet or prioritized, so
probably not the best issue to work on right now. Check out our help wanted
or P1, P2 labels for issues ready to be worked on now!

**Comment by sholkayvishal** [comment]
Hi, is this issue now open? I mean can I try to solve this now as it has a P3 label?

**Comment by bbinto** [comment]
@ekager - I think that's a neat thing to do if a contributor can pick this up, I assume we need @brampitoyo to provide UI?

**Comment by vesta0** [comment]
@ekager @brampitoyo have you discussed the user journey and are there any mock-ups?

**Comment by ekager** [comment]
@vesta0 we already have this feature in custom tabs where you can long press on the URL bar to copy the URL to the clipboard. So it would be the same, just in normal browsing.

**Comment by EmmanuelMess** [comment]
@ekager I might have misunderstood the issue, because it seems you want the "Add custom URL" pop-up to appear AND the link to be copied to the clipboard; it seems to me that this could lead to an "impass" where they have to lose their clipboard contents to add a custom url from that button. 

It is true that the user can go the long way and manually add a custom url through the settings. But it seems that it would be a better idea to add a second item to the pop-up.

**Comment by ekager** [comment]
Closing because long press on URL bar is no longer the logic for add custom URL.
