### ISSUE TITLE
Just-in time information and one-tap action – Default Browser

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#2896]
### Why/User Benefit/User Problem
- Allow users to quickly set Focus as their default browser

### What / Requirements
- Provide intent sheet on a specific trigger (screen tip and/or settings page)

### Acceptance Criteria (how do I know when I’m done?)
- Intent sheet showing up and working
- User can set Focus as their default browser without leaving the app

## Success criteria/Telemetry
- Probe to track how many times/people initiated the intent sheet and selected Focus successfully

--------------
Per https://github.com/mozilla-mobile/focus-android/issues/2816#issuecomment-402697895 @brampitoyo should think of a nice contextual hint to ask users to set default browser.

**Comment by brampitoyo** [comment]
![set-default-browser 2x](https://user-images.githubusercontent.com/51007/43119678-79508ea4-8f6b-11e8-810f-126dcf851ff3.png)

**Comment by Sdaswani** [comment]
Cool @brampitoyo - when do we show this toast / tip?

**Comment by brampitoyo** [comment]
@Sdaswani I think that the menu item should show up only when Focus isn’t set a default browser, but the toast and modal dialogue should show up whenever the menu item is tapped.

**Comment by Sdaswani** [comment]
@brampitoyo this toast only shows up in the setting screen right?

**Comment by brampitoyo** [comment]
Yes.

**Comment by Sdaswani** [comment]
Looking at the data, out of 400 million foregrounds, settings has only be accessed some 2 millions times. Not very many people will ever see this tip. https://sql.telemetry.mozilla.org/dashboard/android-focus

**Comment by kfontecilla** [comment]
@brampitoyo Is there an update here as well? See Susheel's last comment. Thx

**Comment by brampitoyo** [comment]
Hi @kfontecilla 

“Set default browser” can be a start screen tip that will lead to a one-tap action:

![set default browser 2x](https://user-images.githubusercontent.com/51007/43692078-5416194e-9978-11e8-811f-82711705bc16.png)

This solves the problem that Susheel outlined.

However, labelling the Settings menu item clearly (the initial idea up above) is still a good idea. It won’t hurt us to do it in parallel to the start screen tip.

**Comment by brampitoyo** [comment]
@Sdaswani Yes. My current plan is to simply underline the deep link, which would apply to both iOS and Android.

(Obviously, if the deep link leads to SUMO, we want to say something along the lines of “Learn More”).

**Comment by bbinto** [comment]
@brampitoyo is this ready for eng-breakdown?

**Comment by brampitoyo** [comment]
Yes. This issue is now ready for engineering breakdown.

Just to clarify that this issue contains 2 separate moving parts:

1. A description under the Settings menu item (the menu item title remains unchanged):

    > **Set as default browser**
    > Open every link in Firefox Focus

2. A system dialogue that appears when the user taps on the Settings menu item, or on the start screen tip.

<img width="750" alt="screen shot 2018-08-28 at 3 45 35 pm" src="https://user-images.githubusercontent.com/51007/44699697-88876580-aad9-11e8-812c-226eaefc377a.png">

<img width="754" alt="screen shot 2018-08-28 at 3 44 07 pm" src="https://user-images.githubusercontent.com/51007/44699700-8b825600-aad9-11e8-9238-d924a6269acf.png">

**Comment by Sdaswani** [comment]
@sblatz does the current default browser tip show the 'Open With' system modal dialogue? Or does it just link to settings?

**Comment by Sdaswani** [comment]
Also @brampitoyo any objection getting this into 8.0 instead of 7.0?

**Comment by brampitoyo** [comment]
> […] any objection getting this into 8.0 instead of 7.0?

No objection, for a few reasons:

* Currently, the start screen tip links to the Settings menu item, and the menu item links to the System Setting to change default browser. It’s less direct, so we’ll have a lower completion rate, but it will still get the user to the right destination at the end of the day.
* 7.0 already contains a lot of new features, and we’ll need time to test and squash all the issues.

**Comment by sblatz** [comment]
@Sdaswani @brampitoyo This is the current functionality of the "make default browser" tip. I was under the impression that all we could do is push them to settings where they could change it themselves. Do other apps provide this alternative to setting default? cc @ekager 

![default browser 2018-08-28 10_50_29](https://user-images.githubusercontent.com/4400286/44731341-fbc8b180-aab0-11e8-8be1-ed3ba1900d82.gif)

**Comment by Sdaswani** [comment]
@sblatz I like the direct jump to changing the settings for 7.0. We can test conversion of course.

**Comment by brampitoyo** [comment]
@sblatz 

> […] all we could do is push them to settings where they could change it themselves.

It’s awesome that we don’t have to go to our Settings, then have our users tap to go to the system’s Settings. This will help our conversion rate.

This is the clearly better option.

**Comment by sblatz** [comment]
I believe this needs closed since the tip has the deep linking and so does the settings option. @Sdaswani to confirm?

**Comment by Sdaswani** [comment]
@sblatz I think this is trying to use the technique described here https://github.com/mozilla-mobile/focus-android/issues/2896#issuecomment-416441863, which shows you don't need to even leave the app.

**Comment by brampitoyo** [comment]
@Sdaswani is correct.

Deep-linking to the system Settings.app is better than deep-linking to a menu item inside our own Settings.

But being able to set default browser without leaving Firefox Focus is even better than deep-linking. And this is the mechanism that we want to build in this issue.

**Comment by sblatz** [comment]
After quite a bit of investigation, I've determined that this functionality is not possible exactly as described. 

There are three situations when the user toggles to make us default:
* **No default app is set**: in this case, we can display the desired menu where users can select a browser and set "always"

* **User installed a new browser since setting their default**: same behavior as above

* **User has a default set**: this is where we run into problems. There's no way for us to get this system prompt. In this case, for example, Opera Mini asks the user to clear the default (seen below) which then takes them to, in my opinion, a much more confusing screen than the one we're presenting now. We _could_ shove the user to the "defaults" section in this case like we're doing now, though.

<img width="300" src="https://user-images.githubusercontent.com/4400286/45379577-6e1bb480-b5ce-11e8-8faf-97853c4b7134.png">
<img width="300" src="https://user-images.githubusercontent.com/4400286/45379620-91466400-b5ce-11e8-8f2d-70ddb5de9371.png">


@brampitoyo @Sdaswani thoughts on this?

**Comment by Sdaswani** [comment]
@sblatz thanks for the investigation. I look forward to @brampitoyo's feedback - I'm ok passing on this until we see how the current default browser formulation is performing in market.

**Comment by colintheshots** [comment]
It sounds like we could do a mix of the Opera Mini solution and what we're currently doing. I should note that the Intent we're currently opening (android.settings.MANAGE_DEFAULT_APPS_SETTINGS) is API 24+ and we fallback to opening the SUMO page.

**Comment by sblatz** [comment]
Yeah, at the very least we should implement this for API <24.

**Comment by brampitoyo** [comment]
@sblatz Thanks for your thorough research!

There are at least two ways out of this problem:

1. Instead of linking to the “Default apps” page inside system Settings, we always link directly to the “Browser app” sub-page. Then at least we’ll eliminate the need to find the correct sub-page to modify browser settings. Is there a way to do this?

2. Detect the user’s browser state, then offer the correct UI.
    * If there’s no default browser set, show desired menu
    * If a default browser is already set (which is most of the time), link to the “Default apps” page inside system Settings (it’s even better if we can link to the “Browser app” sub-page)

If we can’t do either of these, it seems like our current way of doing things (link to “Default apps”) is the least confusing compromise!

What do you think?

**Comment by sblatz** [comment]
New behavior:

![default 2018-09-18 10_06_49](https://user-images.githubusercontent.com/4400286/45693237-a4a38300-bb2a-11e8-9daa-c0a3d2e0b8cc.gif)

**Comment by Sdaswani** [comment]
That’s pretty cool @sblatz!

**Comment by brampitoyo** [comment]
Looks great, @sblatz! This is exactly the functionality we wanted when there’s no default browser set.

**Comment by sblatz** [comment]
@vesta0 @Sdaswani do we want any sort of new Telemetry to distinguish between the ways in which a user enabled us as the default browser? Or should this continue to use the same ping?

**Comment by Sdaswani** [comment]
I think different named events for the various ways users enable / use a feature makes sense. But just go through data review.

**Comment by sblatz** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**

* Are users using engaging with a simpler way to enable Focus as a default browser?

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

* The answer to this question will help us determine if even more simplification is needed in the process to make Focus the default browser. This will benefit users as they will have a more streamlined process for making us default if they so choose.

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

* We could run an experiment or survey in order to determine this information, however it would be rather tedious and drawn out for such a small change in Telemetry.

4) **Can current instrumentation answer these questions?**

* Current instrumentation can only answer whether or not people are enabling us as the default browser, not which method they’re using to do so. Because of this, we have no way of knowing which method is simpler or more convenient for users.

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

* All data is Category 2.

**Events**

| Event                                    | category | method     | object | value  |
|------------------------------------------|----------|------------|--------|--------|
| Show “open with” default browser prompt | action   | show | make_default_browser_open_with |     |
Show settings default browser prompt | action   | show | make_default_browser_settings |     |       

6) **How long will this data be collected?**

* @mmccorks will permanently monitor this data.

7) **What populations will you measure?**

* All release, beta, and nightly users with telemetry enabled.

8) **Please provide a general description of how you will analyze this data.**

* Re-dash queries + dashboards

9) **Where do you intend to share the results of your analysis?**

* Only on re-dash and with mobile teams.

**Comment by sblatz** [comment]
Ready for data review from @liuche :)

**Comment by Sdaswani** [comment]
@sblatz @liuche is on PTO and i'm not sure who is covering for her on data review. but i think this can go in 8.0 right so we have time?

**Comment by vesta0** [comment]
@sblatz @Sdaswani yes this will go in 8.0

**Comment by pocmo** [comment]
I noticed two issues with the implementation:
* The "always" option doesn't appear the first time I click on the preference. I have to select Focus and then I will have to click again and then I see the "always" option.
* After going back to the app my browser has loaded https://www.mozilla.org/openGeneralSettings (an error page)

**Comment by Sdaswani** [comment]
@sblatz? https://github.com/mozilla-mobile/focus-android/issues/2896#issuecomment-425009365

**Comment by sblatz** [comment]
@pocmo that’s odd... what version of android are you running? I’ll investigate this today!
