### ISSUE TITLE
Sentry: RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2902]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4326354/

```
RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6753)
    at java.lang.reflect.Method.invoke(Method.java)
...
(2 additional frame(s) were not displayed)

Context.startForegroundService() did not then call Service.startForeground()
```

This is one of the Focus top crashes, with 162 crashes from 80 users.

**Comment by colintheshots** [comment]
See #2901.

In general, this common exception occurs when a phone is being sluggish. Android gives the app five seconds to start the foreground service and it didn't happen in time. This could be strictly due to a slow phone with an old processor and less memory requiring frequent garbage collections. More likely, the issue is caused by ANRs, which can simply be more significant on some phones than others. This is likely related to other ANR issues already reported.
