### ISSUE TITLE
Some images don't show up properly on web pages 

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#291]
Open http://m.androidcentral.com/android-o-guessing-game-has-officially-started navigation icons at the top don't show properly. (x-d out) does that have to do with the image format? I've noticed this behavior on another page inside focus

**Comment by ahunt** [comment]
I can reproduce this only if webfont blocking is enabled. However, disabling webfonts in firefox for android doesn't break this (I don't know if that means our webfont blocking is broken, or if firefox's blocking is broken).

This could be the result of our blocking methodology, I'll need to debug the page in question to figure out. (My theory is that the font files aren't being loaded as a font, hence firefox doesn't block them since it only blocks files being loaded via the font loading mechanism, whereas focus blocks all files that are fonts, regardless of where they're being used.)

I wonder if that means we'd need to provide an explanation that webfont blocking can break some sites (we already have text that could be used as part of the "Block other content trackers" pref)? Webfont blocking is disabled by default, so this shouldn't affect users until they select webfont blocking.

**Comment by bbinto** [comment]
Please let us know if you find the reason why this issue does occur in Focus but not in Firefox/web fonts blocked.

Since I've seen this happening on other websites as well, and since more and more web devs, I guess, rely on this dev practice to use web fonts for nav icons etc, we need to explain better & and keep it opt-in by default.

I do agree that we should include an explanation below the Block web fonts title. I assume we are in string freeze, so maybe just copying the explanation strings from "Block other content trackers" could work?

**Comment by ahunt** [comment]
I've debugged the site: the icons are in a webfont: that page uses the following font (and special characters, e.g. U+E615): 
https://www.androidcentral.com/sites/all/modules/visor_header/fonts/ac_iconset.woff

Firefox desktop/mobile are able to load fonts for icons (even if webfonts are disabled), by checking which characters are used (special "private use area" characters are used to select an icon from a webfont - in which case gecko loads the font regardless of blocking). We can't do that with webview: we only see the font URL, but we don't know what the font is being used for.

Using GeckoView would "fix" this, but it looks like we don't have a choice if we're using WebView.

(I'm guessing Focus on iOS should likely do the same thing, since it also blocks all .woff files with webfont blocking enabled.)

**Comment by pocmo** [comment]
> (I'm guessing Focus on iOS should likely do the same thing, since it also blocks all .woff files with webfont blocking enabled.)

That's what I thought too. But I just tried and Focus for iOS loads the toolbar icons.

**Comment by bbinto** [comment]
any idea why? @thebnich? 

pocmo / ahunt -- As for the description below the label...can we add (despite string freeze?)

- "May break some Web pages" (leveraging some of the text from "Block other content trackers")
or
- "May result in missing icons or images"

Thoughts?

**Comment by pocmo** [comment]
We can only use the full existing string: "May break some videos and Web pages". Everything else will require a new string.

**Comment by bbinto** [comment]
I assume this has to wait until after launch then? I feel using the exact same phrase (i.e. video) might not be suitable.

I think "May result in missing icons or images" is more appropriate.

**Comment by thebnich** [comment]
> any idea why? @thebnich?

Hm, I don't know what's going on in Focus iOS. It looks like we're blocking every .woff request we're making, and I don't see any of these icons when I look through each resource in the Safari inspector, yet they're still loading.

**Comment by pocmo** [comment]
We added "May result in missing icons or images".
