### ISSUE TITLE
On Webview, CNN video fails to load with TP on

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#2928]
## Steps to reproduce
On Webivew Focus, go to CNN.com , make sure the tracking protection is on
Play one of the news video

### Expected behavior
- Video plays normally with TP on

### Actual behavior
- VIdeo fails to play, saying that manifest failed to load

When Tracking protection is turned off, the video can be played

### Device information
Pixel 2, Android P
Focus master branch, commit https://github.com/mozilla-mobile/focus-android/commit/0e3cff5bc0a16e69dec5b841bdb0359d7aef2b41

**Comment by rpappalax** [comment]
Also seeing this 'could not load manifest file' issue on master w/ TP enabled.
NOTE: same issue on firefox-connect
see: https://github.com/mozilla-mobile-skunkworks/firefox-connect/issues/182
![image](https://user-images.githubusercontent.com/3699494/43099347-c436eac6-8e76-11e8-9963-e064351d1467.png)

**Comment by rpappalax** [comment]
NOTE: this issue is intermittent.  Going to gather evidence on more devices to verify.... TBD

Similar intermittent issue on Fandango.com video trailers.  When "Block other content trackers" is enabled, the video screen is either completely black or video doesn't play. 

*TP settings*
![image](https://user-images.githubusercontent.com/3699494/43106722-be25209a-8e8e-11e8-98e8-82543e3716e5.png)

When turning off "Block other content trackers," screen suddenly appears but doesn't actually play video:

![image](https://user-images.githubusercontent.com/3699494/43107388-a499c4fc-8e91-11e8-9610-7e018ceaa405.png)

![image](https://user-images.githubusercontent.com/3699494/43107352-71791e10-8e91-11e8-839a-be39b674a82b.png)



Device Info:
Virtual Nexus 6 API 23

**Comment by lobontiumira** [comment]
This is no longer an issue on the latest debug build from main from 10/5 or RC 93.1.1 build.
Tested with Google Pixel (Android 10), and Lenovo tablet M10 (Android 10), and Xiaomi mi4i (Android 5.0.2).
