### ISSUE TITLE
Wayland page not displayed correctly

### ISSUE THREAD

**Issue by carun** [mozilla-mobile/focus-android#2937]
# Steps to reproduce

Visit https://wayland.freedesktop.org/faq.html

## Expected behavior

Page displays properly

## Actual behavior

Page displays as a two character column and runs long

## Device information

Android device: Samsung S7 Oreo
Focus version: 6.0 (Build #21861909)

I'm guessing they are parsing user agent because I don't see this issue with chrome.

**Comment by ekager** [comment]
This is only happening on WebView builds as far as I can tell

**Comment by jashgala** [comment]
Few observations:
- When I modified the CSS in Chrome Inspect to use `em` instead of `px`, the page rendered correctly. 
- With Chrome inspect, it can be seen that the width of the `<body>` element in pixels is much less in Focus/Klar compared to it's width in another browser (in my case I used the default android browser).
    - Focus Webview [body element width](https://pasteboard.co/HvwOw4H.png) = 344 pixels + 16 pixel margin
    - Browser Webview [body element width](https://pasteboard.co/HvwPoLZ.png) = 964 pixels + 16 pixel margin

**Comment by lobontiumira** [comment]
This issue no longer reproduces on the 8.16.0 build. Tested with Samsung Galaxy Note 8 (Android 9), and Google Pixel (Android 10).

<img src="https://user-images.githubusercontent.com/40694158/124234934-574b0180-db1d-11eb-9c7c-05a15079e09b.jpg" width="300" height="550" />
