### ISSUE TITLE
Find in page: can only be used _after_ site is fully loaded

### ISSUE THREAD

**Issue by dennisguse** [mozilla-mobile/focus-android#2950]
## Steps to reproduce

_Case 1:_ load a web page
1. Open a web page that does not load immediately.
2. While the web page loads open the menu and go to find in page.

_Case 2:_ load a web page and abort load via menu (after some content has arrived).
1. Open a web page that does not load immediately.
2. While loading: abort load process via menu.
2. Open menu again and go to find in page.

### Expected behavior

_Find in page_ can be used.

### Actual behavior
_Find in page_ functionality is disabled and _only_ enabled after (I assume) full page load.

### Device information

* Android device: 7.1 LineageOS (no Gapps)
* Focus version: 6.0 Build #21842054 (downloaded from Github)

**Comment by jashgala** [comment]
This is behavior is due to [this line of code](https://github.com/mozilla-mobile/focus-android/blob/da23faf8d612a8fa94eaa9369652429a6336e148/app/src/main/java/org/mozilla/focus/menu/browser/MenuItemViewHolder.java#L30).

When I tried to see what happens when I remove it, it causes the find in page view to be opened and as soon as the page load finishes the view disappears. It seems like it is intentionally disabled while the page is loading, to prevent such a thing from happening.

**Comment by kfontecilla** [comment]
@brampitoyo Is this intended behavior? Please confirm.

**Comment by sflorean** [comment]
Reproducible on Focus: 8.3.0 (Build ID: 341281936) with Samsung Galaxy Note10 (Android 10).
