### ISSUE TITLE
Focus:test renderer switch is always off by default upon startup, regardless of the renderer

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2975]
## Steps to reproduce
Build FocusArmNightly, load it on device, and go to focus:test

### Expected behavior
Since Nightly has Geckoview by default, the new renderer switch should be set to true

### Actual behavior
New renderer switch is set to false 
According to @colintheshots , Until a shared preference is set, the value defaults true. The settings page reflects the shared preference, not the default.

### Device information

* Android device: Moto G5
* Focus version: master branch

**Comment by colintheshots** [comment]
The issue here is the switch on the focus:test screen defaults the new rendering engine or GeckoView setting to off. It should default it based upon the build type instead. The issue is the switch starts in the wrong state. It's not that the actual rendering engine used is incorrect. However, going to the screen without changing the switch will turn off GeckoView.

I'll fix this.
