### ISSUE TITLE
Update app shortcut icon – Erase

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#2990]
#### Old

<img width="360" src="https://user-images.githubusercontent.com/51007/43241420-6d191b62-90ef-11e8-809d-590f4018cfe8.png">

#### New

<img width="360" src="https://user-images.githubusercontent.com/51007/43241570-162e37c8-90f0-11e8-91c9-eb1944c6c6aa.jpg">

**Comment by bbinto** [comment]
After t-shirt sizing this, @Sdaswani - please move to 7.0 if it's a small, otherwise P2 backlog, thanks :)

**Comment by Sdaswani** [comment]
seems like a clear S - can we get the asset @brampitoyo ?

**Comment by ekager** [comment]
Was able to do it with a layer drawable, don't need a png :)

**Comment by brampitoyo** [comment]
@ekager Yay for layer drawable. Thanks, Emily!

If in the future we choose to have an app shortcut icon for “Erase & Open” (#2991), it should also have the same icon.

**Comment by Hackertronix** [comment]
@brampitoyo @ekager What is your stance on having **Erase & Open** as an app shortcut? If you think it would help having it, I would like to take up the task to integrate it 😄

**Comment by brampitoyo** [comment]
@Hackertronix I would love to have “Erase & Open” be an app shortcut.

**Comment by Hackertronix** [comment]
Amazing! I am on it

**Comment by Hackertronix** [comment]
@brampitoyo  I have been spending some time on solving this but there seems to be an issue with the project because on even the latest pull the existing **Erase** shortcut doesn't seem to be working. I get a toast saying "Permission Denied", and this is before I made any changes to the codebase. So I am not really able to test my implementation.  

Steps to reproduce:-

1. Clone the repo and perform an install
2. Long press on the launcher icon and tap on **Erase**.
3. You should see a toast saying **Permission Denied**

![screenshot_20180813-133417](https://user-images.githubusercontent.com/5685314/44019964-fda2d04e-9efd-11e8-9ee2-187e39df0d69.png)

Suspecting this to be related to issue #3098 

cc @ekager
