### ISSUE TITLE
Get Settings Icon for Find in Page 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3024]
Hey @brampitoyo ! When you made the spec for #2685, Find in Page wasn't in the menu. I'm assuming we want the search magnifying glass icon? Could you get us an svg with the correct thickness to match the other menu items? 
Thanks!

**Comment by brampitoyo** [comment]
Yes. Sorry about forgetting to post the search icon!

Here it is: [search.svg](http://f.cl.ly/items/1T3X2d271x002m2y181U/Search.svg)

**Comment by brampitoyo** [comment]
@ekager In addition to the search icon, it turned out that there are quite a few icons that needs to be updated!

http://f.cl.ly/items/050E2I2u3w3F24033x0U/focus-android-icons.zip

Some of the icons have been entirely replaced with a new asset (example: share).

However, most of the other icons have been refined, centred and pixel-fitted without changing their basic shapes. Example: delete, home, open in, refresh, tracking protection disabled, warning.

So our updates this time around are really minor.

These new icons have all been coloured `grey-10`: `#f9f9fa` with 100% opacity, up from 80%. Upping the opacity means that we will align with both Focus for iOS and Firefox for Fire TV colour schemes.

Taken altogether, these icons should look more crisp. When seen side by side, they should resolve the visual issue where icons don’t match each other when seen side by side.

**Comment by bbinto** [comment]
Moving this to 7.0, otherwise please let me know if that doesn't make sense, @ekager

**Comment by ekager** [comment]
Closing
