### ISSUE TITLE
Crash reporter should prompt user before sending each crash report

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#3074]
### Acceptance Criteria (how do I know when I’m done?)

----
The Mozilla Data Stewards team analyzed Google's new Play Store requirements and GeckoView's crash report PII and concluded that:

1. Crash reporting can be enabled by default (i.e. out-out) only if we prompt the user for permission before sending each crash report. The prompt may have an "Always allow" option, as long as the app settings have an option to opt out again.
2. Alternatively, crash reporting should be disabled by default (i.e. opt-in), but our new user onboarding can ask users if they would like to opt in.

Prompting before sending each crash report would be user-friendlier. We would not need to clutter our onboarding and users could choose to send crash reports for some sites but not others.

**Comment by cpeterso** [comment]
Thanks! Implementing the same behavior for both new and existing users (approach 2) makes sense. There's no need to bother new users during onboarding if we are already implementing the crash prompt for existing users.

Regarding the settings UI:

Focus+WebView currently has just one setting checkbox: "Send usage data. Mozilla strives to collect only what we need to provide and improve Firefox Focus for everyone." It is enabled by default in Focus (though opt-in for Klar) in both Focus+WebView and Focus+GeckoView because the telemetry does not include PII.

I think Focus+GeckoView will need separate data collection checkboxes for telemetry and crash reporting (like your "Send usage data" and "Send crash reports" example). Focus+WebView's crash reporting is enabled by default because neither the Google Play Store nor Sentry crash reports contain any PII. GeckoView's crash reports, however, contain stack memory that could conceivably contain PII, so Focus+GeckoView can't enable crash reporting by default.

Focus+GeckoView could default "Send usage data" to true and "Send crash reports automatically" to false (until the user selects "Always Send" on the crash prompt). If we wanted to get fancy, "Send crash reports" could offer multiple options (e.g. "Always Ask", "Always Send", "Never Send") instead of a checkbox.

**Comment by brampitoyo** [comment]
> Focus+GeckoView could default "Send usage data" to true and "Send crash reports automatically" to false (until the user selects "Always Send" on the crash prompt).

Agreed.

I’ve made the crash reporter into an in-content page that will show up after the crash.

1. Is this a better approach than showing a dialogue? If I recall correctly, Android 9.0 Pie will no longer show a dialog when the app crashes, so in-content seems like a better idea.
2. Is it better to simplify the Ask/Send/Don’t Send/Always/Never choice into a simple checkbox? It’s easy to understand, and will directly mirror the “Send crash reports” checkbox that we will put under Settings.

Here’s an initial mockup. Thoughts?

<img width="360" src="https://user-images.githubusercontent.com/51007/43876589-e7aa5602-9be9-11e8-98a7-5de72ef7905d.png">

**Comment by cpeterso** [comment]
> 1. Is this a better approach than showing a dialogue? If I recall correctly, Android 9.0 Pie will no longer show a dialog when the app crashes, so in-content seems like a better idea.

I don't have an opinion, but the in-content page looks good! :)

> 2. Is it better to simplify the Ask/Send/Don’t Send/Always/Never choice into a simple checkbox? It’s easy to understand, and will directly mirror the “Send crash reports” checkbox that we will put under Settings.

Would "Send crash reports" checked mean "Always Send" (without asking) and unchecked mean "Always Ask"? Or would "Send crash reports" checked mean "Always Ask" and unchecked mean "Never Send"?

If you would like the "Send crash reports" setting to be a simple checkbox, then I think the wording should be something like "Send crash reports automatically".

> Here’s an initial mockup. Thoughts?

Would checking "Report crashes like this to help Mozilla improve Firefox Focus" mean "Always Send" and auto-restore a crashed session without showing the "Restore Session" page? Or does the checkbox just mean "Report this current crash"?

What would happen if the user pressed the ◀️ back button? Go to the Focus home screen with no open tabs?

**Comment by brampitoyo** [comment]
@cpeterso Let’s go with the in-content page proposal, then.

Clarifying a few details:

> Would checking "Report crashes like this to help Mozilla improve Firefox Focus" mean "Always Send" and auto-restore a crashed session without showing the "Restore Session" page? Or does the checkbox just mean "Report this current crash"?

Checking the box means “Always send report”, not “Report only this crash”.

Originally, I thought that we should try to auto-restore and skip this page.

Meaning:

* If checkbox is ON and you tap “Restore Session”: in future crashes, previous session will be restored and skipping this page, and a report will be sent.
* If checkbox is OFF and you tap “Restore Session”: in future crashes, previous session will be restored and skipping this page, but no report will be sent.

But in a private browser like Firefox Focus, we should give users a choice to either restore or start from scratch (ie. tap the URL bar to enter an address). So this page should not be skipped.

We hope that crashes don’t happen a lot, so that this page (which is a “speed bump” towards the user’s destination) only appears rarely.


> What would happen if the user pressed the ◀️ back button? Go to the Focus home screen with no open tabs?

Pressing the back button can either:

1. Quit the app, erasing previous stored session
2. Or, return to the start screen with the keyboard up and URL bar focused – ready for input

I recommend against quitting the app. The reason being, when the user sees this Restore Session page, the app had just quit (forcefully), so they’re unlikely to want to re-quit the app.

So we should instead go back to the start screen. And if the checkbox was turned ON, then a report would’ve been sent even if the “Restore Session” button isn’t pressed.

**Comment by cpeterso** [comment]
> But in a private browser like Firefox Focus, we should give users a choice to either restore or start from scratch (ie. tap the URL bar to enter an address). So this page should not be skipped.

Sounds good. Summarizing your comment:

* Focus should _always_ show the crash reporter prompt so the user has the option restore their crashed session or tap in the address bar to load a new page. Thus Focus would not have an "Always Send Reports" setting.
* Pressing the back button should instead go back to the start screen. And if the checkbox was turned ON, then a report would’ve been sent even if the “Restore Session” button isn’t pressed.

**Comment by pocmo** [comment]
Some comments:

* If we intent to build this as a component (https://github.com/mozilla-mobile/android-components/issues/506) for all apps then I'd prefer if we start with a generic UI like Fennec's crash report dialog.

* Note that we need to spawn a completely new process (and "launch a new app") when crashing. We can't really show an in-content crash reporter message. Instead this means we would launch something new that looks like the browser and shows something in content. That's complex and with complexity comes the possibility of *this* code crashing.

* Because of the privacy nature of Focus we do not save anything to disk. This means we can't restore anything because the app process just crashed and with that the data is gone.

> Focus+GeckoView could default "Send usage data" to true and "Send crash reports automatically" to false (until the user selects "Always Send" on the crash prompt).

Wait. This means we will never get any crashes in Sentry without the user enabling this. Or do we want to always prompt - even for non-native code crashes?

**Comment by pocmo** [comment]
That's btw. the crash screen of Fennec:

![crash](https://user-images.githubusercontent.com/89638/44392438-78e4ab80-a532-11e8-821c-7042d43a526f.png)

**Comment by cpeterso** [comment]
> Because of the privacy nature of Focus we do not save anything to disk. This means we can't restore anything because the app process just crashed and with that the data is gone.

Does the crash reporter process have access to the URL from the crash report? If so, the reporter could relaunch the original app (e.g. Focus) with the URL. OTOH, any other Focus tabs or session state would still be lost, so the extra work of restoring the one crashing tab might be not be worth the effort.

>> Focus+GeckoView could default "Send usage data" to true and "Send crash reports automatically" to false (until the user selects "Always Send" on the crash prompt).
>
> Wait. This means we will never get any crashes in Sentry without the user enabling this. Or do we want to always prompt - even for non-native code crashes?

The Mozilla Data Stewards say we don't _have_ to show a prompt for non-native code crashes (that don't include PII), but it would be nice to give the user the choice. Prompting for some crashes but not others could make the user experience more confusing.

**Comment by brampitoyo** [comment]
@pocmo wrote:
> Because of the privacy nature of Focus we do not save anything to disk. This means we can't restore anything because the app process just crashed and with that the data is gone.

If we have no way of restoring previously opened tabs, this issue changes significantly. This means that there’s no user benefit of seeing the Crash Reporter UI every time Focus crashes, because they don’t get anything out of it. No possibility of restoring their previous sessions.

> […] we need to spawn a completely new process (and "launch a new app") when crashing. We can't really show an in-content crash reporter message. Instead this means we would launch something new that looks like the browser and shows something in content.

I wonder if we can show a simple dialogue after the crash, that will say (copy not final):

> **Sorry. Firefox Focus had a problem and crashed.**
>
> As a private browser, we never save and cannot restore your last browsing session.
>
> [x] Report crashes like this to help Mozilla improve Firefox Focus
>
> [Restart]

The “Close” button is unnecessary, because the user – who just had their task interrupted – just want to get back to their task as quickly as possible.

And once you’ve set a reporting preference, we can just restart as soon as the app has crashed, without showing any dialogue. There will be very minimal interruption that way.

Thoughts?

**Comment by cpeterso** [comment]
> This means that there’s no user benefit of seeing the Crash Reporter UI every time Focus crashes, because they don’t get anything out of it.

Users might not want to submit crash reports for sensitive sites, like their bank.

**Comment by bbinto** [comment]
@pocmo - is the prompt UI going to be part of the Android components?

**Comment by pocmo** [comment]
> @pocmo - is the prompt UI going to be part of the Android components?

Yeah, the plan is to have a generic prompt UI in the component and offer the app ways to customize this later on.

**Comment by vesta0** [comment]
@brampitoyo will you be working on the crash reporter UI?

**Comment by brampitoyo** [comment]
@pocmo @cpeterso Do we need to have our own in-content page that appears after the Focus is restarted, or can we show a native system dialogue immediately after the crash (without opening the app)?

You’ve already seen this in-content page:

<img width="360" src="https://user-images.githubusercontent.com/51007/43876589-e7aa5602-9be9-11e8-98a7-5de72ef7905d.png">

And here’s a mockup of the system dialogue, which I’ve talked about [before](https://github.com/mozilla-mobile/focus-android/issues/3074#issuecomment-414869086):

<img width="320" src="https://user-images.githubusercontent.com/51007/45468185-76632380-b777-11e8-99da-94106c6a04ae.png"><img width="320" src="https://user-images.githubusercontent.com/51007/45468363-613ac480-b778-11e8-9efe-8f87bce70641.png">

Any thoughts to our preferred approach?

**Comment by cpeterso** [comment]
> Do we need to have our own in-content page that appears after the Focus is restarted, or can we show a native system dialogue immediately after the crash (without opening the app)?

I don't have a strong opinion, but I prefer immediately showing a system dialog over showing an in-content page after app restart.

Also, Focus+GeckoView use multiple e10s processes so a GeckoView tab can crash without crashing the Focus app itself. So we could use an in-content page for crashed tabs. Of course, the Focus app itself can crash, so a system dialog would still be necessary. It would be nice to be able to restart crashed tabs without restarting the entire app, but that might be beyond the scope of the this crash reporter V1.

**Comment by cpeterso** [comment]
> Question: is there a possibility of restoring the content of individual tabs, or do we prefer not to store that?

I'm not sure. @pocmo will have to let you know. He is working both on the crash reporter Android Component and the Focus app.

**Comment by vesta0** [comment]
Need crash reporting support (GeckoView 63) and Android Components (#506 shipping on 15th)

**Comment by brampitoyo** [comment]
Updated mockup of the in-content page for when a tab has crashed looks like this:

<img width="360" src="https://user-images.githubusercontent.com/51007/46824913-42702380-cd60-11e8-95fa-96c37a3a73b1.png">

The system dialogue for when the whole app has crashed remained the same:

<img width="360" src="https://user-images.githubusercontent.com/51007/45468363-613ac480-b778-11e8-9efe-8f87bce70641.png">

**Comment by pocmo** [comment]
**Status Update**

I'm planning to release an MVP version of the component next Monday with 0.27.0 (has not landed yet; needs to get through review).

This version will be able to:
* Capture JVM crashes (Java/Kotlin) and native code crashes (from GeckoView)
* Send crash reports to multiple services. The component comes with support for Sentry and Socorro.
* If desired prompt when a crash occurred.
* If desired toss a non-fatal crash to the app so that the app can show an in-app UI and ask the user whether they want to submit a crash report.

My hope is that we can land this component and test drive it in Nightly. In parallel I am going to integrate the component into our reference browser for extended testing.

Potential tasks for the Focus team:
* Integration of the crash reporter component (see component README after release)
* Building an in-app crash prompt UI for non-fatal crashes (see mocks; work could start independently  from the component now)

The MVP component may not fully satisfy the design requirements yet (e.g. prompt customization). I would like to use the 0.28.0 sprint to add potentially missing pieces and iron out issues that we may find.

**Comment by brampitoyo** [comment]
@boek I’ve posted the spec above: https://github.com/mozilla-mobile/focus-android/issues/3074#issuecomment-429065368

**Comment by pocmo** [comment]
Removing a-c label: Component landed in 0.27.0. Today's release (0.29.0) will include some improvements and more customization options. This should cover the spec. Please file new A-C issues if anything else is needed.

**Comment by vesta0** [comment]
Thank you @pocmo

**Comment by sv-ohorvath** [comment]
Verified on Nightly.
