### ISSUE TITLE
Add Telemetry for Homescreen Tips

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3080]
**Events**

| Event                                    | category | method     | object | value  |
|------------------------------------------|----------|------------|--------|--------|
| Open in new tab tip displayed | action   | show | tip | open_in_new_tab_tip    |        |
| Add to homescreen tip displayed  | action   | show | tip | add_to_homescreen_tip    |        |
| Disable tracking protection tip displayed  | action   | show | tip | disable_tracking_protection_tip    |        |
| Set default browser tip displayed  | action   | show | tip | default_browser_tip    |        |
| Autocomplete URL tip displayed | action   | show | tip | add_autocomplete_url_tip    |        |
| Open in new tab tip tapped | action   | click | tip | open_in_new_tab_tip    |        |
| Add to homescreen tip tapped  | action   | click | tip | add_to_homescreen_tip    |        |
| Disable tracking protection tip tapped  | action   | click | tip | disable_tracking_protection_tip    |        |
| Set default browser tip tapped  | action   | click | tip | default_browser_tip    |        |
| Autocomplete URL tip tapped | action   | click | tip | add_autocomplete_url_tip    |        |
| Autocomplete URL tip tapped | action   | click | tip | add_autocomplete_url_tip    |        |
| Homescreen tips enabled/disabled | action   | click | tip | add_autocomplete_url_tip    |        |

**Event Ping**

| Setting                  | Key                             | Value
|--------------------------|---------------------------------|----------------------
|  Show tips on Firefox Focus home screen        | pref_key_homescreen_tips          | **true**/false

@bbinto, @Sdaswani: this is the current Telemetry I have. Is there anything further you'd like data on? 

For more information, follow #3039.

**Comment by Sdaswani** [comment]
@mmccorks can you validate this table please? https://github.com/mozilla-mobile/focus-android/issues/3080#issue-348357129

**Comment by mmccorks** [comment]
This looks good to me - is this list all of the types of tips that we'll be including?

**Comment by Sdaswani** [comment]
Currently @mmcorks but we should have the finalized list tomorrow.

**Comment by sblatz** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

* Are users using opting out of home screen tips?
* Are users engaging with the deep-linking on home screen tips?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* The answers to these questions provides benefits to our users as well as improving our product decisions moving forward. For example, if we were to find that most users are disabling the tips (i.e. finding them annoying), then perhaps it's a feature we consider removing or making more subtle. Knowing if people are tapping on the deep-linking home screen tips allows us to compare data with actual feature engagement to see if the tips are leading to higher feature usage. This would likely mean we need to make features more apparent to users, or include more tips for other features!

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

* User surveys to ask if they're aware of features is an alternative to answering these questions. Unfortunately, this would be incredibly cumbersome and largely anecdotal unless done on a very large scale. Because of this, Telemetry is a much better solution.

4) Can current instrumentation answer these questions?

* Current instrumentation can only answer whether or not people are using specific features, but not whether or not they're _aware_ of them existing. This telemetry will help us determine if users are simply not interested in the features offered, of if they don't know they exist.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

All data is Category 2. See [the top of this ticket](https://github.com/mozilla-mobile/focus-android/issues/3080#issue-348357129) for events.

6) How long will this data be collected?  Choose one of the following:

* @mmccorks will permanently monitor this data.

7) What populations will you measure?

* All release, beta, and nightly users with telemetry enabled.

8) Please provide a general description of how you will analyze this data.

* Re-dash queries + dashboards

9) Where do you intend to share the results of your analysis?

* Only on re-dash and with mobile teams.

**Comment by sblatz** [comment]
Ready for @liuche's data review :)

**Comment by liuche** [comment]
Data review+ from me
I wonder, does mobile telemetry have a Histograms data type? A lot of these seem like they would be better to send as a histogram, rather than a ping each time - it seems a little inefficient to send a ping each time vs aggregate them, but if it works for @mmccorks that's fine.

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?
Yes, probes documented in this bug, and will be added to the Focus Android telemetry docs

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, controlled by data toggle in Focus Android

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**
Yes, @mmccorks will monitor

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **
Type 2, interaction and boolean preferences

5) Is the data collection request for default-on or default-off?
default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no, just interactions with tips and boolean preference

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**
Yes, interaction data

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
No, establishing a baseline for these features, and deciding whether to keep them in/add more based on user interaction.

**Comment by sblatz** [comment]
@mmccorks Do you think a histogram would be better? I'm happy to change it if that would be more useful :)

**Comment by mmccorks** [comment]
I don't know which would be better, seems like a question for Frank (who I can't @, is does he not have access to this repo?)

**Comment by sblatz** [comment]
@Sdaswani are we able to get Frank access? In the meantime I'll send him a PM to get his feedback!

**Comment by sblatz** [comment]
@fbertsch the ``` pref_key_homescreen_tips ``` is in the core ping to see if users have enabled or disabled home screen tips. If lots of people are disabling them, perhaps that points to users being unhappy with the feature, and thus we may want to remove it or make it more subtle moving forward.

**Comment by fbertsch** [comment]
@sblatz that pref should be added to the `focus-event` ping, which has a `settings` block.

**Comment by sblatz** [comment]
Oh, sorry about that. I'll update this :) Thanks for the heads up!

**Comment by sblatz** [comment]
Closed by #3097.

**Comment by liuche** [comment]
@sblatz can you point me to where the change in the `focus-event` ping is documented as well?

**Comment by sblatz** [comment]
@liuche This was resolved and can be found in the [updated wiki documentation](https://github.com/mozilla-mobile/focus-android/wiki/Telemetry#settings)
