### ISSUE TITLE
Typo in spanish Firefox Focus banner

### ISSUE THREAD

**Issue by stripTM** [mozilla-mobile/focus-android#3111]
## Steps to reproduce
In Google Play Store, the banner of Firefox Focus for the spanish version show "El nagevador privado" rather than "El navegador privado".

### Expected behavior
We'd have to change "nagevador" by "navegador"

### Device information
![nagevador](https://user-images.githubusercontent.com/1289297/44006500-d16b7788-9e85-11e8-8601-48383301bbee.jpg)
![firefox_focus](https://user-images.githubusercontent.com/1289297/44006501-d1857098-9e85-11e8-8e94-ad8a6dc1dd39.jpg)
* Android device: ?
* Focus version: ?

**Comment by ekager** [comment]
cc @Delphine do you know where these marketing translations come from?

**Comment by ekager** [comment]
I passed this to @lwa-moz to handle on the marketing side. Thanks!

**Comment by Delphine** [comment]
Hey Emily. We just talked with Loren on irc. I wasn't doing mobile at the time this was created, but if it was done like when I came on board, then it was a manual process done on mike han's side and with a designer.

I'm not 100% this ever came from localizers. If it did, the designer just manually added localizations that were asked of localizers (work done in bugs). That resulted in some errors in the past, since the designer doesn't necessarily speak those languages :) 

FWIW, L10n team has no access to those banners or the localizations on it, so we can't manage anything about it on our side.

**Comment by bbinto** [comment]
@lwa-moz please let us know when that's been fixed :)

**Comment by lwa-moz** [comment]
We should be good. An updated feature graphic has been uploaded. It will be visible when the store presence completes a refresh in "a few hours".

**Comment by stripTM** [comment]
Verified, thanks.
![firefox_focus](https://user-images.githubusercontent.com/1289297/44293002-90007080-a288-11e8-9296-a2329152ed6b.jpg)

**Comment by Delphine** [comment]
Thanks for fixing!
