### ISSUE TITLE
Release notes for 7.0

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3113]
We need to get release notes for the 7.0 beta release

**Comment by bbinto** [comment]
- Add search suggestions to avoid typing in full search keywords. Enable this feature under settings to provide less friction to get to your search results faster.
- Introducing on-screen tips on the start screen to help you explore new features that might be useful for you
- Visual updates to optimize for the new Android OS (Android Pie)

@BrianNJones and @lwa-moz to make this all sound more aligned with our content strategy and marketing approach :)

**Comment by lwa-moz** [comment]
Looks pretty good - I'd submit that we could rework for a more active voice directed at the user:

We've added new features to help you get the most out of Focus:
- Skip typing out full search terms, and get to your results faster with the new 'Search suggestions' feature, now an option in settings.
- Learn how Focus can help you browse faster and more securely with on-screen tips that appear in the start screen.
- Browse beautifully with rich Android Pie visual upgrades.

**Comment by BrianNJones** [comment]
@bbinto, can you pls confirm if we will have a SUMO article re: on-screen tips?

**Comment by bbinto** [comment]
I believe @jonisavage is aware of that and is creating SUMO pages, correct @jonisavage?

**Comment by BrianNJones** [comment]
@bbinto @jonisavage, I should have asked the question better! Will there be a SUMO article about on-screen tips as a feature (as opposed to the articles about individual tips/function) that Joni is already working on. Thanks!

**Comment by BrianNJones** [comment]
@bbinto 

What's new in Firefox Focus for Android (version 7)
Version: 7.0
Release date: August <X>, 2018

Thank you for updating to a new version of Firefox Focus. This version includes the following new features.

**Search suggestions.** As you type, your default search engine analyzes text you enter in the address bar to show you related searches. Enable search suggestions under Settings.

**Homescreen tips.** The Firefox Focus homescreen displays contextual tips about features you may find useful.

**Optimized for Android 9 Pie.** Visual updates for the newest Android version.

**Comment by bbinto** [comment]
Thanks @BrianNJones, looks good.

One minor suggestion, will people know what contextual hints are? Also they are not really contextual because they don't show up based on a specific user task. 

**Homescreen tips.** The Firefox Focus homescreen displays  tips about features you may find useful.

Thoughts?

@boek - German translation below (withou

**Suchvorschläge:** Während der Eingabe analysiert Ihre Standardsuchmaschine den Text, den Sie in die Adressleiste eingeben, um damit verbundene Suchanfragen anzuzeigen. Aktivieren Sie Suchvorschläge unter Einstellungen.

Version 1: with "contextual"
**Homescreen-Tipps:** Der Firefox Focus-Startbildschirm zeigt kontextbezogene Tipps zu Funktionen an, die Sie möglicherweise nützlich finden.

Version 2: without "contextual"
**Homescreen-Tipps:** Der Firefox Focus-Startbildschirm zeigt Tipps zu Funktionen an, die Sie möglicherweise nützlich finden.

**Optimiert für Android 9 Pie:** Visuelle Updates für die neueste Android-Version.

**Comment by BrianNJones** [comment]
@bbinto I'm confident users will understand "contextual," but you make a great point. I was attaching "contextual" to the fact that the tip understands a user's settings, not to a specific task. We can remove the word without losing much impact.

**Comment by bbinto** [comment]
Version 2 please :)
