### ISSUE TITLE
eu: missing placeholder in translation, key: preference_show_search_suggestions_summary

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#3176]
> Error: * [values-eu/strings.xml] missing placeholder in translation, key: preference_show_search_suggestions_summary

https://tools.taskcluster.net/groups/czKmX5HWTuGaWSrTSFJwdA/tasks/czKmX5HWTuGaWSrTSFJwdA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by pocmo** [comment]
cc: @Delphine

**Comment by Delphine** [comment]
I rejected the translation, so it should be ok now.
Contacted the localizer so he can update the localization soon. thanks!

**Comment by pocmo** [comment]
Retriggered import task and it succeeded.

**Comment by Delphine** [comment]
@julen : Heads up about this issue. I had to go in and invalidate this string because it's missing the placeholder %1$s 
Unfortunately we can't import strings when there's an error like that.
String: https://pontoon.mozilla.org/eu/focus-for-android/app.po/?status=missing&string=189376
Please udpate when you can! Thanks a lot.
