### ISSUE TITLE
No stop button

### ISSUE THREAD

**Issue by thebnich** [mozilla-mobile/focus-android#323]
Open the menu while a page is loading. The menu shows refresh instead of stop.

**Comment by pocmo** [comment]
Because of strings likely not in v1. @antlam thoughts?

**Comment by antlam** [comment]
@pocmo probably over-simplifying, but can we just change the refresh icon to the 'x'?

**Comment by pocmo** [comment]
We'd still need a string for accessibility.

**Comment by ahunt** [comment]
Things remaining:
- Find an X icon: I'm guessing the material close icon is OK?
https://material.io/icons/#ic_close
- Decide whether we need to update the button in the menu when loading stops/starts? I'm guessing we should, since it's conceivable that the menu will remain open while a page finishes loading.

**Comment by antlam** [comment]
Yes and Yes!

**Comment by pocmo** [comment]
Yep! Currently we are using vector icons from the material set. And yep, the button needs to change. Previously we didn't keep a reference to a currently opened menu. Now we might need to and invalidate the menu once the loading status changes.

**Comment by ahunt** [comment]
![phone](https://cloud.githubusercontent.com/assets/1546915/24625581/5a5cd7fc-1864-11e7-86d3-157ecc216ee6.png)
![tablet](https://cloud.githubusercontent.com/assets/1546915/24625588/5ef75c92-1864-11e7-8149-ebe8a7e10779.png)
