### ISSUE TITLE
Turn off Safe browsing on API 26+ devices

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#3236]
## Steps to reproduce
- Run existing Focus + WebView with API 26+
- Safe browsing is on by default, i.e. we are sending the URL information to Google's safe browsing API

### Expected behavior
- User should opt-in / be aware of the feature

### Actual behavior
- No clear description provided to the user that safe browsing is on by default

### Solution
- Turn off by default for 7.0
- For future release, provide UI + opt-in (under settings)

----

Safe browsing was added in Android O and is enabled by default (javadoc says enabled by default): https://android-developers.googleblog.com/2017/06/whats-new-in-webview-security.html

This is a potential privacy risk for our users as it sends the URLs they visit to remote servers: perhaps we should let them decide if it should be enabled or not? Note that we have a more comprehensive effort to add private browsing for GeckoView: #459.

**Comment by colintheshots** [comment]
It's easy to turn off if this is desirable.

https://developer.android.com/reference/android/webkit/WebSettings#setSafeBrowsingEnabled(boolean)

**Comment by colintheshots** [comment]
Should I remove this for the time being? It's basically a one-liner. Or do we want a setting?

**Comment by mcomella** [comment]
@bbinto ^ ?

**Comment by ekager** [comment]
Status of GV API https://bugzilla.mozilla.org/show_bug.cgi?id=1462000

**Comment by cpeterso** [comment]
This bug should block Focus+GV release.

Safe Browsing might already work in GV (because the Safe Browsing lists is coupled with the Tracking Protection lists) with some issues that won't get fixed in time for GV 62. GV has an [API to disable Safe Browsing](https://hg.mozilla.org/mozilla-central/rev/47e290808d8e): `GeckoRuntimeSettings`'s `setBlockMalware()` and `setBlockPhishing()`. Focus 7.0 should explicitly disable GV Safe Browsing until we can test and fix it.

More discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1483342.

**Comment by bbinto** [comment]
Agreed with @cpeterso

**Comment by colintheshots** [comment]
@bbinto The current version of GV in Focus Nightly doesn't yet have the API to disable Safe Browsing. Should I disable Safe Browsing for WebView and consider this blocked for GV?

**Comment by fmarier** [comment]
> This is a potential privacy risk for our users as it sends the URLs they visit to remote servers

Do you have any evidence of this? As far as I am aware, this is not the case.

The way that the Safe Browsing team at Google has described it to me is that Google Play Services downloads the list locally and webviews do a lookup against that, similar to how Firefox and Chrome do it.

**Comment by fmarier** [comment]
> There is no clear documentation I've found yet stating which one they use on Webviews, but it seems perfectly feasible that they simply download lists to avoid adding significant latency to user browsing sessions.

As far as I'm aware (which is what the Google Safe Browsing team told me a few months ago when they strongly suggested we enable this in our newly-released Focus for Android) Google Play uses the update API so that there's only one copy of the list on the device. They don't use the lookup API because that would be terrible for privacy and also would generate an enormous amount of API calls to their backend.

If it's useful, I can ping them again to double-check that this is still the case. It would be unfortunate if Focus was the only Android browser without any protection against malware & phishing, especially if it's based on a misunderstanding.

**Comment by mcomella** [comment]
> > This is a potential privacy risk for our users as it sends the URLs they visit to remote servers

> Do you have any evidence of this? As far as I am aware, this is not the case.

No, I don't, I made an incorrect assumption so thanks for checking in. :)

**Comment by bbinto** [comment]
Ok, thanks @fmarier for clarifying, we should make sure to point users to a SUMO article explaining the way the API works (locally stored list).

@cpeterso - any updates we have to provide to the GeckoView regarding the list stored locally on the device?

Based on @fmarier latest observations, we probably should allow safe browsing for WV, and as a consequence also for GeckoView

**Comment by fmarier** [comment]
> we should make sure to point users to a SUMO article explaining the way the API works (locally stored list).

Here's what we have for Desktop: https://support.mozilla.org/en-US/kb/how-does-phishing-and-malware-protection-work#w_what-information-is-sent-to-mozilla-or-its-partners-when-phishing-and-malware-protection-are-enabled

**Comment by bbinto** [comment]
^ @jonisavage to keep that on her radar, thanks.

**Comment by colintheshots** [comment]
@cpeterso Can this be uplifted to GV 62 for Focus 7.0? https://hg.mozilla.org/mozilla-central/rev/47e290808d8e

**Comment by ekager** [comment]
We have it @colintheshots . So I should disable for 7.0?

**Comment by cpeterso** [comment]
> Can this be uplifted to GV 62 for Focus 7.0? https://hg.mozilla.org/mozilla-central/rev/47e290808d8e

Emily is correct. The Safe Browsing API was uplifted to GV 62 last week. https://bugzilla.mozilla.org/show_bug.cgi?id=1483342

(btw, Safe Browsing does half-work in GV 62, but there are no Safe Browsing error pages. The user sees a blank page or the page navigation doesn't work.)

**Comment by ekager** [comment]
Can I close this issue now? The state of safe browsing is: WebView Safe Browsing is enabled by default (not disabled) and GV Safe Browsing is Disabled until we can add error pages for a better user experience and then we will reenable (#3309).

**Comment by vesta0** [comment]
We are not turning this off for WV. Another issue will be opened to create Sumo page.
