### ISSUE TITLE
Search terms persist in address bar after visiting a search result with DDG

### ISSUE THREAD

**Issue by initrd** [mozilla-mobile/focus-android#3256]
## Steps to reproduce
1. Set DuckDuckGo as the default search engine
2. Search for "firefox"
3. Open the first result (or any result for that matter)
4. Once the result site loads, click on the address bar

### Expected behavior
The address of the site should be shown

### Actual behavior
Search term "mozilla" shows up. Almost no way to edit the current url.

I could not reproduce this bug using Google, Wikipedia, or Amazon.

### Device information

* Android device: Google Pixel, Android 9.0
* Focus version: 7.0 (Build #322411212 Gecko 62.0.20180823143155)

**Comment by Sdaswani** [comment]
@vesta0 i wonder if we have data on how many users choose DDG as their default?

**Comment by vesta0** [comment]
@Sdaswani @ekager we currently have 65,013,589 users who have set DDG as their default. It's the second most popular search engine. I looked over the options proposed in bugzilla, I'll discuss with Barbara and get back to you.

**Comment by ekager** [comment]
DDG is the second most popular search engine.

Unfortunately using the URL change as the flag can lead to unpredictable results which I believe is worse than just disabling. 

Options:
1. Disable this feature for all builds
2. Disable for GV Builds
3. Disable for users who have DDG set as their engine

All are smalls and not much effort. 

Some additional history: Some users in the past have complained that they can't copy the search URL, so many taking this out could be a good thing?

I think this feature in general is not super useful because selecting the URL bar still allows you to type a new search, just not quickly edit a search I suppose, but with search suggestions now, it is faster to search for what you're looking for. Also, all search engines will have the search bar on their search results site where a user can easily change their search.

CC @vesta0 @bbinto @Sdaswani to decide which direction to go in from here

**Comment by ekager** [comment]
Filed #3401 if we need a short term fix for release

**Comment by lobontiumira** [comment]
I was not able to reproduce this issue with Google Pixel (Android 10) on neither of the builds: 12/29 Focus Nightly, Beta 96.0.0-beta.5, or RC 95.2.0.
