### ISSUE TITLE
Focus GV remembers video position when switching tabs

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3302]
## Steps to reproduce
1. On the GV version, open a youtube video.
2. Open a different video in a new tab.
3. Switch tabs.

### Expected behavior
Video position shouldn't be remembered.

### Actual behavior
Video position is saved.

### Device information

* Android device: Samsung Galaxy S8 (Android 8.0)
* Focus version: 7.0 Beta 2.

**Comment by ekager** [comment]
This seems like a feature?

**Comment by colintheshots** [comment]
I agree. I'm not sure why this is a bug. It seems helpful and desired.

**Comment by ekager** [comment]
Some history: In the past with WV, we *had* to reload the page when switching tabs. With GV, we can try to reattach the session without reloading, meaning the video position can be remembered. I think we should close this because this new behavior seems preferred with less reloading while switching tabs.
CC @Sdaswani @vesta0 @bbinto

**Comment by vesta0** [comment]
@Sdaswani @ekager @bbinto I agree with Emily. Sounds like page reloading when switching tabs was a limitation in WV that we won't have in GW. Users didn't like the reloading so this is definitely desirable behaviour. And it all happens within the same session so remembering video location doesn't contradict our privacy promise.

**Comment by ekager** [comment]
Closing this for the mentions above. Don't think it is a bug
