### ISSUE TITLE
L10N import failing

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3391]
Our latest string imports have been failing due to:

```
Error: * [values-cs/strings.xml] missing placeholder in translation, key: tip_disable_tips
```

and we have a few warnings:

```
Warning: * [values-eo/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
Warning: * [values-pl/strings.xml] number of placeholders not matching, key: firstrun_shortcut_text
Warning: * [values-tr/strings.xml] number of placeholders not matching, key: your_rights_content5
Warning: * [values-ppl/strings.xml] number of placeholders not matching, key: tip_set_default_browser
```

Logs:

https://tools.taskcluster.net/groups/ecqG9k5BQ_26RRj5kDCpRg/tasks/ecqG9k5BQ_26RRj5kDCpRg/runs/0/logs/public%2Flogs%2Flive.log

**Comment by MikkCZ** [comment]
Yes, we dropped that actually for two reasons.
- Including the placeholder the string would become pretty long for a short tip on a home screen. From `Vypnout tipy na domovské stránce` to `Vypnout tipy na domovské stránce aplikace %1$s` is a pretty difference, given the product name which is also not from the shortest.
- The user is already in the app and there are no other tips related to it, so it should be pretty clear even without explicitly mentioning the app name.

**Comment by liuche** [comment]
The missing placeholders are something that we have a script to check for while validating the strings. There are strings where the placeholders are absolutely necessary, or it's useful to check because a placeholder might be forgotten.

So this is a technical limitation, because it's not practical to pick and choose where the placeholders are "optional" for a script - when it fails, we just remove the string. Additionally, I assume that whoever wrote the strings has tried to consider where including the brand is useful (if not necessary) especially for new users, so it's best to include the placeholders.

However, we can ask our copywriter.

@BrianNJones, what do you think about this string? Is it necessary to disambiguate between the app start screen and device start screen? Right now, if we change it here, we should change it everywhere.
"Turn off tips on the %1$s start screen"

**Comment by boek** [comment]
@liuche That is a good point, though I think we're at the point now where it would be difficult to change to change the string in time to release.

@flodolo Is it common in other projects? I don't think we do it anywhere else in Focus (otherwise we would get similar errors)

**Comment by liuche** [comment]
@boek in the meantime, you could do a manual import with the script and just leave out that string.

**Comment by flodolo** [comment]
In Firefox (desktop and Android) it is not common but acceptable (raises a warning), either for space constraints, or because the placeholder can't be declined.

**Comment by BrianNJones** [comment]
@liuche @boek, I think there's a strong case that context ("I understand I'm in an app") makes it obvious that the string is specific to the app. I wouldn't change it.

**Comment by MikkCZ** [comment]
If that help, we can use some longer translation to allow the regular import, and than revert back to the short form without the placeholder and sort it time for the next release.

**Comment by boek** [comment]
@MikkCZ I'd be good with that. We could create a new ticket for 7.1 to discuss changing the base string 👍

**Comment by MikkCZ** [comment]
Cool. I have now approved the long version of the string, that includes the placeholder. Pontoon should push it in the next 20 minutes. I kept the original short version of the string as a suggestion for future. All can be found [here](https://pontoon.mozilla.org/cs/focus-for-android/app.po/?search=tip_disable_tips&string=189765).

What place is the best to create a ticket as a reminder for 7.1?

**Comment by boek** [comment]
I created #3404 to track the work required to change the string. Closing this for now, thanks all!
