### ISSUE TITLE
Revoked certificates aren't treated as an error

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#344]
This seems to be deliberate Android/Chrome decision: certificates aren't checked for revocation.
https://code.google.com/p/android/issues/detail?id=68643
https://bugs.chromium.org/p/chromium/issues/detail?id=362710

STR:
1. Open badssl.com
2. Select "revoked"
Expected: "Secure Connection Failed" error page
Actual: page loads (shows a red "Revoked certificate" text)

Chrome on Android exhibits the same behaviour as Focus, Firefox for Android show the expected "Secure Connection Failed" page.

There doesn't seem to be an obvious way to change WebView's behaviour, and it doesn't look like WebView.getCertificate() provides much useful data, so I'm not sure we can easily change this behaviour. (I expect GeckoView wouldn't exhibit this.)

**Comment by marumari** [comment]
Okay, so I checked with the Chrome folks and here is my understanding of the situation:

a) WebViews (which are Chrome in roughly Android 7.0+) don't currently support revocation
b) They will likely get an OCSP parser at some indeterminate point in the future, in which case revocation should more-or-less transparently get turned on (or at least for OCSP stapling, I would assume)
c) This currently isn't done because CRLsets can be large and use a lot of data, and traditional CRL/OCSP checking is slow/privacy invasive/data intensive

We have three options, as near as I can tell:

a) continue to use a WebView and wait for revocation checking to eventually arrive (via OCSP stapling, CRLlite, or the like)
b) try to override something in X509TrustManager, which will likely be nightmarish code and prone to bugs, or
b) switch to using Fennec, which supports using OneCRL

I'm fine with either option a) or c), although I imagine a) would be the route of least additional work.  Note that for major security issues Android support revocations on an OS level level, so it's not as if Android has no revocation abilities for major problems.

@mozkeeler, @jcjones, @dveditz, feel free to pipe in here if I'm way off the mark.

**Comment by st3fan** [comment]
> Note that for major security issues Android support revocations on an OS level level, so it's not as if Android has no revocation abilities for major problems.

Would a system wide revocation also end up in the WebView?

**Comment by marumari** [comment]
I can double check, but I would assume that if they revoked a root or intermediate that it would be reflected in WebViews.

**Comment by pocmo** [comment]
From buddybuild feedback:

> https://revoked.badssl.com
> This website's certificate is revoked, yet we visit it.

https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback
