### ISSUE TITLE
Figure out Why GV A/B Experiment Isn't Rolling Out As Planned

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3443]
@colintheshots is investigating if Fretboard distributes experiments incorrectly (e.g., we ask it to distribute it to 50% of users, and it only distributes it to 20%).

**Comment by colintheshots** [comment]
Based on the results of my Fretboard distribution test, I believe Fretboard is bucketing correctly. I think the issue is either in how the core ping is getting sent or in the data query somehow. https://github.com/mozilla-mobile/android-components/blob/8ba3e0addaf38e2dea1377232eecd18d16e80171/components/service/fretboard/src/test/java/mozilla/components/service/fretboard/FretboardTest.kt

**Comment by boek** [comment]
Looks like it's working now!
