### ISSUE TITLE
Add telemetry to new default browser prompt

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/focus-android#3477]
Breakout ticket from #2896.

Need to add the following Telemetry:

Event | category | method | object | value
-- | -- | -- | -- | --
Show “open with” default browser prompt | action | show | make_default_browser_open_with |  
Show settings default browser prompt | action | show | make_default_browser_settings |

**Comment by sblatz** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**

* Are users using engaging with a simpler way to enable Focus as a default browser?

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

* The answer to this question will help us determine if even more simplification is needed in the process to make Focus the default browser. This will benefit users as they will have a more streamlined process for making us default if they so choose.

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

* We could run an experiment or survey in order to determine this information, however it would be rather tedious and drawn out for such a small change in Telemetry.

4) **Can current instrumentation answer these questions?**

* Current instrumentation can only answer whether or not people are enabling us as the default browser, not which method they’re using to do so. Because of this, we have no way of knowing which method is simpler or more convenient for users.

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

* All data is Category 2.

**Events**

| Event                                    | category | method     | object | value  |
|------------------------------------------|----------|------------|--------|--------|
| Show “open with” default browser prompt | action   | show | make_default_browser_open_with |     |
Show settings default browser prompt | action   | show | make_default_browser_settings |     |       

6) **How long will this data be collected?**

* @mmccorks will permanently monitor this data.

7) **What populations will you measure?**

* All release, beta, and nightly users with telemetry enabled.

8) **Please provide a general description of how you will analyze this data.**

* Re-dash queries + dashboards

9) **Where do you intend to share the results of your analysis?**

* Only on re-dash and with mobile teams.

**Comment by sblatz** [comment]
Ready for @liuche's review :)

**Comment by liuche** [comment]
Okay, @sblatz make sure to update the wiki with these probes!

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate?

@sblatz will update the Telemetry wiki with the info for these probes

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, data controls in Focus.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?**
Yes permanent, @mmccorks will monitor

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

5) Is the data collection request for default-on or default-off?
Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
No, simply usage of UI

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**
Yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
baseline for this feature

**Comment by sblatz** [comment]
Added to the wiki!
