### ISSUE TITLE
"Make default browser" toggle doesn't switch on - Android 5

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3617]
## Steps to reproduce
1. Clean install of Focus.
2. Go to Setttings>General>Make default browser.
3. Turn the toggle on and select Focus as the default app.

### Expected behavior
The toggle should be switched on, Focus becomes the default browser.

### Actual behavior
The toggle doesn't switch on and the settings page closes and returns to the initial state. However, a link from Gmail will open in Focus by default. So the feature is working but the toggle seems not to.

### Device information
* Android device: Mi 4i (Android 5.0.2)
* Focus version: 8.0 webView & geckoView

See recording here: https://drive.google.com/file/d/16Gl46-fmMde367qdigKYQ84MgH6O3m4P/view?usp=sharing

**Comment by sblatz** [comment]
This is due to our "open with" implementation not being possible to implement without a bunch of hacks (see [this conversation](https://github.com/mozilla-mobile/focus-android/issues/3504#issuecomment-427925599)).

I'd recommend that we revert to the old solution of opening a SUMO page for Android <6.0 since we don't want to use reflection to hack together a solution.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly (2018-12-20).
