### ISSUE TITLE
Appending to search suggestion in the Toolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#3646]
### Why/User Benefit/User Problem
When entering a search term, sometimes a suggestion that pops up adds more value to it but you may also want to continue adding more details. Having an icon that allows you to append a suggestion to the end of your search term _without_ starting the search will allow a user to better scope their searches.

### What / Requirements
An icon at the side of each search suggestion that allows you click it and having your search term + the suggestion appended into the Toolbar.

Below is an example of a search term, and after clicking the arrow on the right of 'cats meowing': 
<img width="607" alt="out" src="https://user-images.githubusercontent.com/1370580/46985683-99a42a00-d0b9-11e8-821a-0d7863c074d4.png">

### Acceptance Criteria (how do I know when I’m done?)
N/A?

**Comment by Sdaswani** [comment]
This is a good suggestion, @brampitoyo to consider, @ekager thinks it wouldn't be a terrible amount of eng work (but she is not committing to that estimate).

**Comment by jonalmeida** [comment]
This might also be a good Hacktoberfest issue if we come up with a good UX for it.

**Comment by brampitoyo** [comment]
This could be a good one. It fits with our mission of getting users to where they want to go faster.

But note that it just brings us up to parity with other browsers, and isn’t unique to us.

Do we know why Fennec doesn’t do this already?

**Comment by bansalayush** [comment]
@brampitoyo @jonalmeida @Sdaswani  Can i work on this ?

**Comment by ekager** [comment]
@bansalayush , this does not have any UX finalized or product decision so it is not ready to be worked on.

**Comment by brampitoyo** [comment]
At the moment, it doesn’t seem clear that tapping on the arrow will append to the keyword (instead of searching the keyword straight away).

I don’t have any research to back it up, but maybe you can help!

@bansalayush If you’d like to assist, I’d love to see how other browsers do “append keyword suggestion” in their UI.

More importantly, I’d like to know whether this “append” UI is commonly used, and whether a lot of people use it (this last question may be hard to answer, though – so don’t worry about it if you can’t find anything).

At first glance, and just after doing a fairly basic search around the web, “append keyword suggestion” suggests a feature that’s not used by most users – only by expert or technical ones. If this is the case, then should either not implement it, or put it as a menu item under the “Search” category within Settings – where those who need it can enable it.

**Comment by Poopooracoocoo** [comment]
Fennec lets you tap and hold.
