### ISSUE TITLE
Feature Request: DNS over HTTPS

### ISSUE THREAD

**Issue by Conan1989** [mozilla-mobile/focus-android#3673]
### Why/User Benefit/User Problem
because reasons https://blog.nightly.mozilla.org/2018/06/01/improving-dns-privacy-in-firefox/

**Comment by Mikaela** [comment]
I am still interested in this, while I am not sure how useful it is with how common OS-wide encrypted DNS has became since Android 9 and the talk of Android 12 DoH support.

**Comment by Mikaka27** [comment]
> I am still interested in this, while I am not sure how useful it is with how common OS-wide encrypted DNS has became since Android 9 and the talk of Android 12 DoH support.

This is still useful, for example in my case I use android global dns from adguard, so that I have fewer ads in applications. But in firefox I need to disable ublock origin for specific site to work.
But even if I do disable ublock origin for this site, the global android dns still prevents the website from working.

So only option for now is to disable global ad blocking dns :(
It would be good to allow setting different dns in firefox only.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802038

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
