### ISSUE TITLE
Brainstorm surfacing content blocking toggle 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3705]
### Why/User Benefit/User Problem
Story: I just downloaded Focus, and the first site I visit is broken. I didn't scroll through all of the onboarding slides so I don't even know what content blocking options there are. I uninstall Focus because I don't understand how/where/why to "fix" sites. 

Sometimes "site breakage" is subtle and even as a technical user I can get frustrated and not understand why or even realize it's because of my settings and not just because I'm using a mobile site etc. For example on sephora.com you can't open any of the menus until you disable content blocking. 

### What / Requirements
Not sure yet, there's lots of options. We can try a tip?

We can move menu items around. One idea I thought of and very quickly mocked up (ugly I know) would be to move the erase action to the toolbar (bonus: addresses user complaints about accidental erase) and move content blocking to the FAB. Opening/Clicking/Long-Pressing the FAB could show an easy disable or quick fix option.

![44639286_2045010749054729_5531835538429968384_n](https://user-images.githubusercontent.com/25442310/47321144-a4564600-d608-11e8-878b-26ce32789c8c.png)

Not sure how these ideas can fit into multitasking redesign (#1250) or new toggle actions (#3511) so I'm pinging @brampitoyo for help and his thoughts :)

### Acceptance Criteria (how do I know when I’m done?)
Users are more aware of Content Blocking and how to disable it from the get go to fix their favorite sites. Retention++.

**Comment by sblatz** [comment]
I agree with this being confusing as a first-time user, and could likely be harmful to our retention rate. Moving the erase button to the URL bar would also further align the iOS and Android product. 

I think it'd be interesting to do a "just in time" pop up. Perhaps we could detect "likely" broken sites, and display a popup accordingly that allows the user to quickly toggle off tracking protection to see if that fixes the site.

**Comment by ekager** [comment]
Unfortunately, I'm not sure if there's really a way to tell if a site is broken since it can be very subtle. Maybe we could tell which type of trackers we are blocking and do some more investigation into which trackers are likely to "break" popular sites. But the number of trackers blocked itself isn't necessarily helpful. If the popup shows up on every site because even 1 tracker blocked could "break" it, is that a good user experience?

@boek and @colintheshots any thoughts on the problem or possible solutions?

**Comment by brampitoyo** [comment]
What if we surface the status of Content Blocking at all times, just like we do on iOS?

<img width="360" src="https://user-images.githubusercontent.com/51007/47467913-00ada580-d855-11e8-80d5-97cc8cbfb1e0.png">

When the shield is clicked, Content Blocking may be managed in its own menu:

<img width="360" src="https://user-images.githubusercontent.com/51007/47467953-39e61580-d855-11e8-9cdd-8eea691c7a77.png">

Is showing the shield enough of an indicator that something special is happening to the page?

If it’s not enough, we can show an animation when Content Blocking is active, as we did on desktop:

![shield-animation](https://user-images.githubusercontent.com/51007/47468047-bd076b80-d855-11e8-81bc-7dbc39cd0aab.gif)

Doing this animation carries a risk. On desktop, the shield will show up only if there are trackers detected. So if a page contains no trackers, you won’t see the animation.

But if we follow my suggestion above, the shield will need to show up on all pages, because we want to make it clear that something is active (and may be causing the page to be broken). And since the shield will show up at all times, animating it every time a page loads seems too much and risks being too annoying.

So my suggestion is to go with showing the shield, but maybe not animate it.

It’s even better if we can indicate a page’s ”brokenness“ using another way that doesn’t involve the shield!

**Comment by ekager** [comment]
Thanks for your ideas Bram!! 

I'm still a bit concerned that the average user does not understand that the lock icon or the shield icon are actionable/clickable items in the URL bar. The FAB and the meatball menu are familiar "action" buttons, but icons in the URL bar, could just be icons. 

Should we look at the data about how many users have clicked the lock icon to learn more about users' interactions with these icons?

**Comment by vesta0** [comment]
@ekager I don't think we track those clicks in Focus but we may be able to see how often/many users click on the shield or lock icon in Fennec as a way to better understand users interactions with such icons. user journey and tackling multiple pain points.

@brampitoyo in Fennec today, the shield icon appears when tracking protection is enabled. Are you thinking something similar but with animation? Maybe the animation could simply indicate the number of trackers blocked (instead of user clicking on the right hand dot menu to find out)?

**Comment by brampitoyo** [comment]
I’ve filed #3841 to track all the design changes related to the shield (this issue) as well as the trash can icon (#3517).
