### ISSUE TITLE
Home Screen Titles Replaced on Updating Focus

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3806]
From GPS: 
"Save (link) to Home (screen)" function: created "shortcut" icons become generic after updating Focus app. Each shortcut still opens to proper URL per "Saved As", but now all get identical screen-names/icons to DIFFERENT URLs."
App v7.0.12 Devices: Android v5.0.1 (S4 fone) & v7.0 (S2 Tablet)

And another: 
"Since last update, all of my home screen shortcuts have the words "Firefox focus" appended to the front of the name I gave the shortcuts. Since home screen area is limited on phones, all of my saved web shortcuts are now named "Firefox focus" making them useless because they are all now identical. Who would think it is a good idea to change they way I meant for it to be? If I wanted a shortcut called "Firefox focus weather" I would have typed that rather than simply typing "weather." In what world is this a good idea? Horrible app design, not considering the user."

I'm not sure what we can do at this point, but a few users are sending reviews that the homescreen icons titles and icons were lost when they upgraded Focus versions. The icons have all changed to the same and all shortcuts have the title "Firefox Focus". This is a confusing bug to me because we hand these icons off to the system and as far as I'm aware, do not have access to them after the fact unless we have changed something recently? Could this be because their engine was changed? I can't think of any other homescreen shortcuts changes we have made.

**Comment by colintheshots** [comment]
I'm fairly sure I know the cause and it should hopefully by a one-time issue. HomeActivity was converted from Java to Kotlin on 8/27/2018 without setting the JvmName to the old class/package name. This would cause all homescreen shortcuts to get replaced on the next app release because of the name change from HomeActivity to HomeActivityKt. This sort of change should not happen often and was an understandable mistake. Please re-open if it happens again with a later release.
