### ISSUE TITLE
Change Google Search Code

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#3917]
### What / Requirements
We need to change our search code for Google. We can do this in a major or minor release.

### Acceptance Criteria (how do I know when I’m done?)
New search code sent during searches

Can be done in a major or minor release.

**Comment by mkaply** [comment]
So we are going to make a simple switch for the search code. We'd also like to rename the engine to make it clear it's using the new code.

Change will be to add -m to the end of the codes:

firefox-b-1-m | firefox-b-m

For desktop, we are naming the engines the same as the code:

google-b-1-d.xml

**Comment by Sdaswani** [comment]
@ekager any chance we can get this in 8.0? 9.0 is fine too.

**Comment by boek** [comment]
@Sdaswani Since search is now in a-c I don't think we'll be able to get this in time for 8.0. But we will be shipping an 8.1 with a new homescreen tip that we can bundle this with

**Comment by pocmo** [comment]
The new code will get released with 0.37.0. Removing the a-c label.

**Comment by sblatz** [comment]
The actual search code was updated (as Sebastian mentioned) [here](https://github.com/mozilla-mobile/android-components/pull/1644).

A [follow-up issue](https://github.com/mozilla-mobile/android-components/issues/1667) has been created which is currently planned for 0.38.0. @vesta0 let's keep in mind that telemetry will not reflect these new search codes until this issue is closed :)

**Comment by Sdaswani** [comment]
> let's keep in mind that telemetry will not reflect these new search codes until this issue is closed 

@mkaply do you care about this?

**Comment by mconnormoz** [comment]
We do care about fixing the telemetry, but it doesn't need to block a release if it's a huge pain.
