### ISSUE TITLE
Keyboard closes while typing something in the address bar while a site is being loaded

### ISSUE THREAD

**Issue by cosmic-echo** [mozilla-mobile/focus-android#3937]
## Steps to reproduce
1. Go to a site (might be better a site that takes a considering amount of time to load)
2. Type something in the address bar, but don't press enter
3. Keyboard closes after the site is loaded

### Expected behavior
Keyboard shouldn't close.

### Actual behavior
After the site is loaded, keyboard closes.

### Work around
Press the stop button to cancel the loading process and then type the desired thing in the address bar.

### Device information
* Android device: Moto G4 Play, Android 7.1.1
* Focus version: 7.0.13

### Additional information
I use Gboard. I tried SwiftKey and the same happens.

**Comment by setuidroot** [comment]
I have this same issue.  It seems like it's been an issue forever, but I don't remember it in the very early Webview versions (Less than version 6, I know for sure that version 6 has this issue.)  It's very annoying.  Often times after my keyboard closes, I lose what I was typing in the address bar.  

I use Hacker's keyboard and have had this issue with Focus/Klar versions 6, 7 and 8 (nightly) on Android 5, 6, 7 and 8 on Samsung Galaxy S5 and a couple of other cheap Chinese phones.

I don't know what causes this and I don't know how to fix it.  I just wanted to back up your issue here because you're not the only one.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly.

**Comment by cosmic-echo** [comment]
Thanks, FF team.
