### ISSUE TITLE
InflateException: Class is not an IWebView

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3944]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4448408/

**Comment by ekager** [comment]
Without having seen this happen it's a bit difficult to guess the STR, but I did some investigation: 

This crash first happened 4 months ago, this seems around the same time we added the ability to switch between GV + WV at runtime (#2792).

We inject the current implementation of either WV or GV to IWebView using WebViewProvider.create in `onCreateView` in MainActivity.
From the stack trace, it seems like this step has not happened when it crashes at: 
```org.mozilla.focus.fragment.BrowserFragment in inflateLayout at line 223```
```org.mozilla.focus.fragment.WebFragment in onCreateView at line 53```

Is it possible this happens in some weird pause/resume/destroy/recreate lifecycle? Or maybe when we switch users to experiments? 

If anyone sees this crash please help us out with some STR :)

**Comment by rpappalax** [comment]
@sblatz not sure how to verify this.  do you have any suggestions where we might begin investigating this?

**Comment by sblatz** [comment]
@rpappalax the only way I've heard discussed among the team is to use router settings to "child block" the device you're testing on so that, even though you're connected to the Internet, the fretboard service will never be reached. You can also try specifically blocking traffic to/from the fretboard domain (as I think this is what initially caused the issue).
