### ISSUE TITLE
Refusing search suggestions, then turning them on crashes Focus on a fresh install

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4010]
## Steps to reproduce
1. Clean install of Focus. 
2. Skip the first run, type something in the url bar.
3. Tap "no" on the search suggestions prompt.
4. Clear the search term, without opening a webpage.
5. Go to settings>search. Turn On the search suggestions.
6. Return to the homepage and type in the url bar.
### Expected behavior
Search suggestions work.
### Actual behavior
Focus crashes.
### Device information
* Android device:
Motorola Nexus 6 (Android 7.1.1), Samsung Galaxy S8 (Android 8.0)
* Focus version: 8.0.2, both geckoView & webView.

**Comment by sblatz** [comment]
This is the crash I'm getting:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/4400286/49828114-0efa4700-fd59-11e8-8fcc-e5bc92a906c4.png">

It can be resolved by removing the cancelJobs call inside of [disableSearchSuggestions()](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt#L75). I'm not sure why we need this cancelJobs call since the user wouldn't have actually sent out a job for a search suggestion (as they're not yet enabled). Perhaps @boek has more insight here.

I believe what's happening is we're trying to use an already cancelled job for a new request, but again, I think the simplest solution is to not cancel it since it seems unnecessary.

**Comment by sv-ohorvath** [comment]
Verified as fixed on both GV (Nightly) & WV (Master).
