### ISSUE TITLE
No default cookies setting selected on webView

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4020]
## Steps to reproduce
1. Fresh install Focus with webView.
2. In Privacy settings, open the Cookies menu.
3. Check the setting selected.
### Expected behavior
Since the value is No, the default selection in the menu should be set to No also.
### Actual behavior
The default value is No, but no selection made in the menu. 
*Can be verified with a cookie detection test page that cookies are enabled.
![screenshot_2018-12-13-13-10-51](https://user-images.githubusercontent.com/4037709/49938032-44ca3780-fee1-11e8-9bb2-74eea911542f.png)

### Device information
* Android device: Huawei P9 Lite (Android 6.0)
* Focus version: 8.0.2 Beta, webView.

**Comment by ekager** [comment]
This issue turned out to be more complicated than I thought because it's possible that users are switching between WV/GV with experimentation. Setting a dynamic default is not possible. 

What I tried was setting the value depending on the Settings bool (which does check for WV/GV), and it would select the correct value for the current engine, but then on switching the engine, it wouldn't update, since that value gets saved.

My recommendation is to remove this from P1s because the summary on the preference does correctly display the current Cookies Setting we are using for the user.
