### ISSUE TITLE
For some locale, translate dialog pops up

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#415]
In cases of 'ar' and 'az' (and perhaps a few other locales) when the fake URL bar is tapped for the first time, a dialog appears.  From the cursory look of it, it seems like it is prompting for the downloading of translation.

This happens on device for me so far, (6.0.1 on z3c) and it uses android webview v57.0.2987.132
Would this affect security of the device?

**Comment by npark-mozilla** [comment]
upon looking at this further, this looks like it only shows up after a new android webview is downloaded.  pressing 'cancel' will make the app to no longer prompt for it

**Comment by ahunt** [comment]
I don't see any APIs to disable the translation system, so that probably isn't a viable route.

Discussing over IRC: it seems likely that most "normal" focus users will already have their locales/dictionaries downloaded when they first start Focus (i.e. our testing is special since we're switching locales all the time). On Android 7 and newer, WebView is provided by chrome, so as long users have used chrome at least once, then I'm guessing this won't happen. On Android 5+6, WebView is separate, so if the user has never used any WebView using app before, they'll probably see this dialog (i.e. this is more likely to happen there).
