### ISSUE TITLE
Allow to disable Safe Browsing

### ISSUE THREAD

**Issue by dimqua** [mozilla-mobile/focus-android#4155]
Could you please add an option to disable the [Safe Browsing](
https://support.mozilla.org/en-US/kb/safe-browsing-firefox-focus) feature?

**Comment by z2z** [comment]
This should have been opt-in or Mozilla hosted - community driven solution.

**Comment by yoasif** [comment]
This seems like a regression, as the feature was enabled in issue  #3643.

I don't see it in Focus Nightly 9.0 (Build #330171230 :lizard: 64.0.20190111134233).

**Comment by colintheshots** [comment]
It seems like there's a merge-related bug for the fix to #3748. The setting was meant to be disabled only for WebView, but the current code to do so is outside of the if {} statement checking if we're not using GeckoView.

This is getting a lot of attention because of a couple Reddit threads that got opened this weekend by the privacy audience. It seems highly likely the Reddit userbase inaccurately believes Safe Browsing sends browsing data to Google when it only downloads lists to compare against. It might be best to just fix the setting so they can lose the pitchforks.

**Comment by colintheshots** [comment]
The regression happened in mid-November. The fix is moving one line into the if (!AppConstants.isGeckoBuild) statement.

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly GV65.
