### ISSUE TITLE
Use proguard to minimize the app size?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#425]
Locally I could remove about 600kB from the app by just enabling proguard (release build). But this caused some issues on buddybuild.

**Comment by ahunt** [comment]
It looks like the issues are caused by ACRA, which has fixed the relevant proguard issues in:
https://github.com/ACRA/acra/issues/301
That's in ACRA 4.7, whereas we're building against 4.6.4 (at least that's what the failing build log suggests):
https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/build/58e7de9634ba9d0001aea22b#logs

AFAICT ACRA is used by the buddybuild sdk, we enable that for beta, and I see klarWebkitBeta failing (which is the first beta config in the list of 'klarWebkitDebug, klarWebkitRelease, klarWebkitBeta, focusGeckoDebug, focusWebkitDebug, focusWebkitRelease, focusWebkitBeta'). Hence this seems to be caused by buddybuild's SDK using an outdated ACRA version.

Possible fixes:
- Optimal: get BuddyBuild to update their SDK to use a newer ACRA 
- Quick/horrible fix: disable BuddyBuild SDK (not really viable)
- Quickish/less-horrible: disable proguard for beta builds (but we'd want to have everyone test proguarded builds...)
- Unknown difficulty: add our own proguard overrides to not fail on ACRA

**Comment by ahunt** [comment]
I've filed a feature request with Buddybuild:
http://discuss.buddybuild.com/t/upgrade-android-sdk-acra-dependency-to-allow-building-with-proguard-enabled/140

I've not had much luck using our own proguard rules, but it's possible I'm not doing the right thing there yet.
