### ISSUE TITLE
[A11y] While loading a page over a different one, the page already opened is announced

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4277]
## Steps to reproduce
1. With TalkBack on, load a webpage. Wait for the page to load and the screen reader to announce it.
2. Tap the search bar and load a different page. Wait for the page to load and the screen reader to announce it.
### Expected behavior
1. The 2nd page loading is announced.
### Actual behavior
The homescreen of the first page is announced while loading the 2nd, as the search edit mode is closing.
### Device information

* Android device: HTC (Android 8)
* Focus version: 8.0.11

**Comment by lobontiumira** [comment]
This issue still reproduces on the RC 96.1.1 build with Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
This issue is still reproducible on all builds, with Lenovo Tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).

**Comment by lobontiumira** [comment]
Reproducible on the latest Focus Nightly 104.0a1 from 7/18 with Oppo Find X3 Lite (Android 11).

**Comment by ionutbedregeanu** [comment]
I will pause this ticket because I don't have a solution at this moment. The behaviour is not consistent. I succeed to reproduce the scenario once, but after that I encountered some problems with the talkback app, it was very hard to hit the "next" button when an url was entered. Also when the page is loaded the focus goes to the web view, which didn't happen at first

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802587

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
