### ISSUE TITLE
Add custom (Robolectric) test runner that finds manifest etc.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#432]
When running tests with Robolectric the following message is printed:

    WARNING: No manifest file found at ./AndroidManifest.xml.
    Falling back to the Android OS resources only.
    To remove this warning, annotate your test class with @Config(manifest=Config.NONE).

The side effect of this is that a lot of values like package name etc. are not set correctly - and resources can't be found.

This might be caused by our complex build type / flavor configuration. We might need to write our own test runner that knows where to find things.

**Comment by ahunt** [comment]
When running in AS, adding the following to the top of my test:
@Config(constants = BuildConfig.class, packageName = "org.mozilla.focus")
plus following the AS specific roblectric guide (below) is enough to get rid of that:
http://robolectric.org/getting-started/#note-for-linux-and-mac-users

**Comment by ahunt** [comment]
Another issue:
- If one test uses the the above config, FocusApplication is created - and it enables StrictMode.
- If another test uses the same config, FocusApplication is created again, and crashes because StrictMode is enabled (we load preferences before enabling StrictMode - except that StrictMode is already enabled because of the previous tests)

Current workaround: cleanup StrictMode in those tests - it would be easier to have a common implementation for this?
```
    @After
    public void cleanup() {
        StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().build());
    }
```

**Comment by pocmo** [comment]
This was fixed in the latest version of Robolectric. It's finally able to understand the project structure and can find resources.
