### ISSUE TITLE
App becomes broken after switching

### ISSUE THREAD

**Issue by bobweasel** [mozilla-mobile/focus-android#4439]
## Steps to reproduce
Open a webpage in Focus, switch to another app, by pressing the home button or using "Recent Apps" or any other means, switch back to Focus

### Expected behavior
Webpage is visible and usable

### Actual behavior
Only the address remains in the address bar. Webpage is blank and unusable.  Refreshing does not reload the webpage and the only valid action is to delete browsing history.

### Device information
Browser / Version: Firefox Mobile 71.0
Operating System: Android
Tested Another Browser: Yes

**Comment by Poopooracoocoo** [comment]
This sounds like #4463 now that I've seen this again. This drives me bonkers. I hate Firefox Focus. I'm tempted to either switch to DuckDuckGo Browser or to an older version of Focus. DDG Browser isn't that good though. At least it respects me by not closing tabs without my permissions and has actually fixed MASSIVE bugs like this.

I'm someone who often searches stuff in Focus and will then open links in another browser. I'll usually stack up on the history of a tab and keep going.

This only happens when I leave it in the background for a while. I constantly try to check up on Focus because not only does the phone have memory leak issues but Focus doesn't move my tabs to storage and this bug just adds insult to injury.

I literally threw my phone (into my pillow ofc). I'm so tired of this. I hate everything.

**Comment by Poopooracoocoo** [comment]
@lobontiumira while I'm glad this was fixed, I do hope you read my rant.
