### ISSUE TITLE
Research fingerprinting protections

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#444]
Fingerprinting is the idea that your browser just happens to give away identifiable information (e.g. user agent, am I receiving DNT header, etc.) and if that information is unique enough, you can be tracked across the internet even when you delete your cookies (more [on Wikipedia](https://en.wikipedia.org/wiki/Device_fingerprint)).

I'm not sure [how practical it is to stop fingerprinting](https://security.stackexchange.com/a/23055), but it could be worth investigating.

fwiw, [eff has a system to detect how trackable your browser is](https://panopticlick.eff.org/) which can give you at least some of the identifiable information associated with fingerprinting:
<img width="186" alt="screen shot 2017-04-12 at 09 30 16" src="https://cloud.githubusercontent.com/assets/759372/24968635/b0eadf4c-1f62-11e7-99cc-b4392484f3cb.png">

**Comment by ahunt** [comment]
I've also filed #446 to look into adding the DNT header (I think iOS already does that), I'm guessing that wouldn't affect fingerprintability since it would either be hardcoded to be on or off for _all_ instances of focus, but it might still affect the panopticlick results.

In terms of user agent: we do include the Android version number, in addition to parts of the default WebView UA (which includes chrome/webkit versions). More discussion about the UA is in #55, we already remove the device/build info which WebView includes by default. Up to date devices should hopefully all have identical chrome/webkit versions (i.e. whatever is the latest chrome/webview release), so the Android version would be the only unique-ish identifier there.

**Comment by pocmo** [comment]
From the feedback we got we decided in triage that there are no particular fingerprinting protections that we are going to implement.
