### ISSUE TITLE
Consider removing "Focus" from user agent

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/focus-android#445]
Or as a fallback, providing a user agent spoofer for the most common user agents.

The default user agent includes "Focus", which was a red flag to me: it signals, "Hey! I'm doing something private and maybe trying not to be tracked!" which is a good reason to track someone.

See also #444 - research fingerprinting protections.

Disclaimer: I don't know *that* much about privacy so this could be incorrect.

**Comment by ahunt** [comment]
Mostly mentioned in [this comment](https://github.com/mozilla-mobile/focus-android/issues/444#issuecomment-293686887), we already remove parts of the default WebView (essentially Chrome) UA in order to decrease fingerprintability, e.g. we remove the device name/build version. That alone is probably enough to identify that someone is using Focus (as opposed to e.g. chrome, or WebView in an arbitrary app), so I'm doubtful about the value of removing Focus.

However I'm also not an expert in this domain, so my reasoning could be incorrect too.

FWIW I believe websites could still detect tracking protection (e.g. by checking whether or not a given external blocked tracker script has been loaded), although I guess they wouldn't specifically know if someone is using Focus, vs Firefox with uBlock/adblock/etc (or even Firefox private browsing with tracking protection), vs Brave, vs other browsers that might do adblocking or tracking protection - unless they then check the UA to identify the specific browser.

**Comment by pocmo** [comment]
User agent was added in #55

**Comment by st3fan** [comment]
Feedback from Marshall:

> This seems like a good idea to me. As the thread notes, there will be certain ways for sites to know the person is using an ad blocker, but having this in the user agent make this really easy. Some sites around the web won't be sophisticated enough to identify ad blockers by other methodologies but will be able to inspect the UA.

**Comment by ekep** [comment]
Just tried viewing kissanime.com with Firefox Focus. No go. Probably an user agent identification. UA spoofing might be the best way to handle that. Otherwise FFF is useless in some situations.

**Comment by mcomella** [comment]
Hi @ekep.

kissanime.com doesn't appear to be a valid website (or [is down at the moment](http://downforeveryoneorjustme.com/kissanime.com)) – did you mean another site? kissanime.io works fine on Focus for me but kissanime.us doesn't appear to be working (with or without trackers disabled).

**Comment by hoosteeno** [comment]
StatCounter global browser tracking does not know about Firefox Focus, and so it (sanely, alas) assumes that Focus traffic is Chrome traffic. That means all Focus browsing is working against us on one of our key measures. You can verify this by visiting http://gs.statcounter.com/detect in Focus. 

In order to get "credit" for Focus browsing, it would probably be better for Focus to identify itself as Firefox. That might have the added benefit of obscuring the nature of the browsing, no?

**Comment by pocmo** [comment]
I've send a report to statcounter a while ago. Seems like they are not really interested in updating it.

We decided against using "Firefox" anywhere in the user agent to avoid websites thinking we are regular Firefox and sending us content that is optimized for Gecko. More here: https://github.com/mozilla-mobile/focus-android/issues/55

**Comment by bbinto** [comment]
Can I close this?

**Comment by hoosteeno** [comment]
> Can I close this?

[My own questions](https://github.com/mozilla-mobile/focus-android/issues/445#issuecomment-333983801) are resolved. Useragent is irrelevant for Statcounter because Focus blocks their code.

**Comment by mcomella** [comment]
> Can I close this?

This bug was originally about removing "Focus" for fingerprinting reasons. #444, researching additional fingerprinting protections, was closed because, "From the feedback we got we decided in triage that there are no particular fingerprinting protections that we are going to implement."

Sounds like we can close this.

**Comment by r-a-y** [comment]
I'm of the opinion that you should allow power users to configure the user agent under some form of Advanced Options panel.
