### ISSUE TITLE
"+ Add another search engine" isn't aligned with the present search engines.

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/focus-android#4509]
## Steps to reproduce
1. Open Firefox Focus and navigate to "Settings"/"Search"/"Search Engine".
2. Inspect the "+Add another search engine" 
### Expected behavior
The "+Add another search engine" is aligned with the already added search engines.
### Actual behavior
The "+Add another search engine" is not aligned with the already present search engines.
### Device information

* Android device: Sony Xperia Z5 (Android 7) Samsung Galaxy S9 (Android 8)
* Focus version: Focus: 8.2.0 Build ID: 340992214 with GV 75.0-20200403170909

Screen:
![Screenshot_20200409-154941](https://user-images.githubusercontent.com/49859863/78897443-d9638c00-7a7a-11ea-87fd-1214b23a9d11.png)

**Comment by goforbg** [comment]
Unable to reproduce, Poco F1 Android 10

**Comment by Saharshv** [comment]
It looks the same for me, but I guess it is supposed to look like that. The text is center aligned.

**Comment by partha2000** [comment]
I also feel that it was supposed to look as it is and is not a bug. This is reproducible on my device.

- Android Device: Xiaomi Redmi Note 7 Pro (Android 9)

**Comment by lobontiumira** [comment]
This issue is no longer reproducible on the latest Focus builds.
Tested today with the latest Focus Nightly 99.0 from 2/23 with Oppo Find X3 Lite (Android 11):

![Screenshot_2022-02-23-12-07-09-14_11753d9bf2a67eec1c984b8ccb4d0671](https://user-images.githubusercontent.com/40694158/155298664-df9d4c92-fdbb-4798-b701-7bd5e6a1a5eb.jpg)
