### ISSUE TITLE
Integrate webcompat component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4525]
https://github.com/mozilla-mobile/android-components/tree/master/components/feature/webcompat

**Comment by Amejia481** [comment]
This will be really helpful as activating it will bring the privacy [SmartBlock](https://blog.mozilla.org/security/2021/03/23/introducing-smartblock/) feature. Just to confirm that there are not restrictions per app names I will tag @wisniewskit  to clarify.

**Comment by wisniewskit** [comment]
I'm not aware of any such restrictions, no. I think it should be sufficient to just enable the android component/feature which bundles the webcompat addon. But it does rely on webextension experiments which are matched with the current version of Gecko/GeckoView, so if Focus is out-of-sync there, we might run into issues.

**Comment by wisniewskit** [comment]
One thing we might want to do is add support for the addon to distinguish between Fenix and Fennec (rather than just Android), so that we can disable shims/interventions on one but not the other (which might come in handy).

That could presumably be done by updating the code here, and I can help with that: https://searchfox.org/mozilla-central/source/browser/extensions/webcompat/lib/shims.js#12

**Comment by Amejia481** [comment]
Thanks for the clarification all the help.

**Comment by jonalmeida** [comment]
Fixed in mozilla-mobile/focus-android@95b49cc
