### ISSUE TITLE
data: url is shown when server not found error page is shown

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#455]
From feedback:

![dataurl](https://cloud.githubusercontent.com/assets/89638/24999002/33cd7472-203c-11e7-9cae-78063777dfef.jpg)

**Comment by pocmo** [comment]
https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/feedback?fid=58ee7131f4ce1b0001791d64&bnum=931

**Comment by ahunt** [comment]
FWIW I only get this in no-network situations, but not when typing an artificial/non-existing site URL.

**Comment by ahunt** [comment]
And actually fixing this might require special casing. This is related to the weird case where we got onPageStarted() without onPageFinished() later, in which case webView thinks its URL==data:text/...., and we get sent onProgressChanged() events (we then read the URL via WebView.getUrl() then and send it to the frontend).

Fortunately webView still appears to remember the original URL, because when you reenable wifi (for a valid domain), it will load the original domain.

One solution is not sending onUrlChanged() for "data:text/html;charset=utf-8;base64,". To make it even more messy, the url passed in via onPageStarted/Finished is actually the expected URL (and only WebView.getUrl() returns the data URL). Usually we want the opposite behaviour since the onPageStarted/Finished URL could be spoofed (#301).

I wonder if we can somehow test all these scenarios - unfortunately it's not clear why webview is doing these weird things either.
