### ISSUE TITLE
2 Anti-Features present: "This app tracks and reports your activity" and "KnownVuln"

### ISSUE THREAD

**Issue by mtris** [mozilla-mobile/focus-android#4609]
Hello: In F-Droid, Firefox Klar now has 2 Anti-Feautures "Red Flagged":
- This app tracks and reports your activity
- KnownVuln

I've used previous versions of the Klar app, before it was flagged and I am unsure if the flags are just for the current app version, or if now all app versions are corrupt.

Thank you for your time and consideration. Sincerely,

**Comment by jonalmeida** [comment]
Hello,

> * This app tracks and reports your activity

Based on the definition in F-Droid:
> This Anti-Feature is applied to apps that track you and/or report your activity to somewhere, either without your permission or by default (i.e. you’d have to actively seek out an option to disable it).

Firefox Klar does not do this. Reporting crashes are opt-in (unless F-Droid has modified the source to make it opt-out, but this is unlikely) as you can see here [in the source](https://github.com/mozilla-mobile/focus-android/blob/8c8fb4ed25249eda1ee226e10d25b669148a8ded/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L70).

In fact, in the latest release we are currently [not even sending anything](https://github.com/mozilla-mobile/focus-android/pull/4601/files#diff-16b7ab9d46296b79c83bb860edef2231L699-L720) **even if you opt-in** (for technical reasons this is broken).

> * KnownVuln

From the link on the F-Droid page that [lists all the known vulnerabilities](https://f-droid.org/wiki/page/Category:Apps_with_KnownVuln_antifeature), Klar is not listed there at this current time.

I recommend contacting F-Droid support about these warnings since we do not maintain that release.

**Comment by mtris** [comment]
Hi Jon and Firefox Klar Team: Thank you very much for the info and follow-up. I'll contact f-droid and see what happens.
I've been a fan of Klar since v1.0. I appreciate the rapid response. Thanks again. Sincerely,

**Comment by mtris** [comment]
Hello - I wanted to follow up and let you know I contacted f-droid regarding as suggestef. Here is the start of the ticket if needed:

https://gitlab.com/fdroid/fdroidclient/-/issues/2062

Thank you again, I appreciate your time. Sincerely,

**Comment by kbrosnan** [comment]
Closing this as it is not directly a Focus issue.
