### ISSUE TITLE
The trashcan icon is moving with the keyboard when having more than 1 tab open

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4617]
## Steps to reproduce
1. Launch Focus and visit google.com;
2. Long tap on Images and choose Open link in new tab;
3. Tap on Google input field;
4. Observe the trashcan icon above the keyboard;
### Expected behavior
The trashcan icon is not displayed above the keyboard.
### Actual behavior
The trashcan icon is displayed above the keyboard.

![rsz_screenshot_20200828-161912](https://user-images.githubusercontent.com/48799384/91565171-75b6fe00-e94a-11ea-95b2-ef998b03e242.png)

### Device information

* Android device: Pixel 2 (Android 9);
* Focus version: Focus 8.7.2 Build ID: 342410345 GV 80.0.20200827204751

**Comment by Ankita13-code** [comment]
Heyy @ebalazs-sv!
This seems as a pretty good first issue. I would like to work on it so can you please assign this issue to me?

**Comment by gouri-panda** [comment]
@pocmo Can I work on this issue?
https://github.com/mozilla-mobile/focus-android/blob/f7de21b82c0be09f4419cc216bc8ad963c7c31bd/app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardViewDelegate.java#L55-L63
It seems if we remove the `viewToHide`'s  setVisibility method. it will work fine. and also we need to add more padding (i.e in `updateBottomPadding`) e.g 25dp to the actual bottom  of the fabicon because some devices have a suggestions bar above the keyboard

**Comment by lobontiumira** [comment]
Verified as fixed on the debug build 8.13.1 (1191.0a1-20210705095222) with Google Pixel (Android 10).
