### ISSUE TITLE
Images missing on winecountry.com

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#474]
From feedback:

> Web fonts enabled but still missing images 

![winecountry](https://cloud.githubusercontent.com/assets/89638/25136140/715f2df0-2454-11e7-8f00-29953b4fcc35.jpg)

**Comment by pocmo** [comment]
The images are hosted on s3.amazonaws.com

**Comment by ahunt** [comment]
This only happens with "Block other content trackers" enabled - this is different from the remotestash.co bug (remotestash loads from e.g. twitter, which is in the "social" category, and we don't explicitly warn that sites might be broken in that case).

(We explicitly warn that "Block other content trackers" breaks some sites.)

**Comment by ahunt** [comment]
I did a quick experiment with injecting our own images in place of blocked images - that really doesn't work well (I used the lock icon since it's one of the few png resources we ship). The main issue is the images will be the wrong size, and will therefore sometimes cover other page content:
![lockimage](https://cloud.githubusercontent.com/assets/1546915/25196094/6d45b7b6-24f4-11e7-800a-9980f3162254.png)

**Comment by pocmo** [comment]
So this seems to be a valid blocking case and we now have the switch to make it easier to disable blocking temporarily -> Closed
