### ISSUE TITLE
Several links from https://rpappalax.github.io/testapp don't work

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#4742]
## Steps to reproduce
1. Go to https://rpappalax.github.io/testapp or https://daleharvey.github.io/testapp/.
2. Scroll down to the hyperlinks section.
3. Tap on "Email link" or "Telephone link".
4. Tap on "Open this PDF file".
5. Tap on External app (play store) using URL (market://...).

### Expected behavior
The user is asked to open the link in another app, or the phone app opens with your number pre-populated.

### Actual behavior
Looks like the page reloads briefly, but nothing else happens.

### Device information
* Android device: Google Pixel (Android 10), Samsung Note 10 (Android 11)
* Focus version: build from master (#1186.0.1- 20210310152336)
* Not reproducible on Foxus 8.14.0 with Google Pixel 2 (Android 9)

https://user-images.githubusercontent.com/40694158/111782023-3558a680-88c1-11eb-9017-4f509e5cf85b.mp4

**Comment by pocmo** [comment]
Related to #4749. This may need `feature-applinks` integration.

**Comment by lobontiumira** [comment]
I was able to reproduce this issue on the 91.1.0 build, with Google Pixel (Android 10).

**Comment by rpappalax** [comment]
@lobontiumira FYI I've moved the test page into the mozilla-mobile github org.
https://mozilla-mobile.github.io/testapp/
https://github.com/mozilla-mobile/testapp

It won't fix this particular issue (as the issue seems to be with the application), but I have made some updates to the test page and put it in the mozilla-mobile org so please use that one from now on.  thanks!

see also: https://github.com/mozilla-mobile/focus-android/issues/5014

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.2.2 build with OnePlus 6T (Android 9), and Lenovo Tab (Android 10).
