### ISSUE TITLE
Pressing back on search from the homescreen exits the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4755]
## Steps to reproduce
1. Open the app, type something in the search bar.
2. Press back to cancel the search/dismiss the search screen.
3. The keyboard is hidden. Press back again.
### Expected behavior
Not sure if one back button press to hide the keyboard is expected, but at the second back press it should show the home screen.
### Actual behavior
After the second back button press, it exits the app.
If you open a webpage and do these steps it behaves correctly, returning to the page.
### Device information
* Android device: Pixel 4 (Android 11)
* Focus version: debug and release 8.13.1 (86.0-20210222142601)

**Comment by edaigle** [comment]
The problem seems to the use of `isOverlay` in `onBackPressed `, in `UrlInputFragment.kt`: 

`    private val isOverlay: Boolean
        get() = tab != null
`

`    fun onBackPressed(): Boolean {
        if (isOverlay) {
            animateAndDismiss()
            return true
        }

        return false
    }
`

Since tab is null when we are on the homescreen, `onBackPressed` returns false, which causes its counterpart in `MainActivity.kt` to exit the app rather than return. 

Being very new to this project I didn't want to be too bold in devising a fix, but if anyone has a suggestion for the preferred strategy here I'd be happy to work on a PR :-)
