### ISSUE TITLE
 Mobile specific Amazon search attribution codes for Focus

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#4885]
See equivalent Fenix GH entry: https://github.com/mozilla-mobile/fenix/issues/19162.
This issue is to track implementation in Focus.

Jira link: https://jira.mozilla.com/browse/FADP-2721

**Comment by rocketsroger** [comment]
This is now in Focus v8.16.0.  Please verify.  Thanks!

**Comment by lobontiumira** [comment]
Tested on the 8.16.0 Focus build with Google Pixel (Android 10), and here are my findings:
* US - moz-us-mbl-20
* UK - moz-uk-mbl-21
* Germany - moz-de-mbl-21
* Japan - moz-jp-mbl-22
* Italy - moz-it-mbl-21
* Canada - moz-ca-mbl-20
* Spain - moz-es-mbl-21
* Netherlands - moz-nl-mbl-21
* Sweden - moz-se-mbl-21
* France - moz-fr-mbl-21


Australia has amazon.com.au as a search engine, but doesn't display the Amazon ID tracker at all.
I.e. I've searched for "puma" with the amazon.com.au search engine, and the search link is https://www.amazon.com.au/s?k=puma
Due to this comment [here](https://github.com/mozilla-mobile/fenix/issues/19162#issuecomment-852770175), I'll close this issue as verified.
