### ISSUE TITLE
Create a Focus megazord for native components

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4922]
We're going to be using Glean and Nimbus in Focus. Today, we can use those components separately, but do we **need** to create one?

**Comment by rfk** [comment]
I expect that it should be safe to use Glean and Nimbus in Focus without creating a special Focus megazord, and instead using the default setup that we ship with Fenix. The only observable downside should be that your app ships some unrelated application-services Rust code that it doesn't need.

I'm motivated to use this as an opportunity to revamp some of how we managing megazords for Android consumers, so please flag me if/when this downside becomes a problem for you and we can figure out a good path forward.

For my context: will Focus use GeckoView at all? (I ask because GeckoView+Glean has its own interesting megazording thing going on as well).

**Comment by jonalmeida** [comment]
> For my context: will Focus use GeckoView at all? (I ask because GeckoView+Glean has its own interesting megazording thing going on as well).

Focus uses GeckoView exclusively. 🙂 

I do recall reading the doc about this new dependency structure, although I didn't see a strict timeline for it, so assumed we should move forward with a megazord-like solution for the time being IF that is a low-effort solution.

**Comment by rfk** [comment]
> assumed we should move forward with a megazord-like solution for the time being IF that is a low-effort solution.

👍🏻 to moving forward in this manner, yes.

**Comment by jonalmeida** [comment]
@jhugman and I spoke about this in relation to https://github.com/mozilla-mobile/focus-android/pull/5890.

With Focus, being smaller/faster is part of the product image, so if we can reduce the size this would be good as we integrate more native components in the future.

The discussion that rfk hinted at above is still ongoing, however James said it is leaning more towards an app-specific megazord, so there is more reason to go in this direction.

**Comment by iorgamgabriel** [comment]
A smaller megazord for Focus would probably be nice to have even after the migration.

**Comment by jonalmeida** [comment]
A megazord is useful to de-duplicate native dependencies in our rust components. It would be useful to compare what is the file-size impact with and without a megazord before we decide to invest time into setting one up.

I'm not sure how to do that exactly, but maybe someone on the app services team could assist us?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802009

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
