### ISSUE TITLE
Update single text tip section to corousel

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#4949]
### Why/User Benefit/User Problem

Right now we are displaying the tips one by one in a random manner or based on previous user actions.
We need to update this section to a carousel of tips

### What / Requirements

Update main screen tips section to a carousel of tips as [in design](https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2131%3A52697)

Order of Tips: https://docs.google.com/spreadsheets/d/1qm1oYtQQcIntd-1-EVH-p5Lbtm_7CHdNNBe1d8E41_8/edit#gid=0

### Acceptance Criteria (how do I know when I’m done?)

As a user I want to be able to see all the tips in a carousel manner

### Implementation questions:

- The list of tips it will be dynamic or static(it will be the same list always)?

- If it will be dynamic, based on what criteria we decide the structure of tips list?

**Comment by ionutbedregeanu** [comment]
@brampitoyo Based on which criteria we should filter the list of tips which should be displayed?
If I already saw a tip it should be removed from carousel? 
Their order should be random?

**Comment by amedyne** [comment]
Per discussion today:
@channingcarter provided a spreadsheet for the order on which tips to display.

**Comment by cadeyrn** [comment]
@ionutbedregeanu While testing I found the following issues: #4069, #5271, #5272.

**Comment by brampitoyo** [comment]
@ionutbedregeanu I will consult with @mheubusch at Content Design about the ordering of Pro Tips. Stay tuned.

In the meantime, let’s display them in the order that Michelle had recommended.

**Comment by amedyne** [comment]
@brampitoyo, @channingcarter provided a spreadsheet for the ordering of the ProTips. This spreadsheet is what Ionut used for this implementation. I shared the file to you.

**Comment by brampitoyo** [comment]
@ionutbedregeanu Yes. @amedyne is correct. The ordering of the Pro Tips should follow the spreadsheet. Never mind my request. Thank you.

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 9/1 with Samsung Galaxy Note 8 (Android 9).
The tips carousel has the following tips, always in the same order:

* "Why yes, we do have a fresh new look!
Read more about this and other updates to Firefox Focus."

* "Create shortcuts to the sites you visit most:
Select Add to Shortcuts from the Firefox Focus menu"

* "Want to keep Enhanced Tracking Protection off for a site you trust?
Add it to the Allowlist in Settings [linked text]"

* "Site missing content or acting strange?
Try turning off Enhanced Tracking Protection"

* "Want to see the full version of a site?
Switch on Desktop Site from the Firefox Focus menu [linked text]"

Tapping on the "Add it to the Allowlist in Settings [linked text]" redirects the user to the https://support.mozilla.org/en-US/kb/add-trusted-websites-your-allow-list-firefox-focus?as=u&utm_source=inproduct&redirectslug=add-trusted-websites-your-allow-list&redirectlocale=en-US SUMO page in a new tab.

Tapping on the "Switch on Desktop Site from the Firefox Focus menu [linked text]" redirects the user to the https://support.mozilla.org/en-US/kb/switch-desktop-view-firefox-focus-android SUMO page in a new tab.

@ionutbedregeanu is this the expected behavior? The first pro tip is always displayed, no matter the actions done: opening/closing a tab, putting the app in the background, force closing the app.

**Comment by ionutbedregeanu** [comment]
Right now we are having a static list of tips which are always displayed, so is the expected behaviour. But yes, i'm pretty sure that those tips will be filtered soon

**Comment by delia-pop** [comment]
Verified as fixed as well on 93.1.0 RC build with Huawei P9 Lite (Android 8).
