### ISSUE TITLE
Add search/ads telemetry

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#4967]
Follow-up from Fenix's https://github.com/mozilla-mobile/fenix/issues/6557 and https://github.com/mozilla-mobile/fenix/issues/6558 .

Needs https://github.com/mozilla-mobile/android-components/issues/7249

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest Nightly build using a Google Pixel 3a (Android 11)

Metrics ping **30f5ad95-2a01-4d83-8efa-d2ce3b662320**

```
"labeled_counter": {
          "browser.search.ad_clicks": {
            "google.in-content.organic.none": 1
          },
          "browser.search.in_content": {
            "baidu.in-content.organic._1000969a": 2,
            "baidu.in-content.sap._1000969a": 1,
            "bing.in-content.organic.none": 2,
            "duckduckgo.in-content.organic.h_": 1,
            "duckduckgo.in-content.sap.fpas": 3,
            "google.in-content.organic.none": 1,
            "google.in-content.sap-follow-on.firefox-b-m": 1,
            "google.in-content.sap.firefox-b-m": 1,
            "yahoo.in-content.organic.none": 5
          },
          "browser.search.with_ads": {
            "google": 1
          }
```

[Logcat](https://github.com/mozilla-mobile/focus-android/files/6938448/focusTLM.txt)

Used more or less the same STR from [#20229](https://github.com/mozilla-mobile/fenix/issues/20229#issuecomment-884943406) and the `"bing.in-content.sap.mozb"` wasn't generated on focus.
Could be because I've manually added Bing as a search engine and performed a couple of searches whereas on Fenix I've added it from the Default search engine list.
