### ISSUE TITLE
"Open in Focus" and "Report site issue" missing from custom tab menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5084]
## Steps to reproduce
1. Set Focus as the default browser
2. Open a custom tab (from Gmail, for example)
3. Open the menu and check the Open in Focus option
### Expected behavior
Not sure if it was intentional to hide the option (not specified in the designs)
### Actual behavior
The "Open in Focus" option is missing, but there is an "Open in..." option as in the browser.
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: latest debug build 8/9 from `main`

**Comment by jonalmeida** [comment]
> I think this is the desired menu option according to the new designs. CC: @brampitoyo

I wonder if that was just an oversight.

**Comment by brampitoyo** [comment]
@mcarare Sorry. @jonalmeida was right. This was an oversight.

Here’s what our Custom Tabs main menu look like:

<img width="360" alt="Android - Browser - Main Application Menu on Custom Tab@2x" src="https://user-images.githubusercontent.com/51007/128814396-6c9d368d-ef7a-4c39-9aa2-c5fe41887e49.png">

Source: https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A282824

Note that the Share icon already appears in the top toolbar, so it doesn’t need to be duplicated inside the menu.

Also note that both of the “Open in…” menu items don’t have icons. This is intentional. We’ll insert them when we have them drawn.
