### ISSUE TITLE
"Clear visited CSS" JavaScript breaks styles

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#529]
I noticed that we remove too many styles on some pages:

![styles_removed](https://cloud.githubusercontent.com/assets/89638/25438633/636cb162-2a9a-11e7-83e5-2f8b3c7b0d17.png)

**Comment by pocmo** [comment]
@ahunt Is this something we can fix or does this mean this workaround isn't suitable?

**Comment by ahunt** [comment]
I think we can probably fix this: the CSS code currently removes any rule sets targeting :visited. The button on the mozilla website uses:
.blueprint .button.button-green, .button.button-green, a.button.button-green:link, a.button.button-green:visited, button.button.button-green { /* stuff here */ }

If we only remove :visited items from the selector (instead of removing the whole rule set), then the button should still look acceptable.

**Comment by ahunt** [comment]
We should maybe also add some JS tests as part of this (maybe the existing UI tests can  be reused for this purpose)?
