### ISSUE TITLE
v93.0.𝒙 doesn't report version correctly

### ISSUE THREAD

**Issue by TPS** [mozilla-mobile/focus-android#5337]
## Steps to reproduce
1. Install any 93.0.* version of Ff Focus/Klar.
2. Check Android app info for it.

### Expected behavior
They should report their version accurately.

### Actual behavior
They _all_ say "version 93.0" though they're _really_ (at this report), 93.0.0 or 93.0.1.

### Device information
* Android device: Any
* Focus version: 93.0.*

**Comment by Tobi823** [comment]
### Steps to reproduce
1. Go to https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.focus.release/latest (I got this address from https://bugzilla.mozilla.org/show_bug.cgi?id=1627518)
2. Download app-klar-arm64-v8a-release-unsigned.apk
3. Analyse the .apk with Android Studio 
4. In AndroidManifest.xml it reads `android:versionName="93.0"` instead of `android:versionName="93.0.1"`

### Expected behavior
The versionName should be the same as in "tag_name" in the public/logs/chain_of_trust.log file (from https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.focus.release/latest)

### Actual behavior
Sometimes, the versionName is not the same

### Result
Users of the app FFUpdater https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/ still receive an "update is available" notification although the latest APK file is downloaded and installed.

But I don't know if you guys fixed it - maybe it's more a problem for the guys running the FirefoxCI-service (https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.focus.release/latest)?

**Comment by amedyne** [comment]
@jonalmeida FYI.

**Comment by jonalmeida** [comment]
This is intentional right now as these are builds do not go through our full release process, so I didn't bump the version numbers there.

**Comment by jonalmeida** [comment]
> Users of the app FFUpdater https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/ still receive an "update is available" notification although the latest APK file is downloaded and installed.

These releases were marked as "pre-release" on GitHub as well to hint that they shouldn't go out to end users. It might be something for the developers of that all to fix, i.e. don't notify users of updates if they are labelled pre-release.

**Comment by TPS** [comment]
Solved since v93.1.1.
