### ISSUE TITLE
Add telemetry for the install source

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/focus-android#5684]
Similar to what we did in Fennec with https://bugzilla.mozilla.org/show_bug.cgi?id=1221646

Using `PackageManager.getInstallerPackageName()` we can determine from which App Store Focus was installed. And likely also filter out installs that did not originate from Google Play.

It will give us values like this:

```
null - developer
com.android.vending - google play
com.amazon.venezia - amazon app
com.sec.android.app.samsungapps - samsung app store
```

@pocmo you did this for Fennec - any concerns?

@athomasmoz  We should probably do the same for Fenix.

**Comment by lobontiumira** [comment]
Verified on the Focus Nightly build 95.0 (353061210 GV 95.0a1-20211101084651) with Google Pixel (Android 10).
I've installed the build with Android Studio.

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/mira-2111020001)

```
"metrics": {
        "string": {
          "browser.locale_override": "none",
          "geckoview.validation.version": "95.0a1",
          "geckoview.validation.build_id": "20211101084651",
          "preferences.user_theme": "Light",
          "browser.install_source": "",
          "browser.default_search_engine": "DuckDuckGo"
        }
```
I can only verify the null-developer option, because Focus Nightly isn't available yet in Play Store, or Samsung App Store.
