### ISSUE TITLE
Add option to provide Shortcuts name

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#5740]
### Why/User Benefit/User Problem

Shortcuts on the home screen cannot be renamed and the name is chosen by default.

### What / Requirements

Add a dialog before saving a shortcut, similar to adding shortcuts to the device launcher screen.

### Acceptance Criteria (how do I know when I’m done?)

Users have the option to name their shortcuts, at least at creation time.

P.S.: This request was also encountered in play store reviews.

**Comment by brampitoyo** [comment]
@mcarare For maximum simplicity and least interruption, I’d prefer for shortcut renaming to happen only after the user long-presses the shortcut tile and select “Rename”.

It’s detailed in this Figma: https://www.figma.com/file/KggJlo8pg2T2Q8nn0Ec5c3/Shortcuts?node-id=1875%3A63694

Otherwise, Fenix already has a rename UI, and we should reuse it on Focus.

**Comment by mcarare** [comment]
@brampitoyo I want to confirm shortcuts behavior when they show up in search fragment:

Currently, on long-press, you still have the option to remove or rename the top sites. 

Should this behavior be kept, or should the shortcuts on the search fragment only be clickable to open the URL?

**Comment by lobontiumira** [comment]
Verified on the 97.0 Focus Nightly (build 353560954 GV 97.0a1-20211220094500) with Google Pixel (Android 10).
When the user deletes all the characters, the "Ok" button becomes inactive.
However, I filed #6110 for the UI.

![rename shortcut ui](https://user-images.githubusercontent.com/40694158/147073766-f655040f-899c-4348-b9d0-977c883f806a.png)
