### ISSUE TITLE
[L10N] Incorrect linked text for the first carousel tip in Japanese

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5816]
## Steps to reproduce
1. Change the device language to Japanese. 
2. Launch Firefox Focus 
3. Observe that the 1st carousel tip.

### Expected behavior
The first character from the second string is also displayed as hyperlink.

### Actual behavior
The first character from the second string is not displayed as linked text.

### Device information
* Android device: Huawei P9 Lite (Android 8).
* Focus version: 95.0.0-beta.3 (Build 353082029 GV 95.0-20211101163752)/ latest debug build from main 11/08.

![Screenshot_20211108-171626](https://user-images.githubusercontent.com/89388888/140769487-46bfd256-7cab-4d73-a50a-26e0d5a814b8.jpg)

**Comment by delia-pop** [comment]
The issue is also present on the Beta 95.0.0-beta.4 (Build 353140212 GV 95.0-20211109194756).

**Comment by Delphine** [comment]
@marsf : Hi! Is this something you can fix in Pontoon? Otherwise let me know so we can find a fix. thanks!

**Comment by marsf** [comment]
@Delphine : At least, It cannot be fixed in Pontoon.

Pontoon:
https://pontoon.mozilla.org/ja/focus-for-android/all-resources/?string=230880

Github source code:
https://github.com/mozilla-mobile/focus-android/blob/e37d4c3ddec02b19b4963139ff54204f833664ff/app/src/main/res/values-ja/strings.xml#L752

However, IMO, adding a following space character after '\n' may resolve this issue. It is just for quick fix.

**Comment by dskmori** [comment]
I'm not good at Kotlin programming, but this process seems to affect this issue.

https://github.com/mozilla-mobile/focus-android/blob/6ee1d1c88cd4382543d744c470a2321cc9628e2d/app/src/main/java/org/mozilla/focus/tips/TipsAdapter.kt#L48

I think "`+ 2`" creates inflexible behaviar.

**Comment by lobontiumira** [comment]
This is fixed in Japanese on the latest Focus Nightly build 353201509 GV 96.0a1-20211115093917. Verified with Sony Xperia Z5 Premium (Android 7.1.1), and Samsung Galaxy Note 8 (Android 9).
![Screenshot_20211116-150749](https://user-images.githubusercontent.com/40694158/141992922-d425f7ac-68a6-401f-8ece-f3ef751f33de.png)

I've encountered another language that has the same issue - Chinese:

![chinese](https://user-images.githubusercontent.com/40694158/141993216-2cf709c7-d1a8-4d8d-86a4-c567ce46052e.png)

@mcarare should I file a new issue for this?

**Comment by mcarare** [comment]
@lobontiumira Yes, please!

**Comment by lobontiumira** [comment]
Filed [5882](https://github.com/mozilla-mobile/focus-android/issues/5882).
Closing this ticket as fixed.

**Comment by marsf** [comment]
@mcarare:
I have to remain a comment as a localizer. It has been resolved, but not fixed in the code itself.

The string should be separated to 2 line parts, or the link tag of second line must be handled on Pontoon.
