### ISSUE TITLE
The page goes blank after the initial load

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#5849]
## Preconditions:
VPN set to the US or BRAZIL

## Steps to reproduce

1. Navigate to : https://www.americanas.com.br/produto/2116805661?utm_medium=afiliados&utm_source=aflb2w&utm_campaign=marca%3Aacom%3Bmidia%3Aafiliados%3Bformato%3A00%3Bsubformato%3A00%3Bidcampanha%3Aacom%3Bfranq%3A22193_1636577023_7517eefa56eb951213701a2693ff5914&utm_content=22193_1636577023_7517eefa56eb951213701a2693ff5914&epar=AF_00_00_AB_ACOM&opn=AFLACOM&franq=22193_1636577023_7517eefa56eb951213701a2693ff5914
2. Observe the result

### Expected behavior
The page loads
### Actual behavior
The page goes blank after the initial load
### Device information

* Android device:  Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)

* Focus version:  Firefox Focus 94.1.2 (353121860 🦎94.0-20211028161635🦎) 

**Notes:**
1. Reproducible regardless of the status of ETP
2. Not reproducible on the latest build of Firefox Nightly
3. Not reproducible using "Private mode" browsing
4. Attaching relevant screen recordings:
![blamnk](https://user-images.githubusercontent.com/75027050/141273139-62c20e3e-67fc-48f3-9f8f-8dbb595dd9ba.gif)

**Comment by softvision-oana-arbuzov** [comment]
This issue is not reproducible on Focus Nightly, the page content loads.
![image](https://user-images.githubusercontent.com/12184325/146329961-5db0eb5c-5e2c-493c-858b-500ad276cbe7.png)

**Tested with:**
Browser / Version: Firefox Release 97.0 (🦎 97.0a1-202111214094205) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density), Samsung Galaxy S8 (Android 9) - 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)
