### ISSUE TITLE
Automation: Uplift translations from main to release branches

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#5896]
We have an automated process for landing translations in `main`. Whenever we branch for an upcoming release the current state of translations will be on that branch and no further updates will reach the release branches. This can be problematic for translations that come in after branching, but also for fixing bugs in translations (see https://github.com/mozilla-mobile/focus-android/issues/5813).

In the Fenix repository we automatically uplift translations from `main` to release branches. This is done by the following GitHub workflow:
https://github.com/mozilla-mobile/fenix/blob/main/.github/workflows/sync-strings.yml

We need a similar process here too. The workflow in Fenix uses two custom actions (`mozilla-mobile/fenix-beta-version`, `mozilla-mobile/sync-strings-action`). We need to check if they work out of the box with Focus too or if we need to adapt them or create Focus specific versions.

**Comment by rvandermeulen** [comment]
@Delphine I don't see any indication that Focus is getting string uplifts during Beta at this point in time, so AFAICT this issue is still relevant (and probably grossly under-prioritized).

**Comment by Mugurell** [comment]
The recent workflow added for this doesn't work ([eg](https://github.com/mozilla-mobile/focus-android/actions/runs/2499415451) seemingly because Focus uses a "`major_version` .`minor_version`" naming scheme for branches while this action hardcodes a "`major_version` .`minor_version` .`patch_version`" naming scheme for branches as Fenix uses.

This would be addressed in https://github.com/mozilla-mobile/fenix-beta-version/pull/5.

**Comment by Mugurell** [comment]
https://github.com/mozilla-mobile/fenix-beta-version/releases/tag/4.0.0 is now available to also add support for the smaller naming scheme used by Focus.
