### ISSUE TITLE
Tapping on "Languages" displays a glitching Language page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6170]
## Steps to reproduce
1. Install the latest Focus Nightly from 1/6.
2. Go to Settings - General, and tap on Languages.
3. Observe the transition from General page to Languages page.

### Expected behavior
The Languages page is displayed without visual glitches.

### Actual behavior
The Languages page is displayed with a visual glitch - please see the video below.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Lenovo tab M10 (Android 10), Xiaomi mi4i (Android 5.0.2)
* Focus version: 1/6 Focus Nightly
* Regression from #5293 

https://user-images.githubusercontent.com/40694158/148355367-e927acd0-0264-48bf-ad48-1776e9044726.mp4

**Comment by iorgamgabriel** [comment]
I can't do nothing about this glitch . It takes a little to show all the languages . I think this is expected .

**Comment by lobontiumira** [comment]
@iorgamgabriel isn't it possible to make the transition as smooth as in Fenix - please see the short video below:


https://user-images.githubusercontent.com/40694158/148507130-f28ad2b6-9139-47e3-908e-e136595e2794.mp4

**Comment by Mugurell** [comment]
Drive-by comment: Fenix has the same general behavior and shows the same issue - for a split second the screen will be empty

<img width="428" alt="image" src="https://user-images.githubusercontent.com/11428869/148508728-25a585e8-fb7f-480a-82f9-4ecd9191c209.png">

though indeed at a quick glance it seems that on Fenix the delay to display languages is smaller.

The difference may be because of the way the locale list is initialized:
- on Fenix Fenix being more direct - [[onCreateView -> createInitialLocaleSettingsState](https://github.com/mozilla-mobile/fenix/blob/46b5dd27065a50643dd96145ae39131014d45a45/app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsFragment.kt#L52)] -> [[onViewCreated -> "adapter".update(...)](https://github.com/mozilla-mobile/fenix/blob/46b5dd27065a50643dd96145ae39131014d45a45/app/src/main/java/org/mozilla/fenix/settings/advanced/LocaleSettingsFragment.kt#L100)]
- on Focus involving more ceremony - [[onCreateView -> Store init -> LanguageScreenAction.InitLanguages](https://github.com/mozilla-mobile/focus-android/blob/046818927a750922ac19b6029ee87597e2b16155/app/src/main/java/org/mozilla/focus/locale/screen/LanguageScreenStore.kt#L20)] -> [[Middleware -> LanguageScreenAction.UpdateLanguages](https://github.com/mozilla-mobile/focus-android/blob/046818927a750922ac19b6029ee87597e2b16155/app/src/main/java/org/mozilla/focus/locale/screen/LanguageMiddleware.kt#L40)] -> [[Reducer -> update state](https://github.com/mozilla-mobile/focus-android/blob/046818927a750922ac19b6029ee87597e2b16155/app/src/main/java/org/mozilla/focus/locale/screen/LanguageScreenStore.kt#L63)] -> [[composable observe and display changes](https://github.com/mozilla-mobile/focus-android/blob/046818927a750922ac19b6029ee87597e2b16155/app/src/main/java/org/mozilla/focus/locale/screen/LanguageFragment.kt#L63L70)]

One potential improvement we could try is to have the store initialized when the fragment is created, so no not wait with the lazy block until `onCreateView`.
Then we could do some profiling to see how big of an impact following that init in middleware flow causes or how big of an impact using a composable here have, something that may prove useful for other flows also and also on Fenix.

CCing @csadilek and @pocmo for visibility.

**Comment by mcarare** [comment]
This happens because of a documented bug in ProvideWindowInsets. 
The problem is that the CompposeVIew is laid out at the first `onMeasure` call, but unfortunately, at that time, we do not have `windowInsets` yet so at the first composition the content padding would be 0. After we receive the actual values the top bar receives the proper content padding, hence the slight glitch. 

We could implement a minor hack, given the fact the status bar height can be measured before the content of the compose view is being set.

**Comment by delia-pop** [comment]
This was also reproduced on Beta 97.0.0-beta.1 with Google Pixel (Android 12). Moreover, please note that the flicker can also be observed when the list in completely loaded, while switching the languages. The menu's heading and the arrow icon are overlapping for a split second the Android status bar.

https://user-images.githubusercontent.com/89388888/149185989-16f189aa-f261-46a2-b31d-27eb47737cb4.mp4

**Comment by Mugurell** [comment]
The "hack" proposed in https://github.com/google/accompanist/issues/155#issuecomment-781931625 seems to be reported as working and safe to use.
We'd need it for future refactorings to compose until that is part of the framework api so I'd say we can go with that instead of having to stik to xml based layouts.

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.2 with Google Pixel (Android 12).

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 98.0 (build 360191102 with GV 98.0a1-20220117035808) with Lenovo Tab M10 (Android 10), and Samsung Galaxy Note 8 (Android 9).

**Comment by delia-pop** [comment]
Reproducible on Beta 97.0.0-beta.4 with Motorola Moto G30 (Android 11) and Lenovo Tab M10 (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on RC 97.2.0 with Lenovo Tab M10 (Android 10).
