### ISSUE TITLE
Toggle for trash icon location

### ISSUE THREAD

**Issue by petermcneil** [mozilla-mobile/focus-android#6178]
### Why/User Benefit/User Problem

In the version 96 release, the trash icon was moved to the navigation bar. It is now out of reach of the natural holding position for right-handed people, requiring repositioning of the hand to clean out the tab.

The way I personally use focus depends on it being in the bottom right location. I use it as a browser for quick, ad-hoc queries, where I can stop them clogging up my history and keep tracking down to a minimum.

I open the app from the launcher and immediately clear the open tab with trash icon. This then opens up the keyboard and I start typing in my query.

[I realise this is the definition of this xkcd 😅](https://xkcd.com/1172/)

### What / Requirements

I propose that both locations for the trash icon exist. By default the one in the task bar is there, and the user can toggle on the old location in preferences.

### Acceptance Criteria (how do I know when I’m done?)
A user can toggle the trash can location

**Comment by wmburke** [comment]
I agree with this request. I too use this right handed and with the trash icon in the upper left, I now have to use both hands in order to operate the browser.

I would also propose that an alternate solution would be to put the trash icon on the right side of the screen and put the toolbar at the bottom of the screen like it is in the Android version of Firefox.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802002

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
