### ISSUE TITLE
Check telemetry max lengths

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#629]
See e.g. "custom_tab_close_but" in telemetry.

We use the value field when sending telemetry for the custom tab intent, which contains a list of features requested by that intent (e.g. has a close button, has a toolbar colour, wants a bottom toolbar, etc). It looks like the limit for value is 80 characters, so we probably need to split this up and/or use shorter strings.

**Comment by pocmo** [comment]
I implemented max size for the fields here:
https://github.com/mozilla-mobile/telemetry-android/blob/master/telemetry/src/main/java/org/mozilla/telemetry/event/TelemetryEvent.java#L97

The numbers are from the event telemetry docs:
http://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/collection/events.html

>     category: Max. byte length is 30.
>     method: Max. byte length is 20.
>     object: Max. byte length is 20.
>     value: Max. byte length is 80.
>     extra: Max. number of keys is 10. - Each extra key name: Max. string length is 15. - Each extra value: Max. byte length is 80.

My implementation in the telemetry library is a bit bonkers, assuming that 1 character = 1 byte. But as we are mostly using characters from the US / ASCII it is okay. When implementing this I was actually wondering whether I should shorten the string or just throw an exception so that the developer notice that something is not right.

**Comment by ahunt** [comment]
If a custom tabs intent has all features enabled, we'll send a value with 195 chars (plus ", " between each item in the list), that also isn't great.

There are 12 Custom Tab "features" that we gather telemetry on, extras supports 10 keys, so that isn't an ideal solution - but we could send two different events - one with supported features, one for unsupported (the numbers will change if/when we add support for all CT features).

I wonder if we should reduce the number of CT features we gather telemetry on (6 are for unsupported features), and/or if we should reduce the amount of text per feature (we're currently using things like "hasBottomToolbar", whereas we could just use "bt" or numeric codes"). Do we really care about e.g. "disablesUrlbarHiding"?
