### ISSUE TITLE
Use #272727 to UI to show blocking is OFF 

### ISSUE THREAD

**Issue by antlam** [mozilla-mobile/focus-android#637]
As per convos in channel. 

Right now, we indicate that Trackers are being blocked through the default state of the switch UI in the menu. To add to this, the toolbar background color also changes between two states, loading, and finished loading. Where "loading" is the dark grey that is reused when the switch in the menu is flipped off. 

But we want to increase the visibility of this status further to drive home the messaging here. @brampitoyo any thoughts?

**Comment by brampitoyo** [comment]
I’m going to tackle this issue first thing next week.

I want to keep @mheubusch’s suggestion in mind: the main UI to indicate this problem is the fact that the webpage *itself*  is broken or looks incomplete.

So the visual we’ll do may involve teaching our users “when you see something broken on the page, the signal icon/visual will also look like something is broken”.

Of course, we don’t want to imply that TP is only good for breaking sites! We want to instead adopt methods that adblockers, data savers and antiviruses uses. Basically, we want to say, “When TP is on, you’ll be protected. So turn it on at all times unless you encounter these side effects”.

**Comment by brampitoyo** [comment]
The way I thought we can do this is either by:

#### Put a crossed-out shield on the side of the menu button or the site status (lock) icon

![crossed-out-shield-on-the-side](https://cloud.githubusercontent.com/assets/51007/26533080/845ba6c0-445e-11e7-85f0-6bf0f880c72b.png)

Or,

#### Fade the crossed-out shield in and out of the menu button or the site status icon

![crossed-out-shield-menu-button-animation](https://cloud.githubusercontent.com/assets/51007/26533202/320e7fc0-4461-11e7-8038-a603733ad5e8.gif)

![crossed-out-shield-site-status-animation](https://cloud.githubusercontent.com/assets/51007/26533223/bdede044-4461-11e7-9cc1-da2164413a55.gif)

(I’ve set the shield icon to not take up too much time, but with a slow enough animation that you’ll notice the difference. The shield only shows up every 5 seconds, for 2 seconds, with fade in and fade out going for 1.5 seconds each way.)

There’s prior work we can refer to. We’re also fading in and out when your webcam/microphone is active on desktop. But there, the speed is much higher and would be far too distracting.

I prefer going with option 3: fade in and out of the menu button. What do you think?

**Comment by brampitoyo** [comment]
@antlam and I chatted extensively about this earlier today, and came up with something helpful:

![blocking off - mdpi](https://cloud.githubusercontent.com/assets/51007/26564932/729a3b20-4532-11e7-8eb7-1f9ee4afedc3.png)

Seen in context (compare and contrast with how it looks when `blocking = on`):

<img width="1201" alt="screen shot 2017-05-30 at 12 14 11 pm" src="https://cloud.githubusercontent.com/assets/51007/26564949/85cd72fc-4532-11e7-9915-545032617174.png">

* The `blocking = off` state should have a separate and darker background colour than the `loading` state.
  * We picked `#272727`. It’s a shade that mobile Photon also uses.
* There should be an icon to the left of the three-dots menu which indicates that `blocking = off`. This icon shouldn’t look similar to the Tracking Protection icon, since Focus uses a different list.
  * The icon isn’t just an indicator. You can tap it. In fact, it enlarges the menu hit area. So when you tap it, the menu will also open.

Icon asset: https://cl.ly/3d1E1W1Q1o2y

A few caveats:

* We’re in the process of getting/designing an appropriate, Photon-style icon. The icon we posted isn’t final, but the final icon will probably not look all that different from the one above.
* The icon part is optional if we can’t get a11y strings. We can at least still deploy the dark grey background colour.

**Comment by pocmo** [comment]
> The blocking = off state should have a separate and darker background colour than the loading state.

Okay, I'll look into getting this in.

> The icon part is optional if we can’t get a11y strings. We can at least still deploy the dark grey background colour.

Yeah, we made the final string export last Friday. Also note that in custom tabs mode there might already be an icon next to the settings menu. On tablets there might be even two: an (optional) custom tab action button and the refresh/stop button. So maybe move this to to a separate issue that we can handle after v1 (designing final icon, mocking custom tab / tablet layouts).

**Comment by pocmo** [comment]
> Yeah, we made the final string export last Friday. Also note that in custom tabs mode there might already be an icon next to the settings menu. On tablets there might be even two: an (optional) custom tab action button and the refresh/stop button. So maybe move this to to a separate issue that we can handle after v1 (designing final icon, mocking custom tab / tablet layouts).

Adding to this: With more time we might even be able to come up with something that somehow integrates the switch / counter idea here too - instead of a plain icon that opens the menu too (this part is a bit weird). There are roughly 2 weeks left for writing code. Assuming that next week we should only focus on stabilizing / fixing bugs - this means we only have this week for changes like this - I'm a bit afraid we are going to rush something that is not quite right.

**Comment by antlam** [comment]
Renaming to reflect current status ^ 👍 

Thank you @brampitoyo and @pocmo !
