### ISSUE TITLE
Proxy support (setting)

### ISSUE THREAD

**Issue by cubanitoalex** [mozilla-mobile/focus-android#64]
Can you enter a manual proxy? Proxy: port???

**Comment by pocmo** [comment]
For your use case do you require an app setting to setup a proxy just for Focus or would it be enough if we use the proxy setup in the WiFi settings (I think we already do)?

**Comment by flakomix** [comment]
I would like in the same application, because with your project I would compile the browser already with the internal proxy, so that the user is easier and I do not have to configure anything or give it my network.

**Comment by flakomix** [comment]
I do not know if you understand me, I would not like to give details to my users about my network..
It is very difficult to include in your project the proxy settings inside the same app

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Proxies support](https://trello.com/c/1XQgjyad/22-proxies-support)

**Comment by lfxc** [comment]
having the ability to use a socks proxy with this browser should really be a requirement.   If we're talking true privacy, the user should have the ability to decide and control what and how their focus browser traffic goes through.  Not at the wifi level, because that makes things very messy, but as a proxy within the focus app itself.  It should allow proxy capability just like any other browser out there at the very least at the code level so others can extend the browser to allow for this option.   Focus for ios does support this capability at the code level.

**Comment by quakenet2** [comment]
+1. I'd like to specify a proxy for this app. I don't use Wifi settings because I use USB-reverse-tether.

**Comment by quakenet2** [comment]
GUI example:
[ Set custom proxy > ]

----

[<-]
Proxy type: [ HTTP ]
IP: [xxxxxxxxx]
Port: [xxxxxxxx]
Ignore for: []

**Comment by bbinto** [comment]
No current plans, sorry, other priorities/features/bugs take precedence at the moment, but we will revisit it though periodically.
