### ISSUE TITLE
Enable HTTPS-only mode in Beta and Production release

### ISSUE THREAD

**Issue by amedyne** [mozilla-mobile/focus-android#6404]
Enable HTTPS-only mode in Beta and Production releases.

**Comment by lobontiumira** [comment]
Verified the HTTPS-Only mode option is displayed in the **RC 97.1.1 build**.
@ionutbedregeanu, @jonalmeida we cannot test thoroughly, because about:config is not available in RC builds (please see #6210), and therefor cannot set the "dom.security.https_first_pbm" to false, in order for the http pages to open as http pages.
<img src="https://user-images.githubusercontent.com/40694158/154026186-74815c3f-6853-4266-81d7-ad29766781a8.jpg" width="300" height="550" />

On **Beta 98.0.0-beta.2**, the HTTPS-Only mode option is displayed, and it is functioning as expected.
Both builds were tested with Samsung Galaxy Note 8 (Android 9), and Lenovo Tab M10 (Android 10).

I'll remove the QAReady label until further notice.

**Comment by lobontiumira** [comment]
I'll close this ticket because it has reached its purpose.
