### ISSUE TITLE
[Experiment] The treatment branch of the Android A/B v97 experiment allows multiple tabs on the first run

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#6528]
**[Affected Versions]:**
- Firefox Focus 97.2.0 (Build #360591303) GV: 97.0.1-20220216172458
- Firefox Focus 98.0 (Build #360591110) GV: 98.0.20220224185616

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)
- Android 10 (Oneplus 6) 

**[Prerequisites]:**
- Have a Focus for Android build with the following modifications:
     The following lines added to local.properties:
`nimbus.remote-settings.url = https://settings.stage.mozaws.net`
`debuggable = true`
A new “.nimbus” file (in the same location as local.properties) containing the following line:
`https://settings.stage.mozaws.net`
- Have the build installed on an Android device <7 day ago.

**[Steps to reproduce]:**
1. Open the browser from prerequisites to enroll in treatment-a of the [Stage Copy Focus Android A/B v97 Experiment - New Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/stage-copy-focus-android-ab-v97-experiment-new-users) experiment.
2. Navigate to a page.
3. Close and reopen the browser.
4. Press one of the links and tap “Open link in private tab”.

**[Expected result]:**
-  The “Open link in private tab” option is not displayed and it is not possible to have multiple tabs open.

**[Actual result]:**
-  The “Open link in private tab” option is displayed and it opens the link in a new tab.

**[Notes]:**
- The issue is not reproducible if step 2 is removed.
- The issue is also reproducible for the [Production experiment in Preview](https://experimenter.services.mozilla.com/nimbus/focus-android-ab-v97-experiment-new-users-copy), using Firefox Focus 98 built as Release (with the collection URL used being `https://firefox.settings.services.mozilla.com`).
- The issue is also reproducible for the Existing Users experiment.
- Attached is a [recording of the issue](https://drive.google.com/file/d/1o3XRH0PWQRPrXRoZ7i9S2l0LJr-_vfX-/view?usp=sharing).

**Comment by heres-maria** [comment]
After further investigation, it seems the issue is related to whether the user navigates to a webpage between the startup they are enrolled in the study and the startup when the experiment is applied to the build. I have updated the STR and notes accordingly.

**Comment by ionutbedregeanu** [comment]
I noticed that after a fresh install the experiments are downloaded but not applied, even if we put the app in background or simply wait. 
Instead they are applied after an app restart.
From the attached photos of this comment we can also see that we are receiving the experiment as active even if it's not applied yet
#### Experiment active but not applied
<img width="1412" alt="Screenshot 2022-03-02 at 14 00 14" src="https://user-images.githubusercontent.com/11731652/156359194-053b7277-9c97-434e-83c2-06ace79ebad4.png">

#### Experiment active and applied
<img width="1416" alt="Screenshot 2022-03-02 at 14 00 40" src="https://user-images.githubusercontent.com/11731652/156359204-f5564227-9017-4771-a993-dc9184e34c4b.png">

I'm not sure if this is the expected behaviour or not. I already asked the nimbus team and we are waiting a response.

**Comment by jhugman** [comment]
The Focus integration of Nimbus downloads the experiment recipes at startup, and then applies them as updates at next startup.

This is the recommended way of setting up Nimbus: it allows app developers to treat Nimbus as a store of immutable configuration.

The alternative would be to download the experiment recipes and then immediately apply them (as implemented by https://github.com/mozilla-mobile/focus-android/pull/6444). This would be mean that application features which call into Nimbus may get different configuration within the same session of the app. Worse still, this could mean that some parts of the application (a collection of features) would get old configuration, and some new, potentially putting the app in an inconsistent state, which could be a poor user experience or tainted experiment data. Either way, this is a bad thing.

Unfortunately, this makes running experiments on _first run_ difficult, because the fetch finishes sometime after startup (depending on network conditions).

There are mitigations:

 * **new users instead of first run**: we offer a way of targeting based on `days_since_install`, so we can target new users of the app.
 * ** `applyPendingExperiments` at safe checkpoints in the app**: we expose the `applyPendingExperiments` method for the app to be called at a point when the app feels it's safe to change configuration, a.k.a. a checkpoint. For example, this might be as the user closes the first screen of onboarding but before the main app has been created.
 * **invert the defaults to false**: in situations where a new feature is being added, we advise that the default behaviour is to turn the feature off, and let the experiment (and/or rollout) turn the feature on. This prevents a poor user experience of getting a feature then having it turned off. This also makes sense from a data point of view, since it allows a feature to be tested within the same date range.

/cc @jonalmeida @ionutbedregeanu

**Comment by Mugurell** [comment]
@jhugman I'd say the default value should always be the value that the control branch would set and the current app behavior before the experiment. In this case - `true`.
Otherwise we'd get the inverse of this bug: Users in "control" would get on the first tun - when the experiments are downloaded the opposite behavior than they should.

Can it be made that `getActiveExperiments()` would not return experiments that are not yet applied? I think this is the essence of this report.

**Comment by Mugurell** [comment]
Fix should be available in the next Nightly.
After validation this should be uplifted to Beta 99.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible using a Focus Release built from the latest main branch for the Stage environment and the [Stage Copy Focus Android A/B v97 Experiment - New Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/stage-copy-focus-android-ab-v97-experiment-new-users) and the [[cmuresan] Stage copy of Focus Android A/B v97 Experiment - Existing Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cmuresan-stage-copy-of-focus-android-ab-v97-experiment-existing-users) experiments. 

- The "Open link in private tab" option is not displayed for the treatment-a branch even at first startup. Restarting the app after navigating to a page also correctly does not display the option.

Tested using Firefox Focus 99.0 (Build #360681124 GV: 100.0a1-20220308100756) as Release on Android 9 - Samsung Galaxy S8.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible using a [beta version of the experiment](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/beta-copy-focus-android-ab-v97-experiment-new-users) on Firefox 99.0 (Build #360751743 Gv: 99.0-20220313185831) (built from [Focus/Klar 99.0.0-beta.2-beta](https://github.com/mozilla-mobile/focus-android/releases/tag/v99.0.0-beta.2) set to stage) on Android 9 - Samsung Galaxy S8.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible with the [New Users experiment](https://experimenter.services.mozilla.com/nimbus/focus-android-ab-v97-experiment-new-users-copy) on [Focus v98.3.0](https://github.com/mozilla-mobile/focus-android/releases/tag/v98.3.0)[](https://github.com/mozilla-mobile/focus-android/releases/latest) - Android 9 - Samsung Galaxy S8.
