### ISSUE TITLE
CFR's are dismissed when rotating the device to landscape

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6536]
## Steps to reproduce
1. Open a secure page, like wikipedia.org.
2. The CFR for shield icon is displayed.
3. Rotate the device to landscape mode (if you are in portrait mode), or viceversa.

### Expected behavior
Even if the device is rotated, the CFR's are still displayed.

### Actual behavior
Rotating the device dismisses the CFR.
a. However, closing the tab, and opening a new secure page, triggers the CFR for shiled icon again.
b. Regarding the CFR for delete icon, it is not triggerred again.

### Device information
* Android device: all
* Focus version: Focus Nightly from 2/28
* Shot video regarding the CFR for shield icon:

https://user-images.githubusercontent.com/40694158/156129552-ceed0671-927e-4c48-a9d9-f336a26c85bd.mp4

**Comment by Mugurell** [comment]
This is the expected behavior after https://github.com/mozilla-mobile/focus-android/pull/6411 .
This is in accordance with how we treat other popups to prevent anchoring issues - after screen rotation a popup may be placed incorrectly.
If the user didn't expressly dismissed the CFR 
- by tapping on the "x" button or 
- by tapping outside of the popup to dismiss it

the CFR will be shown again the next time when the conditions to show it are met, until expressly dismissed by the user.
