### ISSUE TITLE
The new onboarding has discrepancies on dark mode

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6561]
## Steps to reproduce
1. Set the device on dark mode.
2. Have a fresh profile.
3. Open Focus Nightly, and observe the new onboarding.

### Expected behavior
The new onboarding is fully visible on dark mode, like in [Figma design](https://www.figma.com/file/ahqwL3sByHprH2Rru9R58b/Onboarding-2022?node-id=3716%3A5792).

### Actual behavior
The new onboarding has elements that are barely visible.
Also, the icons from the left side is not aligned with the text - please see the attached screenshot.

### Device information
* Android device: Samsung Galaxy Note 8 (Android 9), Oppo Find X3 Lite (Android 11)
* Focus version: Focus Nightly 99.0a1 (build 360620510 GV 99.0a1-20220302065857)

![new onboarding](https://user-images.githubusercontent.com/40694158/156525931-2fbca371-e3e0-4ea6-9571-46d669b86732.png)

**Comment by lobontiumira** [comment]
Reproducible also on Lenovo Tablet M10 (Android 10):

![new onboarding tablet](https://user-images.githubusercontent.com/40694158/156527737-df61b34a-d656-4e98-a37b-05c8a67b430a.png)

**Comment by indurs** [comment]
@Mugurell , the triaged tickets in 

    https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
    https://github.com/mozilla-mobile/fenix/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
are either  being assigned or most of the issues are from 2020 and early 2021.

Is it fine if I work on this issue. I can reproduce this on Pixel 2, Android 11, Focus: Version 99.0

I'm actually interested on fixing the "Crash when tapping the search widget while in PIP #24040 " . But I think it would be better if I start with a simple issue.

Thank You


![Screenshot_20220304-062849](https://user-images.githubusercontent.com/12825812/156679212-70dd948a-0c2b-4c38-8d63-7606411b8b64.png)

**Comment by Mugurell** [comment]
@indurs 
> Is it fine if I work on this issue. I can reproduce this on Pixel 2, Android 11, Focus: Version 99.0
> 
> I'm actually interested on fixing the "Crash when tapping the search widget while in PIP #24040 " . But I think it would be better if I start with a simple issue.

We'd appreciate your help on this.
The desire outcome is for the onboarding screen to keep the light theme colors even in dark more - always show the light theme version.
Please note that this is a high priority issue. If you need assistance just ask.

**Comment by indurs** [comment]
Thank you @mugurell.

**Comment by indurs** [comment]
@Mugurell 
Just wanted to make sure I'm going in the right direction.

I'm going through the following fragment, theme and composable.
 org.mozilla.focus.fragment.onboarding.OnboardingFragment​

FocusTheme

KeyFeatureCard​

-About the issue

Expected behavior

The new onboarding is fully visible on dark mode.
 The onboarding screen should keep the light theme colors even if the user selects dark mode in the device settings

issues/Reason

1. The new onboarding has elements that are barely visible.
• Onboarding screen uses dark theme and the  
onboardingTitle uses dark color. So the title is not visible.


2. Also, the icons from the left side is not aligned with the text - please see the attached screenshot.
• KeyFeatureCard composable is used for displaying the content below the onboarding title. 
Title and description texts are displayed to the right of the icon. Title text uses a text style that has dark color. So the title is not visible and the description that appears below looks as if it's  not aligned.

Possible solution
Onboarding screen uses composable
Instead of having a single theme - FocusTheme 
for the whole app, we can have multiple themes. 
Compose app can have more than one theme. 
For the onboarding screen we can just have a separate theme for light theme colors.

**Comment by Mugurell** [comment]
@indurs 
> Possible solution Onboarding screen uses composable Instead of having a single theme - FocusTheme for the whole app, we can have multiple themes. Compose app can have more than one theme. For the onboarding screen we can just have a separate theme for light theme colors.

Composable themes allows to easily pick another configuration or certain attributes on the spot, just for the composable they are applied to. Our theme also supports to easily change the color palette - for light or dark modes.
In our case it might work to just use `FocusTheme(darkTheme = false)` [here](https://github.com/mozilla-mobile/focus-android/blob/b2dc452eac23a388ddc650e42168cb8ca276ae4a/app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt#L69).

This theme will not apply though to the images used in `KeyFeatureCard` as they use a hardcoded reference to a color with day/night variations. We might be able to use a `ColorFilter` to force the color used for light mode as tint.

**Comment by indurs** [comment]
@Mugurell  Thank you for the pointer. This seems to be a less complex way.Since I'm traveling, would it be ok if I start coding on Monday.

**Comment by Mugurell** [comment]
> @Mugurell  Thank you for the pointer. This seems to be a less complex way.Since I'm traveling, would it be ok if I start coding on Monday.

Sure! Thank you!

**Comment by indurs** [comment]
@Mugurell, is it fine if I add you as Co-Author for this issue. I've fixed the issue. It's my first time contributing to open source and my first PR. I'll create the PR asap.

**Comment by Mugurell** [comment]
> @Mugurell, is it fine if I add you as Co-Author for this issue. I've fixed the issue. It's my first time contributing to open source and my first PR. I'll create the PR asap.

Awesome that you're close to your first PR! Congrats!
Please ensure you are following the general recommendations from here https://github.com/mozilla-mobile/fenix#i-want-to-open-a-pull-request. Because these are visual changes it would also be great to have the results shown on a short video added to the PR (to also be able to check "Screenshots" in the checklist.
.No need for the co-authoring.

**Comment by indurs** [comment]
@Mugurell , just submitted the PR. Thank You for guiding me! I've included you as a Co-author. 

I saw this message after submitting the PR

1 workflow awaiting approval
First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) 6 expected and 1 successful checks

**Comment by lobontiumira** [comment]
Verified as fixed on the Focus Nightly 99.0a1 (build 360670512 with GV 99.0a1-20220307093830) with Lenovo Tab M10 (Android 10):

![Untitled](https://user-images.githubusercontent.com/40694158/157188059-0d56a5d0-7b50-414d-9c1f-7c618d279044.png)
