### ISSUE TITLE
[Experiment] “Report Site Issue…” is wrongly displayed for the “Your Rights” page with multiple tabs disabled

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#6622]
**[Affected Versions]:**
- Firefox Focus 100.0 (Build #360681813 GV: 100.0a1-20220308100756) built as Release

**[Affected Platforms]:**
- Android 9 (Samsung Galaxy S8)

**[Prerequisites]:**
- Have a Focus for Android build with the following modifications:
     The following lines added to local.properties:
`nimbus.remote-settings.url = https://settings.stage.mozaws.net/`
`debuggable = true`
A new “.nimbus” file (in the same location as local.properties) containing the following line:
`https://settings.stage.mozaws.net`

**[Steps to reproduce]:**
1. Open the browser from prerequisites to enroll in [Stage Copy Focus Android A/B v97 Experiment - New Users](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/stage-copy-focus-android-ab-v97-experiment-new-users) in the treatment branch (the branch you have been enrolled in can be found looking at logcat logs at startup with the `nimbus` filter set).
2. Navigate to a page.
3. Tap “Your Rights” from Settings > Mozilla.
4. Tap “Report Site Issue…” from the overflow menu.
5. Navigate to another page.
6. Tap “Report Site Issue…”.

**[Expected result]:**
- Step 4. The “Report Site Issue…” option is not displayed for the “Your Rights” page, as it is not displayed for it without the experiment.
- Step 6. The “Report Site Issue…” page opens correctly.

**[Actual result]:**
- Step 4. The “Report Site Issue…” option is displayed for the “Your Rights” page.
- Step 6. The page does not open anymore for any page after it was opened for the "Your Rights" page.

**[Notes]:**
- The issue is not reproducible without step 2, as the option is not displayed if the "Your Rights" page was the first tab opened.
- I was not able to reproduce this issue with the default behavior (with multiple tabs).
- The behavior in step 6 is removed after a restart of the app.
- Attached is a [recording of the issue](https://drive.google.com/file/d/1Cd5hnlYdCoFG-jb96c6zjn6jx_D4Nxxk/view?usp=sharing).

**Comment by Mugurell** [comment]
Looked a bit at this with Ionut.
It seems that it all boils down to the `extensionState` that we [inherit from the old tab in `MergeTabsMiddleware`](https://github.com/mozilla-mobile/focus-android/blob/4f235d1a315091dc980c6335dede891ead31bda9/app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt#L106-L110)
The merged tab will have the webcompat extension installed and enabled.

Then while debugging I was seeing that after the middleware finishes it's job we do [`registerSessionHandlers`](https://github.com/mozilla-mobile/android-components/blob/57db992e40f96abbee4c86c405027234b99f9fc8/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt#L394) for the web extensions but in between this (may be a race, may be because I was pausing execution) I also saw that we get a call to [`WebExtensionAction.UpdateTabPageAction`](https://github.com/mozilla-mobile/android-components/blob/57db992e40f96abbee4c86c405027234b99f9fc8/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/WebExtensionReducer.kt#L76) which would now disable the webcompat extension but this action comes with the id of the old tab that we removed in `MergeTabsMiddleware` so updating that extension's state in the current tab will fail.

**Comment by Mugurell** [comment]
Since fixing this involves a big refactoring in AC it's probably better to first asses whether Focus continue with supporting multiple tabs and so this won't be an issue anymore or Focus will only support one tab at a time in which case we should ensure this scenario is supported as best as possible.

**Comment by ionutbedregeanu** [comment]
Multiple tabs experiment will be removed, so we can close this ticket
https://github.com/mozilla-mobile/focus-android/pull/7623
