### ISSUE TITLE
Intermittent UI test failure - ShortcutsTest.renameShortcutTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6784]
### Stacktrace:
probably same ANR [reported here](https://github.com/mozilla-mobile/fenix/issues/24047)
`03-30 01:42:53.854: E/Finsky(12437): java.util.concurrent.ExecutionException: com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out (timeout delayed by 40 ms after scheduled time): bvj@a734394[status=PENDING, info=[tag=[class akjm]]]
03-30 01:42:53.854: E/Finsky(12437): 	at awuc.s(PG:3)
03-30 01:42:53.854: E/Finsky(12437): 	at awuc.get(PG:2)
03-30 01:42:53.854: E/Finsky(12437): 	at awxe.a(PG:1)
03-30 01:42:53.854: E/Finsky(12437): 	at awvz.r(Unknown Source:9)
03-30 01:42:53.854: E/Finsky(12437): 	at alff.run(Unknown Source:4)
03-30 01:42:53.854: E/Finsky(12437): 	at android.os.Handler.handleCallback(Handler.java:938)
03-30 01:42:53.854: E/Finsky(12437): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-30 01:42:53.854: E/Finsky(12437): 	at android.os.Looper.loop(Looper.java:223)
03-30 01:42:53.854: E/Finsky(12437): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
03-30 01:42:53.854: E/Finsky(12437): 	at java.lang.reflect.Method.invoke(Native Method)
03-30 01:42:53.854: E/Finsky(12437): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-30 01:42:53.854: E/Finsky(12437): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-30 01:42:53.854: E/Finsky(12437): Caused by: com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out (timeout delayed by 40 ms after scheduled time): bvj@a734394[status=PENDING, info=[tag=[class akjm]]]
03-30 01:42:53.855: I/Finsky(12437): [2] VerifyInstallTask.mC(6): Verification complete: id=12, package_name=org.mozilla.focus.debug.test
03-30 01:42:53.888: I/ActivityManager(460): Killing 12308:com.google.android.keep/u0a114 (adj 915): empty #17
03-30 01:42:53.919: I/Zygote(287): Process 12308 exited due to signal 9 (Killed)
03-30 01:42:53.939: I/libprocessgroup(460): Successfully killed process cgroup uid 10114 pid 12308 in 43ms
03-30 01:42:56.397: W/ProcessCpuTracker(460): Failed to stat(/proc/15473): android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
03-30 01:42:56.397: W/ProcessCpuTracker(460): Skipping unknown process pid 15473
03-30 01:42:46.197: D/logd(0): Skipping 256 entries from slow reader, pid 10492, from LogBuffer::kickMe()
03-30 01:42:56.446: D/logd(0): Skipping 244 entries from slow reader, pid 10492, from LogBuffer::kickMe()
03-30 01:42:57.310: I/WindowManager(460): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: a6dd7c1 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (177.0, 497.0)]), policyFlags=0x6b000000
03-30 01:42:57.362: D/logd(0): Skipping 256 entries from slow reader, pid 10492, from LogBuffer::kickMe()
03-30 01:42:57.442: I/ActivityManager(460): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
03-30 01:42:57.442: I/ActivityManager(460): Killing 13456:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 01:42:57.445: W/Binder(13362): Caught a RuntimeException from the binder stub implementation.
03-30 01:42:57.445: W/Binder(13362): java.lang.SecurityException: Calling from not trusted UID!
03-30 01:42:57.445: W/Binder(13362): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
03-30 01:42:57.445: W/Binder(13362): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
03-30 01:42:57.445: W/Binder(13362): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
03-30 01:42:57.445: W/Binder(13362): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-30 01:42:57.445: W/Binder(13362): 	at android.os.Binder.execTransact(Binder.java:1123)
03-30 01:42:57.449: I/ServiceChildProcess(13987): Destroying GeckoServiceChildProcess
03-30 01:42:57.450: I/ServiceChildProcess(14112): Destroying GeckoServiceChildProcess
03-30 01:42:57.450: D/AndroidRuntime(13362): Shutting down VM
03-30 01:42:57.452: E/JavaBinder(13362): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
03-30 01:42:57.452: E/JavaBinder(13362): java.lang.RuntimeException: Bad file descriptor
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.os.BinderProxy.transactNative(Native Method)
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
03-30 01:42:57.452: E/JavaBinder(13362): 	at android.os.Binder.execTransact(Binder.java:1123)
03-30 01:42:57.452: W/ActivityTaskManager(460): Force removing ActivityRecord{cd245f6 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
03-30 01:42:57.466: I/focus.debug:gp(14112): System.exit called, status: 0
03-30 01:42:57.466: I/AndroidRuntime(14112): VM exiting with result code 0, cleanup skipped.
03-30 01:42:57.495: I/BackdropActivity(11890): onResume()
03-30 01:42:57.497: I/ActivityManager(460): Killing 13987:org.mozilla.focus.debug:tab27/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 01:42:57.498: I/ActivityTaskManager(460): Activity requesting to dismiss Keyguard: ActivityRecord{d28d848 u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
03-30 01:42:57.502: I/ActivityManager(460): Killing 14112:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 01:42:57.508: I/ActivityManager(460): Killing 12458:com.google.android.googlequicksearchbox/u0a98 (adj 985): empty #17
03-30 01:42:57.513: D/WindowManager(460): notifyANR took 205ms`
### Build:
3/30 Debug

**Comment by AndiAJ** [comment]
Flaky 1x on 3/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9167412189149449845/executions/bs.c9ebde29f22fb319/testcases/1)

**Comment by AndiAJ** [comment]
Failed 1x on 4/16 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5844236252701674209/executions/bs.1d644ffd0bb76403/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5844236252701674209/executions/bs.697bad25b093b0ba/testcases/1)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 7/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5272136364834545234/executions/bs.bf34d6a469a48c88/test-cases)

06-30 23:08:44.853: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: a35761c org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5004ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (177.0, 497.0)]), policyFlags=0x6b000000
06-30 23:08:45.009: I/ActivityManager(479): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-30 23:08:45.009: I/ActivityManager(479): Killing 11821:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-30 23:08:45.011: W/ActivityTaskManager(479): Force removing ActivityRecord{ef11f1a u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-30 23:08:45.013: W/Binder(11667): Caught a RuntimeException from the binder stub implementation.
06-30 23:08:45.013: W/Binder(11667): java.lang.SecurityException: Calling from not trusted UID!
06-30 23:08:45.013: W/Binder(11667): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-30 23:08:45.013: W/Binder(11667): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-30 23:08:45.013: W/Binder(11667): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-30 23:08:45.013: W/Binder(11667): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-30 23:08:45.013: W/Binder(11667): 	at android.os.Binder.execTransact(Binder.java:1123)
06-30 23:08:45.015: I/ServiceChildProcess(12582): Destroying GeckoServiceChildProcess
06-30 23:08:45.033: I/ActivityManager(479): Killing 12582:org.mozilla.focus.debug:tab30/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-30 23:08:45.036: I/ActivityManager(479): Killing 12702:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-30 23:08:45.037: I/ActivityManager(479): Killing 8958:com.google.android.contacts/u0a102 (adj 985): empty #17
06-30 23:08:45.042: D/WindowManager(479): notifyANR took 210ms

**Comment by sv-ohorvath** [comment]
Flaky 1x on 7/7 - same ANR crash: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6197743399989482563/executions/bs.dc24aa6a465063da

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
