### ISSUE TITLE
[PiP] Some videos when in PiP mode display the toolbar of the tab

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6804]
## Steps to reproduce
1. Open cnn.com, and search for an article with a video (i.e. https://edition.cnn.com/2022/03/31/asia/north-korea-missile-test-misinformation-intl-hnk/index.html).
2. Start the video, tap on fullscreen mode.
3. Tap on the device's home button to enable PiP mode.
4. Scroll a bit on the PiP floating window.

### Expected behavior
The video & settings buttons are displayed.
 
### Actual behavior
The toolbar, and the upper part of the tab are displayed. 
The user has to tap on the "extend" option to go back in the Focus app in order to see the actual video.

### Device information
* Android device: Oppo Find X3 Lite (Android 11), HTC 10 (Android 8), Lenovo Tab M10 (Android 10)
* Focus version: Focus Nightly 3/31, RC 99.1.1, and RC 99.1.0
* Not reproducible on youtube.com, or vimeo.com

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/8387941/logcat.txt)
![Screenshot_1](https://user-images.githubusercontent.com/40694158/161023242-5391929b-fbd2-4397-a819-42f0ccd097e3.jpg)

https://user-images.githubusercontent.com/40694158/161023303-8f51d1d0-3b87-4545-af56-ac60ef310d40.mp4

**Comment by amedyne** [comment]
@lobontiumira Can you confirm if this behavior is specific to this site?

**Comment by cpeterso** [comment]
Amedyne says this bug might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1757031.

**Comment by Mugurell** [comment]
This issue seems particular to the website and so it's a different issue that the one from the Bugzilla ticket.

It seems like the website is trying to make use of the [fullscreen web APIs](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) to enhance the experience and everything does work pretty nicely with normal usage.
But that same "feature" breaks Picture-In-Picture.

This can be seen on Chrome also, even without picture in picture if a video is playing in fullscreen & landscape when changing the orientation to portrait the video will exit fullscreen (quite probably the website is doing this).
The same happens on Focus and Fenix.
And the same happens while being in Picture-In-Picture. If the video was fullscreen with the device in landscape, when entering picture in picture and going to device's homescreen the orientation is automatically changed to portrait. So based on the above scenario the video will not be in fullscreen anymore.

This seems almost like a webcompat issue, it's just that a useful feature breaks another.


Chrome also: portrait to landscape sets fullscreen:
<video src="https://user-images.githubusercontent.com/11428869/161217443-5b14f000-76b7-4846-82f5-261cb8a59e08.mp4" width="33%" />

Chrome also: landscape to portrait exits fullscreen
<video src="https://user-images.githubusercontent.com/11428869/161217693-c774f44c-2d29-4708-ab9c-3f06a53f901f.mp4" width="33%" />


--- 
What Chrome does (and maybe we should do also): when a fullscreen video is not fullscreen anymore (as we see is happening on CNN) Picture-In-Picture mode is closed:


https://user-images.githubusercontent.com/11428869/161219192-a07b7a53-4141-4a22-8439-ffb5bbc30c24.mp4

**Comment by amedyne** [comment]
@jeffreygee Any thoughts from UX on this? I am inclined to follow how Chrome does it.

**Comment by jeffreygee** [comment]
@amedyne I agree. When a fullscreen video is not fullscreen anymore Picture-In-Picture mode should be closed -- this seems like the most logical experience

**Comment by lobontiumira** [comment]
Hello everyone,
I've tested on the latest Focus Nightly 101.0a1 (build 360960510 with GV 101.0a1-20220405094056) on several devices:
* Oppo Find X3 Lite (Android 11) - phone,
* Google Pixel (Android 10) - phone,
* Samsung Galaxy Note 8 (Android 9) - phone, and
* Lenovo Tab M10 (Android 10) - tablet.

and I've encountered two behaviors.

* On phones, the PiP remains active, the video is visible without any display of the toolbar of the tab:

https://user-images.githubusercontent.com/40694158/161910232-62ddaac5-55b8-4d1a-af67-863f8fef52e8.mp4

* On tablet, the PiP is closed but with visual glitches - please see the video below:

https://user-images.githubusercontent.com/40694158/161910285-3badbd76-d4e0-4ede-8567-c2b8b2b0412f.mp4

@ionutbedregeanu, @jeffreygee please review.
I'll remove the QAReady label for now.

**Comment by ionutbedregeanu** [comment]
"On phones, the PiP remains active, the video is visible without any display of the toolbar of the tab:" -> this is expected behaviour because the video doesn't exit from fullscreen while is in PiP
"On tablet, the PiP is closed but with visual glitches" -> I will think about how to improve this. That glitch appears because the video goes first in PiP, after that exists from fullscreen and in that moment we are knowing that we need to close it

**Comment by ionutbedregeanu** [comment]
@lobontiumira I tested the same scenario on Chrome and it seems they have the same problem. Maybe we should consider it expected behaviour

https://user-images.githubusercontent.com/11731652/163176824-c2fd5c53-5abf-436c-8657-9c267bf89343.mp4

**Comment by lobontiumira** [comment]
Based on the comment above, I will close this ticket.
Thank you!
