### ISSUE TITLE
Menu: Quick share 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#687]
Currently we show a "Share..." option in the menu. Additionally we would like to show the last/most used app for sharing as a quick share action:

![quickshare](https://cloud.githubusercontent.com/assets/89638/26629914/bf3575ee-4604-11e7-88b4-97b264d244b8.png)

**Comment by ekager** [comment]
I’ve been looking into this issue and checking out the quick share implementation in Fennec. There are definitely some trade offs to adding this feature to Focus. For one, the implementation from Fennec would add a lot of files to Focus, which is meant to be compact. Secondly, this would take a decent chunk of time for me to implement, and I’m not sure it’s as high priority as other additions I could be adding this summer. Lastly, the UX for the share options drawer might have to change since I would have to customize a new menu type to present the share options. 
 
If this is high priority, and you want me to keep working on it, I can, but there are some tradeoffs and it’s not as simple as just adding a new menu option. UX  - @brampitoyo any additional thoughts on priorities for this issue or UX implications?

**Comment by brampitoyo** [comment]
Focus’ unique feature is its ability to clear your browsing data and history in one tap.

Therefore, it may be reasonable to assume that users are:

* More likely to want to *open URLs in Focus*. For example, when using the Reddit app.
* Less likely to want to *share URLs out of Focus*. URLs opened in Focus are supposed to be more private than URLs opened in another browser. Private contents tend to get shared less than non-sensitive contents.

While we should have a share feature (this is a way to get URLs out of Focus.app other than doing manual copy–pasting), making sharing available in one tap can also carry unwanted privacy risk.

Coupled this with the fact that quick share is not trivial to implement and would increase our file size, I recommend us to fix other issues before working on this one.

What do you think, @pocmo?

**Comment by pocmo** [comment]
Let's talk about this in the next triage meeting (for priority). I'm also not keen on adding a bunch of Fennec files. :)

**Comment by jxn** [comment]
Just in case anyone's interested, here's an example (mine) use-case for Firefox Focus:
I would like to use Focus as the default browser, so I get privacy by default when I open the browser or browse in on a search result.  If I want to interact with the page more, I share it to Pocket (for reading later), to Firefox (desktop or android), if I want to open multiple tabs or utilize a logged-in session (such as making a purchase online).

Focus is not good for organizing tabs or using browser extensions or features like debugging or find-in-page... but is a great browser to start in if I don't know that I'll need those things.  Reducing the friction for common sharing options is *very* helpful for this kind of user, though I'm not sure how common that use-case is.

**Comment by pocmo** [comment]
Thanks for the input, @jxn. I was wondering about something similar: Instead of adding all those things to Focus (Tabs, Storing History, ..) we should look into ways to integrate better with third-party apps that offer related functionality (like Pocket).

**Comment by brampitoyo** [comment]
Great idea, @jxn!

Here are some things to think about:

1. Should we offer the ability to customise Android’s default share sheet? I know that it’s not our domain, but the sharing sheet can quickly get cluttered with people, apps, devices, etc. What if Focus’ sharing sheet is a special one that you can populate with your preferred apps?

2. Instead of relying on one sharing sheet to rule them all, can we split the non-specific “Share” action into two separate actions?
  * “Open in a [browser_name] tab”
  * “Save to [app_name]”

I’m also in favour of better third party integration instead of building more features into Focus that can potentially dilute our key selling point (the most private browser) and inflate our apk size.
