### ISSUE TITLE
Menu: Open with (last used app)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#688]
We would like to show the last/most used app as quick action in the "Open with.." menu:
![openwith](https://cloud.githubusercontent.com/assets/89638/26629961/e8e0ee8c-4604-11e7-83a9-b60acda16b24.png)

Note that there might be different options depending on the URL: I might be opening reddit.com links a lot with a reddit app. But this doesn't mean this should be a quick action for YouTube. So we only should add a quick action for apps that can handle the current URL.

**Comment by antlam** [comment]
@bbinto thoughts? this would tidy up the current double menu item of:

Share...
**Open with Firefox
Open with...**
Settings

On the one hand, on iOS, we heard feedback around having "Firefox" front and center like this for new users (even those without Firefox installed). But this might also introduce messaging challenges around privacy.

**Comment by bbinto** [comment]
I like it, I got some feedback from others as well to make sharing quicker/easier (similar to what we have in Firefox, show last app used to share)

**Comment by liuche** [comment]
During triage, talked about the balance between privacy vs convenience - @bbinto will follow up with Gemma to see if this can be validated.

Engineering-wise, from earlier work done by @ekager, this involves duplicating several Android files in order to capture the "last used" app, and probably involves a custom Share menu that might not necessarily match the Android styling per version (e.g., we write one custom version for "Share" dialog that looks like N, but doesn't match the styling of O.)

**Comment by pocmo** [comment]
> Share...
> Open with Firefox
> Open with...
> Settings

Note that there's also a third item: "Open with [default browser]" (If there's a default and it's not Focus or Firefox).

**Comment by antlam** [comment]
> Note that there's also a third item: "Open with [default browser]" (If there's a default and it's not Focus or Firefox).

If there's a default set, I think it's ideal if the icon starts with and shows that default browser.

**Comment by antlam** [comment]
If we're concerned about Privacy, maybe this is still useful if it were implemented per session only? I.e. I've shared with Firefox in this session, it shows up as a "shortcut".

**Comment by bbinto** [comment]
dup of #687
