### ISSUE TITLE
The splash screen is displayed for slightly more than 2 seconds at the first startup

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7032]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361300946 GV: 102.0a1-20220509094710)

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/

**[Steps to reproduce]**:
1. Open Focus for the first time.
2. Observe the splash screen.

**[Expected result]**:
- The splash screen is displayed for a maximum of 2 seconds.

**[Actual result]**:
- The splash screen seems to be displayed for more than 2 seconds (observed ~3.5s) at the first startup.

**[Notes]**:
- The splash screen seems to be displayed for the expected time for subsequent startups.
- Attached is a recording of the issue.

![more than 2s](https://user-images.githubusercontent.com/53752296/168618489-4465af94-0d49-4210-b3e3-164867ada4ad.gif)

**Comment by ionutbedregeanu** [comment]
My bad, this is a confusion started from my side. The splash screen should be displayed for at least 2 seconds.
In the splash screen listener ViewTreeObserver.OnPreDrawListener we are checking(with a small difference between listener checks) if at least 2 seconds have passed, so I will close this ticket since this behaviour is expected
