### ISSUE TITLE
[Intermittent] The onboarding exposure event is sent at non-onboarding startup

### ISSUE THREAD

**Issue by heres-maria** [mozilla-mobile/focus-android#7082]
**[Affected Versions]**:
- Focus Nightly 102.0a1 (Build #361431118 GV: 102.0a1-20220522094633) AC:102.0.20220522143114, edac10adc1, AS: 93.1.0

**[Affected Platforms]**:
- Android 9 - Samsung Galaxy S8

**[Prerequisites]**:
- Have a Focus for Android build with the following modifications:
     - The following lines added to local.properties:
     nimbus.remote-settings.url = https://settings.stage.mozaws.net
     debuggable = true
     - A new “.nimbus” file (in the same location as local.properties) containing the following line: https://settings.stage.mozaws.net/
- Have a Focus for Android Nimbus experiment using the onboarding feature.
- Have a way to observe Logcat (the Android Studio viewer was used for testing).

**[Steps to reproduce]**:
1. Open Focus and close it to avoid #6995.
2. Reopen the app using a [telemetry command](https://mozilla.github.io/glean/book/user/debugging/android.html) (e.g. adb shell am start -n org.mozilla.focus.nightly/mozilla.telemetry.glean.debug.GleanDebugActivity --ez logPings true --es sendPing events --es debugViewTag MH-1).
3. Dismiss onboarding.
4. Close the app.
5. Reopen the app using a telemetry command.
6. Minimize the app, refocus it, and observe Logcat.

**[Expected result]**:
-  The exposure event is only recorded when users are exposed to onboarding.

**[Actual result]**:
- The exposure event is recorded at some startups that do not display the onboarding.

**[Notes]**:
- The issue seems more often reproducible for experiments setting both “is-enabled” and “is-cfr-enabled” to the same value, whether true or false. I was also able to reproduce the issue once using a branch setting “is-enabled” to false and “is-cfr-enabled” to true but not “is-enabled” to true and “is-cfr-enabled” to false so far.
- Attached is a recording of the issue.

https://user-images.githubusercontent.com/53752296/169817295-4edc4d55-206b-4ca7-828d-ed93fe2719b3.mov

**Comment by ionutbedregeanu** [comment]
1. "is-enabled = true" and "is-cfr-enabled = true" -> not expected, I will address that
2. "is-enabled = false" and "is-cfr-enabled = false" -> I didn't noticed a recorded exposure for onboarding feature
3. "is-enabled = false" and "is-cfr-enabled = true" -> Expected behaviour because are part of the same feature and this is not a valid configuration  "is-cfr-enabled" can't be true and "is-enabled = false"
Valid configurations "is-enabled = true" and "is-cfr-enabled = true",  "is-enabled = true" and "is-cfr-enabled = false", "is-enabled = false" and "is-cfr-enabled = false"
