### ISSUE TITLE
Consider setting to move the `Erase` floating action button (FAB) to the left hand side

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-mobile/focus-android#752]
When you’re left-handed and browse one-handed, your thumb is going to be located on the left side of the screen.

There should be a setting that moves our `Erase` FAB button to the left-side, so it’s easy for the left thumb to reach.

This setting can say something like:

**Left-handed erase button** [off/on]

**Comment by pocmo** [comment]
Some random thoughts:

* I'm not completely sold on the idea when thinking about the ecosystem: We would go against the guidelines and behave differently than other apps. I'm okay with that in general but we should have a very good reason for doing that. As someone who is right-handed I think a left-side FAB would actually be easier to reach (one-handed) for me. :)
https://material.io/guidelines/components/buttons-floating-action-button.html#

* Btw. with RTL languages selected it's already mirrored - so this setting might be confusing because it might do the opposite of what we think it does

* I feel like we lose some of our simplicity if we introduce too fine-grained settings instead of using sensible defaults. Am I too protective here?

I removed the "good first bug" label. I think it's a great first bug - but I would like to wait after triage etc. - Those should be bugs that can be picked up immediately.

**Comment by brampitoyo** [comment]
@pocmo, I think you’re right on all counts. Although the Material Design Guidelines didn’t specify a specific side for the FAB, they do tend to hang around the bottom right-hand corner of the screen most of the time (and top left-hand corner only sometimes). Chalk this up to my unfamiliarity with the Android platform.

If you’re left-handed and would really prefer for things to be reordered, I feel like it would be more helpful to force the OS to use an RTL layout instead of getting individual apps to do it. Because then an odd corner case would happen: the OS uses RTL but the app *also* uses RTL; would the two settings cancel each other out?

I’m closing this issue for now.
