### ISSUE TITLE
Onboarding tour: Show next card partially

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#762]
We implemented in #497.

We want to show the next card of the tour partially. There have been several issues when rotating the device and handling alpha animations while scrolling cards. Therefore we decided to skip this in v1 and look at this in the next version again.

**Comment by pocmo** [comment]
Overall the onboarding layouts are nexted and maybe too complex. There might be the opportunity to re-write parts of this. In addition to that there are some issues with edge cases (e.g. very long strings) that we should fix.

**Comment by EmmanuelMess** [comment]
@pocmo 

I don't know how much of a hint you want, because more hint means less space for text, as you said. Here is a (before and after of a) version with a small hint and almost no change in card width:

![screenshot_1537138955](https://user-images.githubusercontent.com/10991116/45601948-79664a00-b9eb-11e8-8e0e-28819ce73655.png) ![screenshot_1537138793](https://user-images.githubusercontent.com/10991116/45601931-242a3880-b9eb-11e8-928c-5a9eb888f525.png)

(On an AVD 3.2" QVGA w/API 27)
