### ISSUE TITLE
The trashcan CFR isn't displayed at all after rotating the device while the TP CFR is displayed

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7652]
## Steps to reproduce
1. Install Focus Nightly - local build with CFR's implemented.
2. Open a webpage, like bbc.com.
3. After the tracking protection CFR is displayed, rotate the device, without touching the screen.
4. The tracking protection CFR is dismissed. Wait for the trashcan CFR to be displayed.

### Expected behavior
The trashcan CFR should be displayed, even if the devices was rotated.

### Actual behavior
The trashcan CFR is not displayed at all.

https://user-images.githubusercontent.com/40694158/189934682-906f8583-0ae6-4d1e-82d4-c9ae9792e50c.mp4

**Workaround**: if the user minimizes Focus, then opens Focus again, the tracking protection CFR is displayed again. Dismissing it, displays the trashcan CFR.

### Device information
* Android device: Oppo Reno 6 (Android 12)
* Focus version: Focus Nightly 106.0a1 - local build
* Video with the workaround:

https://user-images.githubusercontent.com/40694158/189934494-95c85def-80b4-459a-8268-097aa5e892b1.mp4

**Comment by Mugurell** [comment]
As a parenthesis most of the popups including CFRs and menus from Fenix will automatically be dismissed when the user rotates the screen because of anchoring issues. And this was the default behavior for Focus also going forward.

Looking at the expected / actual & workaround scenarios it seems to me like the actual bug here is that the CFR appears after the app is minimized and reopened.
This offers an idea about how to ensure the CFR is shown after the screen is rotated:
Since anchoring issues are expected (intermittently) what we can try is:
- still allowing CFRs to be dismissed when the user rotates the screen but 
- having `BrowserToolbarIntegration` which manages these CFRs now receive a callaback for when the user changes orientation (known from `BrowserFragment - onConfigurationChanged` 
    - this allowing to show again the CFRs for which the conditions are still met but were previously automatically dismissed.
For this approach we should ensure the dismiss telemetry does not also log when the automatic dismissal.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802614

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
