### ISSUE TITLE
The CFRs are dismissed if the users taps anywhere on the screen

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#7653]
## Steps to reproduce
1. Install Focus Nightly - local build with CFRs implemented.
2. Open a webpage, like bbc.com.
3. After the tracking protection CFR is displayed, tap anywhere on the screen.
4. The trashcan CFR is displayed, tap anywhere on the screen.

### Expected behavior
The CFRs should be dismissed only when the users taps on the "X" close option from the top-right corner of the CFRs.

### Actual behavior
The CFRs are dismissed when the user taps anywhere on the screen.

### Device information
* Android device: all
* Focus version: Focus Nightly 106.0a1 - local build.
* Reproducible on Fenix Nightly 106.0a1.

https://user-images.githubusercontent.com/40694158/189935988-fb5773cb-2ea1-44b5-aa60-fe064e8058e5.mp4

@jeffreygee please review.

**Comment by Mugurell** [comment]
If the now expected behavior wasn't part of the initial specs I would argue it's not a bug.

Controlling whether the CFRs are dismissed with outside clicks can easily be done through [CFRPopupProperties.dismissOnClickOutside](https://github.com/mozilla-mobile/focus-android/blob/2407357cfaf3b5f2f21861d9953a6b2b6cb29342/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt#L109).
Another scenario which may worth discussing is whether a back press should dismiss the CFR - this can be easily controlled through [CFRPopupProperties.dismissOnClickOutside](https://github.com/mozilla-mobile/focus-android/blob/2407357cfaf3b5f2f21861d9953a6b2b6cb29342/app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt#L108).

**Comment by rtestard** [comment]
@jeffreygee I think this is expected behavior that the CFR is dismissed if you tap off of it so it does not interrupt the flow but can you please confirm?

**Comment by iorgamgabriel** [comment]
And if the user presses outside or back the cfr should appear again when the user enters in the app ? @rtestard @jeffreygee

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802613

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
