### ISSUE TITLE
IllegalStateException: Not allowed to start SessionNotificationService because app is in background

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/focus-android#7681]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1646396

**Comment by cpeterso** [comment]
We received 1000+ crash reports from Focus 104 (and earlier) about this IllegalStateException (Not allowed to start service org.mozilla.focus/.session.SessionNotificationService because app is in background), but none of the equivalent Fenix exception since Fenix 101. Why Focus but not Fenix?

**Comment by WandersonKalil** [comment]
@Mugurell  @cpeterso THIS is a restriction that occurs from Android 11 onwards: I'm the author of  SuperPower - Root Access Manager, which obviously needs to send a notification to the user of which app has been allowed root access, and SuperPower ran into this same restriction: not allowed to send background broadcast due to app is in idle/background state. The only solution is to start an activity and finish it  immediately ( the purpose  here is to awaken the app so it can receive the broadcast).

**Comment by cpeterso** [comment]
@WandersonKalil, thanks for the tip! I'll share your recommendation on the Bugzilla bug for this exception: https://bugzilla.mozilla.org/show_bug.cgi?id=1646396
