### ISSUE TITLE
Swipe To Switch Tab

### ISSUE THREAD

**Issue by 4shutosh** [mozilla-mobile/focus-android#7730]
### Why/User Benefit/User Problem
Like the default firefox browser, the focus should also enable the swipe to switch tab feature. I don't see why the "focus" makes a difference in not including that behavior.

### What / Requirements
Swipe Gesture to switch tab Should be implemented

**Comment by iorgamgabriel** [comment]
We are not gonna implement this , a decision was made by @rtestard . Too much risk of confusion with the back action and lack of alignment with what users coming from Chrome .

**Comment by cadeyrn** [comment]
@iorgamgabriel Did you saw my comment in the PR (https://github.com/mozilla-mobile/focus-android/pull/7731#issuecomment-1290729896)? The comment regarding Chrome doesn't make sense at all. Chrome **has** this gesture. As well as Firefox and other browsers on Android. 🤔

**Comment by iorgamgabriel** [comment]
Hello @cadeyrn the risk is too high to land this feature . Sorry , it was a decision from product owner . Thank you very much !

**Comment by cadeyrn** [comment]
@iorgamgabriel I did understand that there was product decision. But my concern is still the sentence about Chrome. Could you please explain that part? Since you wrote "lack of alignment with what users coming from Chrome" and Chrome has this feature I am not sure whether the feature was understood at all when the decision was made. And why is there is no risk for Firefox where the same feature is available?
