### ISSUE TITLE
Embedded video is not shown at bpiautosok.hu with "Trackers and Scripts to Block - Content" option enabled

### ISSUE THREAD

**Issue by softvision-raul-bucata** [mozilla-mobile/focus-android#7778]
## Steps to reproduce
1. Navigate to: https://bpiautosok.hu/video-nem-latta-nyilegyenesen-nekihajtott-oldalrol-a-kamionnak-az-autos/.
2. Tap on the "Shield" icon inside the toolbar.
3. Enable the "Content" option from the "Trackers and Scripts to Block"
4. Scroll the page.
5. Observe the result.

### Expected behavior
The embedded video is present and can be played.

### Actual behavior
The embedded video is missing.

### Device information

* Android device: Samsung A51 (Android 11) -1080 × 2400 pixels 20:9 aspect ratio (~405 ppi density)/Google Pixel 3 (Android 12) -1080 x 2160 pixels, 18:9 ratio (~443 ppi density)
* Focus version: Firefox Focus Nightly 107.0a1 (362721708-🦎107.0a1-20220929014928🦎)

**Attached screenshot:**
![Screenshot_26](https://user-images.githubusercontent.com/75027050/193277233-5caa6034-a8e5-4f1d-a24d-d26155914602.jpg)

**Notes:**
We are submitting this issue to clarify how we shall treat future reported similar issues with this option enabled, since this option seems to be Focus specific.
As seen here: https://github.com/webcompat/web-bugs/issues/111577

**Comment by Mugurell** [comment]
Focus just passes the option to GeckoView.
On Fenix there is no option to block content trackers but if forcing this in code I see that indeed the video is blocked there also.
There is a note that ["blocking content trackers my cause issues with some websites"](https://github.com/mozilla-mobile/android-components/blob/fddd02dce9f5c92906e071310a0b6118e130e1be/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L365-L369) though not sure how one would check whether content was blocked because of this or there is a bug.
Moving to Bugzilla for more investigations and recommendations.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794756

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
