### ISSUE TITLE
On Focus's "About" | "Learn More" page, focus doesn't handle the "Download Firefox" button correctly

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#796]
Full details here: https://bugzilla.mozilla.org/show_bug.cgi?id=1374739

**Comment by dholbert** [comment]
STR:
 1. Open Firefox Focus for Android.
 2. Tap the 3-dots menu in upper right.
 3. Choose "About"
 4. Tap "Learn more" link at the bottom.

  --> This takes you to a page on the Mozilla Manifesto with a prominent green "Download Firefox" button at the top

 5. Tap the green "Download Firefox" button.

ACTUAL RESULTS:
I'm immediately taken to a Focus error page:
> The address wasn't understood
> * You might need to install other software to open this address.
> [ Try again ]

EXPECTED RESULTS:
I should be prompted to open the Google Play store (since I think the link is a "market://" URL).


Note: If I visit the same page using Focus's normal browsing mode, e.g. by searching the web for "Mozilla Manifesto" and tapping the correct search result, then the Download Firefox button is functional and I get "expected results".  I only get the broken "actual results" when I visit the page from the Focus menu's "About|LearnMore" flow.

**Comment by dholbert** [comment]
For reference:
[Screenshot 1: the Mozilla Manifesto page that "About | Learn More" takes me to, with green download button that is non-functional when I arrive at the page via this flow](https://bugzilla.mozilla.org/attachment.cgi?id=8879666)

[Screenshot 2: the error page that I hit if I tap that button](https://bugzilla.mozilla.org/attachment.cgi?id=8879668)

**Comment by dholbert** [comment]
and the page in question is https://www.mozilla.org/en-US/about/manifesto/ , which (on Android) has a market:// URL behind its download button (which works fine when I visit that URL directly in Focus, but not when I visit via this "About" flow)

**Comment by sabbir044** [comment]
@pocmo 
The bug is _**handleExternalUrl**_ is not handled for **_InfoFragment_**. I am going to push a fix, just copy code from **_BrowserFragment_**.
