### ISSUE TITLE
[L10N] The newly added "Search in Firefox Focus Beta/Nightly/Klar" aren't translated

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#8046]
## Prerequisites
Have Focus Beta, and Focus Nightly installed.

## Steps to reproduce
1. Set your device to German, or other language besides English.
2. Open a page with text.
3. Long-tap on a non-linked text, to trigger the context menu.
4. Observe the "Search in Firefox Focus Beta/Nightly/Klar" options.

### Expected behavior
All the options from the context menu are translated.

### Actual behavior
The "Search in Firefox Focus Beta/Nightly/Klar" options are not translated.

### Device information
* Android device: Lenovo tablet M10 (Android 10)
* Focus version: Beta 108.0b1, and Nightly 109.0a1 from 11/17

![l10n](https://user-images.githubusercontent.com/40694158/202409664-fe09819f-3c14-4483-a83f-a3e66f5fd64e.jpg)

**Comment by Mugurell** [comment]
Don't think situations like this should be treated like bugs.
Similar to https://github.com/mozilla-mobile/focus-android/issues/6061#issuecomment-995272035 situations like these can happen as translations depend on volunteers.
cc @Delphine

**Comment by Delphine** [comment]
Right, there were issues with the initial string so this didn't land on Pontoon with the correct string yet. There were issues so this may appear untranslated for a little bit still.
The only reason this would be a bug is if that string is needed for that release, and still doesn't land soon. So maybe a good thing to keep this open in case
Otherwise Mugurell is correct, this wouldn't be a bug necessarily

**Comment by cpeterso** [comment]
> Otherwise Mugurell is correct, this wouldn't be a bug necessarily

In that case, I will close this report.
