### ISSUE TITLE
On new page load: Set progress to something higher than 0

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#818]
On slow networks I often run into this issue:
* I click a link to load a page
* We reset the toolbar state (Progress is set to 0)
* It takes some time until the page loads (maybe DNS?) and there's no progress at all
* After some time we receive a progress from WebView and the progress bar shows up

Until the progress bar shows up it feels like nothing is happening. Instead of showing a 0% progress bar (= no progress bar) we should set it to 5% or 10% when we receive the callback from the WebView that a new site is loading.

**Comment by antlam** [comment]
I like that idea! I think it sounds like it could be a perceived performance win too. 

I wonder if there's a non-arbitrary way to determine the most effective "starting point" for the progress/loading bar in these instances.

@brampitoyo do you have thoughts?

**Comment by pocmo** [comment]
I wanted to use a low value - so that the user doesn't experience a progress bar that goes backwards. However it should be big enough so that it's visible. I picked 5% for the first version.

**Comment by brampitoyo** [comment]
There was a semi-related paper written about progress bar and perceived speed:
http://chrisharrison.net/projects/progressbars/ProgBarHarrison.pdf

Here are some of its findings and recommendations:

> 1. Users seem to have a strong aversion to pauses especially towards the end of an operation.
> 2. Users are most willing to tolerate negative progress behavior (e.g., stalls and inconsistent progress) at the beginning of an operation.
> 3. Progress can be downplayed in the beginning and accelerated towards the end, providing a sense of a rapid conclusion that is highly favored by users in our experiment.

Based on these, it seems like setting the progress bar to 5%, where it may stall or take some time, would be okay.

The only suggestion I would add is to animate the time it takes to get from 0%–5% (instead of abruptly starting at 5%), in order to provide a sense of progress.

**Comment by pocmo** [comment]
That's an interesting paper. Thank you for sharing!

Right now I set the progress bar to start at 5% immediately. I'll look into animating it from 0% to 5%. The only tricky part is to not accidentally override an actual progress update that is larger than 5% (in case the page loads very fast).

**Comment by brampitoyo** [comment]
Thanks, @pocmo. I’ve seen this in action on the latest build, and it looks good!

As you wrote, when the page loads so quickly that the progress goes beyond 5% instantly, the progress bar looks like it ‘backpedals’ before going forward.

Example: https://d26dzxoao6i3hh.cloudfront.net/items/0W152Z0l3p3g3d3w2o0q/firefox-focus-progress-bar.mp4

I think that the solution is to intercept how the progress bar is going on pageload. If it’s below 5%, set it to 5%. If it’s above 5%, use that value instead of reverting back.

**Comment by pocmo** [comment]
> I think that the solution is to intercept how the progress bar is going on pageload. If it’s below 5%, set it to 5%. If it’s above 5%, use that value instead of reverting back.

This is actually pretty hard to do. Currently I set the progress to 5% in onPageStarted(). That's the earliest point in time we know that a new page is loading (where we also decide to show the progress bar again). So if there's already a progress higher than 5% then it could be (and I guess it is in most cases) from the previous page load.

To make things worse: Sometimes there are redirects or other reasons why WebView actually might return a smaller progress suddenly.

I'll need to do some debugging to see what's causing this here.

**Comment by pocmo** [comment]
I saw that with the Photon loading bar code we are already animating from 0% to 5%. So this is already implemented in the latest builds. -> Closing.
