### ISSUE TITLE
Notification actions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#826]
I talked to @antlam about this yesterday. We want to add "actions" to the notification to allow the user to switch back to Focus *or* erase the browsing session.

- [x] Add new actions
- [x] Add telemetry probes
- [x] Add action icons for older Android versions
- [x] Polish UI (see comments below)

**Comment by bbinto** [comment]
I think we should get Michelle to review the copy. 

A few other comments
- Some apps show the action buttons right away (e.g. Gmail DELETE | REPLY), without pulling down the notification. Could we do that as well? Because I'm afraid people don't notice it right now because it still just says "Erase browsing history" under the app name.
- If we can make comment 1 work, we could change the  "Erase browsing history" to  "Browsing session running" and the two action buttons showing by default, unless clicking on the notification needs an action as well (currently set to erase)

Thoughts?

**Comment by bbinto** [comment]
(not sure if you preferred re-opening the bug instead of creating a new one)

**Comment by pocmo** [comment]
> Some apps show the action buttons right away (e.g. Gmail DELETE | REPLY), without pulling down the notification. Could we do that as well? Because I'm afraid people don't notice it right now because it still just says "Erase browsing history" under the app name.

Afaik by default Android expands at least the top most notification. If there are others on top then this might cause our notification to be collapsed. The order can be controlled by giving the notification a priority (currently it just has the "default" priority). I'm a bit hesitant to give it the highest priority just because it's not something that should draw immediate attention like for example a mail you just received. However I'll do some research to see what other options we might have.

> If we can make comment 1 work, we could change the "Erase browsing history" to "Browsing session running" and the two action buttons showing by default, unless clicking on the notification needs an action as well (currently set to erase)

The last time I talked to @antlam he wanted to keep the default action when clicking the notification itself. But in general I agree we can improve the notification. I actually wanted to file a bug to address some of visual things (e.g. we do not set a color and therefore all actions are just "gray").

**Comment by bbinto** [comment]
Thanks Sebastian, I'll wait for @antlam to chime in regards to the second bullet. I think we can do a bit more there...color, text etc.

And I agree we should not set the notification priority to "high".

**Comment by antlam** [comment]
Definitely want to get @mheubusch 's help on the content here! We were pinging on Slack too :)

> If we can make comment 1 work, we could change the "Erase browsing history" to "Browsing session running" and the two action buttons showing by default, unless clicking on the notification needs an action as well (currently set to erase)

+1 to @pocmo 's evaluation here.

Since the primary action of Focus is to "Erase". I think it also makes more sense for the primary 'hit target' to perform an "Erase" action and to continuously communicate the same message.

This Notification also exists because we wanted to allow users a quick and easy way to "Erase" their browsing history - without first re-opening the app to in full-screen.

Let's not forget there's also the Recent Apps interaction (list, and double-tap) to allow a user to return to Focus. 

Plus, not to mention, changing it _now_ to a "Return" action instead could be confusing for current users and their workflows

Upon expanding though, we should definitely allow secondary functionality such as returning to a browsing session.

> The last time I talked to @antlam he wanted to keep the default action when clicking the notification itself. But in general I agree we can improve the notification. I actually wanted to file a bug to address some of visual things (e.g. we do not set a color and therefore all actions are just "gray").

1. Let's set a color! we have the our Purple theme color from the FAB!
2. I definitely want to improve the notification, the trick here is balancing it with what we're potentially giving up - Could we add the "return" action first as the secondary action and measure then go from there?

**Comment by pocmo** [comment]
I filed #864 to talk about improving / polishing the notification. Let's use this issue here for the "actions" only.

> Let's set a color! we have the our Purple theme color from the FAB!

I added some screenshots to #864. :)

**Comment by pocmo** [comment]
@antlam Older versions of Android show an icon next to the title of the action (open / erase). This is mandatory. New versions seem to not use them anymore and just show the title only. However I wonder what icons we should use? For "erase" we can use the trash can - and for "open"?

**Comment by antlam** [comment]
Chatted with @pocmo just now, we'll go with the Firefox Icon for 're-open/open/return' in the mean time, and we won't repeat the "Erase" action underneath.
- OS best practices
- more options for the future
- clearer messaging

**Comment by bbinto** [comment]
>> Some apps show the action buttons right away (e.g. Gmail DELETE | REPLY), without pulling down the notification. Could we do that as well? Because I'm afraid people don't notice it right now because it still just says "Erase browsing history" under the app name.

>  However I'll do some research to see what other options we might have.

@pocmo any news if this is possible?

**Comment by mheubusch** [comment]
@antlam I think OPEN is good.

**Comment by pocmo** [comment]
> @pocmo any news if this is possible?

Unfortunately this doesn't seem to be possible. It's up to the system to decide if the notification will be shown expanded or not. And it looks like Android only expands the top notification by default. The order of notifications can only be controlled by assigning an "importance" (min, low, default, max, high). As we are not actually notifying about something that needs attention it's not advised to use a higher importance here though.

**Comment by pocmo** [comment]
Adding to that: From the guidelines Android usually expects the notification itself to switch to a screen in the app - that should offer the same actions as the notification actions (Example: "GMail", you can "archive" or "reply" from the notification - but you could also just switch to the app and do it there). So in this case the actions are only a secondary, sometimes faster, way to do something without switching to the app. Our use case with "open" doesn't really fit this model and this makes this a bit complicated.

**Comment by bbinto** [comment]
Thanks @pocmo.

@antlam / @mheubusch how about "Return" instead of "Open" as open could mean opening the app to start a search? with cleared history?

**Comment by antlam** [comment]
I think Open still makes sense. It's a bit less technical and fits in with the Material language a lot more. :)

**Comment by pocmo** [comment]
All changes are in now.

**Comment by bbinto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update notification actions](https://trello.com/c/PNFFJWpZ/46-update-notification-actions)
