### ISSUE TITLE
NullPointerException: android.content.res.Resources android.content.Context.getResources()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#838]
Buddybuild detected a crash
`app/src/main/java/org/mozilla/focus/locale/Locales.java` line `136`

```java


    /**
     * Get a Resources instance with the currently selected locale applied.
     */
    public static Resources getLocalizedResources(Context context) {
        final Resources currentResources = context.getResources(); <-- CRASHED

        final Locale currentLocale = LocaleManager.getInstance().getCurrentLocale(context);
        @SuppressWarnings("deprecation") final Locale viewLocale = currentResources.getConfiguration().locale;

        if (currentLocale == null || viewLocale == null) {
```

[View File](https://github.com/mozilla-mobile/focus-android/blob/030c555013f5a8c1aff84cb351ffcc03d9f1283c/app/src/main/java/org/mozilla/focus/locale/Locales.java#L136) | [View Full Crash Details](https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/108318b64b3063c21357fceb0e2b39df)

**Comment by mcomella** [comment]
Call stack is:
```
Locales.getLocalizedResources
  InfoActivity.getAboutIntent
    HomeFragment.onMenuItemClick
```

In `onMenuItemClick`, we fetch the context with [`Fragment.getActivity`](https://developer.android.com/reference/android/support/v4/app/Fragment.html#getActivity()) which states, "Return the FragmentActivity this fragment is currently associated with. May return null if the fragment is associated with a Context instead."

**Comment by mcomella** [comment]
I was able to reproduce this crash. STR:
- Open Focus
- Tap settings menu in top-right from home screen
- Go to system settings
- Change locale
- Return to Focus
- Click the "About" button

The problem is that when we change locales, we replace the HomeFragment but don't dismiss the menu so the menu lingers without a Context. However, we assume the context is there when `onMenuItemClick` is called so crash!

---

> May return null if the fragment is associated with a Context instead."

fwiw, I don't know how this can happen. I looked at the code and it appears mContext always refers to the same object as mActivity.

As per the above, `getActivity`/`getContext` can return null when the Fragment is detached, however.
