### ISSUE TITLE
Should we 'erase' when the user goes back to a third-party app?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#888]
**Scenario**:
> Focus is your default browser and you press a link in a third-party app. When pressing 'back' we return to the previously opened app. The browsing session is not erased and still active.

There's no way to 'erase' AND go back in one action. Therefore a user that has finished reading the current website and just wants to get back to the other app, needs to press 'back' and then erase from the notification. Or press 'erase' and then press 'back' again. This can get annoying when Focus is your default browser and you open links in other apps regularly.

**Background**:
Initially we decided that the 'back' button should always bring you back to the previous screen. In case of a normal app start that's the home screen (which is an implicit 'erase'). And when opened from a third party app back to the app (No erase). Inside the app we show a snackbar after 'erasing'. That's something we can't do when switching to a different app.

**Comment by pocmo** [comment]
@antlam @brampitoyo What do you think about that? Should we 'erase' when pressing back and going to the app that opened the link? If yes, should we show a toast in this case? Or can you think of other ways how "back & erase" could be simpler without the overhead?

**Comment by pocmo** [comment]
Looking at Android's way of saving and restoring instances I think 'erase' makes the most sense here: When pressing back the activity gets destroyed and Android does not save the state of it -> There's no loading in the background happening and the next time the activity is started we either have no session anymore (We would have to write our own session restore) or we have to reload everything.

**Comment by antlam** [comment]
@pocmo I think this has some overlap with the "allow me to return to my browsing session without erasing it" issue. Through the notification, we are giving users a way to quickly return to or erase the browsing session.

Pressing back out of a browser app in this type of a workflow is pretty common, but the tricky part here is that we need to be explicit about the **action** we are performing. Whether that is Erasing, or explicitly not Erasing. 

The absence of a notification might be enough here. Or we could do something entirely different like display a simple dialog for the user to choose in this case.

But maybe there's room to investigate how big of a problem this is first. Because on the other side of this is giving users the ability to hop back into a website they needed to keep around.

Adding this to the UX plate :)

**Comment by bbinto** [comment]
a) Do we have other users complaining about this, or is this more about following Android's proper way for using the "back into the app" action?
b) I can see both cases be useful and valid "Because on the other side of this is giving users the ability to hop back into a website they needed to keep around." So here, the question comes up "how often" does each case occur and how often it annoys either of these use cases. Based on our telemetry people use notification actions more than the erase button. Is there a way to find out how often people hit the back button to go back to the app they came from?

I don't see this as something that needs to be solved in v1.1 and we might want to bring in UR to ask user expectations around it.

For our privacy search/browser app users, that probably might be annoying but for our "I use Focus for everything, as my default browser" users, they enjoy the convincing of going back to the page they opened e.g. via Gmail, later via notifications/and as a reminder.

**Comment by mcomella** [comment]
I think it's pretty standard in the Android ecosystem that:
* Back = go to the previous state, *erasing* whatever I was doing
* Home = go to the home screen of the device, *maintaining* whatever I was doing

And as Sebastian mentions, the system does this by default:

> Looking at Android's way of saving and restoring instances I think 'erase' makes the most sense here: When pressing back the activity gets destroyed and Android does not save the state of it

So I think an Android-conventional solution for a link opened from a separate app (1) would be:
* Back = if you have no more pages to go back to, close the app, erase history (i.e. no notification), go to the home screen or app with the link
* Home = keep state (i.e. keep notification) & go to the home screen

Which I think this addresses Anthony's concern:

> Because on the other side of this is giving users the ability to hop back into a website they needed to keep around.

However, I don't know how a regular user perceives back & home and I'm biased because I know 
how the system is "supposed" to work.

(1): If you opened focus directly, we'd probably want back to go back to the home screen instead.

---

> a) Do we have other users complaining about this, or is this more about following Android's proper way for using the "back into the app" action?

I was complaining. :) I initially filed #790 because I thought this was a bug.

I use Focus as my default browser (2) and find it pretty annoying that I always have to take extra steps to clear the notification but I generally never want to go back to what I was doing.

(2): It's my default primarily for speed & lack of distractions from other open tabs

**Comment by pocmo** [comment]
Some additional things:

* This almost only affects users that use Focus as a default browser. All other users rarely open Focus from a third-party app by clicking a link (assuming they have an other browser set as default). Actually it would be interesting to see the number of users with Focus as default browser in telemetry. I filed #895 for that.

* I use Focus as a default browser and agree with mcomella. I often end up with a notification and it feels like overhead to manually clear the session all the time. An additional user showed up in #790.

* The current implementation is buggy: Often you end up with the notification and when you start up Focus the next time there's actually no session. This is bug #790 and that's something we should fix in v1.1. The situation is now that (because of how the Android system works) this either requires us to keep the current flow and add a bunch of code to do the session restore manually - or implement this here and erase (small fix).

* Chrome and Fennec have a similar behavior: If you open a link from an app and press 'back' to go back to the previous app then the next time you open the browser there's no tab for this website.

> a) Do we have other users complaining about this, or is this more about following Android's proper way for using the "back into the app" action?

So far one user in #790. :)

> b) I can see both cases be useful and valid "Because on the other side of this is giving users the ability to hop back into a website they needed to keep around." So, the question comes up "how often" does each case occur and how often it annoys either of these use cases. Based on our telemetry people use notification actions more than the erase button. Is there a way to find out how often people hit the back button to go back to the app they came from?

I'm pretty certain that not many people press 'back' AND go back to the session again. Because of #790 this is almost certainly broken and can't be used much. It's also important to note that this only affects pressing 'back' after opening a link from an external app. Users can still switch between apps with "home" or "recent apps" and the session remains (And this is not broken currently!).

> I don't see this as something that needs to be solved in v1.1 and we might want to bring in UR to ask user expectations around it.

As mentioned above: We at least need to decide how to fix the broken case. Either by keeping the current model and adding manual session restore code (To be honest I'd like to avoid that) or erase on back. Like we do when using Focus from the launcher too.

Overall I think now is the best time to change this behavior. It will get harder in later releases as we get more and more users. :)

**Comment by bbinto** [comment]
I'm ok with erasing on back as you mentioned in your latest comment.

**Comment by phunkular** [comment]
interesting thread, would just like to say that I am using Focus as default browser but I don't have any default set as I like to have the choice

FWIW, I think that home and recents keeping the page loaded makes sense (with notification). Also, I think that the back button killing the page and taking you straight back to the external app that it was launched from (no notification) makes plenty of sense too.

thanks

**Comment by brampitoyo** [comment]
I agree with what @mcomella had written.

Using Twitter as a third-party app and various browsers that open as a separate app (Opera Mini, UC Mini, Yandex Browser, Baidu, etc.), I observed this behaviour:

* Back: return to Twitter; when I run the browser, my previously opened webpage was nowhere to be found.
* Home: return to home screen; when I run the browser, my previously opened webpage was there.

So it makes sense that we follow this behaviour: when pressing back to return to a third-party app, erase the browsing session.

**Comment by antlam** [comment]
Talked to @pocmo about this. I think we're going to go with the Erase action, a toast UI for confirmation.

Next, we'll need measurement probes around default browser setting, back to Erase action, and something else I've probably forgotten... Sebastian?

Leaving reminder for self to file follow up issue for ideal UX in V2.
