### ISSUE TITLE
Add a telemetry probe for "default browser"

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#895]
Looking at #888 it would be very interesting to know how many users (%) have set Focus as their default browser.

**Comment by pocmo** [comment]
o.m.f.utils.Browsers can help here maybe. The big question here is whether this is something that can/should be added as event (Simple, but hard to evaluate?) or as part of the core ping (Needs a schema change and you might want to talk to fbertsch - might be a good idea in any case).

Focus Telemetry docs -> https://github.com/mozilla-mobile/focus-android/blob/master/docs/telemetry.md

**Comment by liuche** [comment]
After talking to Frank Bertsch, it looks like we should be adding things to focus-events because I assume we'd like to be able to correlate with other event telemetry (rather than coreping which doesn't).

Since code freeze is Wednesday, the plan is:
- Add the probe client-side to get code in by Wednesday, not shipping until next week
- Create a bug for the focus-event schema changes and get data review
- Add the field to the schema as an optional and then request code review [1] so that it will be present on the server-side

[1] https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/master/schemas/telemetry/focus-event

**Comment by liuche** [comment]
For reference, bugzilla for data-review: https://bugzilla.mozilla.org/show_bug.cgi?id=1380179
