### ISSUE TITLE
[Meta] Add option for disabling JavaScript

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#907]
Pros:
* It makes loading a website faster
* It is a good protection against fingerprinting

Cons:
* It breaks some websites

**Comment by quakenet2** [comment]
How about include NSA(NoScript for Android)?

**Comment by webbolo** [comment]
I'd love that feature, but only if easily accessible (i.e. toggle control) or - even better - with something like NSA, as quakenet2 said.

**Comment by bbinto** [comment]
https://appbot.co/apps/1486184-firefox-focus-the-privacy-browser/reviews/564369058

**Comment by pocmo** [comment]
Note: For GeckoView we need a new API. But snorp mentioned that this would be easy to add.

**Comment by pocmo** [comment]
> Note: For GeckoView we need a new API. But snorp mentioned that this would be easy to add.

Filed an issue for that: https://bugzilla.mozilla.org/show_bug.cgi?id=1440708

**Comment by ekager** [comment]
Would this be a setting toggle in Settings under Performance?

**Comment by pocmo** [comment]
> Would this be a setting toggle in Settings under Performance?

@brampitoyo Ping! :)

**Comment by brampitoyo** [comment]
@ekager Is right. A natural place to put this would be as a toggle under performance.

Can we call it simply “Block JavaScript”?

We may or may not want to have an explanatory text underneath. If we do, I suggest a variation of something like this:

> Enabling may make pages load faster, but also cause them to behave unexpectedly

Thoughts?

**Comment by ekager** [comment]
Sounds good to me! 
We have a summary string for "Block other content trackers" that is similar; "Enabling may cause some pages to behave unexpectedly", but this may be more clear for the benefits of disabling JavaScript?

**Comment by brampitoyo** [comment]
@ekager Correct. Let’s ping @BrianNJones.

Brian, we would like to add a new control to disable JavaScript. As you’ll read above, turning JavaScript off has big potential benefits and brokenness, so we’d like to make sure that our users understand what they’re doing when they turn this control on.

So far, I’ve came up with strawman strings that need work and can use your expertise:

> **Block JavaScript**
> Enabling may make pages load faster, but also cause them to behave unexpectedly

What do you think?

**Comment by BrianNJones** [comment]
@brampitoyo Think we should try to stay away from "enabling/disabling," since enabling = turning OFF, in this instance.

Block JavaScript
Pages may load faster, but may also behave unexpectedly

**Comment by bbinto** [comment]
@BrianNJones -- should we also mention that maybe ads won't show up.

I'd love see if we can message this toggle in a way that people understand that JavaScript is the biggest culprit and carrier for 3rd party tracking / and ads networks, def. performance bump!

This might be a baby step to provide better blocking of ads and trackers (https://github.com/mozilla-mobile/focus-android/issues/953). 

Most likely a feature for pros, but who know we might be able to educate non-profs that JavaScript can be evil (maybe even referring to a "more" SUMO article).

**Comment by pocmo** [comment]
I'm a bit afraid that a bunch of websites will not work without JavaScript (although I do not _know_) and then users will start to blame the browser - because they might not make the connection between toggling JavaScript off some time ago and a website not working right now.

**Comment by BrianNJones** [comment]
@bbinto -- I'm leery of muddying the "cut ad clutter" message (and increasing cognitive load) by spreading it across too many buckets and toggles. Moving away from the nomenclature of Tracking Protection (not particularly clear, obvious and unambiguous) to something more ad removal- or speed-focused that could makes more sense, I think.

**Comment by brampitoyo** [comment]
Agreed with @BrianNJones about having too many buckets and toggles, and different ways to describe each.

For now, I think that the label that Brian came up with sounds good.

Site brokenness may become a real problem once we put this setting in, because JavaScript does _so much_. I wonder if there’s a time to run a mini study that asks respondents whether they understand that JS blocking is the thing to turn off if sites don’t work? I feel like our users will understand, because they’d be more likely to already use ad blockers and NoScript. But this is just a hypothesis.

However, in the near future… (tangent incoming; we should file a new issue for this)

We should rethink how these blocking features are organised. Should the Settings UI have one unified heading where everything is grouped under? Since increased performance feels quantifiable (see Opera Battery Saver and Chrome Data Saver), does it make sense to include it along with our existing ‘strong privacy’ label? Maybe call it Privacy and Performance? We’ve proven that privacy is attractive to users and have clear benefits. Will performance dilute that message?

Anyway, if everything happens under one section – whatever we call it – then we only have to explain things once: for everything you turn on, you will increase speed, save data/battery and enhance privacy, but a bunch of websites may not work.

Then maybe we can sort the toggles from the least to the most potentially ‘destructive’ in terms of breaking sites?

**Comment by pocmo** [comment]
Regarding broken sites... I wonder if the major toggle in the menu should re-enable JavaScript. Somehow this toggle is our solution to "this site is broken and I just want to use it. I do not care about tracking right now". It doesn't do that for the other option to block web fonts afaik.

**Comment by brampitoyo** [comment]
> I wonder if the major toggle in the menu should re-enable JavaScript

This is a good idea. When you turn the toggle off from the menu, we can turn everything off (rather than just trackers blocking, which may not fix the problem if your JavaScript is off), and this includes enabling JavaScript as well as web fonts.

**Comment by pocmo** [comment]
@bbinto This feature is ready to land. Are you okay with shipping this in 4.2 or should we hold his back for 5.0?

**Comment by pocmo** [comment]
> This is a good idea. When you turn the toggle off from the menu, we can turn everything off (rather than just trackers blocking, which may not fix the problem if your JavaScript is off), and this includes enabling JavaScript as well as web fonts.

Okay, let's file a separate issue for that. :)

**Comment by bbinto** [comment]
Great news! I forgot to ask, do we have telemetry in place for this setting? (If not, we need it)

I normally would say keep it in 5.0 as the UX/feature loaded release, but since we haven't done many updates lately, I think we can give our users this little treat in a dot release.

I think we should have this feature mentioned in the What's new/SUMO.

cc'ing @jonisavage

**Comment by pocmo** [comment]
@ekager Can you make sure that the preference is listed in setPreferencesImportantForTelemetry() in TelemetryWrapper?

**Comment by ekager** [comment]
Hey @brampitoyo can you file a separate issue for the new toggle behavior? Thanks! :)

**Comment by brampitoyo** [comment]
@ekager It’s not so much a new toggle behaviour, just a reorder of toggles to make them more logical and easily browsable.

**Comment by ekager** [comment]
Hey @brampitoyo , I meant this toggle behavior. 

> When you turn the toggle off from the menu, we can turn everything off (rather than just trackers blocking, which may not fix the problem if your JavaScript is off), and this includes enabling JavaScript as well as web fonts.
