### ISSUE TITLE
Covert lock icon from png to svg

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#940]
All of the other icons are from svg files, and I believe we already have the correct Android lock icon svg in this [folder](https://drive.google.com/drive/folders/0B4vOYc4rq2YAeW0zbk1ScnBmejA). Is there some reason that this file is a png? Otherwise I can make a quick change.

**Comment by pocmo** [comment]
I don't think there's a specific reason why this is a PNG. But it has been around since we've built the prototype - so we probably just never replaced it. :)

**Comment by ahunt** [comment]
Quick question, has this been tested on Android 6?  Apologies if it's already been checked, better to be safe than sorry since the lock is quite visible : ).

I noticed that the drawable that landed contains arc curves (i.e. the letter "A" within android:pathData). We had some issue with such drawables in Fennec (see https://www.ahunt.org/wp-content/uploads/2017/02/android_6.png and the Arc curves section in https://www.ahunt.org/2017/02/fun-with-vectordrawables/ ), and it would be good to verify that the same thing doesn't happen here!

(I don't have access to any Android 6 devices at this time unfortunately, or I'd test myself. The issue isn't guaranteed to happen: it only happened for some drawables, but it does at least happen consistently - i.e. if the drawable is affected, then it should always be corrupted, if it isn't then it will always look OK. Fortunately we don't care about Android 4 where VectorDrawable issues were quite inconsistent and sometimes hard to reproduce...)

I've had a quick look through our other VectorDrawable's, and it looks like this is the only one that was unfortunate enough to end up with arc curves. It seems to be a bit random, SVG producers sometimes use them, and sometimes don't. I'm hoping to write a lint check to catch these in future at least.

**Comment by ekager** [comment]
Looks fine to me on Nexus 4 API 23, but good to keep in mind for testing! @antlam and I discussed on Slack possibly updating this lock icon in the future, so the above would be good to keep in mind! Thanks @ahunt !
<img width="338" alt="screen shot 2017-07-28 at 3 33 16 pm" src="https://user-images.githubusercontent.com/25442310/28738774-5b1a524a-73aa-11e7-9e44-fb7f5b95467b.png">
