### ISSUE TITLE
[meta] Block more ads (blocklists management)

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/focus-android#953]

**Comment by pocmo** [comment]
In addition to the 4 categories we offer in settings?

**Comment by bbinto** [comment]
- import block list from local file or remote URL e.g. easylist

Why? Disconnect list needs some improvements. Some websites with popup ads ruin the experience.

**Comment by dimqua** [comment]
Are there any requeerments for blocklists format? I don't know any other blocklists in JSON format except of Disconnect lists. 

Both [Easylist](https://adblockplus.org/subscriptions#type_ads) and [Adguard](https://kb.adguard.com/en/general/adguard-ad-filters) lists support English and other languages.

**Comment by bbinto** [comment]
Adding some more background from #125 (via @pocmo)

Looking at the popular ublock extension they come with various lists of their own and support a bunch of third-party lists. One of the most popular lists is probably EasyList. That's for example their German list: https://easylist-downloads.adblockplus.org/easylistgermany.txt

I guess we would need to look at some of them and decide which are trustworthy and block content we would like to block. Maintaining those lists seems to be a lot of work that we probably couldn't handle on our own.

Some things to consider:

-Those lists seem to update frequently. A good implementation would require us to download/update those lists often - at best without requiring an app update.
-Those lists are way more complex than our URL based tracking protection lists. They contain some CSS rules to hide elements etc. and other more advanced URL based filter rules. We would need to be able to read and process those lists. In addition to that we would need to check if some of those techniques are even possible on top of WebView.

**Comment by pocmo** [comment]
This would be a great use case for (limited!!) WebExtension support in GeckoView. Otherwise this is going to be a very big project for us.

**Comment by brampitoyo** [comment]
![settings - privacy security - content blocking 2x](https://user-images.githubusercontent.com/51007/44969217-4a3dea80-afa0-11e8-859f-7dcbce429850.png)

Proposed UI for blocklist management.

The idea is to have most users be protected under the “recommended settings”, that will automatically select the best settings for many categories (cookies, trackers, JS, etc.).

One of those categories are “Ads”.

Under “Ads”, when manual control is enabled, blocklists can be turned on and off at will.

Blocklists are displayed in sub-categories that try to be helpful. These categories aren’t final in any way, but they’re better than pure alphabetical sorting.

Remember: most users are happy to use recommended settings and won’t enable manual control, so by default, we should  enable blocklists that has good site compatibility.

My proposal:

* For all locales, consider enabling **EasyList** and **EasyPrivacy**.
* For each locale, if a **local blocklist** is available, consider enabling it
* In my design, **Crypto Mining** has its own page, but why not include them as a sub-category under “Ads”? Consider enabling **NoCoin**.
* In my design, **Trackers** also has its own page. This is done as a conservative measure, but since the Disconnect list we use is yet another blocklist, why not include them as a sub-category under “Ads”?

**Comment by brampitoyo** [comment]
We’re going to work on this problem further on #2603, so I’m closing this issue.
