### ISSUE TITLE
Use post instead of get request of search engines

### ISSUE THREAD

**Issue by pExeen** [mozilla-mobile/focus-android#977]
Because if it would reduce the possible tracking.

**Comment by pocmo** [comment]
Can you elaborate? How does this reduce tracking possibilities?

**Comment by pExeen** [comment]
I my ISP logs my traffic it will only see that I used a search engine insead of seeing what I searched because it was in the URL.

**Comment by pExeen** [comment]
*If

**Comment by phunkular** [comment]
it's not so black and white because there are significant usability differences, I found that this link offers the best explanation:

http://www.diffen.com/difference/GET-vs-POST-HTTP-Requests

If your get request is over ssl then the only information that you are divulging is the length of the URL with the included request attached. This would be like trying to crack a password and knowing that it is 16 characters long compared to cracking a password and not knowing the length, starting at 1 characters and working up. The point is that it is easier but that it will still be very complicated...  I think that this could be used more with network level statistical and timing attacks such as those use to deanonymize tor and vpn users, so whilst it is not necessarily a mainstream point, it is not completely moot either... certainly looking where the future of internet freedom seems to be heading anyway.

As focus is in its infancy with a seemingly bright future ahead, perhaps it is not a bad idea to build actual strong privacy and tracking protection from the get go and so investigating these issues more throughly might be a good idea. A good place to start would be looking at the assumptions for best practice that firefox makes compared to the tor browser 

https://www.torproject.org/projects/torbrowser/design/

**Comment by bbinto** [comment]
should be fixed with #1176, no?
